<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><!-- PageID 1928 - generated by RedDot 5.6 - 5.6.1.9 - Y-9bp -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!-- INSERT PAGE TITLE HERE (immediately following gblPAGE_TITLE) -->
<title>2005 International CES:&nbsp;</title>

<!-- INSERT SEARCH ZONE HERE -->
 <META NAME="searchZone" CONTENT="generalCESweb">
<link rel="StyleSheet" href="/print/global_includes/js/mainMethod.css" type="text/css">
<LINK REL="SHORTCUT ICON" HREF="http://www.easymovement.com/ces/favicon.ico">
<!-- Browser detection script -->
    <script src="/print/global_includes/js/browser_detection.js" type="text/javascript"></script>
<SCRIPT language="javascript1.2">
    function newWin(urlString,pgNum) {
        var popupWindow;
        urlString += "?pageID=" + pgNum;
 
        popupWindow = window.open(urlString,"","toolbar=yes,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=550,width=618,left=50,top=50");
    }  
 
    function openNewWindow(strURL) {
        window.name = "main";
        var newWindow = window.open(strURL,"newWindow", "toolbar=no,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=400,width=450,left=50,top=50");
    }
    // Script for e-mail this page - gets the url of the page the user is on before the e-mail page tool button is clicked
    function loadReferrer() {
        referrerString = opener.document.location.href;
        document.emailForm.page.value = referrerString;
    }
</SCRIPT>
<!-- Rollover script (do we still need these?) --> 
<script language="javascript1.2"> 
    /* for graphical rollovers */
   function rollOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function rollOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function introllOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function introllOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function snrollOver(which,name) 
    {
    var on="/global_images/1.0/1.0" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function snrollOff(which) 
    {
    var on="/global_images/1.0/1.0" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
        
    //do we still need this?   
    function onLoadHandler() {
       if( typeof(bodyOnLoadFunction) != 'undefined' ) {
           return eval(bodyOnLoadFunction);
       }
    }
</script>
<script language="javascript">
    <!--
    var activeNavId=0;
    var thisPageUrl='/attendees/show_floor/areas/central_plaza.asp';
    
        var parentLinks=new Array('dummy','/print/attendees/default.htm','/print/attendees/show_floor/default.asp');
    
        function checkActiveNav(theUrl) {
            var linkUrl=theUrl;
            var returnValue=false;
            
            if (linkUrl==thisPageUrl) {
                returnValue=true;
            } else if (parentLinks.length>2 && linkUrl==parentLinks[parentLinks.length-1]) {
                returnValue=true;   
            } else if (parentLinks.length>3 && linkUrl==parentLinks[parentLinks.length-2]) {
                returnValue=true;
            } else if (parentLinks.length>4 && linkUrl==parentLinks[parentLinks.length-3]) {
                returnValue=true;
            }
        return returnValue;
    }
    //-->
    </script>
    <style>
        <!--
            .attendeesBGImg {
                background-image: url('/print/global_images2005/attendees_bg.gif');
            }
            .text_colored, .intro_copy, .section_title, .subhead, .body_title, .intro_dates, .box10 {
               color: #498429;
            }
            
        //-->
    </style>
</head>
<body leftmargin='0' topmargin='0' rightmargin='0' bottommargin='0' marginwidth='0' onLoad="onLoadHandler();self.focus();"> 
<div style="position:absolute; top: 15; left: 15" ><a href='javascript:;' onClick='window.print();return false'><img src="/print/global_images2005/print.jpg" width="115" height="20" border="0" alt=""></a></div>
<IMG SRC="/print/global_images2005/attPrintBanner.jpg" width="601" BORDER="0" vspace=0><br><table width="600" cellspacing="0" cellpadding="0" border="0">
    <tr>
<!-- /left column -->

<!-- main body content -->    
    <td width="10" class="attendees7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="100%" class="attendees7" valign="top">
    <img src="/print/global_images2005/spacer.gif" height="10" width="1"><br>
<!-- center content -->


<div class="body_title">CES Central Plaza<br><img src="/print/global_images2005/spacer.gif" height="16" width="1"></div>
<div class="text"> 
<!-- text for main page -->

<span class="text">
<IMG src="/print/images/general/icon_Central_Plaza_large_june05.gif"><BR><BR>Located directly in front of the Las Vegas Convention Center, the CES Central&nbsp;Plaza&nbsp;houses: 
<UL>
<LI>Outdoor exhibits, including Gibson Audio and Yahoo!</LI>
<LI>Exhibitor registration </LI></UL><BR><STRONG><IMG height=83 src="/print/images/general/CES_Concierge.gif" width=150 align=right><A href="/print/attendees/show_floor/areas/concierge.asp">CES Concierge Center<BR></A></STRONG>Located directly in front of the Las Vegas Convention Center, this large concierge-style area hosts a variety of assistance counters to extend a helping hand to you. In addition to sign language interpreters, foreign language interpreters, badge holder pickup stations and food and beverage carts, you find stations to help you:<BR>
<UL>
<LI>With general show questions </LI>
<LI>Find exhibitors and products </LI>
<LI>Watch live feeds of CES keynotes and NFL playoff games </LI>
<LI>Make free VoIP phone calls&nbsp; </LI>
<LI>Book restaurant reservations </LI>
<LI>Send e-mail and use the Internet </LI>
<LI>Reserve personal tours of the show</LI></UL><BR>This new destination offers you a personal checkpoint for all your CES needs. <BR><BR><STRONG>NextGen06 Demonstration Home</STRONG><BR>Sponsored by CEA's TechHome Division, the NextGen06 Demonstration Home highlights the practical application of home automation and whole house broadband for the next generation of homeowners. <BR><BR><STRONG><IMG height=96 hspace=6 src="/print/images/general/mecp_SMALL.gif" width=65 align=right>Select Products MECP Installer Challenge and MECP Installer Training<BR></STRONG>Come watch as the best-of-the-best installers compete in a four-day mobile installation contest to build the best car, and receive installer training as well.
</span>

<!-- text for main page -->
</div>
<!--/print/attendees/show_floor/areas/concierge.asp-->

<!-- /center content -->
    <br><br><br>
    </td>
    <td width="10" class="attendees7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
<!-- optional added value -->

<!-- /optional added value -->
</tr>
<!-- /main body row -->
<!--/print/attendees/conferences/default.asp/print/attendees/directory/default.asp/print/attendees/show_floor/default.asp/print/attendees/special_events/default.asp/print/attendees/awards/default.asp/print/attendees/travel/default.asp-->
<!--/print/attendees/show_floor/areas/default.asp

/print/attendees/show_floor/areas/grand_lobby.asp
/print/attendees/show_floor/areas/north.asp
/print/attendees/show_floor/areas/central.asp
/print/attendees/show_floor/areas/south12.asp
/print/attendees/show_floor/areas/south34.asp
/print/attendees/show_floor/areas/central_plaza.asp
/print/attendees/show_floor/areas/sands.asp
/print/attendees/show_floor/areas/hilton.asp
/print/attendees/show_floor/areas/alexis_park.asp
/print/attendees/show_floor/areas/other.asp
/print/attendees/show_floor/maps/default.asp

/print/attendees/show_floor/techzones/default.asp

/print/attendees/show_floor/special_displays/default.asp

/print/attendees/show_floor/floor_plans/default.asp

/print/attendees/show_floor/product_locator/default.asp

-->
</table>
</body>
</html>