<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="head"><title>
	2013 International CES, January 8 - 11 - Home
</title><meta charset="UTF-8" /> 
<link href="/CMSPages/GetResource.ashx?stylesheetname=cesweb" type="text/css" rel="stylesheet"/> 
<link rel="icon" href="/cesweb/media/CESWeb/favicon.ico" type="image/x-icon"> 
<link rel="shortcut icon" href="/cesweb/media/CESWeb/favicon.ico" type="image/x-icon"> 
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script type="text/javascript" src="/cesweb/media/CESWeb/assets/js/ConferenceProgram/displayCart.js"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3975226-4']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!--[if lt IE 9]>
<style>
#topnav>li>a { font-family: Arial !important; font-size: 14px !important; letter-spacing: -1px; font-weight: bold;}
/* #topnav>li{ padding-left:28px !important; } */
.greenbox-bg ul a.lefttopnavhead { font-family: Arial !important; font-size: 14px !important; font-weight: bold; }
</style>
<![endif]-->
<!--[if IE 8]>
<style>
#topnav > li { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=/hIEfix.png,sizingMethod=crop); zoom: 1; }
.greenbox-bg ul a.lefttopnavhead { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=/hIEfix.png,sizingMethod=crop); zoom: 1; }
</style>
<![endif]-->
<!-- Yahoo! Web Analytics - All rights reserved -->
<script type="text/javascript" src="http://d.yimg.com/mi/eu/ywa.js"></script>
<script type="text/javascript">
/*globals YWA*/
var YWATracker = YWA.getTracker("1000217290027");
//YWATracker.setDocumentName("");
//YWATracker.setDocumentGroup("");
//YMATracker.setAction("");
YWATracker.submit();
</script>
<noscript>
<div><img src="http://s.analytics.yahoo.com/p.pl?a=1000217290027&amp;js=no" width="1" height="1" alt="" /></div>
</noscript>
<!-- /Yahoo! Web Analytics - All rights reserved -->

<script src="/cesweb/media/CESWeb/assets/js/custom/jquery-feed-rotator-min.js" type="text/javascript"></script>
<script type="text/javascript">
(function($){
    $(document).ready(function(){
	topNewsFeed = $('#header-feed').feedRotator();
	setTimeout(function(){
		$('#topnav').show();
	}, 2000);
    });
})(jQuery);
</script><SCRIPT TYPE="text/javascript"> 
<!-- 
var filename="http://www.cesweb.org/hp/CEA-audio-minus15.mp3";
if (navigator.appName == "Microsoft Internet Explorer")
    document.writeln ('<BGSOUND SRC="' + filename + '">');
else if (navigator.appName == "Netscape")
    document.writeln ('<div style="display: none;"><audio autoplay="autoplay" controls="controls"><source type="audio/ogg" src="http://www.cesweb.org/hp/CEA-audio-minus15.ogg"></source><source type="audio/mpeg" src="http://www.cesweb.org/hp/CEA-audio-minus15.mp3"></source>Your browser does not support the audio element.</audio></div>');
    
// -->
</SCRIPT>

<meta name="google-site-verification" content="0q37dtYpr1d_nWh888XnhbKgzq7Y0d9vhcuxtHfxG_8" />
<NOSCRIPT>
<BGSOUND SRC="http://www.cesweb.org/hp/CEA-audio-minus15.mp3" LOOP="1">
</NOSCRIPT> 
</head>
<body class="LTR ENUS ContentBody"  class="home" id="home">
    <form method="post" action="/default.aspx" id="form">
<div class="aspNetHidden">
<input type="hidden" name="manScript_HiddenField" id="manScript_HiddenField" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTYwODg0MzQ2Ng9kFgICARBkZBYCAgMPZBYCZg9kFgJmD2QWBAICD2QWAmYPZBYCZg9kFgJmDxYCHgtfIUl0ZW1Db3VudAIHFg5mD2QWAmYPZBYCZg8VAhFodHRwOi8vd3d3LmNlLm9yZwxDRUEgLSBDRS5vcmdkAgEPZBYCZg9kFgJmDxUCFWh0dHA6Ly93d3cuY2Vzd2ViLm9yZxFJbnRlcm5hdGlvbmFsIENFU2QCAg9kFgJmD2QWAmYPFQIgaHR0cDovL3d3dy5kZWNsYXJlaW5ub3ZhdGlvbi5jb20TSW5ub3ZhdGlvbiBNb3ZlbWVudGQCAw9kFgJmD2QWAmYPFQISaHR0cDovL2Jsb2cuY2Uub3JnEERpZ2l0YWwgRGlhbG9ndWVkAgQPZBYCZg9kFgJmDxUCF2h0dHA6Ly93d3cuY2V2aXNpb24ub3JnD1Zpc2lvbiBNYWdhemluZWQCBQ9kFgJmD2QWAmYPFQIdaHR0cDovL3d3dy5ncmVlbmVyZ2FkZ2V0cy5vcmcPR3JlZW5lciBHYWRnZXRzZAIGD2QWAmYPZBYCZg8VAhZodHRwOi8vcmVzZWFyY2guY2Uub3JnD01hcmtldCBSZXNlYXJjaGQCDg9kFgICBQ9kFgICAg9kFgJmD2QWAmYPZBYGAgEPZBYEZg9kFgICAg9kFgpmD2QWAmYPZBYCZg8VBjpodHRwOi8vY2Vzd2ViLm9yZy9Db25mZXJlbmNlLVByb2dyYW0vU2Vzc2lvbi1TY2hlZHVsZS5hc3B4Y34vY2Vzd2ViL21lZGlhL0NFU1dlYi9TbGlkZXNob3clMjBJbWFnZXMvQ29uZmVyZW5jZXNfUmVnT3Blbl9PY3QxLkpQRz93aWR0aD05OTEmaGVpZ2h0PTM5NiZleHQ9LmpwZwBWPGEgY2xhc3M9InJlYWRtb3JlIiBocmVmPSdodHRwOi8vY2Vzd2ViLm9yZy9Db25mZXJlbmNlLVByb2dyYW0vU2Vzc2lvbi1TY2hlZHVsZS5hc3B4Jz4ABDwvYT5kAgEPZBYCZg9kFgJmDxUGG2h0dHA6Ly95b3V0dS5iZS93ZGktaDNScFhiQVp+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzL21vYmlsZU5hdGl2ZV92My5qcGc/d2lkdGg9OTkxJmhlaWdodD0zOTUmZXh0PS5qcGcANzxhIGNsYXNzPSJyZWFkbW9yZSIgaHJlZj0naHR0cDovL3lvdXR1LmJlL3dkaS1oM1JwWGJBJz4ABDwvYT5kAgIPZBYCZg9kFgJmDxUGNGh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9TaG93LUZsb29yL0NFUy1Nb2JpbGUtQXBwLmFzcHhVfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy9DRVMtTW9iaWxlLmpwZz93aWR0aD05OTEmaGVpZ2h0PTM5NiZleHQ9LmpwZwBQPGEgY2xhc3M9InJlYWRtb3JlIiBocmVmPSdodHRwOi8vd3d3LmNlc3dlYi5vcmcvU2hvdy1GbG9vci9DRVMtTW9iaWxlLUFwcC5hc3B4Jz4ABDwvYT5kAgMPZBYCZg9kFgJmDxUGMWh0dHA6Ly9jZXN3ZWIub3JnL0Zvci1UaGUtUHJlc3MvUHJlc3MtRXZlbnRzLmFzcHhmfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy9IUF9FdmVudHNfVW52ZWlsZWRTdG9ja2hvbG0uanBnP3dpZHRoPTk5MSZoZWlnaHQ9Mzk2JmV4dD0uanBnAE08YSBjbGFzcz0icmVhZG1vcmUiIGhyZWY9J2h0dHA6Ly9jZXN3ZWIub3JnL0Zvci1UaGUtUHJlc3MvUHJlc3MtRXZlbnRzLmFzcHgnPgAEPC9hPmQCBA9kFgJmD2QWAmYPFQZGaHR0cDovL2NlLm9yZy9FdmVudHMtYW5kLUF3YXJkcy9FdmVudHMvMjAxMi1FdmVudHMvSW5kdXN0cnktRm9ydW0uYXNweGJ+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzL0hQX0V2ZW50c19JbmR1c3RyeUZvcnVtLmpwZz93aWR0aD05OTEmaGVpZ2h0PTM5NiZleHQ9LmpwZwBiPGEgY2xhc3M9InJlYWRtb3JlIiBocmVmPSdodHRwOi8vY2Uub3JnL0V2ZW50cy1hbmQtQXdhcmRzL0V2ZW50cy8yMDEyLUV2ZW50cy9JbmR1c3RyeS1Gb3J1bS5hc3B4Jz4ABDwvYT5kAgEPZBYCAgIPZBYKZg9kFgJmD2QWAmYPFQFjfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy9Db25mZXJlbmNlc19SZWdPcGVuX09jdDEuSlBHP3dpZHRoPTk5MSZoZWlnaHQ9Mzk2JmV4dD0uanBnZAIBD2QWAmYPZBYCZg8VAVp+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzL21vYmlsZU5hdGl2ZV92My5qcGc/d2lkdGg9OTkxJmhlaWdodD0zOTUmZXh0PS5qcGdkAgIPZBYCZg9kFgJmDxUBVX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9TbGlkZXNob3clMjBJbWFnZXMvQ0VTLU1vYmlsZS5qcGc/d2lkdGg9OTkxJmhlaWdodD0zOTYmZXh0PS5qcGdkAgMPZBYCZg9kFgJmDxUBZn4vY2Vzd2ViL21lZGlhL0NFU1dlYi9TbGlkZXNob3clMjBJbWFnZXMvSFBfRXZlbnRzX1VudmVpbGVkU3RvY2tob2xtLmpwZz93aWR0aD05OTEmaGVpZ2h0PTM5NiZleHQ9LmpwZ2QCBA9kFgJmD2QWAmYPFQFifi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy9IUF9FdmVudHNfSW5kdXN0cnlGb3J1bS5qcGc/d2lkdGg9OTkxJmhlaWdodD0zOTYmZXh0PS5qcGdkAgUPZBYEZg9kFgICAg9kFiBmD2QWAmYPZBYCZg8VCSI8ZGl2IGNsYXNzPSduZXdzX3RhYicgaWQ9J25ld3NfMScgAAE+CjEwLzExLzIwMTIkODdhYjg0YjMtNmFiMS00NTI5LTlkNmUtYTgwMWE5ZTdhNmNkFkNFUyBVbnZlaWxlZCBTVE9DS0hPTE1jfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL05ld3MvQnV6endvcnRoeSUyMFRodW1ibmFpbHMvMTEwNTlfTmV3RXZlbnQuanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTI1JmV4dD0uanBn6QNBdHRlbnRpb24gbWVtYmVycyBvZiB0aGUgcHJlc3MhIFRoZSBDb25zdW1lciBFbGVjdHJvbmljcyBBc3NvY2lhdGlvbiBoYXMgYWRkZWQgb25lIG1vcmUgc3RvcCBvbiB0aGUgQ0VTIFVudmVpbGVkIHRvdXIuIENFQSB3aWxsIGJlIGdpdmluZyBhIHNuZWFrIHBlZWsgb2Ygd2hhdCZyc3F1bztzIHRvIGNvbWUgYXQgdGhlIDIwMTMgSW50ZXJuYXRpb25hbCBDRVMgYXQgb3VyIGZpcnN0IGV2ZXIgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL0Zvci1UaGUtUHJlc3MvUHJlc3MtRXZlbnRzLmFzcHgjNmp1bXAiPkNFUyBVbnZlaWxlZCBTVE9DS0hPTE08L2E+LiBKb2luIHVzIGZvciB0aGlzIGV4Y2l0aW5nIHByZXNzLW9ubHkgZXZlbnQgYXQgdGhlIFdvcmxkIFRyYWRlIENlbnRlciBTdG9ja2hvbG0gb24gT2N0LiAyOSBmb3IgYSBkYXkgb2YgdGVjaCB0cmVuZHMsIGZvcmVjYXN0cyBhbmQgYSBzaG93Y2FzZSBvZiB0aGUgbGF0ZXN0IHRlY2hub2xvZ3kuDQoAZAIBD2QWAmYPZBYCZg8VCQAAAAoxMC8xMS8yMDEyJDc1ZTQzZWM3LTQzMGItNDVhYi1hNjIzLWNjNzc3ZTQzNTNhMTZJdOKAmXMgTmV2ZXIgVG9vIEVhcmx5IHRvIFN0YXJ0IFBsYW5uaW5nIGZvciAyMDEzIENFUyFlfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL05ld3MvQnV6endvcnRoeSUyMFRodW1ibmFpbHMvQ0VTTW9iaWxlMTIweDEyMC5qcGc/d2lkdGg9MTIwJmhlaWdodD0xMjAmZXh0PS5qcGf+BlRoZSAyMDEzIEludGVybmF0aW9uYWwgQ0VTIHdpbGwgYmUgZm91ciBvZiB0aGUgbW9zdCBleGNpdGluZyBkYXlzIG9mIHRoZSB5ZWFyIGZvciBhbGwgb2Ygb3VyIGF0dGVuZGVlcywgYW5kIHRoZSBjb25zdW1lciBlbGVjdHJvbmljcyBpbmR1c3RyeS4mbmJzcDsgQ0VTIGhhcyB0d28gZ3JlYXQgdG9vbHMgdG8gaGVscCB5b3Ugc2VhcmNoIGZvciBleGhpYml0b3JzLCBwcm9kdWN0cywgdGVjaG5vbG9neSwgZXZlbnRzLCBlZHVjYXRpb25hbCBzZXNzaW9ucywgc2NoZWR1bGUgbWVldGluZ3MsIGNvbm5lY3Qgd2l0aCBmcmllbmRzIGFuZCBtb3JlLjxiciAvPg0KPGJyIC8+DQpUaGUgTXlDRVMgdG9vbCB3aWxsIGhlbHAgdG8gbWF4aW1pemUgeW91ciBleHBlcmllbmNlIGF0IHRoZSBzaG93IGJ5IGFsbG93aW5nIHlvdSB0byBjcmVhdGUgYW5kIG9yZ2FuaXplIHlvdXIgcGVyc29uYWwgc2NoZWR1bGUgZm9yIHlvdXIgdGltZSBpbiBMYXMgVmVnYXMuJm5ic3A7IExlYXJuIG1vcmUgYW5kIDxhIGhyZWY9Imh0dHA6Ly9jZXMxMy5tYXB5b3Vyc2hvdy5jb20vNV8wL3NlYXJjaC5jZm0/Ij5zdGFydCBwbGFubmluZyB5b3VyIHRyaXAgdG9kYXkuPC9hPiBUaGUgQ0VTIE1vYmlsZSBhcHAgd2lsbCBoZWxwIHlvdSBwbGFuIGZvciAyMDEzIENFUyBvbiB0aGUgZ28uIEJ1aWxkIHlvdXIgc2NoZWR1bGUsIHNlYXJjaCB0aGUgc2hvdyBmbG9vciwgYW5kIHJlY2VpdmUgYnJlYWtpbmcgQ0VTIG5ld3MgcmlnaHQgZnJvbSB5b3VyIHRhYmxldCBvciBzbWFydHBob25lLiBWaXNpdCA8YSBocmVmPSJodHRwOi8vY2Vzd2ViLm9yZy9TaG93LUZsb29yL0NFUy1Nb2JpbGUtQXBwLmFzcHgiPkNFU3dlYi5vcmcvY2VzbW9iaWxlPC9hPiB0byBsZWFybiBtb3JlIGFuZCBkb3dubG9hZCBDRVMgTW9iaWxlLgBkAgIPZBYCZg9kFgJmDxUJAAAACTEwLzgvMjAxMiQ2MDFhN2M4OS1jN2EzLTRmYjMtYjFmZi1hYTJiYzI1MzY3Y2Es4oCcU3BlYWtlcnMgYXJlIHdoYXQgSSBkby4gSXTigJlzIG15IGFydC7igJ1ffi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL05ld3MvQnV6endvcnRoeSUyMFRodW1ibmFpbHMvU2FuZHlHcm9zcy5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMjUmZXh0PS5qcGf2K0FmdGVyIGEgY2FyZWVyIHRoYXQgaW5jbHVkZWQgY3JlYXRpbmcgdHdvIHN1Y2Nlc3NmdWwgbG91ZHNwZWFrZXIgY29tcGFuaWVzLCBTYW5keSBHcm9zcyBjb250ZW1wbGF0ZWQgcmV0aXJlbWVudC4gQnV0IGhlIGNvdWxkbiZyc3F1bzt0IGxlYXZlIHRoZSB3b3JrIGhlIGxvdmVkLiAmbGRxdW87U3BlYWtlcnMgYXJlIHdoYXQgSSBkby4gSXQmcnNxdW87cyBteSBhcnQsJnJkcXVvOyA8YSBocmVmPSJodHRwOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9VjFTZHZkS0Fjc0UmYW1wO2ZlYXR1cmU9cGxjcCIgdGFyZ2V0PSJfYmxhbmsiPnNhaWQgR3Jvc3M8L2E+LCBub3cgcHJlc2lkZW50IG9mIGhpcyBuZXcgY29tcGFueSBHb2xkZW5FYXIgVGVjaG5vbG9neSBhbmQgYSBmaW5hbGlzdCB0byBiZSBuYW1lZCAyMDEyIEV4ZWN1dGl2ZSBvZiB0aGUgWWVhciBpbiB0aGUgSW5ub3ZhdGlvbiBFbnRyZXByZW5ldXIgQXdhcmRzLjxiciAvPg0KPGJyIC8+DQo8c3BhbiBzdHlsZT0iY29sb3I6IHJnYigwLCAwLCAwKTsgZm9udC1mYW1pbHk6IEFyaWFsLCBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogMTJweDsgZm9udC1zdHlsZTogbm9ybWFsOyBmb250LXZhcmlhbnQ6IG5vcm1hbDsgZm9udC13ZWlnaHQ6IG5vcm1hbDsgbGV0dGVyLXNwYWNpbmc6IG5vcm1hbDsgbGluZS1oZWlnaHQ6IDE3cHg7IG9ycGhhbnM6IDI7IHRleHQtYWxpZ246IGxlZnQ7IHRleHQtaW5kZW50OiAwcHg7IHRleHQtdHJhbnNmb3JtOiBub25lOyB3aGl0ZS1zcGFjZTogbm9ybWFsOyB3aWRvd3M6IDI7IHdvcmQtc3BhY2luZzogMHB4OyAtd2Via2l0LXRleHQtc2l6ZS1hZGp1c3Q6IGF1dG87IC13ZWJraXQtdGV4dC1zdHJva2Utd2lkdGg6IDBweDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyBkaXNwbGF5OiBpbmxpbmUgIWltcG9ydGFudDsgZmxvYXQ6IG5vbmU7ICI+VGhlIGZpcnN0IGFubnVhbDwvc3Bhbj48YSBocmVmPSJodHRwOi8vd3d3LmNlLm9yZy9OZXdzL05ld3MtUmVsZWFzZXMvUHJlc3MtUmVsZWFzZXMvMjAxMi1QcmVzcy1SZWxlYXNlcy9DRUEtQW5ub3VuY2VzLUZpbmFsaXN0cy1mb3ItSW5hdWd1cmFsLUlubm92YXRpb24tRS5hc3B4IiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiBub25lOyBjb2xvcjogcmdiKDAsIDE1NSwgMTgyKTsgZm9udC1mYW1pbHk6IEFyaWFsLCBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogMTJweDsgZm9udC1zdHlsZTogbm9ybWFsOyBmb250LXZhcmlhbnQ6IG5vcm1hbDsgZm9udC13ZWlnaHQ6IG5vcm1hbDsgbGV0dGVyLXNwYWNpbmc6IG5vcm1hbDsgbGluZS1oZWlnaHQ6IDE3cHg7IG9ycGhhbnM6IDI7IHRleHQtYWxpZ246IGxlZnQ7IHRleHQtaW5kZW50OiAwcHg7IHRleHQtdHJhbnNmb3JtOiBub25lOyB3aGl0ZS1zcGFjZTogbm9ybWFsOyB3aWRvd3M6IDI7IHdvcmQtc3BhY2luZzogMHB4OyAtd2Via2l0LXRleHQtc2l6ZS1hZGp1c3Q6IGF1dG87IC13ZWJraXQtdGV4dC1zdHJva2Utd2lkdGg6IDBweDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPjxzcGFuIGNsYXNzPSJBcHBsZS1jb252ZXJ0ZWQtc3BhY2UiPiZuYnNwOzwvc3Bhbj5Jbm5vdmF0aW9uIEVudHJlcHJlbmV1ciBBd2FyZHM8L2E+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMCwgMCwgMCk7IGZvbnQtZmFtaWx5OiBBcmlhbCwgSGVsdmV0aWNhLCBzYW5zLXNlcmlmOyBmb250LXNpemU6IDEycHg7IGZvbnQtc3R5bGU6IG5vcm1hbDsgZm9udC12YXJpYW50OiBub3JtYWw7IGZvbnQtd2VpZ2h0OiBub3JtYWw7IGxldHRlci1zcGFjaW5nOiBub3JtYWw7IGxpbmUtaGVpZ2h0OiAxN3B4OyBvcnBoYW5zOiAyOyB0ZXh0LWFsaWduOiBsZWZ0OyB0ZXh0LWluZGVudDogMHB4OyB0ZXh0LXRyYW5zZm9ybTogbm9uZTsgd2hpdGUtc3BhY2U6IG5vcm1hbDsgd2lkb3dzOiAyOyB3b3JkLXNwYWNpbmc6IDBweDsgLXdlYmtpdC10ZXh0LXNpemUtYWRqdXN0OiBhdXRvOyAtd2Via2l0LXRleHQtc3Ryb2tlLXdpZHRoOiAwcHg7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZGlzcGxheTogaW5saW5lICFpbXBvcnRhbnQ7IGZsb2F0OiBub25lOyAiPiwgc3BvbnNvcmVkIGJ5IHRoZTxzcGFuIGNsYXNzPSJBcHBsZS1jb252ZXJ0ZWQtc3BhY2UiPiZuYnNwOzwvc3Bhbj48L3NwYW4+PGEgaHJlZj0iaHR0cDovL3d3dy5jZS5vcmcvIiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiBub25lOyBjb2xvcjogcmdiKDAsIDE1NSwgMTgyKTsgZm9udC1mYW1pbHk6IEFyaWFsLCBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogMTJweDsgZm9udC1zdHlsZTogbm9ybWFsOyBmb250LXZhcmlhbnQ6IG5vcm1hbDsgZm9udC13ZWlnaHQ6IG5vcm1hbDsgbGV0dGVyLXNwYWNpbmc6IG5vcm1hbDsgbGluZS1oZWlnaHQ6IDE3cHg7IG9ycGhhbnM6IDI7IHRleHQtYWxpZ246IGxlZnQ7IHRleHQtaW5kZW50OiAwcHg7IHRleHQtdHJhbnNmb3JtOiBub25lOyB3aGl0ZS1zcGFjZTogbm9ybWFsOyB3aWRvd3M6IDI7IHdvcmQtc3BhY2luZzogMHB4OyAtd2Via2l0LXRleHQtc2l6ZS1hZGp1c3Q6IGF1dG87IC13ZWJraXQtdGV4dC1zdHJva2Utd2lkdGg6IDBweDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPkNvbnN1bWVyIEVsZWN0cm9uaWNzIEFzc29jaWF0aW9uJiMzOTtzIChDRUEpPC9hPjxzcGFuIHN0eWxlPSJjb2xvcjogcmdiKDAsIDAsIDApOyBmb250LWZhbWlseTogQXJpYWwsIEhlbHZldGljYSwgc2Fucy1zZXJpZjsgZm9udC1zaXplOiAxMnB4OyBmb250LXN0eWxlOiBub3JtYWw7IGZvbnQtdmFyaWFudDogbm9ybWFsOyBmb250LXdlaWdodDogbm9ybWFsOyBsZXR0ZXItc3BhY2luZzogbm9ybWFsOyBsaW5lLWhlaWdodDogMTdweDsgb3JwaGFuczogMjsgdGV4dC1hbGlnbjogbGVmdDsgdGV4dC1pbmRlbnQ6IDBweDsgdGV4dC10cmFuc2Zvcm06IG5vbmU7IHdoaXRlLXNwYWNlOiBub3JtYWw7IHdpZG93czogMjsgd29yZC1zcGFjaW5nOiAwcHg7IC13ZWJraXQtdGV4dC1zaXplLWFkanVzdDogYXV0bzsgLXdlYmtpdC10ZXh0LXN0cm9rZS13aWR0aDogMHB4OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IGRpc3BsYXk6IGlubGluZSAhaW1wb3J0YW50OyBmbG9hdDogbm9uZTsgIj48c3BhbiBjbGFzcz0iQXBwbGUtY29udmVydGVkLXNwYWNlIj4mbmJzcDs8L3NwYW4+bmV3IGZsYWdzaGlwIHB1YmxpY2F0aW9uPHNwYW4gY2xhc3M9IkFwcGxlLWNvbnZlcnRlZC1zcGFjZSI+Jm5ic3A7PC9zcGFuPjwvc3Bhbj48YSBocmVmPSJodHRwOi8vd3d3LmNlLm9yZy9pMyIgc3R5bGU9InRleHQtZGVjb3JhdGlvbjogbm9uZTsgY29sb3I6IHJnYigwLCAxNTUsIDE4Mik7IGZvbnQtZmFtaWx5OiBBcmlhbCwgSGVsdmV0aWNhLCBzYW5zLXNlcmlmOyBmb250LXNpemU6IDEycHg7IGZvbnQtc3R5bGU6IG5vcm1hbDsgZm9udC12YXJpYW50OiBub3JtYWw7IGZvbnQtd2VpZ2h0OiBub3JtYWw7IGxldHRlci1zcGFjaW5nOiBub3JtYWw7IGxpbmUtaGVpZ2h0OiAxN3B4OyBvcnBoYW5zOiAyOyB0ZXh0LWFsaWduOiBsZWZ0OyB0ZXh0LWluZGVudDogMHB4OyB0ZXh0LXRyYW5zZm9ybTogbm9uZTsgd2hpdGUtc3BhY2U6IG5vcm1hbDsgd2lkb3dzOiAyOyB3b3JkLXNwYWNpbmc6IDBweDsgLXdlYmtpdC10ZXh0LXNpemUtYWRqdXN0OiBhdXRvOyAtd2Via2l0LXRleHQtc3Ryb2tlLXdpZHRoOiAwcHg7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5JdCBJcyBJbm5vdmF0aW9uIChpMyk8L2E+PHNwYW4gc3R5bGU9ImNvbG9yOiByZ2IoMCwgMCwgMCk7IGZvbnQtZmFtaWx5OiBBcmlhbCwgSGVsdmV0aWNhLCBzYW5zLXNlcmlmOyBmb250LXNpemU6IDEycHg7IGZvbnQtc3R5bGU6IG5vcm1hbDsgZm9udC12YXJpYW50OiBub3JtYWw7IGZvbnQtd2VpZ2h0OiBub3JtYWw7IGxldHRlci1zcGFjaW5nOiBub3JtYWw7IGxpbmUtaGVpZ2h0OiAxN3B4OyBvcnBoYW5zOiAyOyB0ZXh0LWFsaWduOiBsZWZ0OyB0ZXh0LWluZGVudDogMHB4OyB0ZXh0LXRyYW5zZm9ybTogbm9uZTsgd2hpdGUtc3BhY2U6IG5vcm1hbDsgd2lkb3dzOiAyOyB3b3JkLXNwYWNpbmc6IDBweDsgLXdlYmtpdC10ZXh0LXNpemUtYWRqdXN0OiBhdXRvOyAtd2Via2l0LXRleHQtc3Ryb2tlLXdpZHRoOiAwcHg7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgZGlzcGxheTogaW5saW5lICFpbXBvcnRhbnQ7IGZsb2F0OiBub25lOyAiPjxzcGFuIGNsYXNzPSJBcHBsZS1jb252ZXJ0ZWQtc3BhY2UiPiZuYnNwOzwvc3Bhbj5hbmQgQ0VBJiMzOTtzIFNtYWxsIEJ1c2luZXNzIENvdW5jaWwsIGhvbm9ycyBleGNlbGxlbmNlIGluIGVudHJlcHJlbmV1cnNoaXAgYW5kIHJlY29nbml6ZXMgdmlzaW9uYXJpZXMgbGVhZGluZyBidXNpbmVzc2VzIHdpdGggcmV2ZW51ZXMgdW5kZXIgJDMwIG1pbGxpb24uIFdpbm5lcnMgd2lsbCBiZSBhbm5vdW5jZWQgYXQgdGhlIHVwY29taW5nPHNwYW4gY2xhc3M9IkFwcGxlLWNvbnZlcnRlZC1zcGFjZSI+Jm5ic3A7PC9zcGFuPjwvc3Bhbj48YSBocmVmPSJodHRwOi8vd3d3LmNlLm9yZy9pbmR1c3RyeWZvcnVtIiBzdHlsZT0idGV4dC1kZWNvcmF0aW9uOiBub25lOyBjb2xvcjogcmdiKDAsIDE1NSwgMTgyKTsgZm9udC1mYW1pbHk6IEFyaWFsLCBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogMTJweDsgZm9udC1zdHlsZTogbm9ybWFsOyBmb250LXZhcmlhbnQ6IG5vcm1hbDsgZm9udC13ZWlnaHQ6IG5vcm1hbDsgbGV0dGVyLXNwYWNpbmc6IG5vcm1hbDsgbGluZS1oZWlnaHQ6IDE3cHg7IG9ycGhhbnM6IDI7IHRleHQtYWxpZ246IGxlZnQ7IHRleHQtaW5kZW50OiAwcHg7IHRleHQtdHJhbnNmb3JtOiBub25lOyB3aGl0ZS1zcGFjZTogbm9ybWFsOyB3aWRvd3M6IDI7IHdvcmQtc3BhY2luZzogMHB4OyAtd2Via2l0LXRleHQtc2l6ZS1hZGp1c3Q6IGF1dG87IC13ZWJraXQtdGV4dC1zdHJva2Utd2lkdGg6IDBweDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPkNFQSBJbmR1c3RyeSBGb3J1bTwvYT48c3BhbiBzdHlsZT0iY29sb3I6IHJnYigwLCAwLCAwKTsgZm9udC1mYW1pbHk6IEFyaWFsLCBIZWx2ZXRpY2EsIHNhbnMtc2VyaWY7IGZvbnQtc2l6ZTogMTJweDsgZm9udC1zdHlsZTogbm9ybWFsOyBmb250LXZhcmlhbnQ6IG5vcm1hbDsgZm9udC13ZWlnaHQ6IG5vcm1hbDsgbGV0dGVyLXNwYWNpbmc6IG5vcm1hbDsgbGluZS1oZWlnaHQ6IDE3cHg7IG9ycGhhbnM6IDI7IHRleHQtYWxpZ246IGxlZnQ7IHRleHQtaW5kZW50OiAwcHg7IHRleHQtdHJhbnNmb3JtOiBub25lOyB3aGl0ZS1zcGFjZTogbm9ybWFsOyB3aWRvd3M6IDI7IHdvcmQtc3BhY2luZzogMHB4OyAtd2Via2l0LXRleHQtc2l6ZS1hZGp1c3Q6IGF1dG87IC13ZWJraXQtdGV4dC1zdHJva2Utd2lkdGg6IDBweDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyBkaXNwbGF5OiBpbmxpbmUgIWltcG9ydGFudDsgZmxvYXQ6IG5vbmU7ICI+PHNwYW4gY2xhc3M9IkFwcGxlLWNvbnZlcnRlZC1zcGFjZSI+Jm5ic3A7PC9zcGFuPmluIFNhbiBGcmFuY2lzY28uICZ0aGluc3A7PC9zcGFuPgBkAgMPZBYCZg9kFgJmDxUJAAAACTEwLzgvMjAxMiQzMmMzZGJmZS0zMDZkLTQ5NTgtOGU4NC02YmQ1ODAwNWVlZmUqT2N0b2JlciBpcyBDRUEncyBNZW1iZXIgQXBwcmVjaWF0aW9uIE1vbnRodX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzLzM5MDY1OV8xOTMzMzE3MzY3NzQzXzc3NzY5MDY1NV9uLmpwZz93aWR0aD0xNjUmaGVpZ2h0PTExOCZleHQ9LmpwZ6EFVGhlIENvbnN1bWVyIEVsZWN0cm9uaWNzIEFzc29jaWF0aW9uIChDRUEpIGlzIGNlbGVicmF0aW5nIHRoZWlyIG1lbWJlcnMgYWxsIG1vbnRoIGxvbmchIEluIGFkZGl0aW9uIHRvIHByb2R1Y2luZyB0aGUgSW50ZXJuYXRpb25hbCBDRVMgaW4gVmVnYXMgZWFjaCB5ZWFyLCBDRUEgd29ya3MgYWxsIHllYXIgcm91bmQgdG8gZ3JvdyBhbmQgcHJvbW90ZSB0aGUgaW5kdXN0cnkuIFdlIHdvdWxkIGxpa2UgdG8gdGhhbmsgb3VyIG1lbWJlcnMgZm9yIGNyZWF0aW5nLCBtYW51ZmFjdHVyaW5nLCBpbm5vdmF0aW5nLCBidXlpbmcgYW5kIHNlbGxpbmcgY29uc3VtZXIgZWxlY3Ryb25pY3MgcHJvZHVjdHMuIFdlIHdpbGwgYmUgcmV3YXJkaW5nIG91ciBtZW1iZXJzIGJ5IGhvc3RpbmcgYSBzZXJpZXMgb2YgY29udGVzdHMgYW5kIGdpdmVhd2F5cyBkdXJpbmcgdGhlIG1vbnRoIG9mIE9jdG9iZXIuIDxhIGhyZWY9Imh0dHA6Ly9ibG9nLmNlLm9yZy9pbmRleC5waHAvMjAxMi8xMC8wNC9tZW1iZXItYXBwcmVjaWF0aW9uLW1vbnRoLWdpdmVhd2F5LTEvIiB0YXJnZXQ9Il9ibGFuayI+VmlzaXQgb3VyIGJsb2c8L2E+IHRvIGxlYXJuIG1vcmUhPGJyIHN0eWxlPSJtYXJnaW46IDBweDsgcGFkZGluZzogMHB4OyAiIC8+DQo8YnIgc3R5bGU9Im1hcmdpbjogMHB4OyBwYWRkaW5nOiAwcHg7ICIgLz4NCgY8L2Rpdj5kAgQPZBYCZg9kFgJmDxUJIjxkaXYgY2xhc3M9J25ld3NfdGFiJyBpZD0nbmV3c18yJyAVc3R5bGU9J2Rpc3BsYXk6bm9uZTsnAT4JMTAvNS8yMDEyJDFhMmY1OWIxLTQ0ODMtNGYwYi1iM2MyLTEyYTM0ODRjMGY3ME9QYW5kb3Jh4oCZcyBUaW0gV2VzdGVyZ3JlbiB0byBLZXlub3RlIHRoZSAyMDEzIENFUyBMZWFkZXJzIGluIFRlY2hub2xvZ3kgRGlubmVyZX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL3BhbmRvcmFfbG9nb18xNjUuanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTI1JmV4dD0uanBnkQVUaGUgSW50ZXJuYXRpb25hbCBDRVMgaGFzIGhvc3RlZCB0aGUgYmlnZ2VzdCBuYW1lcyBpbiB0ZWNobm9sb2d5IGFzIHNwZWFrZXJzIHRocm91Z2hvdXQgdGhlIHllYXJzLCBhbmQgdGhlIDIwMTMgQ0VTIGlzIG5vIGRpZmZlcmVudC4gU29tZSBvZiB0aGlzIHllYXImIzM5O3MgYXR0ZW5kZWVzIHdpbGwgaGF2ZSB0aGUgcHJpdmlsZWdlIG9mIGhlYXJpbmcgZnJvbSBUaW0gV2VzdGVyZ3JlbiwgY2hpZWYgc3RyYXRlZ3kgb2ZmaWNlciBhbmQgZm91bmRlciBvZiBQYW5kb3JhLCBhIHRydWUgaW5ub3ZhdG9yIGluIEludGVybmV0IHJhZGlvIHdobyB3aWxsIGRlbGl2ZXIgdGhlIGtleW5vdGUgYWRkcmVzcyBhdCB0aGUgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL05ld3MvQ0VTLVByZXNzLVJlbGVhc2VzL0NFUy1QcmVzcy1SZWxlYXNlLmFzcHg/Tm9kZUlEPWRiNzg1ZmE4LTc5YjEtNDFiNC04NDUwLThiNmJkYjg1MDQ2ZCI+TGVhZGVycyBpbiBUZWNobm9sb2d5IERpbm5lciw8L2E+IGFuIGludml0YXRpb24tb25seSBldmVudCBvbiBXZWRuZXNkYXksIEphbi4gOSwgaG9ub3JpbmcgdGhlIHRvcCB0ZWNobm9sb2dpc3RzLCBlbnRyZXByZW5ldXJzIGFuZCBwb2xpY3ltYWtlcnMgaGVscGluZyB0byBmdXJ0aGVyIHRlY2hub2xvZ3kgaW5ub3ZhdGlvbi4AZAIFD2QWAmYPZBYCZg8VCQAAAAkxMC80LzIwMTIkMjRlYjg1ZTUtMGViMy00ZmFkLWI1MWQtMWY5OTFhNGUzYTllUVZlcml6b24ncyBDaGFpcm1hbiBhbmQgQ0VPLCBMb3dlbGwgTWNBZGFtLCB0byBEZWxpdmVyIEtleW5vdGUgQWRkcmVzcyBhdCAyMDEzIENFU3J+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvTmV3cy9CdXp6d29ydGh5JTIwVGh1bWJuYWlscy8yazExQ0VTX1Zlcml6b25fTE0tQnV6endvcnRoeS5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMjUmZXh0PS5qcGfTBVRoZSBvcGVuaW5nIGRheSBvZiB0aGUgMjAxMyBJbnRlcm5hdGlvbmFsIENFUywgVHVlc2RheSwgSmFuLiA4LCB3aWxsIGtpY2sgb2ZmIGFuIGluY3JlZGlibGUgd2VlayBmb3IgdGhlIGNvbnN1bWVyIGVsZWN0cm9uaWNzIGluZHVzdHJ5LiBDRUEgaGFzIHJlY2VudGx5IGFubm91bmNlZCB0aGF0IExvd2VsbCBNY0FkYW0sIENoYWlybWFuIGFuZCBDRU8gb2YgVmVyaXpvbiwgd2lsbCBkZWxpdmVyIGEga2V5bm90ZSBhZGRyZXNzIG9uIFR1ZXNkYXkgYWZ0ZXJub29uLCBpbiBhZGRpdGlvbiB0byBrZXlub3RlcyBmcm9tIHRoZSBDb25zdW1lciBFbGVjdHJvbmljcyBBc3NvY2lhdGlvbiZyc3F1bztzIENFTyBHYXJ5IFNoYXBpcm8gYW5kIFBhbmFzb25pYyBDb3Jwb3JhdGlvbiZyc3F1bztzIFByZXNpZGVudCBLYXp1aGlybyBUc3VnYS4gJm5ic3A7TWNBZGFtIGN1cnJlbnRseSBvdmVyc2VlcyB0aGUgb3BlcmF0aW9ucyBvZiBWZXJpem9uIENvbW11bmljYXRpb25zLCBpbmNsdWRpbmcgYWxsIGJ1c2luZXNzIHVuaXRzIGFuZCBzdGFmZiBmdW5jdGlvbnMuUGxlYXNlIGpvaW4gdXMgb24gVHVlc2RheSwgSmFuLiA4IGluIHRoZSBQYWxhenpvIEJhbGxyb29tIGF0IFRoZSBWZW5ldGlhbiBmb3IgdGhpcyBleGNpdGluZyBrZXlub3RlIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9FdmVudHMvS2V5bm90ZXMvRGF5LU9uZS1BZnRlcm5vb24iPmFkZHJlc3M8L2E+LiZuYnNwOwBkAgYPZBYCZg9kFgJmDxUJAAAACTEwLzMvMjAxMiQ4YjJmNTQ0OC0yYzQxLTRiODEtYjMyYi0wNzg1NzVkMWQxYzYwSW50ZXJuYXRpb25hbCBHYXRld2F5IFNlbGxzIE91dCBhdCBUaGUgVmVuZXRpYW4gcH4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL0NFU19JbnRlcm5hdGluYWxHYXRld2F5XzE2NS5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMjUmZXh0PS5qcGfoBVRoZSBDb25zdW1lciBFbGVjdHJvbmljcyBBc3NvY2lhdGlvbiAoQ0VBKSA8YSBocmVmPSJodHRwOi8vd3d3LmNlc3dlYi5vcmcvTmV3cy9DRVMtUHJlc3MtUmVsZWFzZXMvQ0VTLVByZXNzLVJlbGVhc2UuYXNweD9Ob2RlSUQ9YzMzNjMwMjctZDA2My00NjRjLTkyNjctNGVmY2EzYTZhOGFjIj5hbm5vdW5jZWQgdG9kYXk8L2E+IHRoYXQgdGhlIEludGVybmF0aW9uYWwgR2F0ZXdheSBUZWNoWm9uZSBoYXMgc29sZCBvdXQgaW4gaXRzIG5ldyBsb2NhdGlvbiwgVGhlIFZlbmV0aWFuLCBhdCB0aGUgMjAxMyBJbnRlcm5hdGlvbmFsIENFUy48YnIgLz4NCjxiciAvPg0KVGhlIEludGVybmF0aW9uYWwgR2F0ZXdheSBhbGxvd3MgYXR0ZW5kZWVzIHRvIGV4cGFuZCB0aGVpciBnbG9iYWwgbmV0d29ya3MgYXQgQ0VTLiBUaGUgVGVjaFpvbmUgd2lsbCBmZWF0dXJlIG1vcmUgdGhhbiA0NjAgZXhoaWJpdG9ycyBpbiBIYWxsIEQgb2YgVGhlIFZlbmV0aWFuLCBzaG93Y2FzaW5nIGlubm92YXRpdmUgdGVjaG5vbG9naWVzIGFuZCBwcm9kdWN0cyBmcm9tIGludGVybmF0aW9uYWwgZGVzdGluYXRpb25zLCBpbmNsdWRpbmcgQ2hpbmEsIEtvcmVhLCBIb25nIEtvbmcgYW5kIFRhaXdhbi4gRHVlIHRvIHRoZSBzZWxsIG91dCBpbiBIYWxsIEQsIEludGVybmF0aW9uYWwgR2F0ZXdheSBleGhpYml0cyB3aWxsIGFsc28gYmUgZm91bmQgb24gTGV2ZWwgMSBhdCB0aGUgVmVuZXRpYW4sIGluIHRoZSBNYXJjbyBQb2xvIGJhbGxyb29tLgBkAgcPZBYCZg9kFgJmDxUJAAAACTEwLzMvMjAxMiRiMTM3NzkzNS1mNjNkLTQwMzItOTQ4MC0yMDQ3NDY2MzFmZjVMQ29uc3VtZXIgRWxlY3Ryb25pY3MgQXNzb2NpYXRpb24sIEdvb2dsZSB0byBTaGFyZSBJbnNpZ2h0cyBmcm9tIDIwMTIgRGViYXRlc29+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvTmV3cy9CdXp6d29ydGh5JTIwVGh1bWJuYWlscy8xMTA0N19EZWJhdGVzSFBTbGlkZS1TbWFsbC5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMjUmZXh0PS5qcGe2B1RoZSA8YSBocmVmPSJodHRwOi8vd3d3LmNlLm9yZyI+Q29uc3VtZXIgRWxlY3Ryb25pY3MgQXNzb2NpYXRpb248L2E+IChDRUEpIGFuZCA8YSBocmVmPSJodHRwOi8vd3d3Lmdvb2dsZS5jb20iPkdvb2dsZTwvYT4gYXJlIHBhcnRuZXJpbmcgb24gJmxkcXVvOzxhIGhyZWY9Imh0dHA6Ly93d3cuY2Uub3JnL05ld3MvTmV3cy1SZWxlYXNlcy9QcmVzcy1SZWxlYXNlcy8yMDEyLVByZXNzLVJlbGVhc2VzL0NFQS1hbmQtR29vZ2xlLVNob3djYXNlLVRlY2hub2xvZ3ktYXQtUHJlc2lkZW50aWFsLmFzcHgiPkluc2lnaHRzIGZyb20gdGhlIDIwMTIgRGViYXRlczwvYT4sJnJkcXVvOyBhIGpvaW50IGVmZm9ydCB0byBwcm92aWRlIHZvdGVycyB3aXRoIGluc2lnaHRmdWwgYW5kIGNvbXBlbGxpbmcgaW5mb3JtYXRpb24gYWJvdXQgdGhlIHByZXNpZGVudGlhbCBhbmQgdmljZSBwcmVzaWRlbnRpYWwgZGViYXRlcyB1c2luZyBHb29nbGUmcnNxdW87cyBpbm5vdmF0aXZlIHRlY2hub2xvZ2llcy4gSXQgd2lsbCBkZWJ1dCBkdXJpbmcgdG9uaWdodCZyc3F1bztzIGZpcnN0IGRlYmF0ZSBpbiBEZW52ZXIuPGJyIC8+DQo8YnIgLz4NClRoZSBlZmZvcnQgaW5jbHVkZXMgYSBzdGF0ZS1vZi10aGUtYXJ0IGRpZ2l0YWwgd2FsbCB0aGF0IGRpc3BsYXlzIHNlYXJjaCBhbmQgdmlkZW8gdHJlbmRzLCBpbnNpZ2h0cyBhbmQgY29uc3VtZXIgcmVzZWFyY2guIFRoZSBkaWdpdGFsIHdhbGwgZmVhdHVyZXMgdGhlIHRvcCBzZWFyY2ggdHJlbmRzIGFyb3VuZCB0aGUgZGViYXRlcyBhbmQgdXNlci1nZW5lcmF0ZWQgY29udGVudCBmcm9tIEdvb2dsZSsuIENoZWNrIG91dCBHb29nbGUmcnNxdW87cyA8YSBocmVmPSJodHRwOi8vd3d3Lmdvb2dsZS5jb20vZWxlY3Rpb25zL2VkL3VzIj5lbGVjdGlvbiBodWI8L2E+IGZvciBtb3JlIGluZm9ybWF0aW9uIG9uIHRoZSAyMDEyIGVsZWN0aW9uLjxiciAvPg0KBjwvZGl2PmQCCA9kFgJmD2QWAmYPFQkiPGRpdiBjbGFzcz0nbmV3c190YWInIGlkPSduZXdzXzMnIBVzdHlsZT0nZGlzcGxheTpub25lOycBPgkxMC8yLzIwMTIkOTE4NjBkYzUtYTc0Yi00MGRiLTg1NGMtY2UxZmM1ZGM3MzEzV0RCTCBEaXN0cmlidXRpbmcgRm91bmRlciBEYXZpZCBMb3JzY2ggaXMgRmluYWxpc3QgZm9yICAyMDEyIEV4ZWN1dGl2ZSBvZiB0aGUgWWVhciBBd2FyZGF+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvTmV3cy9CdXp6d29ydGh5JTIwVGh1bWJuYWlscy9EYXZpZC1Mb3JzY2guanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTI1JmV4dD0uanBnighXaGVuIGhlIHN0YXJ0ZWQgREJMIERpc3RyaWJ1dGluZyBpbiAxOTg5LCBEYXZpZCBMb3JzY2ggc2F3IGFuIGV4Y2l0aW5nIGJ1c2luZXNzIG9wcG9ydHVuaXR5IHRvIHNlcnZlIGFuIHVudG91Y2hlZCBtYXJrZXQgaW4gdGhlIFdlc3QuIE5vdyBoZSBpcyBhIGZpbmFsaXN0IHRvIGJlIG5hbWVkIDIwMTIgRXhlY3V0aXZlIG9mIHRoZSBZZWFyIGluIHRoZSBJbm5vdmF0aW9uIEVudHJlcHJlbmV1ciBBd2FyZHMuIDxhIGhyZWY9Imh0dHA6Ly95b3V0dS5iZS9wY25IYXl1eTNGdyI+SGVhciBtb3JlPC9hPiBmcm9tIERhdmlkIGFib3V0IGhpcyBwYXRoIHRvIHN1Y2Nlc3MgYW5kIGhvdyBoZSB1c2VkIENFUyB0byBncm93IGhpcyBidXNpbmVzcy48YnIgLz4NCjxiciAvPg0KVGhlIGZpcnN0IGFubnVhbDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Uub3JnL05ld3MvTmV3cy1SZWxlYXNlcy9QcmVzcy1SZWxlYXNlcy8yMDEyLVByZXNzLVJlbGVhc2VzL0NFQS1Bbm5vdW5jZXMtRmluYWxpc3RzLWZvci1JbmF1Z3VyYWwtSW5ub3ZhdGlvbi1FLmFzcHgiPiBJbm5vdmF0aW9uIEVudHJlcHJlbmV1ciBBd2FyZHM8L2E+LCBzcG9uc29yZWQgYnkgdGhlIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Uub3JnIj5Db25zdW1lciBFbGVjdHJvbmljcyBBc3NvY2lhdGlvbiYjMzk7cyAoQ0VBKTwvYT4gbmV3IGZsYWdzaGlwIHB1YmxpY2F0aW9uIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Uub3JnL2kzIj5JdCBJcyBJbm5vdmF0aW9uIChpMyk8L2E+IGFuZCBDRUEmIzM5O3MgU21hbGwgQnVzaW5lc3MgQ291bmNpbCwgaG9ub3JzIGV4Y2VsbGVuY2UgaW4gZW50cmVwcmVuZXVyc2hpcCBhbmQgcmVjb2duaXplcyB2aXNpb25hcmllcyBsZWFkaW5nIGJ1c2luZXNzZXMgd2l0aCByZXZlbnVlcyB1bmRlciAkMzAgbWlsbGlvbi4gV2lubmVycyB3aWxsIGJlIGFubm91bmNlZCBhdCB0aGUgdXBjb21pbmcgPGEgaHJlZj0iaHR0cDovL3d3dy5jZS5vcmcvaW5kdXN0cnlmb3J1bSI+Q0VBIEluZHVzdHJ5IEZvcnVtPC9hPiBpbiBTYW4gRnJhbmNpc2NvLiAmdGhpbnNwOwBkAgkPZBYCZg9kFgJmDxUJAAAACTEwLzIvMjAxMiQxZDQyMDlhMy1mOTYzLTQ2MmEtYTU4ZS03NTc3ZDM4ODQyMmQzTmV3IGF0IENFUzogR3VpZGVkIFRvdXJzIGZvciB0aGUgU3RhcnQtdXAgQ29tbXVuaXR5X34vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL0V1cmVrYVBhcmsuanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTI1JmV4dD0uanBn1gVEaXNjb3ZlciB0ZWNoLXNwcm91dGluZyBzdGFydC11cHMgYW5kIGZyb20tdGhlLWdhcmFnZSBpbm5vdmF0b3JzIG9uIGEgZmFzdC1wYWNlZCwgZ3VpZGVkIHRvdXIgb2YgdGhlIEV1cmVrYSBQYXJrIFRlY2hab25lLCBhIG9uZS1zdG9wIGRlc3RpbmF0aW9uIGF0IHRoZSAyMDEzIEludGVybmF0aW9uYWwgQ0VTIHRoYXQgZmVhdHVyZXMgYWxsIGVhcmx5LXN0YWdlIGNvbXBhbmllcyBnZW5lcmF0aW5nIHRvbW9ycm93JiMzOTtzIGJpZ2dlc3QgaWRlYXMuPGJyIC8+DQo8YnIgLz4NCkV4Y2x1c2l2ZSBmb3IgdmVudHVyZSBjYXBpdGFsaXN0cywgZmluYW5jaWFsIGFuYWx5c3RzLCBlbnRyZXByZW5ldXJzIGFuZCBmb3VuZGVycywgdGhpcyB0d28taG91ciBpbm5vdmF0aW9uIGltbWVyc2lvbiBpbmNsdWRlcyBhIGJyaWVmIG92ZXJ2aWV3IG9mIHRoZSBleGhpYml0cywgYSBwcml2YXRlIHRvdXIgb2Ygc2VsZWN0IEV1cmVrYSBQYXJrIGV4aGliaXRvcnMgYW5kIGEgYnVzaW5lc3MtYm9vc3RpbmcgbmV0d29ya2luZyByZWNlcHRpb24gd2l0aCBmZWxsb3cgdG91ci10YWtlcnMgYW5kIGFsbCBvZiB0aGUgRXVyZWthIFBhcmsgZXhoaWJpdG9ycy4gRS1tYWlsIHVzIGF0IDxhIGhyZWY9Im1haWx0bzpDRVN0b3Vyc0BDRS5vcmc/c3ViamVjdD1DRVMlMjBHdWlkZWQlMjBUb3VycyUyMGF0JTIwRXVyZWthJTIwUGFyayI+Q0VTdG91cnNAQ0Uub3JnPC9hPiBmb3IgbW9yZSBpbmZvcm1hdGlvbi4AZAIKD2QWAmYPZBYCZg8VCQAAAAk5LzI2LzIwMTIkYjVmOGU1NmEtNDY5Yi00YjJmLWIzOWItZjg2OTVjZTJkZDI5Rkpha2UgU2lnYWwsIEZvdW5kZXIgYW5kIENFTyBvZiBMaXZpbyBSYWRpbywgU2hhcmVzIEhpcyBCZXN0IENFUyBNZW1vcnldfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL05ld3MvQnV6endvcnRoeSUyMFRodW1ibmFpbHMvaGVhZHNob3QucG5nP3dpZHRoPTE2NSZoZWlnaHQ9MTI1JmV4dD0ucG5nnAQ8c3BhbiBzdHlsZT0iZm9udC1zaXplOjEycHg7Ij4mcXVvdDtNeSBiZXN0IG1lbW9yeSB3YXMgQ0VTIDIwMDguIEkgc3RhcnRlZCBMaXZpbyBhIGZldyBkYXlzJnJzcXVvOyBlYXJsaWVyLCBwcmludGVkIGJ1c2luZXNzIGNhcmRzIGFuZCB3YXMgb2ZmIHRvIHRoZSBzaG93IHdpdGggbm8gaWRlYSBleGFjdGx5IHdoYXQgSSB3YXMgZ29pbmcgdG8gZG8uIEFsbCBJIGhhZCBzY2hlZHVsZWQgd2FzIGEgZmV3IG1lZXRpbmdzIHdpdGggcGVvcGxlIEkgdXNlZCB0byB3b3JrIHdpdGggZnJvbSBwcmV2aW91cyBqb2JzLiBPbmUgb2YgdGhvc2UgbWVldGluZ3Mgd2FzIHdpdGggYSBsaXR0bGUgY29tcGFueSBjYWxsZWQgUGFuZG9yYS4gVGhlIHJlc3QgaXMgaGlzdG9yeS4mcXVvdDsgPGEgaHJlZj0iaHR0cDovL2Jsb2cuY2Uub3JnL2luZGV4LnBocC8yMDEyLzA5LzI1L2dldC10by1rbm93LXlvdXItaW5kdXN0cnktZm9ydW0tc3BlYWtlcnMtamFrZS1zaWdhbC8iPlJlYWQgbW9yZSBmcm9tIEpha2U8L2E+Ljwvc3Bhbj48YnIgLz4NCjxiciAvPg0KPGJyIC8+DQoAZAILD2QWAmYPZBYCZg8VCQAAAAk5LzI1LzIwMTIkYjBiNDg0ZTMtZDNmMS00NWEyLTg3ZWItNzZkZGFkNTUyYWVjI0FkbWlzc2lvbiB0byBDRVMgaXMgTm93IGluIHRoZSBNYWlsYX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL01haWxlclRlYXNlci5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMjUmZXh0PS5qcGe7A0lmIHlvdSZyc3F1bzt2ZSBhbHJlYWR5IHJlZ2lzdGVyZWQgZm9yIENFUywga2VlcCBhbiBleWUgb24geW91ciBtYWlsYm94IGF0IGhvbWUgYmVjYXVzZSBhZG1pc3Npb24gYmFkZ2VzIGFyZSBhbHJlYWR5IG9uIHRoZSB3YXkuIEl0JnJzcXVvO3MgaW1wb3J0YW50IHRoYXQgeW91IGhvbGQgb250byB5b3VyIGJhZGdlIG9uY2UgeW91IHJlY2VpdmUgaXQgdG8gZW5zdXJlIHlvdXIgZW50cnkgaW50byBDRVMsIHRoZSB3b3JsZCYjMzk7cyBsYXJnZXN0IGNvbnN1bWVyIHRlY2hub2xvZ3kgdHJhZGVzaG93LiBXaGVuIHlvdSBhcnJpdmUgaW4gSmFudWFyeSwgeW91IGNhbiBnbyB0byB0aGUgPGEgaHJlZj0ifi9GQVEvR2VuZXJhbC5hc3B4I2p1bXB0bzMtNyI+bmVhcmVzdCBCYWRnZSBIb2xkZXJzIFBpY2t1cCBsb2NhdGlvbjwvYT4gdG8gcmVjZWl2ZSB5b3VyIGJhZGdlIGhvbGRlci4gBjwvZGl2PmQCDA9kFgJmD2QWAmYPFQkiPGRpdiBjbGFzcz0nbmV3c190YWInIGlkPSduZXdzXzQnIBVzdHlsZT0nZGlzcGxheTpub25lOycBPgk4LzMwLzIwMTIkYmI3NGVmMzctNjM1Yy00MDdiLWFjNTctZDliMzdlMjhjZjBiI0Jvb2sgSG90ZWwgUm9vbXMgTm93IGZvciBCZXN0IFJhdGVzan4vY2Vzd2ViL21lZGlhL0NFU1dlYi9Ib3RlbCUyMGFuZCUyMFRyYXZlbCUyMEltYWdlcy9Ib3RlbHMvU3RyaXBfMTY1eDEyNS5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMjUmZXh0PS5qcGfNA1RoZXJlJiMzOTtzIG5vIHF1ZXN0aW9uIHRoYXQgTGFzIFZlZ2FzIGlzIGJ1c2llc3Qgd2hlbiBDRVMgaXMgaW4gdG93bi4gVGhhdCBtZWFucyBob3RlbCByb29tcyBmaWxsIHF1aWNrbHkuIDxhIGhyZWY9Imh0dHA6Ly9jZXN3ZWIub3JnL0hvdGVsLVRyYXZlbC9Ib3RlbC1SZXNlcnZhdGlvbnMuYXNweCI+Qm9vayB5b3VyIHJvb20gdG9kYXk8L2E+PHNwYW4gc3R5bGU9InRleHQtZGVjb3JhdGlvbjogdW5kZXJsaW5lOyI+IDwvc3Bhbj5hbmQgYXZvaWQgdGhlICZsZHF1bztzb2xkIG91dCZyZHF1bzsgc2lnbnMuIENFUyBtYWtlcyBpdCBlYXN5IGZvciB5b3UgYnkgbGlzdGluZyByYXRlcywgYXZhaWxhYmlsaXR5IGFuZCBkaXNjb3VudCBjb2RlcyA8YSBocmVmPSJodHRwOi8vY2Vzd2ViLm9yZy9Ib3RlbC1UcmF2ZWwvSG90ZWwtUmVzZXJ2YXRpb25zLmFzcHgiPmFsbCBpbiBvbmUgcGxhY2U8L2E+LjxiciAvPg0KAGQCDQ9kFgJmD2QWAmYPFQkAAAAJOC8yOS8yMDEyJGY1ZGYyMDU1LWM5ODYtNGM0Ny1iMWUxLWI2MmQ2ZmUxODZhZjJGcmVlIENFUyBSZWdpc3RyYXRpb246IEp1c3QgYSBIYW5kZnVsIG9mIERheXMgTGVmdGR+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvMjI2eDIwMCUyMEJhbm5lciUyMEFkcy9TYXZlX3RoZV9kYXRlXzIyNngyMDAuanBnP3dpZHRoPTIyNiZoZWlnaHQ9MjAwJmV4dD0uanBnuwJSZWdpc3RlciBub3cgYmVmb3JlIHRoZSBmZWVzIGluY3JlYXNlIHRvICQxMDAgb24gU2F0dXJkYXksIFNlcHRlbWJlciAxIGFuZCB0byAkMjAwIG9uIEphbnVhcnkgMiE8YnIgLz4NCiZuYnNwOzxiciAvPg0KV2l0aCBtb3JlIHRoYW4gZm91ciBkZWNhZGVzIG9mIHN1Y2Nlc3MsIHRoZSBJbnRlcm5hdGlvbmFsIENvbnN1bWVyIEVsZWN0cm9uaWNzIFNob3cgKENFUykgcmVhY2hlcyBhY3Jvc3MgZ2xvYmFsIG1hcmtldHMsIGNvbm5lY3RzIHRoZSBpbmR1c3RyeSBhbmQgZW5hYmxlcyBDRSBpbm5vdmF0aW9ucyB0byBncm93IGFuZCB0aHJpdmUuPGJyIC8+DQoAZAIOD2QWAmYPZBYCZg8VCQAAAAk4LzEzLzIwMTIkY2Q2NThhMDMtOGY3ZS00NGQ3LWEzYTMtZGUxNTk0ZWNmODczZ0NhbGwgZm9yIEVudHJpZXMgT3BlbiBmb3IgSW5ub3ZhdGlvbnMgMjAxMyBEZXNpZ24gYW5kIEVuZ2luZWVyaW5nIEF3YXJkcyBIb25vcmluZyBCZXN0IGluIENFIElubm92YXRpb25gfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL0lubm92YXRpb24lMjBBd2FyZHMvSW5ub3ZhdGlvbnNfMjAxM19SU1MuanBnP3dpZHRoPTE3NyZoZWlnaHQ9MTUyJmV4dD0uanBnsgZUaGUgaW5kdXN0cnktcmVjb2duaXplZCBhbm51YWwgY29tcGV0aXRpb24gaG9ub3JzIG91dHN0YW5kaW5nIGRlc2lnbiBhbmQgZW5naW5lZXJpbmcgYWNyb3NzJm5ic3A7PGEgaHJlZj0iaHR0cDovL2Nlc3dlYi5vcmcvQXdhcmRzL0NFUy1Jbm5vdmF0aW9ucy1Bd2FyZHMvQXdhcmRzLUNhdGVnb3JpZXMuYXNweCI+PHU+MjkgY29uc3VtZXIgZWxlY3Ryb25pY3MgY2F0ZWdvcmllczwvdT48L2E+LiBUd28gbmV3IHByb2R1Y3QgY2F0ZWdvcmllcyB3ZXJlIGFkZGVkIHRvIHRoZSAyMDEzIGF3YXJkcyBwcm9ncmFtOiBUZWNoIGZvciBhIEJldHRlciBXb3JsZCBhbmQgQWNjZXNzaWJsZSBhbmQgVW5pdmVyc2FsIERlc2lnbiBUZWNobm9sb2dpZXMuIFRlY2ggZm9yIGEgQmV0dGVyIFdvcmxkIHJlY29nbml6ZXMgdGVjaG5vbG9naWVzIHRoYXQgc2hhcmUgYSBjb21tb24gZ29hbCBhbmQgdGhlIGFiaWxpdHkgdG8gaW1wYWN0IHRoZSB3b3JsZCBpbiBhIHBvc2l0aXZlIHdheSwgZWl0aGVyIGRvbWVzdGljYWxseSwgb3IgYXJvdW5kIHRoZSBnbG9iZS4gQWNjZXNzaWJsZSBhbmQgVW5pdmVyc2FsIERlc2lnbiBUZWNobm9sb2dpZXMgZm9jdXNlcyBvbiB0ZWNobm9sb2dpZXMgdGhhdCBoYXZlIGlubm92YXRpdmUgZmVhdHVyZXMgdGhhdCBlbmFibGUgZWFzZSBvZiB1c2UgYnkgYW55b25lLCBpbmNsdWRpbmcsIGJ1dCBub3QgbGltaXRlZCB0bywgc2VuaW9ycyBhbmQgcGVvcGxlIHdpdGggZGlzYWJpbGl0aWVzLCByZWdhcmRsZXNzIG9mIGNvZ25pdGl2ZSBhYmlsaXR5LCBoZWFyaW5nLCBtb2JpbGl0eSwgdmlzdWFsIG9yIG90aGVyIGltcGFpcm1lbnRzLgBkAg8PZBYCZg9kFgJmDxUJAAAACTcvMjMvMjAxMiQ2OThhNDhiMC1lMGFhLTRjOGUtODI4OC1jNzhhZjNlNWM0ZDQ+Sm9pbiBFbGl0ZSBQcm9mZXNzaW9uYWxzIFdobyBKdWRnZSB0aGUgQmVzdCBJbm5vdmF0aW9ucyBhdCBDRVNgfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL0lubm92YXRpb24lMjBBd2FyZHMvSW5ub3ZhdGlvbnNfMjAxM19SU1MuanBnP3dpZHRoPTE3NyZoZWlnaHQ9MTUyJmV4dD0uanBn0wJEZWZpbmUgd2hlcmUgaW52ZW50aW9uIGFuZCBleGVjdXRpb24gdGFrZSBmbGlnaHQhIEpvaW4gdGhlIGVsaXRlIHBhbmVsIG9mIGluZHVzdHJ5IHByb2Zlc3Npb25hbHMgd2hvIGp1ZGdlIHRoZSBiZXN0IGlubm92YXRpb24gYXQgdGhlIDIwMTMgSW50ZXJuYXRpb25hbCBDRVMhIEhlbHAgZGVjaWRlIHdoaWNoIHN0dW5uaW5nIG5ldyBpZGVhcyBnbyBhYm92ZSBhbmQgYmV5b25kIGluIGRlc2lnbiBhbmQgZW5naW5lZXJpbmcgdG8gbWFrZSBpdCBhcyBhbiZuYnNwOzxhIGhyZWY9In4vQXdhcmRzL0NFUy1Jbm5vdmF0aW9ucy1Bd2FyZHMvMjAxMi5hc3B4Ij5Jbm5vdmF0aW9ucyBIb25vcmVlPC9hPi4GPC9kaXY+ZAIBD2QWAgICD2QWIGYPZBYCZg9kFgJmDxUDFzxsaSBpZD0nbmV3c18xX2J1dHRvbicgD2NsYXNzPSdvbl9wYWdlJz4gPjxhIG9uY2xpY2s9InJldHVybiBuZXdzQWN0aXZlKCduZXdzXzEnKTsiIGhyZWY9Jyc+MTwvYT48L2xpPmQCAQ9kFgJmD2QWAmYPFQMAAABkAgIPZBYCZg9kFgJmDxUDAAAAZAIDD2QWAmYPZBYCZg8VAwAAAGQCBA9kFgJmD2QWAmYPFQMXPGxpIGlkPSduZXdzXzJfYnV0dG9uJyAAPiA+PGEgb25jbGljaz0icmV0dXJuIG5ld3NBY3RpdmUoJ25ld3NfMicpOyIgaHJlZj0nJz4yPC9hPjwvbGk+ZAIFD2QWAmYPZBYCZg8VAwAAAGQCBg9kFgJmD2QWAmYPFQMAAABkAgcPZBYCZg9kFgJmDxUDAAAAZAIID2QWAmYPZBYCZg8VAxc8bGkgaWQ9J25ld3NfM19idXR0b24nIAA+ID48YSBvbmNsaWNrPSJyZXR1cm4gbmV3c0FjdGl2ZSgnbmV3c18zJyk7IiBocmVmPScnPjM8L2E+PC9saT5kAgkPZBYCZg9kFgJmDxUDAAAAZAIKD2QWAmYPZBYCZg8VAwAAAGQCCw9kFgJmD2QWAmYPFQMAAABkAgwPZBYCZg9kFgJmDxUDFzxsaSBpZD0nbmV3c180X2J1dHRvbicgAD4gPjxhIG9uY2xpY2s9InJldHVybiBuZXdzQWN0aXZlKCduZXdzXzQnKTsiIGhyZWY9Jyc+NDwvYT48L2xpPmQCDQ9kFgJmD2QWAmYPFQMAAABkAg4PZBYCZg9kFgJmDxUDAAAAZAIPD2QWAmYPZBYCZg8VAwAAAGQCBw9kFgJmD2QWAgICD2QWCGYPZBYCZg9kFgJmDxUCHmh0dHA6Ly9jZXN3ZWIub3JnL2JyYW5kbWF0dGVyc11+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzL0JyYW5kTWF0dGVyc18yMjB4NTcuanBnP3dpZHRoPTIyMCZoZWlnaHQ9NTcmZXh0PS5qcGdkAgEPZBYCZg9kFgJmDxUCHy9TaG93LUZsb29yL0NFUy1Nb2JpbGUtQXBwLmFzcHhffi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL0NFUyUyME1vYmlsZSUyMEFwcC9DRVNNb2JpbGViYW5uZXIyMjB4NTcuanBnP3dpZHRoPTIyMCZoZWlnaHQ9NTcmZXh0PS5qcGdkAgIPZBYCZg9kFgJmDxUCE2h0dHA6Ly9ibG9nLmNlLm9yZy9Yfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL2Fzc2V0cy9pbWFnZXMvZXh0cmFzL2RpZy1kaWFsb2d1ZS5qcGc/d2lkdGg9MjIwJmhlaWdodD01NyZleHQ9LmpwZ2QCAw9kFgJmD2QWAmYPFQIhaHR0cDovL2Nlc3dlYi5vcmcvY2VzZ3JlZW5pbmcuYXNwVX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9hc3NldHMvaW1hZ2VzL2V4dHJhcy9jZXMtZ3JlZW4uanBnP3dpZHRoPTIyMCZoZWlnaHQ9NTcmZXh0PS5qcGdkZJPir49hqq/HsrbJ2LtdPUWslbL490EKvxGiV8vjvP1S" />
</div>

<input type="hidden" name="lng" id="lng" value="en-US" />
<script src="/ScriptResource.axd?d=N6Jl9XMQzDo-M2VzrTGsHPZJGE_S0b4WAFqG2dSX7CkNtipRz9-bk6m1eCad7PfvRzztBSdjlldijvTkzJwz-B7gytD2o4JDVsEtYwIA_if0EqaKmLOMsnSmleNoFWfh0&amp;t=34d147fd" type="text/javascript"></script>
    <div id="CMSHeaderDiv">
	<!-- -->
</div>
    <script type="text/javascript" src="/cesweb/media/CESWeb/assets/js/custom/functions.js"></script>
<!-- start black bar -->
            <div id="header-wrapper">
		<div id="header-top-wrapper">
			<div id="header-top">
				<div id="header-more-sites">
					<div id="header-more-expander">
						<ul>
                                                	<li><a href="http://www.ce.org">CEA - CE.org</a></li><li><a href="http://www.cesweb.org">International CES</a></li><li><a href="http://www.declareinnovation.com">Innovation Movement</a></li><li><a href="http://blog.ce.org">Digital Dialogue</a></li><li><a href="http://www.cevision.org">Vision Magazine</a></li><li><a href="http://www.greenergadgets.org">Greener Gadgets</a></li><li><a href="http://research.ce.org">Market Research</a></li>


						</ul>
						<a id="the-expander" href="#">More CEA sites</a>
					</div>
				</div>
				<div id="header-feed">
				</div>
			</div>
		</div>
            </div>
<!-- end black bar -->
<div id="newwrap">
    <div id="container">
        <div id="content-container">
            <div id="header">
                <div id="logo">
                    <a href="/Home.aspx"><img id="p_lt_zoneLogo_EditableImage_imgImage" src="/cesweb/media/CESWeb/assets/images/header/cesweb_headerlogo.png" alt="" /></a>
                </div>
                <div id="headTop">
                    <div id="topsearch">
                                    <input type="hidden" id="Hidden1" value="default_collection" name="site" />
            <input type="hidden" id="Hidden2" value="2011CESweb" name="client" />
            <input type="hidden" id="Hidden3" value="2011CESweb" name="proxystylesheet" />
            <input type="hidden" id="Hidden4" value="xml_no_dtd" name="output" />
<input class="searchbox" id="searchbox" name="q" onblur="if(this.value=='') this.value='Search';" onfocus="if(this.value=='Search') this.value='';" type="text" value="Search" />
                		<!-- Pyxl ADD search from below-->
						<!--        <form action="http://googlebox.ce.org/search?" method="GET" name="searchCES">
						            <input type="hidden" id="Hidden1" value="default_collection" name="site">
						            <input type="hidden" id="Hidden2" value="2011CESweb" name="client">
						            <input type="hidden" id="Hidden3" value="2011CESweb" name="proxystylesheet">
						            <input type="hidden" id="Hidden4" value="xml_no_dtd" name="output">
						            <input type="text" onfocus="if(this.value=='Search') this.value='';" onblur="if(this.value=='') this.value='Search';" value="Search" class="searchbox" name="q"><input type="submit" onclick="document.searchCES.submit();" class="searchbutton" value="">
						            </form> 
						<A href="http://www.cesweb.org/cesgreening.asp"><img src="http://www.cesweb.org/hp/images/ces-green.jpg" border="0" valign=top ></A>
					</div>
						    <div id="topimages">
						        <img src="http://www.cesweb.org/hp/images/divider.jpg" class="divider"/>
						         <a href=http://www.cesweb.org/socialcircle target="_blank"><img src="http://www.cesweb.org/hp/images/socialcircle.aspx" alt="Social Circle" /></a>
						&nbsp;&nbsp;&nbsp;&nbsp;-->
	             </div>
                </div>
                <div class="clr"></div>
                <div id="ctacontainer">
                    <div id="showdate"> <img id="p_lt_zoneShowDate_EditableImage1_imgImage" src="/cesweb/media/CESWeb/assets/images/header/CESweb_headerdate.png" alt="" /> </div>
                    <div id="register">
	<a href="/Register.aspx" target="_blank" title="Register for CES"><img alt="Register" border="0" name="cesweb_register" onmouseout="out(8)" onmouseover="over(8)" src="/cesweb/media/CESWeb/assets/images/nav/cesweb_register1.png" /></a></div>
<div id="exhibit">
	<a href="/For-Exhibitors/Exhibit-at-CES.aspx" title="Exhibit at CES"><img alt="Exhibit at CES" border="0" name="cesweb_exhibit" onmouseout="out(9)" onmouseover="over(9)" src="/cesweb/media/CESWeb/assets/images/nav/cesweb_exhibit1.png" /></a></div>

                </div>
            </div>
            <div style="display: none;">/followme.asp/exhibitor-directory.asp/cesgreening.asp/registration.asp/searchResults.asp/error404.asp/partners.asp/contactus.asp/sitemap.asp/privacyPolicy.asp/aboutces.asp/myCES.asp/aboutcea.asp</div>
			<div id="nav-bar">
                
	<ul class="level1CMSListMenuUL" id="topnav">
		<li class="level1CMSListMenuLI ExhibitorDirectory" style=""><a href="http://ces13.mapyourshow.com/5_0/search.cfm?" class="level1CMSListMenuLink" style="">Exhibitor Directory</a></li>
		<li class="level1CMSListMenuLI ConferenceProgram"><a href="/Conference-Program.aspx" class="level1CMSListMenuLink">Conference Program</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Conference-Tracks.aspx" class="level2CMSListMenuLink">Conference Tracks</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/SuperSessions.aspx" class="level2CMSListMenuLink">SuperSessions</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Session-Schedule.aspx" class="level2CMSListMenuLink">Session Schedule</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Speaker-Directory.aspx" class="level2CMSListMenuLink">Speaker Directory</a></li>
			<li class="level2CMSListMenuLI" style=""><a href="/Conference-Program/Conference-Pricing.aspx" class="level2CMSListMenuLink" style="">Conference Pricing</a></li>
			<li class="hassub"><a href="/Conference-Program/Call-for-Speakers.aspx" class="level2CMSListMenuLink">Call for Speakers</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI last "><a href="/Conference-Program/Call-for-Speakers/Submission-FAQs.aspx" class="level3CMSListMenuLink">Submission FAQs</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI last "><a href="/Conference-Program/Speaker-Services.aspx" class="level2CMSListMenuLink">Speaker Services</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI Events"><a href="/Events.aspx" class="level1CMSListMenuLink">Events</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Events/Cea-Events.aspx" class="level2CMSListMenuLink">CEA Events</a></li>
			<li class="level2CMSListMenuLI"><a href="/Events/SINOCES.aspx" class="level2CMSListMenuLink">SINOCES</a></li>
			<li class="level2CMSListMenuLI"><a href="/Events/Keynotes.aspx" class="level2CMSListMenuLink">Keynotes</a></li>
			<li class="level2CMSListMenuLI"><a href="/Events/Last-Gadget-Standing.aspx" class="level2CMSListMenuLink">Last Gadget Standing</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Events/Mobile-Apps-Showdown.aspx" class="level2CMSListMenuLink">Mobile Apps Showdown</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI Awards"><a href="/Awards.aspx" class="level1CMSListMenuLink">Awards</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Awards/CNET-Best-Of.aspx" class="level2CMSListMenuLink">CNET Best Of CES</a></li>
			<li class="hassub"><a href="/Awards/CES-Innovations-Awards.aspx" class="level2CMSListMenuLink">CES Innovations Awards</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/About-Innovations.aspx" class="level3CMSListMenuLink">About Innovations</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/Awards-Categories.aspx" class="level3CMSListMenuLink">Awards Categories</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/Call-for-Entries.aspx" class="level3CMSListMenuLink">Call for Entries</a></li>
				<li class="level3CMSListMenuLI last "><a href="/Awards/CES-Innovations-Awards/Call-for-Judges.aspx" class="level3CMSListMenuLink">Call for Judges</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI"><a href="/Awards/IAWTV-Awards.aspx" class="level2CMSListMenuLink">IAWTV Awards</a></li>
			<li class="level2CMSListMenuLI"><a href="/Awards/Hot-Stuff-Awards.aspx" class="level2CMSListMenuLink">Hot Stuff Awards</a></li>
			<li class="level2CMSListMenuLI"><a href="/Awards/Stars-of-CES.aspx" class="level2CMSListMenuLink">The 2013 What HI-FI? Sound and Vision Stars of CES </a></li>
			<li class="level2CMSListMenuLI last "><a href="/Awards/Tech-Engineering-Emmy-Awards.aspx" class="level2CMSListMenuLink">Technology &amp; Engineering Emmy(r) Awards</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI ShowFloor"><a href="/Show-Floor.aspx" class="level1CMSListMenuLink">Show Floor</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/By-Exhibit-Halls.aspx" class="level2CMSListMenuLink">By Exhibit Hall</a></li>
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/By-Product-Category.aspx" class="level2CMSListMenuLink">By Product Category</a></li>
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/CES-TechZones.aspx" class="level2CMSListMenuLink">CES TechZones</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Show-Floor/CES-Mobile-App.aspx" class="level2CMSListMenuLink">CES Mobile App</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI HotelTravel"><a href="/Hotel-Travel.aspx" class="level1CMSListMenuLink">Hotel/Travel</a>
		<ul class="subnav">
			<li class="level2CMSListMenuHighlightedLI"><a href="/Hotel-Travel/Hotel-Reservations.aspx" class="level2CMSListMenuLinkHighlighted">Hotel Reservations</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/CES-Block-Request-Form.aspx" class="level2CMSListMenuLink">CES Block Request Form</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Airline-Discounts.aspx" class="level2CMSListMenuLink">Airline Discounts</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/CES-Shuttle-Service.aspx" class="level2CMSListMenuLink">CES Shuttle Service</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Las-Vegas-Monorail.aspx" class="level2CMSListMenuLink">Las Vegas Monorail</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Transportation,-Parking,-and-Car-Rental.aspx" class="level2CMSListMenuLink">Transportation, Parking, and Car Rental</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Hotel-Travel/Las-Vegas-Travel-Tips.aspx" class="level2CMSListMenuLink">Las Vegas Travel Tips</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI News"><a href="/News.aspx" class="level1CMSListMenuLink">News</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/News/News-Feed.aspx" class="level2CMSListMenuLink">News Feed</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/Exhibitor-Releases.aspx" class="level2CMSListMenuLink">Exhibitor Releases</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/CES-Press-Releases.aspx" class="level2CMSListMenuLink">CES Press Releases</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/Media-Coverage.aspx" class="level2CMSListMenuLink">Media Coverage</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/Multimedia-Gallery.aspx" class="level2CMSListMenuLink">Multimedia Gallery</a></li>
			<li class="hassub"><a href="/News/Newsletters.aspx" class="level2CMSListMenuLink">Newsletters</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/News/Newsletters/CES-Up-to-the-Minute.aspx" class="level3CMSListMenuLink">CES Up to the Minute</a></li>
				<li class="level3CMSListMenuLI" style=""><a href="/For-Exhibitors/Exhibitor-Source-Newsletter.aspx" class="level3CMSListMenuLink" style="">Exhibitor&#39;s Source Newsletter</a></li>
				<li class="level3CMSListMenuLI"><a href="/News/Newsletters/Exhibitor-PR-Newsletter.aspx" class="level3CMSListMenuLink">Exhibitor PR Newsletter</a></li>
				<li class="level3CMSListMenuLI last "><a href="/News/Newsletters/CES-Partner-Connection.aspx" class="level3CMSListMenuLink">CES Partner Connection</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI last " style=""><a href="/For-the-Press.aspx" class="level2CMSListMenuLink" style="">Press Services</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI last "><a href="/FAQ.aspx" class="level1CMSListMenuLink">FAQ</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/FAQ/General.aspx" class="level2CMSListMenuLink">General</a></li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Press.aspx" class="level2CMSListMenuLink">Press</a></li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Exhibitor.aspx" class="level2CMSListMenuLink">Exhibitor</a></li>
			<li class="hassub"><a href="/FAQ/FAQs-by-Venue.aspx" class="level2CMSListMenuLink">FAQs by Venue</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/FAQ/FAQs-by-Venue/Las-Vegas-Convention-Center.aspx" class="level3CMSListMenuLink">Las Vegas Convention Center</a></li>
				<li class="level3CMSListMenuLI"><a href="/FAQ/FAQs-by-Venue/The-Venetian.aspx" class="level3CMSListMenuLink">The Venetian</a></li>
				<li class="level3CMSListMenuLI"><a href="/FAQ/FAQs-by-Venue/Las-Vegas-Hilton.aspx" class="level3CMSListMenuLink">Las Vegas Hotel (LVH)</a></li>
				<li class="level3CMSListMenuLI last "><a href="/FAQ/FAQs-by-Venue/Renaissance-Hotel.aspx" class="level3CMSListMenuLink">Renaissance Hotel</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Speaker.aspx" class="level2CMSListMenuLink">Speaker</a></li>
			<li class="level2CMSListMenuLI last "><a href="/FAQ/First-Timer-ResourCES.aspx" class="level2CMSListMenuLink">First-Timer ResourCES</a></li>
		</ul>
		</li>
	</ul>
        
			    
			</div>
		</div>
	</div>
    <div class="container-home">
    	
 

<div id="slideshow" >
<div id="slideshow" >
    <div id="lofslidecontent45" class="lof-slidecontent">
        <div class="preload"><div></div>
    </div>
    <!-- MAIN CONTENT --> 
    <div class="lof-previous" href="" onclick="return false">Previous</div>
    <div class="lof-next" href="" onclick="return false">Next</div>    
    <div class="lof-main-outer">
        <ul class="lof-main-wapper">
<li>
 
  <a href="http://cesweb.org/Conference-Program/Session-Schedule.aspx"><img src="/cesweb/media/CESWeb/Slideshow%20Images/Conferences_RegOpen_Oct1.JPG?width=991&height=396&ext=.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://cesweb.org/Conference-Program/Session-Schedule.aspx'> </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="http://youtu.be/wdi-h3RpXbA"><img src="/cesweb/media/CESWeb/Slideshow%20Images/mobileNative_v3.jpg?width=991&height=395&ext=.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://youtu.be/wdi-h3RpXbA'> </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="http://www.cesweb.org/Show-Floor/CES-Mobile-App.aspx"><img src="/cesweb/media/CESWeb/Slideshow%20Images/CES-Mobile.jpg?width=991&height=396&ext=.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://www.cesweb.org/Show-Floor/CES-Mobile-App.aspx'> </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="http://cesweb.org/For-The-Press/Press-Events.aspx"><img src="/cesweb/media/CESWeb/Slideshow%20Images/HP_Events_UnveiledStockholm.jpg?width=991&height=396&ext=.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://cesweb.org/For-The-Press/Press-Events.aspx'> </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="http://ce.org/Events-and-Awards/Events/2012-Events/Industry-Forum.aspx"><img src="/cesweb/media/CESWeb/Slideshow%20Images/HP_Events_IndustryForum.jpg?width=991&height=396&ext=.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://ce.org/Events-and-Awards/Events/2012-Events/Industry-Forum.aspx'> </a>
           
           
        </p>
    </div>
</li>
</div><div class="lof-navigator-wapper">
        <div onclick="return false" href="" class="lof-previous">Previous</div>
            <div class="lof-navigator-outer">
                <ul class="lof-navigator">

<li><img src="/cesweb/media/CESWeb/Slideshow%20Images/Conferences_RegOpen_Oct1.JPG?width=991&height=396&ext=.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/mobileNative_v3.jpg?width=991&height=395&ext=.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/CES-Mobile.jpg?width=991&height=396&ext=.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/HP_Events_UnveiledStockholm.jpg?width=991&height=396&ext=.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/HP_Events_IndustryForum.jpg?width=991&height=396&ext=.jpg" ></li>
</ul>
            </div>
        <div onclick="return false" href="" class="lof-next">Next</div>
    </div> 
</div>
</div>
</div>
 <div id="page-bottom">
                
<div id="mid-bar">
    <div class="icon_wrap">
       <a href="/Twitter.aspx" target="_blank"><img alt="Twitter" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/twitter.png" width="25" /></a> <a href="/Facebook.aspx" target="_blank"><img alt="facebook" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/facebook.png" width="25" /></a> <a href="/StumbleUpon.aspx" target="_blank"><img alt="stumbleupon" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/stumbleupon.gif" width="25" /></a> <a href="/Flickr.aspx" target="_blank"><img alt="flickr" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/flickr.png" width="25" /></a> <a href="/YouTube.aspx" target="_blank"><img alt="youtube" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/youtube.png" width="25" /></a> <a href="/LinkedIn.aspx" target="_blank"><img alt="linkedin" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/linkedin.png" width="25" /></a> <a href="/News/News-Feed.aspx" target="_blank"><img alt="rss" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/rss.png" width="25" /></a>
   </div>
</div>

<div id="HP-tabs">
    <div id="tabs">
        <ul>
          <li class="news"><a href="#fragment-1"><span>Buzzworthy</span></a></li>
          <li class="blog"><a href="#fragment-2"><span>Blog</span></a></li>
          <li class="video"><a href="#fragment-3"><span>Videos</span></a></li>
          <li class="photos"><a href="#fragment-4"><span>Photos</span></a></li>
          <li class="myces"><a href="#fragment-5"><span>MyCES</span></a></li> 
        </ul>
        <div id="fragment-1">
        	<!-- Buzzworthy -->
    		<div id="news">
<div class='news_tab' id='news_1' 

>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/11/2012</p></div>
    <h3> <a href="/News/News-Feed#87ab84b3-6ab1-4529-9d6e-a801a9e7a6cd">CES Unveiled STOCKHOLM</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/11059_NewEvent.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Attention members of the press! The Consumer Electronics Association has added one more stop on the CES Unveiled tour. CEA will be giving a sneak peek of what&rsquo;s to come at the 2013 International CES at our first ever <a href="http://www.cesweb.org/For-The-Press/Press-Events.aspx#6jump">CES Unveiled STOCKHOLM</a>. Join us for this exciting press-only event at the World Trade Center Stockholm on Oct. 29 for a day of tech trends, forecasts and a showcase of the latest technology.
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/11/2012</p></div>
    <h3> <a href="/News/News-Feed#75e43ec7-430b-45ab-a623-cc777e4353a1">It’s Never Too Early to Start Planning for 2013 CES!</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/CESMobile120x120.jpg?width=120&height=120&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The 2013 International CES will be four of the most exciting days of the year for all of our attendees, and the consumer electronics industry.&nbsp; CES has two great tools to help you search for exhibitors, products, technology, events, educational sessions, schedule meetings, connect with friends and more.<br />
<br />
The MyCES tool will help to maximize your experience at the show by allowing you to create and organize your personal schedule for your time in Las Vegas.&nbsp; Learn more and <a href="http://ces13.mapyourshow.com/5_0/search.cfm?">start planning your trip today.</a> The CES Mobile app will help you plan for 2013 CES on the go. Build your schedule, search the show floor, and receive breaking CES news right from your tablet or smartphone. Visit <a href="http://cesweb.org/Show-Floor/CES-Mobile-App.aspx">CESweb.org/cesmobile</a> to learn more and download CES Mobile. </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/8/2012</p></div>
    <h3> <a href="/News/News-Feed#601a7c89-c7a3-4fb3-b1ff-aa2bc25367ca">“Speakers are what I do. It’s my art.”</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/SandyGross.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">After a career that included creating two successful loudspeaker companies, Sandy Gross contemplated retirement. But he couldn&rsquo;t leave the work he loved. &ldquo;Speakers are what I do. It&rsquo;s my art,&rdquo; <a href="http://www.youtube.com/watch?v=V1SdvdKAcsE&amp;feature=plcp" target="_blank">said Gross</a>, now president of his new company GoldenEar Technology and a finalist to be named 2012 Executive of the Year in the Innovation Entrepreneur Awards.<br />
<br />
<span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; ">The first annual</span><a href="http://www.ce.org/News/News-Releases/Press-Releases/2012-Press-Releases/CEA-Announces-Finalists-for-Inaugural-Innovation-E.aspx" style="text-decoration: none; color: rgb(0, 155, 182); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); "><span class="Apple-converted-space">&nbsp;</span>Innovation Entrepreneur Awards</a><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; ">, sponsored by the<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.ce.org/" style="text-decoration: none; color: rgb(0, 155, 182); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); ">Consumer Electronics Association&#39;s (CEA)</a><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; "><span class="Apple-converted-space">&nbsp;</span>new flagship publication<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.ce.org/i3" style="text-decoration: none; color: rgb(0, 155, 182); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); ">It Is Innovation (i3)</a><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; "><span class="Apple-converted-space">&nbsp;</span>and CEA&#39;s Small Business Council, honors excellence in entrepreneurship and recognizes visionaries leading businesses with revenues under $30 million. Winners will be announced at the upcoming<span class="Apple-converted-space">&nbsp;</span></span><a href="http://www.ce.org/industryforum" style="text-decoration: none; color: rgb(0, 155, 182); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); ">CEA Industry Forum</a><span style="color: rgb(0, 0, 0); font-family: Arial, Helvetica, sans-serif; font-size: 12px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17px; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); display: inline !important; float: none; "><span class="Apple-converted-space">&nbsp;</span>in San Francisco. &thinsp;</span> </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/8/2012</p></div>
    <h3> <a href="/News/News-Feed#32c3dbfe-306d-4958-8e84-6bd58005eefe">October is CEA's Member Appreciation Month</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/390659_1933317367743_777690655_n.jpg?width=165&height=118&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The Consumer Electronics Association (CEA) is celebrating their members all month long! In addition to producing the International CES in Vegas each year, CEA works all year round to grow and promote the industry. We would like to thank our members for creating, manufacturing, innovating, buying and selling consumer electronics products. We will be rewarding our members by hosting a series of contests and giveaways during the month of October. <a href="http://blog.ce.org/index.php/2012/10/04/member-appreciation-month-giveaway-1/" target="_blank">Visit our blog</a> to learn more!<br style="margin: 0px; padding: 0px; " />
<br style="margin: 0px; padding: 0px; " />
 </p>
        
    </div>


</div><div class='news_tab' id='news_2' 
style='display:none;'
>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/5/2012</p></div>
    <h3> <a href="/News/News-Feed#1a2f59b1-4483-4f0b-b3c2-12a3484c0f70">Pandora’s Tim Westergren to Keynote the 2013 CES Leaders in Technology Dinner</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/pandora_logo_165.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The International CES has hosted the biggest names in technology as speakers throughout the years, and the 2013 CES is no different. Some of this year&#39;s attendees will have the privilege of hearing from Tim Westergren, chief strategy officer and founder of Pandora, a true innovator in Internet radio who will deliver the keynote address at the <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=db785fa8-79b1-41b4-8450-8b6bdb85046d">Leaders in Technology Dinner,</a> an invitation-only event on Wednesday, Jan. 9, honoring the top technologists, entrepreneurs and policymakers helping to further technology innovation. </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/4/2012</p></div>
    <h3> <a href="/News/News-Feed#24eb85e5-0eb3-4fad-b51d-1f991a4e3a9e">Verizon's Chairman and CEO, Lowell McAdam, to Deliver Keynote Address at 2013 CES</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/2k11CES_Verizon_LM-Buzzworthy.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The opening day of the 2013 International CES, Tuesday, Jan. 8, will kick off an incredible week for the consumer electronics industry. CEA has recently announced that Lowell McAdam, Chairman and CEO of Verizon, will deliver a keynote address on Tuesday afternoon, in addition to keynotes from the Consumer Electronics Association&rsquo;s CEO Gary Shapiro and Panasonic Corporation&rsquo;s President Kazuhiro Tsuga. &nbsp;McAdam currently oversees the operations of Verizon Communications, including all business units and staff functions.Please join us on Tuesday, Jan. 8 in the Palazzo Ballroom at The Venetian for this exciting keynote <a href="http://www.cesweb.org/Events/Keynotes/Day-One-Afternoon">address</a>.&nbsp; </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/3/2012</p></div>
    <h3> <a href="/News/News-Feed#8b2f5448-2c41-4b81-b32b-078575d1d1c6">International Gateway Sells Out at The Venetian </a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/CES_InternatinalGateway_165.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The Consumer Electronics Association (CEA) <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=c3363027-d063-464c-9267-4efca3a6a8ac">announced today</a> that the International Gateway TechZone has sold out in its new location, The Venetian, at the 2013 International CES.<br />
<br />
The International Gateway allows attendees to expand their global networks at CES. The TechZone will feature more than 460 exhibitors in Hall D of The Venetian, showcasing innovative technologies and products from international destinations, including China, Korea, Hong Kong and Taiwan. Due to the sell out in Hall D, International Gateway exhibits will also be found on Level 1 at the Venetian, in the Marco Polo ballroom. </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/3/2012</p></div>
    <h3> <a href="/News/News-Feed#b1377935-f63d-4032-9480-204746631ff5">Consumer Electronics Association, Google to Share Insights from 2012 Debates</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/11047_DebatesHPSlide-Small.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The <a href="http://www.ce.org">Consumer Electronics Association</a> (CEA) and <a href="http://www.google.com">Google</a> are partnering on &ldquo;<a href="http://www.ce.org/News/News-Releases/Press-Releases/2012-Press-Releases/CEA-and-Google-Showcase-Technology-at-Presidential.aspx">Insights from the 2012 Debates</a>,&rdquo; a joint effort to provide voters with insightful and compelling information about the presidential and vice presidential debates using Google&rsquo;s innovative technologies. It will debut during tonight&rsquo;s first debate in Denver.<br />
<br />
The effort includes a state-of-the-art digital wall that displays search and video trends, insights and consumer research. The digital wall features the top search trends around the debates and user-generated content from Google+. Check out Google&rsquo;s <a href="http://www.google.com/elections/ed/us">election hub</a> for more information on the 2012 election.<br />
 </p>
        
    </div>


</div><div class='news_tab' id='news_3' 
style='display:none;'
>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/2/2012</p></div>
    <h3> <a href="/News/News-Feed#91860dc5-a74b-40db-854c-ce1fc5dc7313">DBL Distributing Founder David Lorsch is Finalist for  2012 Executive of the Year Award</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/David-Lorsch.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">When he started DBL Distributing in 1989, David Lorsch saw an exciting business opportunity to serve an untouched market in the West. Now he is a finalist to be named 2012 Executive of the Year in the Innovation Entrepreneur Awards. <a href="http://youtu.be/pcnHayuy3Fw">Hear more</a> from David about his path to success and how he used CES to grow his business.<br />
<br />
The first annual<a href="http://www.ce.org/News/News-Releases/Press-Releases/2012-Press-Releases/CEA-Announces-Finalists-for-Inaugural-Innovation-E.aspx"> Innovation Entrepreneur Awards</a>, sponsored by the <a href="http://www.ce.org">Consumer Electronics Association&#39;s (CEA)</a> new flagship publication <a href="http://www.ce.org/i3">It Is Innovation (i3)</a> and CEA&#39;s Small Business Council, honors excellence in entrepreneurship and recognizes visionaries leading businesses with revenues under $30 million. Winners will be announced at the upcoming <a href="http://www.ce.org/industryforum">CEA Industry Forum</a> in San Francisco. &thinsp; </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/2/2012</p></div>
    <h3> <a href="/News/News-Feed#1d4209a3-f963-462a-a58e-7577d388422d">New at CES: Guided Tours for the Start-up Community</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/EurekaPark.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Discover tech-sprouting start-ups and from-the-garage innovators on a fast-paced, guided tour of the Eureka Park TechZone, a one-stop destination at the 2013 International CES that features all early-stage companies generating tomorrow&#39;s biggest ideas.<br />
<br />
Exclusive for venture capitalists, financial analysts, entrepreneurs and founders, this two-hour innovation immersion includes a brief overview of the exhibits, a private tour of select Eureka Park exhibitors and a business-boosting networking reception with fellow tour-takers and all of the Eureka Park exhibitors. E-mail us at <a href="mailto:CEStours@CE.org?subject=CES%20Guided%20Tours%20at%20Eureka%20Park">CEStours@CE.org</a> for more information. </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>9/26/2012</p></div>
    <h3> <a href="/News/News-Feed#b5f8e56a-469b-4b2f-b39b-f8695ce2dd29">Jake Sigal, Founder and CEO of Livio Radio, Shares His Best CES Memory</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/headshot.png?width=165&height=125&ext=.png" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;"><span style="font-size:12px;">&quot;My best memory was CES 2008. I started Livio a few days&rsquo; earlier, printed business cards and was off to the show with no idea exactly what I was going to do. All I had scheduled was a few meetings with people I used to work with from previous jobs. One of those meetings was with a little company called Pandora. The rest is history.&quot; <a href="http://blog.ce.org/index.php/2012/09/25/get-to-know-your-industry-forum-speakers-jake-sigal/">Read more from Jake</a>.</span><br />
<br />
<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>9/25/2012</p></div>
    <h3> <a href="/News/News-Feed#b0b484e3-d3f1-45a2-87eb-76ddad552aec">Admission to CES is Now in the Mail</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/MailerTeaser.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">If you&rsquo;ve already registered for CES, keep an eye on your mailbox at home because admission badges are already on the way. It&rsquo;s important that you hold onto your badge once you receive it to ensure your entry into CES, the world&#39;s largest consumer technology tradeshow. When you arrive in January, you can go to the <a href="/FAQ/General.aspx#jumpto3-7">nearest Badge Holders Pickup location</a> to receive your badge holder.  </p>
        
    </div>


</div><div class='news_tab' id='news_4' 
style='display:none;'
>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>8/30/2012</p></div>
    <h3> <a href="/News/News-Feed#bb74ef37-635c-407b-ac57-d9b37e28cf0b">Book Hotel Rooms Now for Best Rates</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/Hotel%20and%20Travel%20Images/Hotels/Strip_165x125.jpg?width=165&height=125&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">There&#39;s no question that Las Vegas is busiest when CES is in town. That means hotel rooms fill quickly. <a href="http://cesweb.org/Hotel-Travel/Hotel-Reservations.aspx">Book your room today</a><span style="text-decoration: underline;"> </span>and avoid the &ldquo;sold out&rdquo; signs. CES makes it easy for you by listing rates, availability and discount codes <a href="http://cesweb.org/Hotel-Travel/Hotel-Reservations.aspx">all in one place</a>.<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>8/29/2012</p></div>
    <h3> <a href="/News/News-Feed#f5df2055-c986-4c47-b1e1-b62d6fe186af">Free CES Registration: Just a Handful of Days Left</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/226x200%20Banner%20Ads/Save_the_date_226x200.jpg?width=226&height=200&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Register now before the fees increase to $100 on Saturday, September 1 and to $200 on January 2!<br />
&nbsp;<br />
With more than four decades of success, the International Consumer Electronics Show (CES) reaches across global markets, connects the industry and enables CE innovations to grow and thrive.<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>8/13/2012</p></div>
    <h3> <a href="/News/News-Feed#cd658a03-8f7e-44d7-a3a3-de1594ecf873">Call for Entries Open for Innovations 2013 Design and Engineering Awards Honoring Best in CE Innovation</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/Innovation%20Awards/Innovations_2013_RSS.jpg?width=177&height=152&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The industry-recognized annual competition honors outstanding design and engineering across&nbsp;<a href="http://cesweb.org/Awards/CES-Innovations-Awards/Awards-Categories.aspx"><u>29 consumer electronics categories</u></a>. Two new product categories were added to the 2013 awards program: Tech for a Better World and Accessible and Universal Design Technologies. Tech for a Better World recognizes technologies that share a common goal and the ability to impact the world in a positive way, either domestically, or around the globe. Accessible and Universal Design Technologies focuses on technologies that have innovative features that enable ease of use by anyone, including, but not limited to, seniors and people with disabilities, regardless of cognitive ability, hearing, mobility, visual or other impairments. </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>7/23/2012</p></div>
    <h3> <a href="/News/News-Feed#698a48b0-e0aa-4c8e-8288-c78af3e5c4d4">Join Elite Professionals Who Judge the Best Innovations at CES</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/Innovation%20Awards/Innovations_2013_RSS.jpg?width=177&height=152&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Define where invention and execution take flight! Join the elite panel of industry professionals who judge the best innovation at the 2013 International CES! Help decide which stunning new ideas go above and beyond in design and engineering to make it as an&nbsp;<a href="/Awards/CES-Innovations-Awards/2012.aspx">Innovations Honoree</a>. </p>
        
    </div>


</div>
</div><div id=news-nav>
				<ul id=news_nav_buttons>
					<li class=up>Pages:</li>
<li id='news_1_button' 
class='on_page'
 ><a onclick="return newsActive('news_1');" href=''>1</a></li>









<li id='news_2_button' 

 ><a onclick="return newsActive('news_2');" href=''>2</a></li>









<li id='news_3_button' 

 ><a onclick="return newsActive('news_3');" href=''>3</a></li>









<li id='news_4_button' 

 ><a onclick="return newsActive('news_4');" href=''>4</a></li>










</ul>
			</div>
		</div>
		
		<div id="fragment-2">
			<!-- Blog -->
		    <div id=blog></div>
			<div id=blog-nav></div>
		</div>
		<div id="fragment-3">
		    <!-- video -->
    	    <div id=resp></div>
		</div>
		<div id="fragment-4">
	    	<!-- Photos -->
	    	<h3>2012 International CES Photos</h3>
	    	<br>Download high-resolution&nbsp;photos from the <a href="/For-The-Press/Image-Gallery.aspx"><strong>Image Gallery</strong>.</a><br><br>View photos from our <strong><a href="http://www.cesweb.org/flickr" target=_blank>flickr</a></strong> stream: 
			<p><iframe height=460 src="/photos.aspx" frameBorder=0 width=680 scrolling=no></iframe></p>
		</div>
		<div id="fragment-5">
    	    <!-- MyCES -->
		    <p>&nbsp;</p>
			<p><img align=left src="/cesweb/media/CESWeb/assets/images/myces/MY_CES_2k10.gif" width=128 height=86>With the MyCES Planner, you can&nbsp;create a personalized show agenda that allows you to:</p>
			<ul class=text>
				<li class=text>Add exhibitors of interest to your agenda </li>
				<li class=text>Use the My Events calendar to organize your show-related activities </li>
				<li class=text>Print a map of the show floor highlighting your exhibitors of interest </li>
			</ul>
			<p><a href="http://ces12.mapyourshow.com/myshow/login.cfm">If you already have a MyCES account</a>, take advantage of these tools and start planning your show today! <a href="http://ces12.mapyourshow.com/myshow/login.cfm">If you don't have a MyCES account, create one today</a>, watch the 2012 CES come to life as we add new exhibitors, events and announcements,&nbsp;and start planning your show today! </p>
			<p></p>
			<p>
				<table border=0 cellSpacing=0 cellPadding=0>
					<tbody>
						<tr>
							<th colSpan=6><img src="/cesweb/media/CESWeb/assets/images/myces/myCES-top.jpg" height=23></th>
						</tr>
						<tr>
							<th colSpan=6>&nbsp;</th></tr>
						<tr align=middle>
							<td><a href="http://ces13.mapyourshow.com" target=_blank><img border=0 src="/cesweb/media/CESWeb/assets/images/myces/dir-search(1).jpg"></a></td>
							<td><a href="http://ces13.mapyourshow.com/exhibitor_results.cfm?type=list&list=featured" target=_blank><img border=0 src="/cesweb/media/CESWeb/assets/images/myces/featured-exhibitors(1).jpg"></a></td>
							<td><a href="http://ces13.mapyourshow.com/advanced_search.cfm?by=category" target=_blank><img border=0 src="/cesweb/media/CESWeb/assets/images/myces/product-search(2).jpg"></a></td>
							<td><a href="http://ces13.mapyourshow.com/myshow/login.cfm" target=_blank><img border=0 src="/cesweb/media/CESWeb/assets/images/myces/myplanner(1).jpg"></a></td>
							<td><a href="" target=_blank title="Coming Soon"><img border=0 src="/cesweb/media/CESWeb/assets/images/myces/maps(2).jpg"></a></td>
							<td><a href="" target=_blank title="Coming Soon"><img border=0 src="/cesweb/media/CESWeb/assets/images/myces/conferences.jpg"></a></td>
							<td></td>
						</tr>
						<tr>
							<td></td>
							<td align=center></td>
							<td></td>
							<td></td>
							<td align=center></td>
						</tr>
						<tr>
							<th colSpan=6>&nbsp;</th>
						</tr>
						<tr>
							<th colSpan=6><img src="/cesweb/media/CESWeb/assets/images/myces/myCES-bottom.jpg" height=23></th>
						</tr>
					</tbody>
				</table>
			</p>
		</div>
    </div>
</div>
<!-- End Tab Structure -->


<div id="sidelinks">
    <img style="padding-bottom: 3px;" src="/cesweb/media/CESWeb/assets/images/tabs/cesweb_intltab.png">
    <a href="/For-Exhibitors.aspx" title="For Exhibitors"><img src="/cesweb/media/CESWeb/assets/images/nav/cesweb_exhibitors1.png" alt="Exhibitors" name="cesweb_exhibitors" onMouseOver="over(10)" onMouseOut="out(10)" style="padding-bottom:3px;" /></a>
    <a href="/For-The-Press.aspx" title="For Press"><img src="/cesweb/media/CESWeb/assets/images/nav/cesweb_press1.png" alt="Press" name="cesweb_press" onMouseOver="over(11)" onMouseOut="out(11)"  style="padding-bottom:3px;" /></a>
    <a href="/For-International-Visitors.aspx" title="For Visitors"><img src="/cesweb/media/CESWeb/assets/images/nav/cesweb_visitors1.png" alt="Visitors" name="cesweb_visitors" onMouseOver="over(12)" onMouseOut="out(12)" style="padding-bottom:3px;"/></a>
    <a href="/Entertainment-Matters.aspx" title="Entertainment Matters"><img src="/cesweb/media/CESWeb/assets/images/nav/EMatCES1.jpg" alt="Entertainment Matters" name="entertainment_matters" onMouseOver="over(13)" onMouseOut="out(13)" style="padding-bottom:3px;"/></a>
</div>

<div id="extra">
	<img src="/cesweb/media/CESWeb/assets/images/tabs/cesweb_extras.png">
    <div class="extras-slider">
    
        
<div class="extras-slide">
      	<a href="http://cesweb.org/brandmatters"><img src="/cesweb/media/CESWeb/Slideshow%20Images/BrandMatters_220x57.jpg?width=220&height=57&ext=.jpg" alt="" /></a>
</div>
  <div class="extras-slide">
      	<a href="/Show-Floor/CES-Mobile-App.aspx"><img src="/cesweb/media/CESWeb/CES%20Mobile%20App/CESMobilebanner220x57.jpg?width=220&height=57&ext=.jpg" alt="" /></a>
</div>
  <div class="extras-slide">
      	<a href="http://blog.ce.org/"><img src="/cesweb/media/CESWeb/assets/images/extras/dig-dialogue.jpg?width=220&height=57&ext=.jpg" alt="" /></a>
</div>
  <div class="extras-slide">
      	<a href="http://cesweb.org/cesgreening.asp"><img src="/cesweb/media/CESWeb/assets/images/extras/ces-green.jpg?width=220&height=57&ext=.jpg" alt="" /></a>
</div>
  

        
    	   
        <div class="extras-slider-nav">
            <input type="hidden" class="extras-slider-current" value="0"/>
            <div class="extras-slider-left"></div>
            <div class="extras-slider-right"></div>
        </div>
    </div>
</div>
<div id="facebook">
     <img src="/cesweb/media/CESWeb/assets/images/tabs/cesweb_fbtab.png" /><br />
     <iframe src="http://www.facebook.com/plugins/likebox.php?id=9181619833&amp;width=240&amp;connections=0&amp;stream=true&amp;&amp;force_wall=trueheader=false&amp;height=428" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:240px; height:428px;" allowTransparency="true"></iframe>
</div>
</div>

        
    </div>
    <div id="sitelinks">
        
    </div>
</div> 
<div id="footer-home">
    <div id="footer_nav-home">
        <a href="/About-CES.aspx">About CES</a><span>|</span> <a href="/About-CEA.aspx">About CEA</a><span>|</span> <a href="/News/News-Feed.aspx">RSS News</a><span>|</span> <a href="/MyCES.aspx">MyCES</a><span>|</span> <a href="/Contact-Us.aspx">Contact Us</a><span>|</span> <a href="/Site-Map.aspx">Site Map</a><span>|</span> <a href="/Privacy-Policy.aspx">Privacy Policy</a><span>|</span> <a href="/Partners.aspx">Partners</a>&nbsp;
       
    </div>
    <div id="copyright-home">
    Copyright &copy; 2003 - 2012 CEA. All rights reserved.
    </div>
    
    <a target="_blank" href="http://www.CE.org"><img id="p_lt_footerLogoZone_EditableImage2_imgImage" src="/cesweb/media/CESWeb/assets/images/footer/cesweb_footerlogo.png" alt="" /></a>
</div>
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0013/2569.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

    
    

<script type="text/javascript">
//<![CDATA[
(function() {var fn = function() {$get("manScript_HiddenField").value = '';Sys.Application.remove_init(fn);};Sys.Application.add_init(fn);})();//]]>
</script>
</form>
</body>
</html>
