<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><!-- PageID 1340 - generated by RedDot 5.6 - 5.6.1.8 - Y-9bp -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!-- INSERT PAGE TITLE HERE (immediately following gblPAGE_TITLE) -->
<title>2005 International CES:&nbsp;August 2004</title>



<!-- INSERT SEARCH ZONE HERE -->


<link rel="StyleSheet" href="/print/global_includes/css/mainMethod.css" type="text/css">
<LINK REL="SHORTCUT ICON" HREF="http://www.easymovement.com/ces/favicon.ico">

<!-- Browser detection script -->
    <script src="/print/global_includes/js/browser_detection.js" type="text/javascript"></script>

<SCRIPT language="javascript1.2">
    function newWin(urlString,pgNum) {
        var popupWindow;
        urlString += "?pageID=" + pgNum;
 
        popupWindow = window.open(urlString,"","toolbar=yes,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=550,width=618,left=50,top=50");
    }  
 
    function openNewWindow(strURL) {
        window.name = "main";
        var newWindow = window.open(strURL,"newWindow", "toolbar=no,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=400,width=450,left=50,top=50");
    }

    // Script for e-mail this page - gets the url of the page the user is on before the e-mail page tool button is clicked
    function loadReferrer() {
        referrerString = opener.document.location.href;
        document.emailForm.page.value = referrerString;
    }
</SCRIPT>

<!-- Rollover script (do we still need these?) --> 
<script language="javascript1.2"> 
    /* for graphical rollovers */
   function rollOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function rollOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function introllOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function introllOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function snrollOver(which,name) 
    {
    var on="/global_images/1.0/1.0" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function snrollOff(which) 
    {
    var on="/global_images/1.0/1.0" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
        
    //do we still need this?   
    function onLoadHandler() {
       if( typeof(bodyOnLoadFunction) != 'undefined' ) {
           return eval(bodyOnLoadFunction);
       }
    }
</script>
<script language="javascript">
<!--
var activeNavId=0;
var thisPageUrl='/exhibitors/newsletter/aug2k4_pg1.asp';

var parentLinks=new Array('dummy','/print/exhibitors/default.htm','/print/exhibitors/newsletter/default.asp');

function checkActiveNav(theUrl) {
    var linkUrl=theUrl;
    var returnValue=false;
    
    if (linkUrl==thisPageUrl) {
        returnValue=true;
    } else if (parentLinks.length>2 && linkUrl==parentLinks[parentLinks.length-1]) {
        returnValue=true;   
    } else if (parentLinks.length>3 && linkUrl==parentLinks[parentLinks.length-2]) {
        returnValue=true;
    } else if (parentLinks.length>4 && linkUrl==parentLinks[parentLinks.length-3]) {
        returnValue=true;
    }
    return returnValue;
}

//-->
</script>
    <style>
        <!--
            UL {
                MARGIN-TOP: .5em;
                /*LIST-STYLE-IMAGE: url(/print/global_images2005/bullet.gif);*/
                MARGIN-BOTTOM: 0em;
                MARGIN-LEFT: 2em;
                VERTICAL-ALIGN: top;
            }

            .exhibitorBGImg {
                background-image: url('/print/global_images2005/exhibitor_bg.gif');
            }

            .text_colored, .intro_copy, .section_title, .subhead, .body_title, .intro_dates {
               color: #2B5492;
            }

        //-->
    </style>

</head>

<body leftmargin='0' topmargin='0' rightmargin='0' bottommargin='0' marginwidth='0' onLoad="onLoadHandler();self.focus();"> 
<div style="position:absolute; top: 15; left: 15" ><a href='javascript:;' onClick='window.print();return false'><img src="/print/global_images2005/print.jpg" width="115" height="20" border="0" alt=""></a></div>
<IMG SRC="/print/global_images2005/attPrintBanner.jpg" width="601" BORDER="0" vspace=0><br><table width="600" cellspacing="0" cellpadding="0" border="0">
    <tr>
<!-- /left column -->

<!-- main body content -->    
    <td width="10" class="exhibitor7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="100%" class="exhibitor7" valign="top">
    <img src="/print/global_images2005/spacer.gif" height="10" width="1"><br>
<!-- center content -->


<div class="body_title">The Exhibitor's Source:<br><img src='/print/global_images2005/spacer.gif' width='1' height='5' border='0'><br>
<table cellpadding='0' cellspacing='0' width='100%'><tr><td><span class='section_title'><em>Focus on the International CES</em></span></td><td align='right'><span class='text'><b>August 2004</b></span></td></tr></table></div>

<a name="1352"></a>
<img src="/print/global_images2005/spacer.gif" alt="" width="100%" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/print/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="100%" height="2" hspace="0" vspace="0" border="0"><br>

<div class="subhead" style="padding-top:3px; padding-bottom:7px">Behind the Scenes at CES</div>
<span class="text">
Check out <EM>Behind the Scenes at CES </EM>for updates on the extra efforts the International CES makes to improve the show and make your experience better. <BR><A name=scene1></A>
<P><STRONG>Wireless Access Point Blocking at the LVCC<BR></STRONG>Important! Smart City, the exclusive provider of Internet Service at the Las Vegas Convention Center (LVCC), has installed a new Air-magnet System to help manage the wireless network in the building. </P>
<P>This Air-magnet system will provide numerous reports that inform Smart City how the wireless network is running. It will also indicate when someone brings in their own “access point” (AP) and a general idea of where it is located inside the exhibit hall. To circumvent network disruption, this air-magnet system provides the ability to turn off these APs remotely, known as “blocking.” </P>
<P><STRONG>Therefore, if you plan to utilize some type of access point in the convention center, it is imperative that you notify </STRONG><STRONG>Smart</STRONG><STRONG></STRONG><STRONG> City</STRONG><STRONG> three weeks in advance of the show. This will help to achieve optimum performance and avoid blocking of your access point.</STRONG><STRONG></STRONG></P>
<P>Note: This “blocking” will only affect access points, not other products that use the 2.4 frequency. Look for more details on products that use the 2.4 frequency in a future issue of the <EM>Exhibitor’s Source</EM>. </P><A name=scene2></A>
<P><STRONG>CEA Media Tour Promotion<BR></STRONG>To get a jump on promoting the 2005 show, CES is teaming up with the Las Vegas Convention and Visitors Authority (LVCVA) and several other large Las Vegas tradeshows for the first ever South American road show. </P>
<P>South America is a bustling international market,&nbsp;and we&nbsp;want their business!&nbsp;We're reaching out to business and consumer press in South America and talking to buyers in an effort to increase&nbsp;attendance at the 2005 International CES. The event will be held in Sao Paulo, Brazil, September 13-17, 2004, and is the first official press event of the 2005 International CES season.&nbsp; </P><A name=scene3></A>
<P><STRONG>Protecting Your E-mail Address<BR></STRONG>We’re sensitive to the amount of e-mail messages you receive each day and do not release your address to any outside parties. In an effort to address unsolicited messages that you might see as “spam,” we have set up a <A href="mailto:DoNotSpam@ce.org">DoNotSpam@ce.org</A> mailbox. </P>
<P>If you feel you have received an unsolicited message from a party outside the International CES, forward the message to <A href="mailto:DoNotSpam@ce.org">DoNotSpam@ce.org</A>. You will receive an automatic e-mail response, defining the parameters of legitimate e-mail messages, along with copy you can use to respond to the unwanted message. </P><A name=testing></A>Through this monthly <EM>Exhibitor’s Source</EM> newsletter, the International CES communicates important exhibitor information on the first Tuesday of each month. You may occasionally receive an <EM>Exhibitor’s Source Update</EM> with an important intermittent announcement. Any additional messages from International CES partner organizations are mailed on their behalf, and they do not receive direct access to our exhibitor lists.
</span>
<a name="1351"></a>
<img src="/print/global_images2005/spacer.gif" alt="" width="100%" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/print/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="100%" height="2" hspace="0" vspace="0" border="0"><br>

<div class="subhead" style="padding-top:3px; padding-bottom:7px">CES Unveiled: The Official Press Event of the International CES</div>
<span class="text">
It's bigger and better. And it's a press event like no other. Right before the International CES opens. 4–7 p.m. Tuesday, January 4, 2005, in the Las Vegas Convention Center Room S226 is your chance to meet the top names in international trade and consumer press—print, broadcast and online.&nbsp; 
<P><IMG height=49 src="/print/images/general/CES_Unveiled_event.gif" width=250 align=right>Meet the press in one easy location, while the event is filmed for CES’ satellite video news release for distribution to broadcast stations nationwide. </P>
<P>Media and analysts also will get a sneak peek at the Innovations Design and Engineering Showcase honorees and the 2005 International CES product debuts during <EM>CES Unveiled: The Official Press Event of the International CES</EM>. Media and analysts will enjoy cocktails and hors d’oeuvres, while checking out tabletop demonstrations and networking with Innovations honorees and CES exhibitors. </P>
<P>Participants receive:</P>
<UL>
<LI>Access to more than 350 credentialed media and analysts in attendance </LI>
<LI>Free contact lists of pre-registered and confirmed media/analysts </LI>
<LI>A 50-word description and logo in the press event program guide </LI>
<LI>Extensive pre-show promotion to CES’ worldwide media list via Web, e-mail, news wires, print materials and direct individual pitching </LI>
<LI>Your product displayed among the Innovations 2005 Honorees’ products—a <EM>must see</EM> for press and analysts! </LI>
<LI>Four exhibitor passes to the event </LI>
<LI>One 6-foot draped exhibit table </LI>
<LI>500 watts of electrical service </LI>
<LI>44”x 7” sign for your tabletop </LI>
<LI>High-speed Internet access </LI>
<LI>Telephone lines and A/V equipment available </LI></UL>
<P>2004 CES Press Event attendees included editors from <EM>NBC Today Show, </EM>CNN, ABC News, Bloomberg News, <EM>Business Week, Wired, Maxim </EM>and <EM>Rolling Stone. </EM></P>Only credentialed media and analysts are allowed to attend this exclusive CEA-sponsored event. Make sure you’re there! Interested exhibitors should contact Ryan Strowger, Manager, Business Development, CEA at <A href="mailto:rstrowger@ce.org">rstrowger@ce.org</A> or 703-907-7679.
</span>
<a name="1350"></a>
<img src="/print/global_images2005/spacer.gif" alt="" width="100%" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/print/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="100%" height="2" hspace="0" vspace="0" border="0"><br>

<div class="subhead" style="padding-top:3px; padding-bottom:7px">Innovations Plus: A New Destination</div>
<span class="text">
<IMG height=50 src="/print/images/general/InnovationsPlus(1).gif" width=165 align=right>The new CES Central Plaza will feature Innovations Plus, a brand new destination at CES. Exhibitors there will have their product displayed among the Innovations 2005 Honorees showcase, Best of Innovations, TechZones and some of the hottest exhibits at the 2005 International CES. 
<UL>
<LI><STRONG>Innovations 2005 honorees</STRONG> and <STRONG>Best of Innovations</STRONG> product displays </LI>
<LI><STRONG>New to market</STRONG> exhibits, featuring examples of how to effectively introduce new products to market </LI>
<LI><STRONG>Design Company Displays</STRONG>, highlighting design capabilities from members of the IDSA </LI>
<LI><STRONG>Dave Graveline’s <EM>Into Tomorrow</EM></STRONG> radio broadcast and live interview </LI>
<LI><STRONG>CES Gaming Arcade</STRONG> </LI>
<LI><STRONG>Flash Forward 2.0:</STRONG> Bringing Digital Imaging Into Focus </LI>
<LI><STRONG>Outdoor exhibits</STRONG> including Gibson Audio </LI>
<LI><STRONG>International CES TechZones</STRONG>, including </LI></UL>
<TABLE cellSpacing=0 cellPadding=0 width="85%" align=center border=0>
<TBODY>
<TR>
<TD width="50%">
<UL>
<LI>Assistive Technologies </LI>
<LI>Bluetooth </LI>
<LI>Cardio Play Zone </LI>
<LI>Launch </LI>
<LI>MBOA Ultrawideband </LI></UL></TD>
<TD width="50%">
<UL>
<LI>MP3 &amp; Internet Audio </LI>
<LI>Portable Power </LI>
<LI>Pulvar.com Von &reg; Consumer </LI>
<LI>RFID </LI>
<LI>USB </LI></UL></TD></TR></TBODY></TABLE>
<P>Innovations Plus is open to International CES exhibitors, companies with new products, releases or versions, Innovations 2005 honorees and entrants, and participants in CES Unveiled: The Official Press Event of the International CES. </P>For more information, contact an International CES representative at (703) 907-7645.
</span>
<a name="1347"></a>
<img src="/print/global_images2005/spacer.gif" alt="" width="100%" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/print/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="100%" height="2" hspace="0" vspace="0" border="0"><br>

<div class="subhead" style="padding-top:3px; padding-bottom:7px">Let Us Help You Build Your Brand</div>
<span class="text">
<IMG height=125 hspace=6 src="/print/global_includes/flash/see_us_atCES.gif" width=107 align=right>The International CES logo is globally recognized. Make the investment of your CES resources even more worthwhile, and download the “<A href="/print/exhibitors/resource_center/logos/default.asp">See Us at CES” logo</A> (login required) to include in your pre-show literature. 
<P><EM>Available only to International CES exhibitors! <BR></EM>Make sure the entire consumer electronics industry knows that you’re participating in the world’s leading consumer technology show this January. As you begin your marketing for the 2005 International CES, incorporate the logo in your pre-show promotions, including print and web advertising. And watch your show attendance grow! </P>
<P>To take advantage of other ways to build your brand through CES, contact our Promotional Opportunities Manager at (703) 907-7688. </P>
</span>
<p><img src="/print/global_images2005/spacer.gif" alt="" width="1" height="16" hspace="0" vspace="0" border="0"></p>
<div align="center">

    [ <strong>page 1</strong> ]
 &nbsp; 

    [ <strong>page 2</strong> ]
 &nbsp;

    [ <strong>page 3</strong> ]

</div>

<!-- /center content -->
    <br><br><br>
    </td>
    <td width="10" class="exhibitor7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
<!-- optional added value -->

    <td width="10" class="exhibitor8"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="190" class="exhibitor8" valign="top"><img src="/print/global_images2005/spacer.gif" alt="" width="190" height="28" hspace="0" vspace="0" border="0""><br>
    
    
<style type="text/css">
    <!--
    .columnsubhead {
    font-weight: bold;
    color: #FFFFFF;
}
    -->
</style>
<style type="text/css">
    <!--
    .tableborder {
    border: 1px solid #999999;
    }
    -->
</style>

<!-- top of Dan Cole's column -->


<table width="100%" border="0" cellpadding="5" cellspacing="0" class="tableborder">
<tr>
    <td bgcolor="#1B3D85" class="columnsubhead"><div align="center">A Message From Dan Cole</div></td>
</tr>
<tr>
    <td>
    <p align="center"><img src="/print/images/ces_photos/dan_cole.jpg" alt="Dan Cole"><br>
    <span class="subhead">Dan Cole</span><br>
    Vice President, Exhibitor Services, Sales and Business Development, International CES</p>
    <hr align="center" width="90%" size="1" noshade color="#999999">
    <!-- article start -->
    <p><strong>Upcoming Exhibitor Workshop </strong><br> by Dan Cole</p>
    I remember the first time I got up in front of a public audience to speak: college speech class. Five minutes, and I had to tell 50 classmates about Bruce Springsteen—someone I knew little about, although I loved his music. It was the longest 300 seconds of my life, and I thought I would die. 
<P>I didn’t, but with time, I did learn that with practice it gets easier. And I also learned that there’s nothing to fear once the unknown is pulled out of the equation. If you know what you’re talking about—if you know what you’re doing—there’s nothing to sweat. </P>
<P>That’s why I think the free workshop coming up in September is such a great resource for International CES exhibitors. Spending a day at the Las Vegas Convention Center with an experienced CES team and many of the show’s vendors builds confidence and the expertise you need and also takes all of the guesswork out of your exhibit experience. </P>
<P>It’s free, the hotel’s only $59, and believe me, it’s worth the time and trip for new and ‘old’ exhibitors, alike. For first timers, it’s all about learning and ROI. And for the old pros, it’s all about getting deep discounts on anything you may need (another perk for first timers as well, of course). </P>
<P>There’s not much time left to register, though; the deadline is August 20. So register now, and you can also check out the agenda and other detailed information about what we have lined up for you. </P>
<P>And, unfortunately for me, Springsteen ain't coming to Washington this summer. </P>
<P>‘Hope to see you September 21 in Las Vegas at the Exhibitor Workshop. </P>
    <!-- article end -->
    <img src="/print/images/general/dan_cole_sig.gif"><br>Dan Cole</p></td>
</tr>
</table>
    <br><br><br>    
    </td>
    <td width="10" class="exhibitor8"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>


<!-- /optional added value -->
</tr>
<!-- /main body row -->
<!--/print/exhibitors/space/default.asp/print/exhibitors/promotions/default.asp/print/exhibitors/resource_center/default.asp/print/exhibitors/pr/default.asp/print/exhibitors/manual/default.asp/print/exhibitors/newsletter/default.asp/print/exhibitors/downloads/default.asp-->
<!--/print/exhibitors/newsletter/oct2k4_pg1.asp
/print/exhibitors/newsletter/sept2k4_pg1.asp
/print/exhibitors/newsletter/aug2k4_pg1.asp
/print/exhibitors/newsletter/jul2k4_pg1.asp

-->
</table>
</body>
</html>