<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="head"><title>
	Home - 2014 International CES, January 7 - 10
</title><meta name="description" content="The International CES is a global consumer electronics and consumer technology tradeshow that takes place every January in Las Vegas, Nevada." /> 
<meta charset="UTF-8" /> 
<meta name="keywords" content="International CES, CES, CES 2010, CES 2011, CES 2012, CES 2013, CES 2014, CES 2015, CES 2016, CES 2017, CES 2018, Consumer Electronics Show, Consumer Technology, Consumer Electronics, Consumer Electronics Association, CES Las Vegas, ces show, ces vegas, CES Unveiled, ces tradeshow, ces conference, ces registration, ces exhibitor, ces innovation awards, innovation awards, best of ces, ces keynote, ces show floor, technology, silicon valley, technology innovation, disruptive technology, start-ups," /> 
<link href="/CMSPages/GetResource.ashx?stylesheetname=cesweb" type="text/css" rel="stylesheet"/> 
<!-- Twitter Summary Card -->
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@IntlCES">
<meta name="twitter:creator" content="@IntlCES">
<meta name="twitter:title" content="Home">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="http://content.ce.org/2013ces/images/hpimages/header/cesweb_headerlogo.png">
<!-- End of Twitter Summary Card -->
<meta name="google-site-verification" content="QtrhioDQsJvHnE2CJvCMQUzCnU0kH5zXiEksoj6pIDo" />
<link rel="icon" href="/cesweb/media/CESWeb/favicon.ico" type="image/x-icon"> 
<link rel="shortcut icon" href="/cesweb/media/CESWeb/favicon.ico" type="image/x-icon"> 
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3975226-4']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script><script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<!--[if lt IE 9]>
<style>
#topnav>li>a { font-family: Arial !important; font-size: 14px !important; letter-spacing: -1px; font-weight: bold;}
/* #topnav>li{ padding-left:28px !important; } */
.greenbox-bg ul a.lefttopnavhead { font-family: Arial !important; font-size: 14px !important; font-weight: bold; }
</style>
<![endif]-->
<!--[if IE 8]>
<style>
#topnav > li { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=/hIEfix.png,sizingMethod=crop); zoom: 1; }
.greenbox-bg ul a.lefttopnavhead { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=/hIEfix.png,sizingMethod=crop); zoom: 1; }
</style>
<![endif]-->


<script src="/cesweb/media/CESWeb/assets/js/custom/jquery-feed-rotator-min.js" type="text/javascript"></script>
<script type="text/javascript">
(function($){
    $(document).ready(function(){
	topNewsFeed = $('#header-feed').feedRotator();
	setTimeout(function(){
		$('#topnav').show();
	}, 2000);
    });
})(jQuery);
</script><script language="javascript" src="http://www.mapyourshow.com/includes/floorplan.js"></script> 
<link href="/CMSPages/GetResource.ashx?_webparts=1180" type="text/css" rel="stylesheet"/> 
</head>
<body class="LTR ENUS ContentBody"  class="home" id="home">
    <form method="post" action="/Home.aspx" id="form">
<div class="aspNetHidden">
<input type="hidden" name="manScript_HiddenField" id="manScript_HiddenField" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUJODc3OTc4NjAwD2QWAgIBEGRkFgICBQ9kFgJmD2QWAmYPZBYIAgEPZBYCZg9kFgJmD2QWEGYPZBYCZg9kFgJmDxUCEWh0dHA6Ly93d3cuY2Uub3JnDENFQSAtIENFLm9yZ2QCAQ9kFgJmD2QWAmYPFQIVaHR0cDovL3d3dy5jZXN3ZWIub3JnEUludGVybmF0aW9uYWwgQ0VTZAICD2QWAmYPZBYCZg8VAiBodHRwOi8vd3d3LmRlY2xhcmVpbm5vdmF0aW9uLmNvbRNJbm5vdmF0aW9uIE1vdmVtZW50ZAIDD2QWAmYPZBYCZg8VAhZodHRwOi8vd3d3LmNlLm9yZy9ibG9nEERpZ2l0YWwgRGlhbG9ndWVkAgQPZBYCZg9kFgJmDxUCFGh0dHA6Ly93d3cuY2Uub3JnL2kzC2kzIE1hZ2F6aW5lZAIFD2QWAmYPZBYCZg8VAh1odHRwOi8vd3d3LmdyZWVuZXJnYWRnZXRzLm9yZw9HcmVlbmVyIEdhZGdldHNkAgYPZBYCZg9kFgJmDxUCFmh0dHA6Ly9yZXNlYXJjaC5jZS5vcmcPTWFya2V0IFJlc2VhcmNoZAIHD2QWAmYPZBYCZg8VAhxodHRwOi8vd3d3LmNlYWZvdW5kYXRpb24ub3JnDkNFQSBGb3VuZGF0aW9uZAIID2QWAmYPDxYCHgdWaXNpYmxlaGRkAgsPZBYCZg9kFgICAg9kFgJmD2QWAmYPZBYGAgEPZBYEZg9kFgICAg9kFgpmD2QWAmYPZBYCZg8VBxUvRXZlbnRzL0tleW5vdGVzLmFzcHgAMy9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy8xMzMwNF8zLmpwZwAyPGEgY2xhc3M9InJlYWRtb3JlIiBocmVmPScvRXZlbnRzL0tleW5vdGVzLmFzcHgnID4ABDwvYT5kAgEPZBYCZg9kFgJmDxUHcGh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9OZXdzL0NFUy1QcmVzcy1SZWxlYXNlcy9DRVMtUHJlc3MtUmVsZWFzZS5hc3B4P05vZGVJRD00NjViYTk0YS00M2RkLTQwOWMtYTNjYy03NDczNmQxNmQ3ZTUPdGFyZ2V0PSdfYmxhbmsnOS9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy9FTV9DRVNIUFNsaWRlLmpwZwCcATxhIGNsYXNzPSJyZWFkbW9yZSIgaHJlZj0naHR0cDovL3d3dy5jZXN3ZWIub3JnL05ld3MvQ0VTLVByZXNzLVJlbGVhc2VzL0NFUy1QcmVzcy1SZWxlYXNlLmFzcHg/Tm9kZUlEPTQ2NWJhOTRhLTQzZGQtNDA5Yy1hM2NjLTc0NzM2ZDE2ZDdlNScgdGFyZ2V0PSdfYmxhbmsnPgAEPC9hPmQCAg9kFgJmD2QWAmYPFQeEAWh0dHA6Ly93d3cuY2Vzd2ViLm9yZy92aWRlbz9iY2tleT1BUX5+LEFBQUFCaDNDX2RFfix6QmtYcUNVOEtWYVBENWVXTWxMNFRTZC03MnJpTGRnViZhbXA7YmNsaWQ9Mjc1Mjc4MDUxNzAwMSZhbXA7YmN0aWQ9Mjc1Mjg2ODIzNzAwMQ90YXJnZXQ9J19ibGFuaydAL2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzLzEzMzA1X0NFU1RWc2xpZGVfdmlkLmpwZwCwATxhIGNsYXNzPSJyZWFkbW9yZSIgaHJlZj0naHR0cDovL3d3dy5jZXN3ZWIub3JnL3ZpZGVvP2Jja2V5PUFRfn4sQUFBQUJoM0NfZEV+LHpCa1hxQ1U4S1ZhUEQ1ZVdNbEw0VFNkLTcycmlMZGdWJmFtcDtiY2xpZD0yNzUyNzgwNTE3MDAxJmFtcDtiY3RpZD0yNzUyODY4MjM3MDAxJyB0YXJnZXQ9J19ibGFuayc+AAQ8L2E+ZAIDD2QWAmYPZBYCZg8VB1NodHRwOi8vd3d3LmNlLm9yZy9CbG9nL0FydGljbGVzLzIwMTMvT2N0b2Jlci9TdGF5LUNvbm5lY3RlZC13aXRoLUluZHVzdHJ5Rm9ydW0uYXNweA90YXJnZXQ9J19ibGFuayc8L2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzL0NFQUlGX0NFU0hQU2xpZGUuanBnAH88YSBjbGFzcz0icmVhZG1vcmUiIGhyZWY9J2h0dHA6Ly93d3cuY2Uub3JnL0Jsb2cvQXJ0aWNsZXMvMjAxMy9PY3RvYmVyL1N0YXktQ29ubmVjdGVkLXdpdGgtSW5kdXN0cnlGb3J1bS5hc3B4JyB0YXJnZXQ9J19ibGFuayc+AAQ8L2E+ZAIED2QWAmYPZBYCZg8VBzQvRm9vdGVyLVBhZ2VzL0Fib3V0LUNFUy9Ib3ctdG8tUmVnaXN0ZXItZm9yLUNFUy5hc3B4AEMvY2Vzd2ViL21lZGlhL0NFU1dlYi9TbGlkZXNob3clMjBJbWFnZXMvMTI5NTZfSG93dG9SZWdfSFBTbGlkZTIuanBnAFE8YSBjbGFzcz0icmVhZG1vcmUiIGhyZWY9Jy9Gb290ZXItUGFnZXMvQWJvdXQtQ0VTL0hvdy10by1SZWdpc3Rlci1mb3ItQ0VTLmFzcHgnID4ABDwvYT5kAgEPZBYCAgIPZBYKZg9kFgJmD2QWAmYPFQEzL2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzLzEzMzA0XzMuanBnZAIBD2QWAmYPZBYCZg8VATkvY2Vzd2ViL21lZGlhL0NFU1dlYi9TbGlkZXNob3clMjBJbWFnZXMvRU1fQ0VTSFBTbGlkZS5qcGdkAgIPZBYCZg9kFgJmDxUBQC9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy8xMzMwNV9DRVNUVnNsaWRlX3ZpZC5qcGdkAgMPZBYCZg9kFgJmDxUBPC9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1NsaWRlc2hvdyUyMEltYWdlcy9DRUFJRl9DRVNIUFNsaWRlLmpwZ2QCBA9kFgJmD2QWAmYPFQFDL2Nlc3dlYi9tZWRpYS9DRVNXZWIvU2xpZGVzaG93JTIwSW1hZ2VzLzEyOTU2X0hvd3RvUmVnX0hQU2xpZGUyLmpwZ2QCBQ9kFgRmD2QWAgICD2QWIGYPZBYCZg9kFgJmDxUJIjxkaXYgY2xhc3M9J25ld3NfdGFiJyBpZD0nbmV3c18xJyAAAT4KMTAvMjIvMjAxMyQyMjlmNDMxOS1hMjRhLTQ4YmUtYWQyZS1mZDMxZTZjNGViN2FJU29ueSBQcmVzaWRlbnQgYW5kIENFTyBLYXp1byBIaXJhaSB0byBEZWxpdmVyIEtleW5vdGUgQWRkcmVzcyBhdCAyMDE0IENFU2V+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvTmV3cy9CdXp6d29ydGh5JTIwVGh1bWJuYWlscy9LYXp1by1IaXJhaV9Tb255LmdpZj93aWR0aD0xNjUmaGVpZ2h0PTExMCZleHQ9LmdpZrEGUHJlc2lkZW50IGFuZCBDRU8gb2YgU29ueSBDb3Jwb3JhdGlvbiwgS2F6dW8gKCZsZHF1bztLYXomcmRxdW87KSBIaXJhaSwgd2lsbCBkZWxpdmVyIHRoZSBvcGVuaW5nIG1vcm5pbmcgVGVjaCBUaXRhbnMga2V5bm90ZSBhZGRyZXNzIGF0IHRoZSAyMDE0IEludGVybmF0aW9uYWwgQ0VTLCBicmluZ2luZyBoaXMgdW5pcXVlIHBlcnNwZWN0aXZlIGFuZCBpbnNpZ2h0cyBhYm91dCB0aGUgbGF0ZXN0IGlubm92YXRpb25zIG9jY3VycmluZyBhdCB0aGUgaW50ZXJzZWN0aW9uIG9mIGNvbnRlbnQgYW5kIGhhcmR3YXJlLiBNci4gSGlyYWkmcnNxdW87cyBrZXlub3RlIGFkZHJlc3Mgd2lsbCBiZSBwYXJ0IG9mIHRoZSA8YSBocmVmPSJodHRwOi8vY2Vzd2ViLm9yZy9FdmVudHMvS2V5bm90ZXMuYXNweCI+VGVjaCBUaXRhbnMga2V5bm90ZSBzZXJpZXM8L2E+LCB3aGVyZSBDRU9zIGZyb20gdGhlIG1vc3QgcG93ZXJmdWwgY29tcGFuaWVzIGluIHRlY2hub2xvZ3kgcHJlc2VudCB0aGVpciB2aXNpb24gZm9yIHJldm9sdXRpb25zIGluIHByb2R1Y3RzLCBzZXJ2aWNlcyBhbmQgbmV0d29ya3MgdGhhdCB3aWxsIHNoYXBlIHRoZSBuZXh0IHdhdmUgb2YgaW5ub3ZhdGlvbi48YnIgLz4NCiZuYnNwOzxiciAvPg0KUmVhZCB0aGUgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL05ld3MvQ0VTLVByZXNzLVJlbGVhc2VzL0NFUy1QcmVzcy1SZWxlYXNlLmFzcHg/Tm9kZUlEPTVlM2ZiYTdhLWYyYWYtNDA0MC1iMWFlLWM2N2U4NjdmM2Q0NSIgdGFyZ2V0PSJfYmxhbmsiPmZ1bGwgcHJlc3MgcmVsZWFzZTwvYT4uPGJyIC8+DQombmJzcDs8YnIgLz4NCgBkAgEPZBYCZg9kFgJmDxUJAAAACjEwLzIyLzIwMTMkMjFkNWJhNzctNzAzNi00NDQ0LTkwMTMtMTllNjJmZGI2NDQ4O0NFQSBSZWxlYXNlcyAyMHRoIEFubnVhbCBDRSBIb2xpZGF5IFB1cmNoYXNlIFBhdHRlcm5zIFN0dWR5YX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL2hvbGlkYXktYnV6ei5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5qcGfKCENFQSZyc3F1bztzIDxlbT4yMHRoIEFubnVhbCBDRSBIb2xpZGF5IFB1cmNoYXNlIFBhdHRlcm5zIFN0dWR5IDwvZW0+d2FzIHJlbGVhc2VkIGF0IENFQSZyc3F1bztzIEluZHVzdHJ5IEZvcnVtIGluIExvcyBBbmdlbGVzLiBUaGUgY29uc3VtZXIgc3R1ZHkgZm91bmQgNzQgcGVyY2VudCBvZiB0aG9zZSBwbGFubmluZyB0byBwdXJjaGFzZSBnaWZ0cyB0aGlzIGhvbGlkYXkgc2Vhc29uIGludGVuZCB0byBidXkgQ0UgYXMgZ2lmdHMgdGhpcyB5ZWFyLCBhbGxvY2F0aW5nIDMzIHBlcmNlbnQgb2YgdGhlIG92ZXJhbGwgaG9saWRheSBnaWZ0IGJ1ZGdldCB0byBDRS48YnIgLz4NCjxiciAvPg0KQ0VBIGFsc28gcmVsZWFzZWQgdGhlIHJlc3VsdHMgZnJvbSBpdHMgPGVtPjEwPHN1cD50aDwvc3VwPiBBbm51YWwgVGVlbiBDRSBIb2xpZGF5IFB1cmNoYXNlIFBhdHRlcm5zIFN0dWR5PC9lbT4mbmJzcDt3aGljaCBleGFtaW5lcyBDRSB3aXNoIGxpc3RzLCBnaWZ0aW5nIGludGVudGlvbnMgYW5kIGhvbGlkYXkgc2hvcHBpbmcgcGF0dGVybnMgYW1vbmcgdGVlbnMgYWdlcyAxMiB0byAxNy4gQm90aCByZXBvcnRzIGFyZSBhdmFpbGFibGUgZnJlZSB0byBDRUEgbWVtYmVyIGNvbXBhbmllcyBhdCA8YSBocmVmPSJodHRwOi8vc3BtZW1iZXJzLmNlLm9yZy9Mb2dpbi9QYWdlcy9kZWZhdWx0LmFzcHgiIHRhcmdldD0iX2JsYW5rIj5tZW1iZXJzLkNFLm9yZzwvYT4uIE5vbi1tZW1iZXJzIG1heSBwdXJjaGFzZSB0aGUgcmVwb3J0cyBhdCB0aGUgPGEgaHJlZj0iaHR0cDovL3N0b3JlLmNlLm9yZy9EZWZhdWx0LmFzcHg/VGFiSUQ9MjUxJmFtcDtwcm9kdWN0SWQ9NDc1NzMyIiB0YXJnZXQ9Il9ibGFuayI+Q0VBIFN0b3JlPC9hPi48YnIgLz4NCiZuYnNwOzxiciAvPg0KQWNjZXNzIGJvdGggcmVwb3J0cyBhbmQgcmVhZCB0aGUgZnVsbCByZWxlYXNlIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Uub3JnL05ld3MvTmV3cy1SZWxlYXNlcy9QcmVzcy1SZWxlYXNlcy8yMDEzLVByZXNzLVJlbGVhc2VzL0FubnVhbC1DRUEtSG9saWRheS1Gb3JlY2FzdC1hbmQtU3R1ZHktRmluZHMtQ29uc3VtLmFzcHgiIHRhcmdldD0iX2JsYW5rIj5oZXJlPC9hPi48YnIgLz4NCgBkAgIPZBYCZg9kFgJmDxUJAAAACjEwLzIyLzIwMTMkMGFlNjYzYTItOGI5OC00OGJmLWE0MTItNGU4MDIwNTEyOTBhSk1hcmlhIE1lbm91bm9zIEp1c3QgQW5ub3VuY2VkIGFzIDIwMTMgQ0VTIEVudGVydGFpbm1lbnQgTWF0dGVycyBBbWJhc3NhZG9yZX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL01hcmlhLUV4dHJhLWJ1enouanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTEwJmV4dD0uanBnqwlUZWxldmlzaW9uIGhvc3Qgb2YgRVhUUkEsIENvLUZvdW5kZXIgb2YgQWZ0ZXJCdXp6IFRWIE5ldHdvcmssIGlubm92YXRpdmUgam91cm5hbGlzdCBhbmQgYXV0aG9yIE1hcmlhIE1lbm91bm9zIHdpbGwgc2VydmUgYXMgdGhlIDxhIGhyZWY9Imh0dHA6Ly9zdGFnaW5nLmNlcy5vcmcvRW50ZXJ0YWlubWVudC1NYXR0ZXJzLmFzcHgiPkVudGVydGFpbm1lbnQgTWF0dGVyczwvYT4gKEVNKSBBbWJhc3NhZG9yIGZvciB0aGUgMjAxNCBJbnRlcm5hdGlvbmFsIENFUzxmb250IHNpemU9IjEiPi48L2ZvbnQ+Jm5ic3A7VGhlIEVNIEFtYmFzc2Fkb3IgaWxsdW1pbmF0ZXMgQ0VTJnJzcXVvOyBmb2N1cyBvbiBicmlkZ2luZyB0aGUgZW50ZXJ0YWlubWVudCBhbmQgdGVjaG5vbG9neSBpbmR1c3RyaWVzLiBTcG9uc29yZWQgYnkgPGVtPlZhcmlldHk8L2VtPiwgdGhlPGEgaHJlZj0iaHR0cDovL3N0YWdpbmcuY2VzLm9yZy9FbnRlcnRhaW5tZW50LU1hdHRlcnMuYXNweCI+IEVudGVydGFpbm1lbnQgTWF0dGVyczwvYT4mbmJzcDtwcm9ncmFtIHdpbGwgZmVhdHVyZSBleGhpYml0cywga2V5bm90ZXMsIHBhbmVscyBhbmQgZXZlbnRzIGNyaXRpY2FsIHRvIHRoZSBIb2xseXdvb2QgY29tbXVuaXR5LCBpbmNsdWRpbmcgdGhlIDIwMTQgSUFXVFYgQXdhcmRzIEdhbGEgYW5kIDxlbT5WYXJpZXR5JnJzcXVvO3MgPC9lbT5FbnRlcnRhaW5tZW50IFN1bW1pdCBhdCBDRVMuIE5ldyB0byB0aGUgcHJvZ3JhbSBhcmUgdGhlIEJyZWFrdGhyb3VnaCBvZiB0aGUgWWVhciBBd2FyZHMsIHByb2R1Y2VkIGJ5IFBlbnNrZSBNZWRpYSBDb3JwLiwgd2hpY2ggd2lsbCByZWNvZ25pemUgZXh0cmFvcmRpbmFyeSBhY2hpZXZlbWVudHMgaW4gYSBudW1iZXIgb2YgY2F0ZWdvcmllcyBpbmNsdWRpbmcgbWVkaWEsIGVudGVydGFpbm1lbnQgYW5kIHRlY2hub2xvZ3kuIFJlYWQgdGhlIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9OZXdzL0NFUy1QcmVzcy1SZWxlYXNlcy9DRVMtUHJlc3MtUmVsZWFzZS5hc3B4P05vZGVJRD00NjViYTk0YS00M2RkLTQwOWMtYTNjYy03NDczNmQxNmQ3ZTUiPmZ1bGwgcmVsZWFzZTwvYT4gYW5kIDxhIGhyZWY9Imh0dHBzOi8vY2VzLml0bmludC5jb20vMjAxNC9yZWdvbmxpbmUvUmVnTG9naW4uYXNweCIgdGFyZ2V0PSJfYmxhbmsiPnJlZ2lzdGVyPC9hPiBmb3IgQ0VTIHRvZGF5LiZuYnNwOzxiciAvPg0KAGQCAw9kFgJmD2QWAmYPFQkAAAAKMTAvMjEvMjAxMyQzZGE2MGY2MC1lZjcwLTRjNTktYjAyOC1kYjgyMzJmYTYxZDlBQ0VBIFJlbGVhc2VzIHRoZSAyMDE0IEVkaXRpb24gb2YgRml2ZSBUZWNobm9sb2d5IFRyZW5kcyB0byBXYXRjaCBbfi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL05ld3MvQnV6endvcnRoeSUyMFRodW1ibmFpbHMvNXRlY2hzLmdpZj93aWR0aD0xNjUmaGVpZ2h0PTExMCZleHQ9LmdpZvMFUmVsZWFzZWQgZHVyaW5nIGEgcGFuZWwgZGlzY3Vzc2lvbiBhdCBDRUEmcnNxdW87cyBJbmR1c3RyeSBGb3J1bSBpbiBMb3MgQW5nZWxlcywgPGVtPkZpdmUgVGVjaG5vbG9neSBUcmVuZHMgdG8gV2F0Y2g8L2VtPiBpcyBhbiBhbm51YWwgcHVibGljYXRpb24gdGhhdCBleGFtaW5lcyBmaXZlIHByb21pbmVudCB0ZWNobm9sb2d5IHRyZW5kcyB0aGF0IHdpbGwgaW5mbHVlbmNlIHRoZSBjb25zdW1lciBlbGVjdHJvbmljcyBpbmR1c3RyeSBpbiB0aGUgeWVhcnMgYWhlYWQuIFVzaW5nIHRoZSBsYXRlc3QgY29uc3VtZXIgcmVzZWFyY2ggYW5kIG1hcmtldCBmb3JlY2FzdHMsIHRoZSAyMDE0IGlzc3VlIGxvb2tzIGF0IHRoZSBJbnRlcm5ldCBvZiBUaGluZ3MgKElvVCksIGRyaXZlcmxlc3MgY2FycywgZGlnaXRhbCBoZWFsdGggY2FyZSwgcm9ib3RpY3MgYW5kIHRoZSBmdXR1cmUgb2YgdmlkZW8gZGlzdHJpYnV0aW9uIGFuZCBjb25zdW1wdGlvbi4gPGVtPkZpdmUgVGVjaG5vbG9neSBUcmVuZHMgdG8gV2F0Y2g8L2VtPiBpcyBhIHNwZWNpYWwgc3VwcGxlbWVudCB0byBDRUEmcnNxdW87cyBiaS1tb250aGx5IGZsYWdzaGlwIHB1YmxpY2F0aW9uLCA8YSBocmVmPSJodHRwOi8vd3d3LmNlLm9yZy9pMyI+SXQgSXMgSW5ub3ZhdGlvbjwvYT4gKDxlbT5pMzwvZW0+KS4gQWNjZXNzIHRoZSA8YSBocmVmPSJodHRwOi8vd3d3LmNlLm9yZy9GaXZlVGVjaHMiIHRhcmdldD0iX2JsYW5rIj5mdWxsIHJlcG9ydDwvYT4uJm5ic3A7PGJyIC8+DQoGPC9kaXY+ZAIED2QWAmYPZBYCZg8VCSI8ZGl2IGNsYXNzPSduZXdzX3RhYicgaWQ9J25ld3NfMicgFXN0eWxlPSdkaXNwbGF5Om5vbmU7JwE+CjEwLzIxLzIwMTMkZDI3MWUzOWItODcwOS00NTZmLTg1YzktMzllZjAzYjZmYThiJkNFUyBUViBMYXVuY2hlcyBXaXRoIOKAnFRlY2ggVHJlbmRz4oCdWn4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL2Nlc3R2LmdpZj93aWR0aD0xNjUmaGVpZ2h0PTExMCZleHQ9LmdpZq8GVG9kYXksIENFQSBsYXVuY2hlcyBDRVMgVFYsIGFuIGFubnVhbCB3ZWIgc2VyaWVzIGdpdmluZyB5b3UgYSBnbGltcHNlIGF0IHdoYXQmcnNxdW87cyB0byBjb21lIGF0IHRoaXMgeWVhciZyc3F1bztzIEludGVybmF0aW9uYWwgQ0VTLiBXZSBmaW5kIG91cnNlbHZlcyBhdCBhIG1vbnVtZW50YWwgY3Jvc3Nyb2FkcyBpbiB0aGUgaGlzdG9yeSBvZiB0ZWNoIGFzIHdlIGhlYWQgaW50byB0aGUgMjAxNCBJbnRlcm5hdGlvbmFsIENFUy4gQ2hlY2sgb3V0IHRoZSB0cmVuZHMgdGhhdCBhcmUgcmVjYXN0aW5nIGFuZCB1bHRpbWF0ZWx5IHJlZGVmaW5pbmcgdGhlIHVzZXIgZXhwZXJpZW5jZSBhcyB0ZWNoIG1vdmVzIGZyb20gYW4gZW5hYmxlciB0byBhIGRlc3RpbmF0aW9uIGF0IHRoZSAyMDE0IENFUyBpbiA8YSBocmVmPSJodHRwOi8vd3d3LmNlc3dlYi5vcmcvdmlkZW8/YmNrZXk9QVF+fixBQUFBQmgzQ19kRX4sekJrWHFDVThLVmFQRDVlV01sTDRUU2QtNzJyaUxkZ1YmYW1wO2JjbGlkPTI3NTI3ODA1MTcwMDEmYW1wO2JjdGlkPTI3NTI4NjgyMzcwMDEiPkNFUyBUViAmbGRxdW87VGVjaCBUcmVuZHMuJnJkcXVvOyA8L2E+U3Vic2NyaWJlIHRvIHRoZSBvZmZpY2lhbCBDRVMgPGEgaHJlZj0iaHR0cDovL3d3dy55b3V0dWJlLmNvbS9jZXNvbnRoZXR1YmUiPllvdVR1YmU8L2E+PGEgaHJlZj0iaHR0cDovL3d3dy55b3V0dWJlLmNvbS9jZXNvbnRoZXR1YmUiIHRhcmdldD0iX2JsYW5rIj4gPC9hPmNoYW5uZWwgdG8gYmUgdGhlIGZpcnN0IHRvIGtub3cgd2hlbiB0aGUgbmV4dCBlZGl0aW9uIG9mIENFUyBUViBnb2VzIGxpdmUuPGJyIC8+DQoAZAIFD2QWAmYPZBYCZg8VCQAAAAkxMC85LzIwMTMkZDY2MTUyMzktOTEzYS00YmUzLWIxNGQtOTA3YzYyMTliMTQyL0V4cGVyaWVuY2UgVFYsIFNvdW5kIGFuZCBNb3JlIGF0IENFQSBEZW1vIERheXMgY34vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL2RlbW8tZGF5cy1idXp6LnBuZz93aWR0aD0xNjUmaGVpZ2h0PTExMCZleHQ9LnBuZ94DQ0VBIERlbW8gRGF5cyBhcmUgYmFjayB0aGlzIGZhbGwsIGVuY291cmFnaW5nIGNvbnN1bWVycyB0byB2aXNpdCB0aGVpciBsb2NhbCBlbGVjdHJvbmljcyByZXRhaWxlcnMgdG8gZXhwZXJpZW5jZSBob21lIGVudGVydGFpbm1lbnQgdGVjaG5vbG9naWVzIGZpcnN0IGhhbmQuIFRoaXMgZmFsbCZyc3F1bztzIERlbW8gRGF5cyB3aWxsIGNvbnRpbnVlIHRocm91Z2ggdGhpcyBjb21pbmcgd2Vla2VuZCwgT2N0b2JlciAxMi0xNCwgYW5kIHdpbGwgc2hvd2Nhc2UgdGhlIGxhdGVzdCBpbiBUVnMsIGF1ZGlvIGFuZCBob21lIGVudGVydGFpbm1lbnQgYWNjZXNzb3JpZXMuIExlYXJuIG1vcmUgYWJvdXQgPGEgaHJlZj0iaHR0cDovL2NlYWRlbW9kYXlzLmNvbS9ob21lLmFzcHg/dj0xMDkyMDEzIiB0YXJnZXQ9Il9ibGFuayI+RGVtbyBEYXlzPC9hPiBhbmQgZmluZCBhbiBlbGVjdHJvbmljcyByZXRhaWxlciBuZWFyIHlvdS4mbmJzcDs8YnIgLz4NCgBkAgYPZBYCZg9kFgJmDxUJAAAACTEwLzkvMjAxMyQ2N2MzZDdkNC0xMTcxLTQ3OWUtYWEwOC00NTYxMDFhZWMxZDEvRGlkIFlvdSBNaXNzIHRoZSBFdXJla2EgUGFyayBFeGhpYml0b3IgV2ViaW5hcj9ufi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL0ZvciUyMEV4aGliaXRvcnMvTWVkaWElMjBPcHBzL0NFU19FdXJla2FQYXJrX0Nyb3dkXygzKS5naWY/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5naWayCDxzcGFuIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7Ij5JZiB5b3UgY291bGRuJnJzcXVvO3QgdHVuZSBpbiB0byB0aGUgbGl2ZSBFdXJla2EgUGFyayBFeGhpYml0b3IgV2ViaW5hciwgeW91IGNhbiBub3cgdmlldyBpdDwvc3Bhbj48YSBocmVmPSJodHRwOi8vY29uc3VtZXJlbGVjdHJvbmljcy5hZG9iZWNvbm5lY3QuY29tL3AzeWphZ2xkd2x1LyIgc3R5bGU9ImJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsiIHRhcmdldD0iX2JsYW5rIj4mbmJzcDs8L2E+PGEgaHJlZj0iaHR0cDovL2NvbnN1bWVyZWxlY3Ryb25pY3MuYWRvYmVjb25uZWN0LmNvbS9wM3lqYWdsZHdsdS8iIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IiB0YXJnZXQ9Il9ibGFuayI+aGVyZS48L2E+PHNwYW4gc3R5bGU9ImJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsiPiZuYnNwO1RoZSB3ZWJpbmFyIGhlbHBzJm5ic3A7PC9zcGFuPjxhIGhyZWY9Imh0dHA6Ly9jZXN3ZWIub3JnL1Nob3ctRmxvb3IvQ0VTLVRlY2hab25lcy5hc3B4IzVqdW1wIiBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyIgdGFyZ2V0PSJfYmxhbmsiPkV1cmVrYSBQYXJrPC9hPjxzcGFuIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7Ij4mbmJzcDsoRVApIGV4aGliaXRvcnMgbG9va2luZyB0byBlbmhhbmNlIHRoZWlyIG1lZGlhIGV4cG9zdXJlIGF0IHRoZSAyMDE0IEludGVybmF0aW9uYWwgQ0VTIGJ5IG91dGxpbmluZyB1c2VmdWwgUFIgdGlwcyBhbmQgdG9vbHMgdGhhdCB3aWxsIGdpdmUgRVAgZXhoaWJpdG9ycyBhIGNvbW11bmljYXRpb25zIGFkdmFudGFnZS4gVHVuZSBpbiB0byB0aGlzIHVuaXF1ZSBQUiB3ZWJpbmFyLCBwcmVzZW50ZWQgYnkgZXhwZXJpZW5jZWQgQ0VTIFBSIGV4cGVydHMgZnJvbSBDRUEsIEJ1c2luZXNzIFdpcmUgYW5kIFVQIEdsb2JhbCwgdG8gZmluZCBvdXQgaG93IHlvdXIgY29tcGFueSBjYW4gbWF4aW1pemUgZXhwb3N1cmUuJm5ic3A7PC9zcGFuPgBkAgcPZBYCZg9kFgJmDxUJAAAACTEwLzcvMjAxMyQ5YWYzM2Y1ZC1mYTZiLTQwNjYtOGVhNi1jMjBmZmQ0OGVhM2U8Q0VBIEFubm91bmNlcyBFeHBhbnNpb24gb2YgRXVyZWthIFBhcmsgYW5kIFR3byBOZXcgVGVjaFpvbmVzXn4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL2Nlc2Nyb3dkMi5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5qcGfXB1RoZSBFdXJla2EgUGFyayBUZWNoWm9uZSBhdCB0aGUgMjAxNCBDRVMgd2lsbCBleHBhbmQgYnkgMzAgcGVyY2VudCBhbmQgd2lsbCBmZWF0dXJlIG1vcmUgdGhhbiAyMDAgZW50cmVwcmVuZXVycyBhbmQgc3RhcnR1cHMuIEluIHBhcnRuZXJzaGlwIHdpdGggVVAgR2xvYmFsIChmb3JtYWxseSB0aGUgU3RhcnR1cCBBbWVyaWNhIFBhcnRuZXJzaGlwIGFuZCBTdGFydHVwIFdlZWtlbmQpLCB0aGUgTmF0aW9uYWwgU2NpZW5jZSBGb3VuZGF0aW9uIGFuZCBHZW5lcmFsIEVsZWN0cmljIENvbXBhbnksIEV1cmVrYSBQYXJrIGlzIGEgZGVkaWNhdGVkIGFyZWEgc2hvd2Nhc2luZyBidWRkaW5nIHN0YXJ0dXBzIGFuZCBlbnRyZXByZW5ldXJzLjxiciAvPg0KPGJyIC8+DQpBbHNvIG5ldyBpbiAyMDE0IGlzIHRoZSBBY2FkZW1pYSBUZWNoIFRlY2hab25lLCB3aGljaCB3aWxsIGJlIHdpdGhpbiBFdXJla2EgUGFyaywgc2hvd2Nhc2luZyB0ZWNobm9sb2dpZXMgZW1lcmdpbmcgZnJvbSBjb2xsZWdlcyBhbmQgdW5pdmVyc2l0aWVzLiBDRUEgYWxzbyBhbm5vdW5jZWQgdGhlIGxhdW5jaCBvZiBFdXJla2EgUGFyazogTkVYVCBUZWNoWm9uZSwgYW4gYXJlYSBmb3IgbWlkLXN0YWdlIHN0YXJ0dXBzIHRoYXQgaGF2ZSBsYXVuY2hlZCBhIHByb2R1Y3Qgd2l0aGluIHRoZSBwYXN0IHllYXIuPGJyIC8+DQo8YnIgLz4NClJlYWQgdGhlIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9OZXdzL0NFUy1QcmVzcy1SZWxlYXNlcy9DRVMtUHJlc3MtUmVsZWFzZS5hc3B4P05vZGVJRD03NTZjN2IyZS01ODEzLTQwNmMtODJjNS1iYjNkYzEyOTNlY2EiIHRhcmdldD0iX2JsYW5rIj5mdWxsIHByZXNzIHJlbGVhc2U8L2E+IGFuZCBsZWFybiBtb3JlIGFib3V0IDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9TaG93LUZsb29yL0NFUy1UZWNoWm9uZXMuYXNweCIgdGFyZ2V0PSJfYmxhbmsiPkNFUyBUZWNoWm9uZXM8L2E+LiZuYnNwOzxiciAvPg0KBjwvZGl2PmQCCA9kFgJmD2QWAmYPFQkiPGRpdiBjbGFzcz0nbmV3c190YWInIGlkPSduZXdzXzMnIBVzdHlsZT0nZGlzcGxheTpub25lOycBPgkxMC83LzIwMTMkODg2ZDhhZDQtMDAyNi00NTkzLThmM2YtODhkMmFjNjA3NmFjMUxhdGVzdCBpbiBVbHRyYSBIRCB0byBCZSBGZWF0dXJlZCBhdCB0aGUgMjAxNCBDRVNifi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL05ld3MvQnV6endvcnRoeSUyMFRodW1ibmFpbHMvMTMtMTE5LTBfODk2NC5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5qcGf5BlVsdHJhIEhEIGlzIHRoZSBuZXh0IGdlbmVyYXRpb24gb2YgZGlzcGxheSB0ZWNobm9sb2d5IGZvciB0aGUgaG9tZSBhbmQgZGVsaXZlcnMgZm91ciB0aW1lcyB0aGUgcmVzb2x1dGlvbiBvZiB0b2RheSZyc3F1bztzIGZ1bGwgSGlnaC1EZWZpbml0aW9uIFRWcywgd2l0aCBtb3JlIHRoYW4gZWlnaHQgbWlsbGlvbiBwaXhlbHMgb2YgcmVzb2x1dGlvbi4gVWx0cmEgSEQgd2FzIGxhdW5jaGVkIGF0IHRoZSAyMDEzIEludGVybmF0aW9uYWwgQ0VTIGFuZCB0aGUgMjAxNCBDRVMgd2lsbCBkaXNjdXNzIGJyaW5naW5nIFVsdHJhIEhEIHRvIG1hcmtldCB0aHJvdWdoIGNvbmZlcmVuY2UgcHJvZ3JhbW1pbmcuIENFQSB3aWxsIHByb2R1Y2UgJmxkcXVvO1VsdHJhIEhEIENvbnRlbnQ6IFdoYXQgV2lsbCBXZSBXYXRjaCBpbiAyMDE0IGFuZCBCZXlvbmQ/JnJkcXVvOyBvbiBKYW51YXJ5IDcsIDIwMTQuICZsZHF1bztTZWVpbmcgaXMgQmVsaWV2aW5nICZuZGFzaDsgM0QsIDRLIGFuZCBVSEQsJnJkcXVvOyB3aWxsIHRha2UgcGxhY2Ugb24gSmFudWFyeSA5LCAyMDE0IGFuZCB3aWxsIGJlIHByb2R1Y2VkIGJ5IHRoZSBJbnRlcm5hdGlvbmFsIDNEIGFuZCBBZHZhbmNlZCBJbWFnaW5nIFNvY2lldHksIGFuIG9mZmljaWFsIENFUyBjb25mZXJlbmNlIHBhcnRuZXIuJm5ic3A7IFNlZSB0aGUgZnVsbCA8YSBocmVmPSJodHRwOi8vd3d3LmNlc3dlYi5vcmcvTmV3cy9DRVMtUHJlc3MtUmVsZWFzZXMvQ0VTLVByZXNzLVJlbGVhc2UuYXNweD9Ob2RlSUQ9ZDBmZTA1MjUtMGI4Yy00OThkLTlkYTYtMTc0YTA1NjY4NjBiIiB0YXJnZXQ9Il9ibGFuayI+cHJlc3MgcmVsZWFzZTwvYT4gdG8gbGVhcm4gbW9yZSBhYm91dCBVbHRyYSBIRCBhdCB0aGUgMjAxNCBDRVMuJm5ic3A7PGJyIC8+DQoAZAIJD2QWAmYPZBYCZg8VCQAAAAkxMC8zLzIwMTMkNDEzOGRjY2ItYzY2MC00NWI0LTlmYWEtOTFjNzRhZDZjOWNmTURpZ2l0YWwgRml0bmVzcyBFeGhpYml0IEFyZWEgRXhwYW5kcyBieSAzMCBQZXJjZW50IGZvciAyMDE0IEludGVybmF0aW9uYWwgQ0VTYX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL2ZpdG5lc3MtYnV6ei5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5qcGf4BlRoZSBkaWdpdGFsIGZpdG5lc3MgZm9vdHByaW50IGF0IENFUyBoYXMgc2VlbiAzMCBwZXJjZW50IGdyb3d0aCBmb3IgMjAxNC4gVGhlIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9TaG93LUZsb29yL0NFUy1UZWNoWm9uZXMuYXNweCMyNmp1bXAiPkZpdG5lc3NUZWNoPC9hPiBUZWNoWm9uZSwgcHJvZHVjZWQgaW4gcGFydG5lcnNoaXAgd2l0aDxhIGhyZWY9Imh0dHA6Ly9saXZpbmdpbmRpZ2l0YWx0aW1lcy5jb20vIiB0YXJnZXQ9Il9ibGFuayI+IExpdmluZyBpbiBEaWdpdGFsIFRpbWVzPC9hPiwgd2lsbCBmb2N1cyBleGNsdXNpdmVseSBvbiB0aGUgbmV3ZXN0IHRlY2hub2xvZ2llcyBmb3IgdGhlIHNwb3J0cyBhbmQgZml0bmVzcyBlbnRodXNpYXN0LiBBY2NvcmRpbmcgdG8gYSBDRUEgc2VtaS1hbm51YWwgcmVwb3J0LCB0aGUgbWFya2V0IGZvciBmaXRuZXNzIHRlY2hub2xvZ3kgaXMgcHJlZGljdGVkIHRvIGdyb3cgbmVhcmx5IDI1IHBlcmNlbnQgaW4gMjAxNCBhbmQgdGhlIDIwMTQgQ0VTIHdpbGwgc2hvd2Nhc2UgdGhlIGxhdGVzdCBkZXZlbG9wbWVudHMgYW5kIGRpc2NvdmVyaWVzIGFjcm9zcyB0aGlzIGdyb3dpbmcgZmllbGQuIFNlZSB0aGUgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL05ld3MvQ0VTLVByZXNzLVJlbGVhc2VzL0NFUy1QcmVzcy1SZWxlYXNlLmFzcHg/Tm9kZUlEPWRmOTJkZjU5LTBhNTYtNDg5NS1iNzNjLTIzZGNhMmMwMGRjMyI+ZnVsbCByZWxlYXNlPC9hPiBhbmQgbGVhcm4gbW9yZSBhYm91dCB0aGUgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL1Nob3ctRmxvb3IvQ0VTLVRlY2hab25lcy5hc3B4IzI2anVtcCIgdGFyZ2V0PSJfYmxhbmsiPkZpdG5lc3NUZWNoPC9hPiBUZWNoWm9uZS48YnIgLz4NCgBkAgoPZBYCZg9kFgJmDxUJAAAACTEwLzMvMjAxMyRhMzFjN2YwNi1mOGZjLTRhZmYtOWU4MC01YWYwZDcwZDEwMTY8SGlnaCBUZWNoIEZhc2hpb24gdG8gQmUgRmVhdHVyZWQgYXQgTmV3IEZhc2hpb25XYXJlIFRlY2hab25lX34vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL2JhZGdlLXBhZ2UuanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTEwJmV4dD0uanBnowdDRUEgcmVjZW50bHkgYW5ub3VuY2VkIGEgbmV3IDxhIGhyZWY9In4vU2hvdy1GbG9vci9DRVMtVGVjaFpvbmVzLmFzcHgiPlRlY2hab25lPC9hPiBmb3IgdGhlIDIwMTQgSW50ZXJuYXRpb25hbCBDRVMuIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9TaG93LUZsb29yL0NFUy1UZWNoWm9uZXMuYXNweCM1OWp1bXAiPkZhc2hpb25XYXJlPC9hPiwgcHJvZHVjZWQgaW4gcGFydG5lcnNoaXAgd2l0aCA8YSBocmVmPSJodHRwOi8vbGl2aW5naW5kaWdpdGFsdGltZXMuY29tLyIgdGFyZ2V0PSJfYmxhbmsiPkxpdmluZyBpbiBEaWdpdGFsIFRpbWVzPC9hPiwgd2lsbCBzaG93Y2FzZSB0aGUgbGF0ZXN0IGlubm92YXRpb25zIGluIHdlYXJhYmxlIHRlY2hub2xvZ3kgdGhhdCBtaXggZmFzaGlvbiBhbmQgZnVuY3Rpb24uJm5ic3A7ICZsZHF1bztUaGUgRmFzaGlvbldhcmUgVGVjaFpvbmUgaW50ZWdyYXRlcyBzdHlsZSwgZnVuY3Rpb24gYW5kIHRlY2hub2xvZ3kgdG8gY3JlYXRlIGEgd293LWZhY3RvciwgaGlnaC10ZWNoIHNwYWNlIGF0IHRoZSAyMDE0IENFUyZyZHF1bzsgc2FpZCBLYXJlbiBDaHVwa2EsIHNlbmlvciB2aWNlIHByZXNpZGVudCwgSW50ZXJuYXRpb25hbCBDRVMgYW5kIGNvcG9yYXRlIGJ1c2luZXNzIHN0cmF0ZWd5LCBDRUEuIFNlZSB0aGUgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL05ld3MvQ0VTLVByZXNzLVJlbGVhc2VzL0NFUy1QcmVzcy1SZWxlYXNlLmFzcHg/Tm9kZUlEPWUzMDQxZjUzLTkzZjUtNDFkYy05MGEyLTM2OTJkZmI1N2YyNiI+ZnVsbCByZWxlYXNlPC9hPiBhbmQgbGVhcm4gbW9yZSBhYm91dCB0aGUgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL1Nob3ctRmxvb3IvQ0VTLVRlY2hab25lcy5hc3B4IzU5anVtcCI+RmFzaGlvbldhcmUgPC9hPlRlY2hab25lLiZuYnNwOzxiciAvPg0KAGQCCw9kFgJmD2QWAmYPFQkAAAAJMTAvMy8yMDEzJGMxZjc0ZTJhLTdjZDAtNDVmZC05YzBlLTAxMTA2OWIyNTE0M0RBdWRp4oCZcyBSdXBlcnQgU3RhZGxlciBXaWxsIERlbGl2ZXIgVGVjaCBUaXRhbnMgS2V5bm90ZSBhdCAyMDE0IENFU2l+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvTmV3cy9CdXp6d29ydGh5JTIwVGh1bWJuYWlscy9DRVMyMDE0X0Jsb2dfU3RhcnRVcC5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5qcGebBVRoZSBsYXRlc3QgdHJlbmRzIGFuZCB0ZWNobm9sb2dpZXMgaW4gdGhlIGF1dG8gaW5kdXN0cnkgYXJlIGNvbWluZyB0byBDRVMuIENFQSByZWNlbnRseSZuYnNwOzxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9OZXdzL0NFUy1QcmVzcy1SZWxlYXNlcy9DRVMtUHJlc3MtUmVsZWFzZS5hc3B4P05vZGVJRD0zYzMxMjYwNC0zZmNmLTRhMzctOGZkNi04OGFhYjk2YzAwMTQiIHRhcmdldD0iX2JsYW5rIj5hbm5vdW5jZWQ8L2E+IGFub3RoZXIga2V5bm90ZSBhZGRyZXNzIGluIHRoZSBUZWNoIFRpdGFuIHNlcmllcywgd2hlcmUgQ0VPcyBmcm9tIHRoZSBtb3N0IHBvd2VyZnVsIGNvbXBhbmllcyBpbiB0ZWNobm9sb2d5IHByZXNlbnQgdGhlaXIgdmlzaW9uIGZvciB0aGUgbmV4dCB3YXZlIG9mIGlubm92YXRpb24uIFJ1cGVydCBTdGFkbGVyLCBDaGFpcm1hbiBvZiB0aGUgQm9hcmQgb2YgTWFuYWdlbWVudCBvZiBBdWRpIEFHLCB3aWxsIGRlbGl2ZXIgYSBrZXlub3RlIGF0IDg6MzAgcC5tLiBNb25kYXksIEphbnVhcnkgNiBpbiBUaGUgQ29zbW9wb2xpdGFuJnJzcXVvO3MgQ2hlbHNlYSB0aGVhdGVyLiBWaXNpdCBvdXIgPGEgaHJlZj0ifi9FdmVudHMvS2V5bm90ZXMuYXNweCI+a2V5bm90ZXM8L2E+IHBhZ2UgZm9yIG1vcmUgaW5mb3JtYXRpb24uJm5ic3A7PGJyIC8+DQoGPC9kaXY+ZAIMD2QWAmYPZBYCZg8VCSI8ZGl2IGNsYXNzPSduZXdzX3RhYicgaWQ9J25ld3NfNCcgFXN0eWxlPSdkaXNwbGF5Om5vbmU7JwE+CTEwLzMvMjAxMyQ4YjBmZDY5OC01MzkwLTQwZGEtOGQ3YS00YjNmMWU5ZTAwNGY5TmV3IE1vdGlvblRlY2ggVGVjaFpvbmUgV2lsbCBGZWF0dXJlIElubm92YXRpb24gaW4gTW90aW9uZH4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzLzEyNDk5TW90aW9uVGVjaC5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5qcGeBBUNFQSByZWNlbnRseSBhbm5vdW5jZWQgYSBuZXcgVGVjaFpvbmUgZm9yIHRoZSAyMDE0IEludGVybmF0aW9uYWwgQ0VTLiA8YSBocmVmPSJodHRwOi8vd3d3LmNlc3dlYi5vcmcvU2hvdy1GbG9vci9DRVMtVGVjaFpvbmVzLmFzcHgjMThqdW1wIiB0YXJnZXQ9Il9ibGFuayI+TW90aW9uVGVjaDwvYT4sIHNwb25zb3JlZCBieSBNRU1TIGluZHVzdHJ5IGdyb3VwLCB3aWxsIGZlYXR1cmUgdGhlIGxhdGVzdCBpbiBtb3Rpb24gdGVjaG5vbG9neSBmaWVsZC4gRnJvbSBnZXN0dXJlIHJlY29nbml0aW9uIGFuZCBhdWdtZW50ZWQgcmVhbGl0eSwgdG8gZXllLXRyYWNraW5nIHRlY2hub2xvZ3kgYW5kIG1vdGlvbiBzZW5zb3JzLCBhdHRlbmRlZXMgd2lsbCBkaXNjb3ZlciBuZXcgd2F5cyB0byBjb25uZWN0IGFuZCBpbnRlcmFjdCB3aXRoIHRoZWlyIGRldmljZXMuIFBsZWFzZSBzZWUgdGhlIGZ1bGwgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL05ld3MvQ0VTLVByZXNzLVJlbGVhc2VzL0NFUy1QcmVzcy1SZWxlYXNlLmFzcHg/Tm9kZUlEPTc0MDQxZTIwLTJhNmMtNDY1YS1iMGRmLWY0OTY0MzVmZmRhMiIgdGFyZ2V0PSJfYmxhbmsiPnByZXNzIHJlbGVhc2U8L2E+IGZvciBtb3JlIGluZm9ybWF0aW9uLiZuYnNwOzxiciAvPg0KAGQCDQ9kFgJmD2QWAmYPFQkAAAAJMTAvMS8yMDEzJGU4YzYxZWFhLTNjM2MtNDkwNS04MGEwLTM2NDYyYmUxNjkzZUNTYXZlIHRoZSBEYXRlOiAyMDE0IENFUyBFdXJla2EgUGFyayBFeGhpYml0b3IgV2ViaW5hciDigJMgT2N0b2JlciA4Yn4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL0VQLWJ1enp3b3J0aHkuanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTEwJmV4dD0uanBnyQZUaGUgMjAxNCBDRVMgRXVyZWthIFBhcmsgRXhoaWJpdG9yIHdlYmluYXIgd2lsbCBoZWxwIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9TaG93LUZsb29yL0NFUy1UZWNoWm9uZXMuYXNweCM1anVtcCI+RXVyZWthIFBhcms8L2E+IChFUCkgZXhoaWJpdG9ycyBsb29raW5nIHRvIGVuaGFuY2UgdGhlaXIgbWVkaWEgZXhwb3N1cmUgYXQgdGhlIDIwMTQgSW50ZXJuYXRpb25hbCBDRVMuIFRoZSB3ZWJpbmFyIHdpbGwgb3V0bGluZSB1c2VmdWwgUFIgdGlwcyBhbmQgdG9vbHMgdGhhdCB3aWxsIGdpdmUgRVAgZXhoaWJpdG9ycyBhIGNvbW11bmljYXRpb25zIGFkdmFudGFnZS4gVHVuZSBpbiB0byB0aGlzIHVuaXF1ZSBQUiB3ZWJpbmFyLCBwcmVzZW50ZWQgYnkgZXhwZXJpZW5jZWQgQ0VTIFBSIGV4cGVydHMgZnJvbSBCdXNpbmVzcyBXaXJlLCB0aGUgTmF0aW9uYWwgU2NpZW5jZSBGb3VuZGF0aW9uIGFuZCBVcEdsb2JhbCwgdG8gZmluZCBvdXQgaG93IHlvdXIgY29tcGFueSBjYW4gbWF4aW1pemUgZXhwb3N1cmUuJm5ic3A7TGVhcm4gbW9yZSBhbmQgcmVnaXN0ZXIgPGEgaHJlZj0iaHR0cDovL3d3dy5jZS5vcmcvRXZlbnRzLWFuZC1Bd2FyZHMvQ0VBLVdlYmluYXItQ2FsZW5kYXIvMjAxNC1FdXJla2EtUGFyay1FeGhpYml0b3ItUFItV29ya3Nob3AuYXNweCIgdGFyZ2V0PSJfYmxhbmsiPmhlcmU8L2E+LjxiciAvPg0KJm5ic3A7PGJyIC8+DQo8c3Ryb25nPkRhdGU8L3N0cm9uZz46IFR1ZXNkYXksIE9jdG9iZXIgOCwgMjAxMzxiciAvPg0KPHN0cm9uZz5UaW1lPC9zdHJvbmc+OiAyJm5kYXNoOzMgcC5tLiAoRVQpIC8gMTFhLm0uJm5kYXNoO05vb24gKFBUKTxiciAvPg0KAGQCDg9kFgJmD2QWAmYPFQkAAAAJOS8yNS8yMDEzJDk0N2FhMjM3LWIxNDgtNDNkNi04N2IwLTVmYTNmOGJjZWJhNDdGaW5kIG91dCBXaGF0J3MgTmV4dCBEdXJpbmcgT3VyIFVwY29taW5nIEdvb2dsZSBIYW5nb3V0Yn4vY2Vzd2ViL21lZGlhL0NFU1dlYi9OZXdzL0J1enp3b3J0aHklMjBUaHVtYm5haWxzL0luZHVzdHJ5Rm9ydW0uanBnP3dpZHRoPTE2NSZoZWlnaHQ9MTA5JmV4dD0uanBnowZJdCYjMzk7cyB0aGUgcXVlc3Rpb24gd2UgYWxsIGFzazogV2hhdCYjMzk7cyBuZXh0PyBXZSBhbnN3ZXIgaXQgZXZlcnkgSmFudWFyeSBhdCBDRVMgaW4gTGFzIFZlZ2FzLiBCdXQgaWYgeW91IGNhbiYjMzk7dCB3YWl0IChoZWNrLCA8ZW0+d2UmbmJzcDs8L2VtPmNhbiYjMzk7dCBldmVuIHdhaXQpLCBiZSBzdXJlIHRvIGpvaW4gb3VyIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Uub3JnL0Jsb2cvQXJ0aWNsZXMvMjAxMy9TZXB0ZW1iZXIvS25vdy1XaGF0LVRlY2gtVHJlbmRzLXRvLVdhdGNoLVdlLURvLmFzcHgiIHRhcmdldD0iX2JsYW5rIj5Hb29nbGUgSGFuZ291dDwvYT4gdGhpcyBUaHVyc2RheSwgd2hlcmUgd2UmIzM5O2xsIGRpc2N1c3MgdGhlIEludGVybmV0IG9mIEV2ZXJ5dGhpbmcsIG9uZSBvZiBvdXIgZml2ZSB0ZWNobm9sb2d5IHRyZW5kcyB0byB3YXRjaCB0aGlzIHllYXIuIEpvaW4gSmVmZiBKb3NlcGgsIHNlbmlvciB2aWNlIHByZXNpZGVudCBvZiBjb21tdW5pY2F0aW9ucyBhbmQgc3RyYXRlZ2ljIHJlbGF0aW9uc2hpcHMgYXQgQ0VBLCBhcyBoZSBsZWFkcyBhIGRpc2N1c3Npb24gd2l0aCBTaGF3biBEdUJyYXZhYywgY2hpZWYgZWNvbm9taXN0IGFuZCBzZW5pb3IgZGlyZWN0b3Igb2YgcmVzZWFyY2ggYXQgQ0VBLCBhbmQgUm9zcyBSdWJpbiwgcHJpbmNpcGFsIGFuYWx5c3QgYXQgUmV0aWNsZSBSZXNlYXJjaC4gPGEgaHJlZj0iaHR0cHM6Ly9wbHVzLmdvb2dsZS5jb20vZXZlbnRzL2NvaTk1MzQ1YjNydGo0NmVmYWppZDFyaXNxcyIgdGFyZ2V0PSJfYmxhbmsiPkpvaW4gb3VyIEhhbmdvdXQ8L2E+LgBkAg8PZBYCZg9kFgJmDxUJAAAACTkvMjAvMjAxMyQwOTE5MDJiOS01ZTg1LTQyNzctYmM5My0wM2VhNTIyNDY2NzZGSW50ZWwgQ0VPLCBCcmlhbiBLcnphbmljaCwgdG8gRGVsaXZlciBUZWNoIFRpdGFucyBLZXlub3RlIGF0IDIwMTQgQ0VTIGl+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvTmV3cy9CdXp6d29ydGh5JTIwVGh1bWJuYWlscy9DRVMyMDE0X0Jsb2dfU3RhcnRVcC5qcGc/d2lkdGg9MTY1JmhlaWdodD0xMTAmZXh0PS5qcGfWBUNFQSBhbm5vdW5jZWQgdGhhdCBCcmlhbiBLcnphbmljaCwgSW50ZWwmcnNxdW87cyBuZXcgQ0VPLCB3aWxsIGRlbGl2ZXIgYSBUZWNoIFRpdGFucyA8YSBocmVmPSJodHRwOi8vd3d3LmNlc3dlYi5vcmcvRXZlbnRzL0tleW5vdGVzL1RlY2gtVGl0YW5zLU1vbmRheSI+a2V5bm90ZSBhZGRyZXNzPC9hPi4gVGhlIFRlY2ggVGl0YW5zIGtleW5vdGUgc2VyaWVzIHdpbGwgZmVhdHVyZSBDRU9zIGZyb20gdGhlIG1vc3QgcG93ZXJmdWwgY29tcGFuaWVzIGluIHRlY2hub2xvZ3kgd2hvIHdpbGwgcHJlc2VudCB0aGVpciB2aXNpb24gZm9yIHRoZSB1cGNvbWluZyByZXZvbHV0aW9ucyBpbiB0aGUgY29uc3VtZXIgdGVjaG5vbG9neSBpbmR1c3RyeS4mbmJzcDsgS3J6YW5pY2gmcnNxdW87cyBrZXlub3RlIGFkZHJlc3Mgd2lsbCBiZSBoZWxkIGF0IDY6MzAgcC5tLiwgTW9uZGF5LCBKYW51YXJ5IDYsIGluIFRoZSBWZW5ldGlhbiZyc3F1bztzIFBhbGF6em8gQmFsbHJvb20uIExlYXJuIG1vcmUgYWJvdXQgPGEgaHJlZj0iaHR0cDovL3d3dy5jZXN3ZWIub3JnL0V2ZW50cy9LZXlub3Rlcy9UZWNoLVRpdGFucy1Nb25kYXkiPktyemFuaWNoJnJzcXVvO3Mga2V5bm90ZTwvYT4gYW5kIHN0YXkgdHVuZWQgZm9yIG1vcmUgQ0VTIDxhIGhyZWY9Imh0dHA6Ly93d3cuY2Vzd2ViLm9yZy9FdmVudHMvS2V5bm90ZXMuYXNweCI+a2V5bm90ZSBhbm5vdW5jZW1lbnRzPC9hPi4mbmJzcDs8YnIgLz4NCgY8L2Rpdj5kAgEPZBYCAgIPZBYgZg9kFgJmD2QWAmYPFQMXPGxpIGlkPSduZXdzXzFfYnV0dG9uJyAPY2xhc3M9J29uX3BhZ2UnPiA+PGEgb25jbGljaz0icmV0dXJuIG5ld3NBY3RpdmUoJ25ld3NfMScpOyIgaHJlZj0nJz4xPC9hPjwvbGk+ZAIBD2QWAmYPZBYCZg8VAwAAAGQCAg9kFgJmD2QWAmYPFQMAAABkAgMPZBYCZg9kFgJmDxUDAAAAZAIED2QWAmYPZBYCZg8VAxc8bGkgaWQ9J25ld3NfMl9idXR0b24nIAA+ID48YSBvbmNsaWNrPSJyZXR1cm4gbmV3c0FjdGl2ZSgnbmV3c18yJyk7IiBocmVmPScnPjI8L2E+PC9saT5kAgUPZBYCZg9kFgJmDxUDAAAAZAIGD2QWAmYPZBYCZg8VAwAAAGQCBw9kFgJmD2QWAmYPFQMAAABkAggPZBYCZg9kFgJmDxUDFzxsaSBpZD0nbmV3c18zX2J1dHRvbicgAD4gPjxhIG9uY2xpY2s9InJldHVybiBuZXdzQWN0aXZlKCduZXdzXzMnKTsiIGhyZWY9Jyc+MzwvYT48L2xpPmQCCQ9kFgJmD2QWAmYPFQMAAABkAgoPZBYCZg9kFgJmDxUDAAAAZAILD2QWAmYPZBYCZg8VAwAAAGQCDA9kFgJmD2QWAmYPFQMXPGxpIGlkPSduZXdzXzRfYnV0dG9uJyAAPiA+PGEgb25jbGljaz0icmV0dXJuIG5ld3NBY3RpdmUoJ25ld3NfNCcpOyIgaHJlZj0nJz40PC9hPjwvbGk+ZAIND2QWAmYPZBYCZg8VAwAAAGQCDg9kFgJmD2QWAmYPFQMAAABkAg8PZBYCZg9kFgJmDxUDAAAAZAIHD2QWAmYPZBYCAgIPZBYEZg9kFgJmD2QWAmYPFQIeL0V4dHJhUGFnZXMvQnJhbmQtTWF0dGVycy5hc3B4XX4vY2Vzd2ViL21lZGlhL0NFU1dlYi9TbGlkZXNob3clMjBJbWFnZXMvQnJhbmRNYXR0ZXJzXzIyMHg1Ny5qcGc/d2lkdGg9MjIwJmhlaWdodD01NyZleHQ9LmpwZ2QCAQ9kFgJmD2QWAmYPFQITaHR0cDovL2Jsb2cuY2Uub3JnL1h+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvYXNzZXRzL2ltYWdlcy9leHRyYXMvZGlnLWRpYWxvZ3VlLmpwZz93aWR0aD0yMjAmaGVpZ2h0PTU3JmV4dD0uanBnZAIPD2QWAmYPDxYCHwBoZBYCZg8PFgIfAGhkZGQSpa7m878bbd4M45izx3OUWpnMdg1Da5IN/c5+khXTuA==" />
</div>

<input type="hidden" name="lng" id="lng" value="en-US" />
<script type="text/javascript">
	//<![CDATA[

function PM_Postback(param) { if (window.top.HideScreenLockWarningAndSync) { window.top.HideScreenLockWarningAndSync(1080); }__doPostBack('m',param); }
function PM_Callback(param, callback, ctx) { if (window.top.HideScreenLockWarningAndSync) { window.top.HideScreenLockWarningAndSync(1080); }WebForm_DoCallback('m',param,callback,ctx,null,true); }
//]]>
</script>
<script src="/ScriptResource.axd?d=bZ8Ml8IJIicjRnK9UItL1u7FqXpr_mPZr1pI4jRGd8lGJG4T6SlHSj_AMUl4I-Vc3N_AKrMpb3eBSk9PNEcN0JIaVdMYeSeLKoWKY7XRO5TbUuMKPVWDnHEIqlaBoQCm0&amp;t=ffffffff8dea9fe4" type="text/javascript"></script>
    <div id="CMSHeaderDiv">
	<!-- -->
</div>
    <div id="ctxM">

</div>
    <script type="text/javascript" src="/cesweb/media/CESWeb/assets/js/custom/functions.js"></script>
<!-- start black bar -->
      <div id="header-wrapper">
		<div id="header-top-wrapper">
			<div id="header-top">
              <div id="header-more-sites">
  <div id="header-more-expander">
    <ul class="ces">
<li><a href="http://www.ce.org">CEA - CE.org</a></li><li><a href="http://www.cesweb.org">International CES</a></li><li><a href="http://www.declareinnovation.com">Innovation Movement</a></li><li><a href="http://www.ce.org/blog">Digital Dialogue</a></li><li><a href="http://www.ce.org/i3">i3 Magazine</a></li><li><a href="http://www.greenergadgets.org">Greener Gadgets</a></li><li><a href="http://research.ce.org">Market Research</a></li><li><a href="http://www.ceafoundation.org">CEA Foundation</a></li>     </ul>
    <a id="the-expander" href="#">More CEA sites</a>
  </div>
</div>
              <div id="header-feed"></div>
			</div>
		</div>
            </div>
<!-- end black bar -->
<div id="newwrap">
    <div id="container">
        <div id="content-container">
            <div id="header">
                <div id="logo">
                    <a href="/Home.aspx"><img id="p_lt_zoneLogo_EditableImage_ucEditableImage_imgImage" src="http://content.ce.org/2013ces/images/hpimages/header/cesweb_headerlogo.png" alt="" />

</a>
                </div>
                <div id="headTop">
                    <div id="topsearch">
                                    <input type="hidden" id="Hidden1" value="default_collection" name="site" />
            <input type="hidden" id="Hidden2" value="2011CESweb" name="client" />
            <input type="hidden" id="Hidden3" value="2011CESweb" name="proxystylesheet" />
            <input type="hidden" id="Hidden4" value="xml_no_dtd" name="output" />
<input class="searchbox" id="searchbox" name="q" onblur="if(this.value=='') this.value='Search';" onfocus="if(this.value=='Search') this.value='';" type="text" value="Search" />
                		<!-- Pyxl ADD search from below-->
						<!--        <form action="http://googlebox.ce.org/search?" method="GET" name="searchCES">
						            <input type="hidden" id="Hidden1" value="default_collection" name="site">
						            <input type="hidden" id="Hidden2" value="2011CESweb" name="client">
						            <input type="hidden" id="Hidden3" value="2011CESweb" name="proxystylesheet">
						            <input type="hidden" id="Hidden4" value="xml_no_dtd" name="output">
						            <input type="text" onfocus="if(this.value=='Search') this.value='';" onblur="if(this.value=='') this.value='Search';" value="Search" class="searchbox" name="q"><input type="submit" onclick="document.searchCES.submit();" class="searchbutton" value="">
						            </form> 
						<A href="http://www.cesweb.org/cesgreening.asp"><img src="http://www.cesweb.org/hp/images/ces-green.jpg" border="0" valign=top ></A>
					</div>
						    <div id="topimages">
						        <img src="http://www.cesweb.org/hp/images/divider.jpg" class="divider"/>
						         <a href=http://www.cesweb.org/socialcircle target="_blank"><img src="http://www.cesweb.org/hp/images/socialcircle.aspx" alt="Social Circle" /></a>
						&nbsp;&nbsp;&nbsp;&nbsp;-->
	             </div>
                </div>
                <div class="clr"></div>
                <div id="ctacontainer">
                    <div id="showdate"> <img id="p_lt_zoneShowDate_EditableImage1_ucEditableImage_imgImage" src="http://content.ce.org/2013CES/2014%20Images/CESweb_headerdate.png" alt="" />

<img id="p_lt_zoneShowDate_2014ShowImage_ucEditableImage_imgImage" src="http://content.ce.org/2013CES/2014%20Images/CESweb_headerdate.png" alt="" />

 </div>
                    <div id="register">
	<a href="https://ces.itnint.com/2014/regonline/" target="_blank" title="Register for CES"><img alt="Register" border="0" name="cesweb_register" onmouseout="out(8)" onmouseover="over(8)" src="/cesweb/media/CESWeb/assets/images/nav/cesweb_register1.png" /></a></div>
<div id="exhibit">
	<a href="/For-Exhibitors/Exhibiting-Opportunities.aspx"><img alt="Exhibit at CES" border="0" name="cesweb_exhibit" onmouseout="out(9)" onmouseover="over(9)" src="/cesweb/media/CESWeb/assets/images/nav/cesweb_exhibit1.png" /></a></div>

                </div>
            </div>
            <div style="display: none;">/followme.asp/exhibitor-directory.asp/cesgreening.asp/registration.asp/searchResults.asp/error404.asp/partners.asp/contactus.asp/sitemap.asp/privacyPolicy.asp/aboutces.asp/myCES.asp/aboutcea.asp</div>
			<div id="nav-bar">
                
	<ul class="level1CMSListMenuUL" id="topnav">
		<li class="level1CMSListMenuLI ExhibitorDirectory" style=""><a href="http://ces14.mapyourshow.com" class="level1CMSListMenuLink" style="">Exhibitor Directory</a></li>
		<li class="level1CMSListMenuLI ConferenceProgram"><a href="/Conference-Program.aspx" class="level1CMSListMenuLink">Conference Program</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Conference-Tracks.aspx" class="level2CMSListMenuLink">Conference Tracks</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/SuperSessions.aspx" class="level2CMSListMenuLink">SuperSessions</a></li>
			<li class="level2CMSListMenuLI" style=""><a href="/Conference-Program/Conference-Pricing.aspx" class="level2CMSListMenuLink" style="">Conference Pricing</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Speaker-Services.aspx" class="level2CMSListMenuLink">Speaker Services</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Conference-Program/Call-for-Speakers.aspx" class="level2CMSListMenuLink">Call for Speakers</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI last "><a href="/Conference-Program/Call-for-Speakers/Submission-FAQs.aspx" class="level3CMSListMenuLink">Submission FAQs</a></li>
			</ul>
			</li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI Events"><a href="/Events.aspx" class="level1CMSListMenuLink">Events</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Events/Keynotes.aspx" class="level2CMSListMenuLink">Keynotes</a></li>
			<li class="hassub"><a href="/Events/CES-Unveiled.aspx" class="level2CMSListMenuLink">CES Unveiled</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/Events/CES-Unveiled/CES-Unveiled-London.aspx" class="level3CMSListMenuLink">CES Unveiled LONDON</a></li>
				<li class="level3CMSListMenuLI"><a href="/Events/CES-Unveiled/CES-Unveiled-PARIS.aspx" class="level3CMSListMenuLink">CES Unveiled PARIS</a></li>
				<li class="level3CMSListMenuLI"><a href="/Events/CES-Unveiled/CES-Unveiled-TEL-AVIV.aspx" class="level3CMSListMenuLink">CES Unveiled TEL AVIV</a></li>
				<li class="level3CMSListMenuLI"><a href="/Events/CES-Unveiled/CES-Unveiled-NEW-YORK.aspx" class="level3CMSListMenuLink">CES Unveiled NEW YORK</a></li>
				<li class="level3CMSListMenuLI last "><a href="/Events/CES-Unveiled/CES-Unveiled-LAS-VEGAS.aspx" class="level3CMSListMenuLink">CES Unveiled LAS VEGAS</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI" style=""><a href="/Events/CES-Events.aspx" class="level2CMSListMenuLink" style="">CES Events</a></li>
			<li class="level2CMSListMenuLI last " style=""><a href="/Events/Cea-Events.aspx" class="level2CMSListMenuLink" style="">CEA Events</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI Awards"><a href="/Awards.aspx" class="level1CMSListMenuLink">Awards</a>
		<ul class="subnav">
			<li class="hassub"><a href="/Awards/CES-Innovations-Awards.aspx" class="level2CMSListMenuLink">CES Innovations Awards</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/Award-Categories.aspx" class="level3CMSListMenuLink">Award Categories</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/How-to-Enter.aspx" class="level3CMSListMenuLink">How to Enter</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/How-We-Judge.aspx" class="level3CMSListMenuLink">How We Judge</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/What-You-Get.aspx" class="level3CMSListMenuLink">What You Get</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/Become-a-Judge-(1).aspx" class="level3CMSListMenuLink">Become a Judge</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/2014-Innovations-Award-Judges.aspx" class="level3CMSListMenuLink">2014 Innovations Award Judges</a></li>
				<li class="level3CMSListMenuLI last "><a href="/Awards/CES-Innovations-Awards/Entry-FAQs.aspx" class="level3CMSListMenuLink">Entry FAQs</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI" style=""><a href="/Awards/Engadget-Best-of-CES-Awards.aspx" class="level2CMSListMenuLink" style="">Engadget Best of the 2014 CES Awards</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Awards/Tech-Engineering-Emmy-Awards.aspx" class="level2CMSListMenuLink">Technology &amp; Engineering Emmy&#174; Awards</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI ShowFloor"><a href="/Show-Floor.aspx" class="level1CMSListMenuLink">Show Floor</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/CES-TechZones.aspx" class="level2CMSListMenuLink">CES TechZones</a></li>
			<li class="level2CMSListMenuLI" style=""><a href="/Show-Floor/Show-Maps.aspx" class="level2CMSListMenuLink" style="">Show Maps</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Show-Floor/Show-Floor-Tours.aspx" class="level2CMSListMenuLink">Show Floor Tours</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI HotelTravel"><a href="/Hotel-Travel.aspx" class="level1CMSListMenuLink">Hotel/Travel</a>
		<ul class="subnav">
			<li class="level2CMSListMenuHighlightedLI"><a href="/Hotel-Travel/Hotel-Reservations.aspx" class="level2CMSListMenuLinkHighlighted">Hotel Reservations</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/CES-Block-Request-Form.aspx" class="level2CMSListMenuLink">CES Block Request Form</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Airline-Discounts.aspx" class="level2CMSListMenuLink">Airline Discounts</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/CES-Shuttle-Service.aspx" class="level2CMSListMenuLink">CES Shuttle Service</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Hotel-Travel/Las-Vegas-Monorail.aspx" class="level2CMSListMenuLink">Las Vegas Monorail</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI News"><a href="/News.aspx" class="level1CMSListMenuLink">News</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/News/News-Feed.aspx" class="level2CMSListMenuLink">News Feed</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/Exhibitor-Releases.aspx" class="level2CMSListMenuLink">Exhibitor Releases</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/CES-Press-Releases.aspx" class="level2CMSListMenuLink">CES Press Releases</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/Media-Coverage.aspx" class="level2CMSListMenuLink">Media Coverage</a></li>
			<li class="level2CMSListMenuLI"><a href="/videos.aspx" class="level2CMSListMenuLink">CES TV</a></li>
			<li class="level2CMSListMenuLI last " style=""><a href="/For-the-Press.aspx" class="level2CMSListMenuLink" style="">Press Services</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI last "><a href="/FAQ.aspx" class="level1CMSListMenuLink">FAQ</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/FAQ/General.aspx" class="level2CMSListMenuLink">General</a></li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Press.aspx" class="level2CMSListMenuLink">Press</a></li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Exhibitor.aspx" class="level2CMSListMenuLink">Exhibitor</a></li>
			<li class="level2CMSListMenuLI last "><a href="/FAQ/Speaker.aspx" class="level2CMSListMenuLink">Speaker</a></li>
		</ul>
		</li>
	</ul>
        
			    
			</div>
		</div>
	</div>
    <div class="container-home">



<div id="slideshow" >
<div id="slideshow" >
    <div id="lofslidecontent45" class="lof-slidecontent">
        <div class="preload"><div></div>
    </div>
    <!-- MAIN CONTENT --> 
    <div class="lof-previous" href="" onclick="return false">Previous</div>
    <div class="lof-next" href="" onclick="return false">Next</div>    
    <div class="lof-main-outer">
        <ul class="lof-main-wapper">
<li>
 
  <a href="/Events/Keynotes.aspx"  ><img src="/cesweb/media/CESWeb/Slideshow%20Images/13304_3.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='/Events/Keynotes.aspx' > </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=465ba94a-43dd-409c-a3cc-74736d16d7e5" target='_blank' ><img src="/cesweb/media/CESWeb/Slideshow%20Images/EM_CESHPSlide.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=465ba94a-43dd-409c-a3cc-74736d16d7e5' target='_blank'> </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="http://www.cesweb.org/video?bckey=AQ~~,AAAABh3C_dE~,zBkXqCU8KVaPD5eWMlL4TSd-72riLdgV&amp;bclid=2752780517001&amp;bctid=2752868237001" target='_blank' ><img src="/cesweb/media/CESWeb/Slideshow%20Images/13305_CESTVslide_vid.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://www.cesweb.org/video?bckey=AQ~~,AAAABh3C_dE~,zBkXqCU8KVaPD5eWMlL4TSd-72riLdgV&amp;bclid=2752780517001&amp;bctid=2752868237001' target='_blank'> </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="http://www.ce.org/Blog/Articles/2013/October/Stay-Connected-with-IndustryForum.aspx" target='_blank' ><img src="/cesweb/media/CESWeb/Slideshow%20Images/CEAIF_CESHPSlide.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='http://www.ce.org/Blog/Articles/2013/October/Stay-Connected-with-IndustryForum.aspx' target='_blank'> </a>
           
           
        </p>
    </div>
</li><li>
 
  <a href="/Footer-Pages/About-CES/How-to-Register-for-CES.aspx"  ><img src="/cesweb/media/CESWeb/Slideshow%20Images/12956_HowtoReg_HPSlide2.jpg" ></a>
    <div class="lof-main-item-desc">
        <h2></h2>
        <p> <a class="readmore" href='/Footer-Pages/About-CES/How-to-Register-for-CES.aspx' > </a>
           
           
        </p>
    </div>
</li>
</div><div class="lof-navigator-wapper">
        <div onclick="return false" href="" class="lof-previous">Previous</div>
            <div class="lof-navigator-outer">
                <ul class="lof-navigator">

<li><img src="/cesweb/media/CESWeb/Slideshow%20Images/13304_3.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/EM_CESHPSlide.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/13305_CESTVslide_vid.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/CEAIF_CESHPSlide.jpg" ></li><li><img src="/cesweb/media/CESWeb/Slideshow%20Images/12956_HowtoReg_HPSlide2.jpg" ></li>
</ul>
            </div>
        <div onclick="return false" href="" class="lof-next">Next</div>
    </div> 
</div>
</div>
</div>
 <div id="page-bottom">
                
<div id="mid-bar">
    <div class="icon_wrap">
       <a href="/Twitter.aspx" target="_blank"><img alt="Twitter" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/twitter.png" width="25" /></a> <a href="/Facebook.aspx" target="_blank"><img alt="facebook" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/facebook.png" width="25" /></a> <a href="https://plus.google.com/b/114786898916421737866/114786898916421737866/" target="_blank"><img alt="Google+" src="/cesweb/media/CESWeb/assets/images/social/CES-870-Google-logo_24x24.gif" style="border-width: 0px; border-style: solid;" /></a> <a href="/Flickr.aspx" target="_blank"><img alt="flickr" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/flickr.png" width="25" /></a> <a href="/YouTube.aspx" target="_blank"><img alt="youtube" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/youtube.png" width="25" /></a> <a href="/LinkedIn.aspx" target="_blank"><img alt="linkedin" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/linkedin.png" width="25" /></a> <a href="/News/News-Feed.aspx" target="_blank"><img alt="rss" border="0" height="25" src="/cesweb/media/CESWeb/assets/images/social/rss.png" width="25" /></a>




   </div>
</div>

<div id="HP-tabs">
    <div id="tabs">
        <ul>
          <li class="news"><a href="#fragment-1"><span>Buzzworthy</span></a></li>
          <li class="blog"><a href="#fragment-2"><span>Blog</span></a></li>
          <li class="video"><a href="#fragment-3"><span>Videos</span></a></li>
          <li class="photos"><a href="#fragment-4"><span>Social Media</span></a></li>
          <li class="myces"><a href="#fragment-5"><span>MyCES</span></a></li> 
        </ul>
        <div id="fragment-1">
        	<!-- Buzzworthy -->
    		<div id="news">
<div class='news_tab' id='news_1' 

>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/22/2013</p></div>
    <h3> <a href="/News/News-Feed#229f4319-a24a-48be-ad2e-fd31e6c4eb7a">Sony President and CEO Kazuo Hirai to Deliver Keynote Address at 2014 CES</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/Kazuo-Hirai_Sony.gif?width=165&height=110&ext=.gif" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">President and CEO of Sony Corporation, Kazuo (&ldquo;Kaz&rdquo;) Hirai, will deliver the opening morning Tech Titans keynote address at the 2014 International CES, bringing his unique perspective and insights about the latest innovations occurring at the intersection of content and hardware. Mr. Hirai&rsquo;s keynote address will be part of the <a href="http://cesweb.org/Events/Keynotes.aspx">Tech Titans keynote series</a>, where CEOs from the most powerful companies in technology present their vision for revolutions in products, services and networks that will shape the next wave of innovation.<br />
&nbsp;<br />
Read the <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=5e3fba7a-f2af-4040-b1ae-c67e867f3d45" target="_blank">full press release</a>.<br />
&nbsp;<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/22/2013</p></div>
    <h3> <a href="/News/News-Feed#21d5ba77-7036-4444-9013-19e62fdb6448">CEA Releases 20th Annual CE Holiday Purchase Patterns Study</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/holiday-buzz.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">CEA&rsquo;s <em>20th Annual CE Holiday Purchase Patterns Study </em>was released at CEA&rsquo;s Industry Forum in Los Angeles. The consumer study found 74 percent of those planning to purchase gifts this holiday season intend to buy CE as gifts this year, allocating 33 percent of the overall holiday gift budget to CE.<br />
<br />
CEA also released the results from its <em>10<sup>th</sup> Annual Teen CE Holiday Purchase Patterns Study</em>&nbsp;which examines CE wish lists, gifting intentions and holiday shopping patterns among teens ages 12 to 17. Both reports are available free to CEA member companies at <a href="http://spmembers.ce.org/Login/Pages/default.aspx" target="_blank">members.CE.org</a>. Non-members may purchase the reports at the <a href="http://store.ce.org/Default.aspx?TabID=251&amp;productId=475732" target="_blank">CEA Store</a>.<br />
&nbsp;<br />
Access both reports and read the full release <a href="http://www.ce.org/News/News-Releases/Press-Releases/2013-Press-Releases/Annual-CEA-Holiday-Forecast-and-Study-Finds-Consum.aspx" target="_blank">here</a>.<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/22/2013</p></div>
    <h3> <a href="/News/News-Feed#0ae663a2-8b98-48bf-a412-4e802051290a">Maria Menounos Just Announced as 2013 CES Entertainment Matters Ambassador</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/Maria-Extra-buzz.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Television host of EXTRA, Co-Founder of AfterBuzz TV Network, innovative journalist and author Maria Menounos will serve as the <a href="http://staging.ces.org/Entertainment-Matters.aspx">Entertainment Matters</a> (EM) Ambassador for the 2014 International CES<font size="1">.</font>&nbsp;The EM Ambassador illuminates CES&rsquo; focus on bridging the entertainment and technology industries. Sponsored by <em>Variety</em>, the<a href="http://staging.ces.org/Entertainment-Matters.aspx"> Entertainment Matters</a>&nbsp;program will feature exhibits, keynotes, panels and events critical to the Hollywood community, including the 2014 IAWTV Awards Gala and <em>Variety&rsquo;s </em>Entertainment Summit at CES. New to the program are the Breakthrough of the Year Awards, produced by Penske Media Corp., which will recognize extraordinary achievements in a number of categories including media, entertainment and technology. Read the <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=465ba94a-43dd-409c-a3cc-74736d16d7e5">full release</a> and <a href="https://ces.itnint.com/2014/regonline/RegLogin.aspx" target="_blank">register</a> for CES today.&nbsp;<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/21/2013</p></div>
    <h3> <a href="/News/News-Feed#3da60f60-ef70-4c59-b028-db8232fa61d9">CEA Releases the 2014 Edition of Five Technology Trends to Watch </a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/5techs.gif?width=165&height=110&ext=.gif" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Released during a panel discussion at CEA&rsquo;s Industry Forum in Los Angeles, <em>Five Technology Trends to Watch</em> is an annual publication that examines five prominent technology trends that will influence the consumer electronics industry in the years ahead. Using the latest consumer research and market forecasts, the 2014 issue looks at the Internet of Things (IoT), driverless cars, digital health care, robotics and the future of video distribution and consumption. <em>Five Technology Trends to Watch</em> is a special supplement to CEA&rsquo;s bi-monthly flagship publication, <a href="http://www.ce.org/i3">It Is Innovation</a> (<em>i3</em>). Access the <a href="http://www.ce.org/FiveTechs" target="_blank">full report</a>.&nbsp;<br />
 </p>
        
    </div>


</div><div class='news_tab' id='news_2' 
style='display:none;'
>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/21/2013</p></div>
    <h3> <a href="/News/News-Feed#d271e39b-8709-456f-85c9-39ef03b6fa8b">CES TV Launches With “Tech Trends”</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/cestv.gif?width=165&height=110&ext=.gif" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Today, CEA launches CES TV, an annual web series giving you a glimpse at what&rsquo;s to come at this year&rsquo;s International CES. We find ourselves at a monumental crossroads in the history of tech as we head into the 2014 International CES. Check out the trends that are recasting and ultimately redefining the user experience as tech moves from an enabler to a destination at the 2014 CES in <a href="http://www.cesweb.org/video?bckey=AQ~~,AAAABh3C_dE~,zBkXqCU8KVaPD5eWMlL4TSd-72riLdgV&amp;bclid=2752780517001&amp;bctid=2752868237001">CES TV &ldquo;Tech Trends.&rdquo; </a>Subscribe to the official CES <a href="http://www.youtube.com/cesonthetube">YouTube</a><a href="http://www.youtube.com/cesonthetube" target="_blank"> </a>channel to be the first to know when the next edition of CES TV goes live.<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/9/2013</p></div>
    <h3> <a href="/News/News-Feed#d6615239-913a-4be3-b14d-907c6219b142">Experience TV, Sound and More at CEA Demo Days </a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/demo-days-buzz.png?width=165&height=110&ext=.png" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">CEA Demo Days are back this fall, encouraging consumers to visit their local electronics retailers to experience home entertainment technologies first hand. This fall&rsquo;s Demo Days will continue through this coming weekend, October 12-14, and will showcase the latest in TVs, audio and home entertainment accessories. Learn more about <a href="http://ceademodays.com/home.aspx?v=1092013" target="_blank">Demo Days</a> and find an electronics retailer near you.&nbsp;<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/9/2013</p></div>
    <h3> <a href="/News/News-Feed#67c3d7d4-1171-479e-aa08-456101aec1d1">Did You Miss the Eureka Park Exhibitor Webinar?</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/For%20Exhibitors/Media%20Opps/CES_EurekaPark_Crowd_(3).gif?width=165&height=110&ext=.gif" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;"><span style="background-color: rgb(255, 255, 255);">If you couldn&rsquo;t tune in to the live Eureka Park Exhibitor Webinar, you can now view it</span><a href="http://consumerelectronics.adobeconnect.com/p3yjagldwlu/" style="background-color: rgb(255, 255, 255);" target="_blank">&nbsp;</a><a href="http://consumerelectronics.adobeconnect.com/p3yjagldwlu/" style="background-color: rgb(255, 255, 255);" target="_blank">here.</a><span style="background-color: rgb(255, 255, 255);">&nbsp;The webinar helps&nbsp;</span><a href="http://cesweb.org/Show-Floor/CES-TechZones.aspx#5jump" style="background-color: rgb(255, 255, 255);" target="_blank">Eureka Park</a><span style="background-color: rgb(255, 255, 255);">&nbsp;(EP) exhibitors looking to enhance their media exposure at the 2014 International CES by outlining useful PR tips and tools that will give EP exhibitors a communications advantage. Tune in to this unique PR webinar, presented by experienced CES PR experts from CEA, Business Wire and UP Global, to find out how your company can maximize exposure.&nbsp;</span> </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/7/2013</p></div>
    <h3> <a href="/News/News-Feed#9af33f5d-fa6b-4066-8ea6-c20ffd48ea3e">CEA Announces Expansion of Eureka Park and Two New TechZones</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/cescrowd2.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The Eureka Park TechZone at the 2014 CES will expand by 30 percent and will feature more than 200 entrepreneurs and startups. In partnership with UP Global (formally the Startup America Partnership and Startup Weekend), the National Science Foundation and General Electric Company, Eureka Park is a dedicated area showcasing budding startups and entrepreneurs.<br />
<br />
Also new in 2014 is the Academia Tech TechZone, which will be within Eureka Park, showcasing technologies emerging from colleges and universities. CEA also announced the launch of Eureka Park: NEXT TechZone, an area for mid-stage startups that have launched a product within the past year.<br />
<br />
Read the <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=756c7b2e-5813-406c-82c5-bb3dc1293eca" target="_blank">full press release</a> and learn more about <a href="http://www.cesweb.org/Show-Floor/CES-TechZones.aspx" target="_blank">CES TechZones</a>.&nbsp;<br />
 </p>
        
    </div>


</div><div class='news_tab' id='news_3' 
style='display:none;'
>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/7/2013</p></div>
    <h3> <a href="/News/News-Feed#886d8ad4-0026-4593-8f3f-88d2ac6076ac">Latest in Ultra HD to Be Featured at the 2014 CES</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/13-119-0_8964.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">Ultra HD is the next generation of display technology for the home and delivers four times the resolution of today&rsquo;s full High-Definition TVs, with more than eight million pixels of resolution. Ultra HD was launched at the 2013 International CES and the 2014 CES will discuss bringing Ultra HD to market through conference programming. CEA will produce &ldquo;Ultra HD Content: What Will We Watch in 2014 and Beyond?&rdquo; on January 7, 2014. &ldquo;Seeing is Believing &ndash; 3D, 4K and UHD,&rdquo; will take place on January 9, 2014 and will be produced by the International 3D and Advanced Imaging Society, an official CES conference partner.&nbsp; See the full <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=d0fe0525-0b8c-498d-9da6-174a0566860b" target="_blank">press release</a> to learn more about Ultra HD at the 2014 CES.&nbsp;<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/3/2013</p></div>
    <h3> <a href="/News/News-Feed#4138dccb-c660-45b4-9faa-91c74ad6c9cf">Digital Fitness Exhibit Area Expands by 30 Percent for 2014 International CES</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/fitness-buzz.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The digital fitness footprint at CES has seen 30 percent growth for 2014. The <a href="http://www.cesweb.org/Show-Floor/CES-TechZones.aspx#26jump">FitnessTech</a> TechZone, produced in partnership with<a href="http://livingindigitaltimes.com/" target="_blank"> Living in Digital Times</a>, will focus exclusively on the newest technologies for the sports and fitness enthusiast. According to a CEA semi-annual report, the market for fitness technology is predicted to grow nearly 25 percent in 2014 and the 2014 CES will showcase the latest developments and discoveries across this growing field. See the <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=df92df59-0a56-4895-b73c-23dca2c00dc3">full release</a> and learn more about the <a href="http://www.cesweb.org/Show-Floor/CES-TechZones.aspx#26jump" target="_blank">FitnessTech</a> TechZone.<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/3/2013</p></div>
    <h3> <a href="/News/News-Feed#a31c7f06-f8fc-4aff-9e80-5af0d70d1016">High Tech Fashion to Be Featured at New FashionWare TechZone</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/badge-page.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">CEA recently announced a new <a href="/Show-Floor/CES-TechZones.aspx">TechZone</a> for the 2014 International CES. <a href="http://www.cesweb.org/Show-Floor/CES-TechZones.aspx#59jump">FashionWare</a>, produced in partnership with <a href="http://livingindigitaltimes.com/" target="_blank">Living in Digital Times</a>, will showcase the latest innovations in wearable technology that mix fashion and function.&nbsp; &ldquo;The FashionWare TechZone integrates style, function and technology to create a wow-factor, high-tech space at the 2014 CES&rdquo; said Karen Chupka, senior vice president, International CES and coporate business strategy, CEA. See the <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=e3041f53-93f5-41dc-90a2-3692dfb57f26">full release</a> and learn more about the <a href="http://www.cesweb.org/Show-Floor/CES-TechZones.aspx#59jump">FashionWare </a>TechZone.&nbsp;<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/3/2013</p></div>
    <h3> <a href="/News/News-Feed#c1f74e2a-7cd0-45fd-9c0e-011069b25143">Audi’s Rupert Stadler Will Deliver Tech Titans Keynote at 2014 CES</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/CES2014_Blog_StartUp.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The latest trends and technologies in the auto industry are coming to CES. CEA recently&nbsp;<a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=3c312604-3fcf-4a37-8fd6-88aab96c0014" target="_blank">announced</a> another keynote address in the Tech Titan series, where CEOs from the most powerful companies in technology present their vision for the next wave of innovation. Rupert Stadler, Chairman of the Board of Management of Audi AG, will deliver a keynote at 8:30 p.m. Monday, January 6 in The Cosmopolitan&rsquo;s Chelsea theater. Visit our <a href="/Events/Keynotes.aspx">keynotes</a> page for more information.&nbsp;<br />
 </p>
        
    </div>


</div><div class='news_tab' id='news_4' 
style='display:none;'
>
    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/3/2013</p></div>
    <h3> <a href="/News/News-Feed#8b0fd698-5390-40da-8d7a-4b3f1e9e004f">New MotionTech TechZone Will Feature Innovation in Motion</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/12499MotionTech.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">CEA recently announced a new TechZone for the 2014 International CES. <a href="http://www.cesweb.org/Show-Floor/CES-TechZones.aspx#18jump" target="_blank">MotionTech</a>, sponsored by MEMS industry group, will feature the latest in motion technology field. From gesture recognition and augmented reality, to eye-tracking technology and motion sensors, attendees will discover new ways to connect and interact with their devices. Please see the full <a href="http://www.cesweb.org/News/CES-Press-Releases/CES-Press-Release.aspx?NodeID=74041e20-2a6c-465a-b0df-f496435ffda2" target="_blank">press release</a> for more information.&nbsp;<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>10/1/2013</p></div>
    <h3> <a href="/News/News-Feed#e8c61eaa-3c3c-4905-80a0-36462be1693e">Save the Date: 2014 CES Eureka Park Exhibitor Webinar – October 8</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/EP-buzzworthy.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">The 2014 CES Eureka Park Exhibitor webinar will help <a href="http://www.cesweb.org/Show-Floor/CES-TechZones.aspx#5jump">Eureka Park</a> (EP) exhibitors looking to enhance their media exposure at the 2014 International CES. The webinar will outline useful PR tips and tools that will give EP exhibitors a communications advantage. Tune in to this unique PR webinar, presented by experienced CES PR experts from Business Wire, the National Science Foundation and UpGlobal, to find out how your company can maximize exposure.&nbsp;Learn more and register <a href="http://www.ce.org/Events-and-Awards/CEA-Webinar-Calendar/2014-Eureka-Park-Exhibitor-PR-Workshop.aspx" target="_blank">here</a>.<br />
&nbsp;<br />
<strong>Date</strong>: Tuesday, October 8, 2013<br />
<strong>Time</strong>: 2&ndash;3 p.m. (ET) / 11a.m.&ndash;Noon (PT)<br />
 </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>9/25/2013</p></div>
    <h3> <a href="/News/News-Feed#947aa237-b148-43d6-87b0-5fa3f8bceba4">Find out What's Next During Our Upcoming Google Hangout</a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/IndustryForum.jpg?width=165&height=109&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">It&#39;s the question we all ask: What&#39;s next? We answer it every January at CES in Las Vegas. But if you can&#39;t wait (heck, <em>we&nbsp;</em>can&#39;t even wait), be sure to join our <a href="http://www.ce.org/Blog/Articles/2013/September/Know-What-Tech-Trends-to-Watch-We-Do.aspx" target="_blank">Google Hangout</a> this Thursday, where we&#39;ll discuss the Internet of Everything, one of our five technology trends to watch this year. Join Jeff Joseph, senior vice president of communications and strategic relationships at CEA, as he leads a discussion with Shawn DuBravac, chief economist and senior director of research at CEA, and Ross Rubin, principal analyst at Reticle Research. <a href="https://plus.google.com/events/coi95345b3rtj46efajid1risqs" target="_blank">Join our Hangout</a>. </p>
        
    </div>





    <div id="news-date" style='clear:both; margin-top: 20px;'><p>9/20/2013</p></div>
    <h3> <a href="/News/News-Feed#091902b9-5e85-4277-bc93-03ea52246676">Intel CEO, Brian Krzanich, to Deliver Tech Titans Keynote at 2014 CES </a></h3>
    <div id="news-content" style="overflow:hidden;">
     <div style="display: inline; float: left; width: 25%">
       <img src="/cesweb/media/CESWeb/News/Buzzworthy%20Thumbnails/CES2014_Blog_StartUp.jpg?width=165&height=110&ext=.jpg" width="150" />
    </div>
        <p style="display: inline; float: left; width: 75%; margin-top: 0;">CEA announced that Brian Krzanich, Intel&rsquo;s new CEO, will deliver a Tech Titans <a href="http://www.cesweb.org/Events/Keynotes/Tech-Titans-Monday">keynote address</a>. The Tech Titans keynote series will feature CEOs from the most powerful companies in technology who will present their vision for the upcoming revolutions in the consumer technology industry.&nbsp; Krzanich&rsquo;s keynote address will be held at 6:30 p.m., Monday, January 6, in The Venetian&rsquo;s Palazzo Ballroom. Learn more about <a href="http://www.cesweb.org/Events/Keynotes/Tech-Titans-Monday">Krzanich&rsquo;s keynote</a> and stay tuned for more CES <a href="http://www.cesweb.org/Events/Keynotes.aspx">keynote announcements</a>.&nbsp;<br />
 </p>
        
    </div>


</div>
</div><div id=news-nav>
				<ul id=news_nav_buttons>
					<li class=up>Pages:</li>
<li id='news_1_button' 
class='on_page'
 ><a onclick="return newsActive('news_1');" href=''>1</a></li>









<li id='news_2_button' 

 ><a onclick="return newsActive('news_2');" href=''>2</a></li>









<li id='news_3_button' 

 ><a onclick="return newsActive('news_3');" href=''>3</a></li>









<li id='news_4_button' 

 ><a onclick="return newsActive('news_4');" href=''>4</a></li>










</ul>
			</div>
		</div>
		
		<div id="fragment-2">
			<!-- Blog -->
		    <div id=blog></div>
			<div id=blog-nav></div>
		</div>
		<div id="fragment-3">
		    <!-- video -->
    	    <div id=resp></div>
		</div>
		<div id="fragment-4">
	    	<!-- Photos 
	    	<h3>2012 International CES Photos</h3>
	    	<br>Download high-resolution&nbsp;photos from the <a href="/For-The-Press/Image-Gallery.aspx"><strong>Image Gallery</strong>.</a><br><br>View photos from our <strong><a href="http://www.cesweb.org/flickr" target=_blank>flickr</a></strong> stream: 
			<p><iframe height=460 src="/photos.aspx" frameBorder=0 width=680 scrolling=no></iframe></p> -->
                <!-- Social Media -->
                You can follow CES via social media when you are at the show and all year long. Get breaking news, win cool prizes and learn more about the world&rsquo;s most important technology event. Want to join the conversation? Be sure to use our official hashtag <strong>#CES2014</strong>.<br />
<br />
<table align="center" border="0" cellpadding="5" cellspacing="2" style="width: 650px;" width="650">
	<tbody>
		<tr>
			<td align="center" height="200" nowrap="nowrap" style="text-align: center; vertical-align: middle; width: 125px; height: 100px;" valign="middle" width="125">
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/CES-579_Facebook.jpg" style="width: 91px; height: 91px; vertical-align: middle; margin: 5px auto;" /><br />
				<a href="http://www.facebook.com/InternationalCES">facebook.com/<br />
				internationalces</a></td>
			<td align="center" height="125" nowrap="nowrap" style="text-align: center; vertical-align: middle; width: 125px; height: 100px;" valign="middle" width="125">
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/Twitter2.jpg" style="width: 91px; height: 91px;" /><br />
				<a href="http://www.twitter.com/intlces">twitter.com/<br />
				intlces</a></td>
			<td align="center" height="125" nowrap="nowrap" style="text-align: center; vertical-align: middle; width: 125px;" valign="middle" width="125">
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/CES-581_You_Tube.jpg" style="width: 91px; height: 91px; vertical-align: middle;" /><br />
				<a href="http://www.youtube.com/cesonthetube">youtube.com/<br />
				cesonthetube</a></td>
			<td align="center" height="200" nowrap="nowrap" style="text-align: center; vertical-align: middle; width: 125px; height: 100px;" valign="middle" width="125">
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/CES-870-Google-logo.jpg" style="width: 92px; height: 92px; vertical-align: middle;" /><br />
				<a href="http://plus.google.com/114786898916421737866/posts">+International CES</a><br />
				&nbsp;</td>
		</tr>
		<tr>
			<td align="center" height="200" style="text-align: center; vertical-align: middle; width: 125px; height: 100px;" valign="middle">
				<br />
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/CES-583_LinkedIn.jpg" style="width: 91px; height: 91px;" /><br />
				<a href="http://linkedin.com/groups/International-CES-2183410" style="text-decoration: underline; color: rgb(0, 185, 212);">linkedin.com/groups/<br />
				International-CES-2183410</a></td>
			<td align="center" height="200" nowrap="nowrap" style="text-align: center; vertical-align: middle; width: 125px; height: 100px;" valign="middle">
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/CES-862-Instagram_Icon_Large-2.jpg" style="width: 91px; height: 91px; vertical-align: middle;" /><br />
				<a href="http://www.instagram.com/intlCES">instagram.com/intlces</a><br />
				&nbsp;</td>
			<td align="center" height="200" nowrap="nowrap" style="text-align: center; vertical-align: middle; width: 125px; height: 100px;" valign="middle">
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/CES-874-Foursquare-logo.jpg" style="width: 91px; height: 91px; vertical-align: middle;" /><br />
				<a href="http://www.foursquare.com/intlCES">foursquare.com/intlces</a><br />
				&nbsp;</td>
			<td align="center" height="200" nowrap="nowrap" style="text-align: center; vertical-align: middle; width: 91px; height: 100px;" valign="middle">
				<br />
				<img alt="" src="http://content.ce.org/2013ces/images/Logos/Social%20Media%20Logos/CES-501-Mobile-APPP_8.jpg" style="width: 91px; height: 91px;" /><br />
				<a href="http://play.google.com/store/apps/details?id=com.coreapps.android.followme.ces2013">Google Play</a><br />
				<a href="http://itunes.apple.com/us/app/official-2013-ces-mobile-app/id550545539?mt=8">Apple App Store</a><br />
				&nbsp;</td>
		</tr>
	</tbody>
</table>
<h2>
	<br />
	Consumer Electronics Association</h2>
<p>
	The Consumer Electronics Association (CEA) unites 2,000 companies within the consumer technology industry and is the industry authority on market research and forecasts; consumer surveys; legislative and regulatory news; engineering standards; training resources and more.</p>
<table align="center" border="0" cellpadding="5" cellspacing="1" style="width: 600px;">
	<tbody>
		<tr>
			<td>
				<br />
				<strong>Facebook</strong><br />
				<a href="http://www.facebook.com/ceafeed">www.facebook.com/ceafeed</a><br />
				<a href="http://www.facebook.com/InnovationMovement">www.facebook.com/InnovationMovement</a><br />
				&nbsp;</td>
			<td>
				<strong>Twitter</strong><br />
				<a href="http://www.twitter.com/cea">www.twitter.com/cea</a><br />
				<a href="http://www.twitter.com/imovement">www.twitter.com/imovement</a></td>
			<td>
				<strong>YouTube</strong><br />
				<a href="http://www.youtube.com/ceaonthetube">www.youtube.com/ceaonthetube</a><br />
				<a href="http://www.youtube.com/IMovementCEA">www.youtube.com/IMovementCEA</a></td>
		</tr>
		<tr>
			<td>
				<strong>Flickr</strong><br />
				<a href="http://www.flickr.com/photos/ceaphotostream">www.flickr.com/photos/ceaphotostream</a></td>
			<td>
				<strong>Blog</strong><br />
				<a href="http://blog.ce.org">blog.ce.org</a></td>
			<td style="vertical-align: top;">
				<br />
				<strong>LinkedIn</strong><br />
				<a href="http://www.linkedin.com/groups?gid=71237" target="_blank">linkedin.com/groups?gid=71237</a></td>
		</tr>
	</tbody>
</table>
<br />
                <!-- End Social Media -->       
		</div>
		<div id="fragment-5">
    	    <!-- MyCES -->
		    <p>&nbsp;</p>
			<p><img align=left src="http://content.ce.org/2013ces/images/HPImages/myces/MY_CES_2k10.gif" width=128 height=86>With the MyCES Planner, you can&nbsp;create a personalized show agenda that allows you to:</p>
			<ul class=text>
				<li class=text>Add exhibitors of interest to your agenda </li>
				<li class=text>Use the My Events calendar to organize your show-related activities </li>
				<li class=text>Print a map of the show floor highlighting your exhibitors of interest </li>
			</ul>
			<p><a href="http://ces14.mapyourshow.com/myshow/login.cfm" target="_blank">If you already have a MyCES account</a>, take advantage of these tools and start planning your show today! <a href="http://ces14.mapyourshow.com/myshow/login.cfm" target="_blank">If you don't have a MyCES account, create one today</a>, watch the 2014 CES come to life as we add new exhibitors, events and announcements,&nbsp;and start planning your show today! </p>
			<p></p>
			<p>
				<table border=0 cellSpacing=0 cellPadding=0>
					<tbody>
						<tr>
							<th colSpan=6><img src="http://content.ce.org/2013ces/images/HPImages/myces/myCES-top.jpg" height=23></th>
						</tr>
						<tr>
							<th colSpan=6>&nbsp;</th></tr>
						<tr align=middle>
							<td><a href="http://ces14.mapyourshow.com/5_0/search.cfm?" target=_blank><img border=0 src="http://content.ce.org/2013ces/images/HPImages/myces/dir-search(1).jpg"></a><p>&nbsp;</p></td>
							<td><a href="http://ces14.mapyourshow.com/5_0/exhibitor_results.cfm?type=list&list=featured" target=_blank><img border=0 src="http://content.ce.org/2013ces/images/HPImages/myces/featured-exhibitors(1).jpg"></a><p>&nbsp;</p></td>
							<td><a href="http://ces14.mapyourshow.com/5_0/advanced_search.cfm?by=category" target=_blank><img border=0 src="http://content.ce.org/2013ces/images/HPImages/myces/product-search(2).jpg"></a><p>&nbsp;</p></td>
							<td><a href="http://ces14.mapyourshow.com/5_0/myshow/login.cfm?" target=_blank><img border=0 src="http://content.ce.org/2013ces/images/HPImages/myces/myplanner(1).jpg"></a><p>&nbsp;</p></td>
							<td><a href="http://www.mapyourshow.com/shows/index.cfm?Show_ID=CES14" target=_blank><img border=0 src="http://content.ce.org/2013ces/images/HPImages/myces/maps(2).jpg"><Center></a><p>&nbsp</p></td>
							<td><img border=0 src="http://content.ce.org/2013ces/images/HPImages/myces/conferences.jpg"><center><p>Coming Soon</p></center></td>
							<td></td>
						</tr>
						<tr>
							<td></td>
							<td align=center></td>
							<td></td>
							<td></td>
							<td align=center></td>
						</tr>
						<tr>
							<th colSpan=6>&nbsp;</th>
						</tr>
						<tr>
							<th colSpan=6><img src="http://content.ce.org/2013ces/images/HPImages/myces/myCES-bottom.jpg" height=23></th>
						</tr>
					</tbody>
				</table>
			</p>
		</div>
    </div>
</div>
<!-- End Tab Structure -->


<div id="sidelinks">
    <img style="padding-bottom: 3px;" src="http://content.ce.org/2013CES/2014%20Images/cesweb_intltab_NODATE.png">
    <a href="/For-Exhibitors.aspx" title="For Exhibitors"><img src="http://content.ce.org/2013ces/images/HPImages/nav/cesweb_exhibitors1.png" alt="Exhibitors" name="cesweb_exhibitors" onMouseOver="over(10)" onMouseOut="out(10)" style="padding-bottom:3px;" /></a>
    <a href="/For-The-Press.aspx" title="For Press"><img src="http://content.ce.org/2013ces/images/HPImages/nav/cesweb_press1.png" alt="Press" name="cesweb_press" onMouseOver="over(11)" onMouseOut="out(11)"  style="padding-bottom:3px;" /></a>
    <a href="/For-International-Visitors.aspx" title="For Visitors"><img src="http://content.ce.org/2013ces/images/HPImages/nav/cesweb_visitors1.png" alt="Visitors" name="cesweb_visitors" onMouseOver="over(12)" onMouseOut="out(12)" style="padding-bottom:3px;"/></a>
    <a href="/Entertainment-Matters.aspx" title="Entertainment Matters"><img src="http://content.ce.org/2013ces/images/HPImages/nav/EMatCES1.jpg" alt="Entertainment Matters" name="entertainment_matters" onMouseOver="over(13)" onMouseOut="out(13)" style="padding-bottom:3px;"/></a>
</div>

<div id="extra">
<img style="padding-bottom: 3px;" src="http://content.ce.org/2013CES/2014%20Images/cesweb_extras_NODATE.png">
    <div class="extras-slider">
    
        
<div class="extras-slide">
      	<a href="/ExtraPages/Brand-Matters.aspx"><img src="/cesweb/media/CESWeb/Slideshow%20Images/BrandMatters_220x57.jpg?width=220&height=57&ext=.jpg" alt="" /></a>
</div>
  <div class="extras-slide">
      	<a href="http://blog.ce.org/"><img src="/cesweb/media/CESWeb/assets/images/extras/dig-dialogue.jpg?width=220&height=57&ext=.jpg" alt="" /></a>
</div>
  

        
    	   
        <div class="extras-slider-nav">
            <input type="hidden" class="extras-slider-current" value="0"/>
            <div class="extras-slider-left"></div>
            <div class="extras-slider-right"></div>
        </div>
    </div>
</div>
<!--<div id="facebook">
     <img src="http://content.ce.org/2013ces/images/HPImages/tabs/cesweb_fbtab.png" /><br />
     <iframe src="http://www.facebook.com/plugins/likebox.php?id=9181619833&amp;width=240&amp;connections=0&amp;stream=true&amp;&amp;force_wall=trueheader=false&amp;height=428" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:240px; height:428px;" allowTransparency="true"></iframe>
</div>-->
</div>


    </div>

    <div id="sitelinks">
        
    </div>
</div> 
<div id="footer-home">
    <div id="footer_nav-home">
        
	<ul class="footerCMSListMenuUL" id="menuElem">
		<li class="footerCMSListMenuLIfooterMenuFirst"><a href="/Footer-Pages/About-CES.aspx" class="footerCMSListMenuLink" >About&nbsp;CES</a></li>
		<li class="footerCMSListMenuLI" style=""><a href="/Footer-Pages/About-CEA.aspx" class="footerCMSListMenuLink" style="" >About&nbsp;CEA</a></li>
		<li class="footerCMSListMenuLI" style=""><a href="/Footer-Pages/RSS-News.aspx" class="footerCMSListMenuLink" style="" >RSS&nbsp;News</a></li>
		<li class="footerCMSListMenuLI" style=""><a href="/Footer-Pages/MyCES.aspx" class="footerCMSListMenuLink" style="" >MyCES</a></li>
		<li class="footerCMSListMenuLI" style=""><a href="/Footer-Pages/Contact-Us.aspx" class="footerCMSListMenuLink" style="" >Contact&nbsp;Us</a></li>
		<li class="footerCMSListMenuLI" style=""><a href="/Footer-Pages/Site-Map.aspx" class="footerCMSListMenuLink" style="" >Site&nbsp;Map</a></li>
		<li class="footerCMSListMenuLI" style=""><a href="/Footer-Pages/Privacy-Policy.aspx" class="footerCMSListMenuLink" style="" >Privacy&nbsp;Policy</a></li>
		<li class="footerCMSListMenuLIfooterMenuLast" style=""><a href="/Footer-Pages/Partners.aspx" class="footerCMSListMenuLink" style="" >Partners</a></li>
	</ul>

<div style="clear: both;"></div>
       
    </div>
    <div id="copyright-home">
    Copyright &copy; 2003 - 2013 CEA. All rights reserved.



<br /><div style="float:right;font-size: .8em; color: #080808;"><span id="p_lt_footerTextZone_whatServer_serverName">WEB-IIS20</span><div style="clear: both;"></div>
</div>
    </div>
    
    <a target="_blank" href="http://www.CE.org"></a>
</div>
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0013/2569.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

<!-- Start Pardot tracking script -->
<script type="text/javascript"> 
piAId = '27962'; 
piCId = '2690'; 

(function() { 
function async_load(){ 
var s = document.createElement('script'); s.type = 'text/javascript';
s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js'; 
var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c); 
} 
if(window.attachEvent) { window.attachEvent('onload', async_load); } 
else { window.addEventListener('load', async_load, false); } 
})(); 
</script> 
<!-- End Pardot tracking script -->


    
    

<script type="text/javascript">
//<![CDATA[
(function() {var fn = function() {$get("manScript_HiddenField").value = '';Sys.Application.remove_init(fn);};Sys.Application.add_init(fn);})();//]]>
</script>

<script type="text/javascript">
	//<![CDATA[
jQuery("#header-top #header-more-sites").show();
var offset = jQuery("#header-top #header-more-sites").find("li").length * -25 - 7 + "px";
jQuery("#header-top #header-more-sites").css("top", offset);
jQuery('#header-top #header-more-sites').hover(function() {
      jQuery(this).css('top', '0px'); 
}, 
   function() {
      jQuery("#header-top #header-more-sites").css("top", offset);
      //jQuery("#header-more-expander #the-expander").css('background-position-y', '19px'); 
   })
//]]>
</script></form>
</body>
</html>
