<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" >
<head id="head"><title>
	2013 International CES, January 8 - 11 - Print Advertising
</title><meta charset="UTF-8" /> 
<link href="/CMSPages/GetResource.ashx?stylesheetname=cesweb" type="text/css" rel="stylesheet"/> 
<link rel="icon" href="/cesweb/media/CESWeb/favicon.ico" type="image/x-icon"> 
<link rel="shortcut icon" href="/cesweb/media/CESWeb/favicon.ico" type="image/x-icon"> 
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script type="text/javascript" src="/cesweb/media/CESWeb/assets/js/ConferenceProgram/displayCart.js"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3975226-4']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<!--[if lt IE 9]>
<style>
#topnav>li>a { font-family: Arial !important; font-size: 14px !important; letter-spacing: -1px; font-weight: bold;}
/* #topnav>li{ padding-left:28px !important; } */
.greenbox-bg ul a.lefttopnavhead { font-family: Arial !important; font-size: 14px !important; font-weight: bold; }
</style>
<![endif]-->
<!--[if IE 8]>
<style>
#topnav > li { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=/hIEfix.png,sizingMethod=crop); zoom: 1; }
.greenbox-bg ul a.lefttopnavhead { filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src=/hIEfix.png,sizingMethod=crop); zoom: 1; }
</style>
<![endif]-->
<!-- Yahoo! Web Analytics - All rights reserved -->
<script type="text/javascript" src="http://d.yimg.com/mi/eu/ywa.js"></script>
<script type="text/javascript">
/*globals YWA*/
var YWATracker = YWA.getTracker("1000217290027");
//YWATracker.setDocumentName("");
//YWATracker.setDocumentGroup("");
//YMATracker.setAction("");
YWATracker.submit();
</script>
<noscript>
<div><img src="http://s.analytics.yahoo.com/p.pl?a=1000217290027&amp;js=no" width="1" height="1" alt="" /></div>
</noscript>
<!-- /Yahoo! Web Analytics - All rights reserved -->

<script src="/cesweb/media/CESWeb/assets/js/custom/jquery-feed-rotator-min.js" type="text/javascript"></script>
<script type="text/javascript">
(function($){
    $(document).ready(function(){
	topNewsFeed = $('#header-feed').feedRotator();
	setTimeout(function(){
		$('#topnav').show();
	}, 2000);
    });
})(jQuery);
</script> 
<link href="/CMSPages/GetResource.ashx?transformations=ces.PromotionalOpportunities.JumpMenuItem" type="text/css" rel="stylesheet"/> 
</head>
<body class="LTR ENUS ContentBody"  class="home" id="home">
    <form method="post" action="/For-Exhibitors/Promotional-Opportunities/Print-Advertising.aspx" id="form">
<div class="aspNetHidden">
<input type="hidden" name="manScript_HiddenField" id="manScript_HiddenField" value="" />
<input type="hidden" name="__VIEWSTATE" id="__VIEWSTATE" value="/wEPDwUKMTYwODg0MzQ2Ng9kFgICARBkZBYCAgMPZBYCZg9kFgJmD2QWBAICD2QWAmYPZBYCZg9kFgJmDxYCHgtfIUl0ZW1Db3VudAIHFg5mD2QWAmYPZBYCZg8VAhFodHRwOi8vd3d3LmNlLm9yZwxDRUEgLSBDRS5vcmdkAgEPZBYCZg9kFgJmDxUCFWh0dHA6Ly93d3cuY2Vzd2ViLm9yZxFJbnRlcm5hdGlvbmFsIENFU2QCAg9kFgJmD2QWAmYPFQIgaHR0cDovL3d3dy5kZWNsYXJlaW5ub3ZhdGlvbi5jb20TSW5ub3ZhdGlvbiBNb3ZlbWVudGQCAw9kFgJmD2QWAmYPFQISaHR0cDovL2Jsb2cuY2Uub3JnEERpZ2l0YWwgRGlhbG9ndWVkAgQPZBYCZg9kFgJmDxUCF2h0dHA6Ly93d3cuY2V2aXNpb24ub3JnD1Zpc2lvbiBNYWdhemluZWQCBQ9kFgJmD2QWAmYPFQIdaHR0cDovL3d3dy5ncmVlbmVyZ2FkZ2V0cy5vcmcPR3JlZW5lciBHYWRnZXRzZAIGD2QWAmYPZBYCZg8VAhZodHRwOi8vcmVzZWFyY2guY2Uub3JnD01hcmtldCBSZXNlYXJjaGQCDg9kFgQCAQ9kFgICAg9kFgJmD2QWAmYPZBYCZg8VAQBkAgUPZBYCAgIPZBYCZg9kFgJmD2QWBAIFD2QWAmYPZBYCAgIPZBYQZg9kFgJmD2QWAmYPFQICNzFDSXQgaXMgSW5ub3ZhdGlvbiAoaTMpLSBPZmZpY2lhbCBQdWJsaWNhdGlvbiBvZiBDRUEsIFByb2R1Y2VyIG9mIENFU2QCAQ9kFgJmD2QWAmYPFQICNDM7SW50ZXJuYXRpb25hbCBDRVMgT2ZmaWNpYWwgU2hvdyBHdWlkZSAmIENvbmZlcmVuY2UgQnJvY2h1cmVkAgIPZBYCZg9kFgJmDxUCAjEwLUNFUyBEYWlseSDigJQgVGhlIE9mZmljaWFsIERhaWx5IG9mIHRoZSBTaG93IGQCAw9kFgJmD2QWAmYPFQICNDIpSW50ZXJuYXRpb25hbCBDRVMgT2ZmaWNpYWwgU2hvdyBEaXJlY3RvcnlkAgQPZBYCZg9kFgJmDxUCAjQ1JUNFUyBEaWdpdGFsIEltYWdpbmcvUGhvdG9ncmFwaHkgRGFpbHlkAgUPZBYCZg9kFgJmDxUCAjQ2MEVudGVydGFpbm1lbnQgTWF0dGVycyBEYWlseSwgcHJvZHVjZWQgYnkgVmFyaWV0eWQCBg9kFgJmD2QWAmYPFQIBOSFJbnRlcm5hdGlvbmFsIENFUyBQcmVzaG93IFBsYW5uZXJkAgcPZBYCZg9kFgJmDxUCAjQ0L0NFUyBEaWdpdGFsIEltYWdpbmcvUGhvdG9ncmFwaHkgUHJlc2hvdyBQbGFubmVyZAIHD2QWAmYPZBYCAgIPZBYQZg9kFgJmD2QWAmYPFQgCNzFDSXQgaXMgSW5ub3ZhdGlvbiAoaTMpLSBPZmZpY2lhbCBQdWJsaWNhdGlvbiBvZiBDRUEsIFByb2R1Y2VyIG9mIENFUxBDYWxsIGZvciBkZXRhaWxz2wdXaGF0IGJldHRlciB3YXkgdG8gYXR0cmFjdCBwdWJsaWNpdHkgdGhhbiB0byBhZHZlcnRpc2UgaW4gdGhlIGluYXVndXJhbCBlZGl0aW9uIG9mIHRoZSBDb25zdW1lciBFbGVjdHJvbmljcyBBc3NvY2lhdGlvbiZyc3F1bztzIChDRUEpICZyZWc7IG5ldyBtYWdhemluZSwgSXQgaXMgSW5ub3ZhdGlvbiAoaTxzdHJvbmc+PGVtPjxzdXA+Mzwvc3VwPjwvZW0+PC9zdHJvbmc+KS48YnIgLz4NCjxiciAvPg0KaTxzdHJvbmc+PGVtPjxzdXA+Mzwvc3VwPjwvZW0+PC9zdHJvbmc+IHdpbGwgc2hvd2Nhc2UgYWxsIGFzcGVjdHMgb2YgaW5ub3ZhdGlvbiBpbiB0ZWNobm9sb2d5LCBwb2xpY3ksIGJ1c2luZXNzIGFuZCBlbmdpbmVlcmluZyBpbiB0aGUgY29uc3VtZXIgdGVjaG5vbG9neSBpbmR1c3RyeS4gSXQgaXMgSW5ub3ZhdGlvbiAoaTxzdHJvbmc+PGVtPjxzdXA+Mzwvc3VwPjwvZW0+PC9zdHJvbmc+KSB3aWxsIGxhdWNoIGF0IHRoZSAyMDEzIEludGVybmF0aW9uYWwgQ0VTIGluIEphbnVhcnkuIEdhaW4gZXhwb3N1cmUgd2l0aCB0aG9zZSB3aG8gY2FyZSBhYm91dCBpbm5vdmF0aW9uIHRoZSBtb3N0LCBhdHRlbmRlZXMgYXQgdGhlIDIwMTMgQ0VTLiBBcyB0aGUgb2ZmaWNpYWwgcHVibGljYXRpb24gb2YgQ0VBLCBpPHN0cm9uZz48ZW0+PHN1cD4zPC9zdXA+PC9lbT48L3N0cm9uZz5oYXMgZXhjbHVzaXZlIGRpc3RyaWJ1dGlvbiB0byBhcmVhcyBvZiB0aGUgc2hvdyB0aGF0IG5vIG90aGVyIHB1YmxpY2F0aW9uIHJlY2VpdmVzLCBpbmNsdWRpbmcgMywwMDAgZXhoaWJpdG9yIGJvb3RocywgcHViIGJpbnMsIENFQSBsb3VuZ2VzLCBleGVjdXRpdmUgc3VpdGVzLCB0aGUgcHJlc3Mgcm9vbSwgdGhlIFZJUCBsdW5jaHJvb20sIENFUyBVbnZlaWxlZCBhbmQgdGhlIElubm92YXRpb25zIEF3YXJkIFNob3djYXNlLjxiciAvPg0KJm5ic3A7PGJyIC8+DQpBZCBDbG9zZTogTm92ZW1iZXIgMzA8YnIgLz4NCk1hdGVyaWFscyBEdWU6IERlY2VtYmVyIDe4ATxkaXYgc3R5bGU9J2Zsb2F0OiByaWdodDsnPjxpbWcgc3JjPScvY2Vzd2ViL21lZGlhL0NFU1dlYi9Qcm9tbyUyME9wcHMvUHJpbnQlMjBBZHZlcnRpc2luZy9pM19yZWQuanBnJyBhbHQ9J0l0IGlzIElubm92YXRpb24gKGkzKS0gT2ZmaWNpYWwgUHVibGljYXRpb24gb2YgQ0VBLCBQcm9kdWNlciBvZiBDRVMnLz48L2Rpdj4AAGxEYW4gQ29sZSZuYnNwOzxiciAvPlBob25lOiZuYnNwOzcwMy05MDctNzk4NzxiciAvPkVtYWlsOiZuYnNwOzxhIGhyZWY9Im1haWx0bzpkY29sZUBDRS5vcmciPmRjb2xlQENFLm9yZzwvYT5kAgEPZBYCZg9kFgJmDxUIAjQzO0ludGVybmF0aW9uYWwgQ0VTIE9mZmljaWFsIFNob3cgR3VpZGUgJiBDb25mZXJlbmNlIEJyb2NodXJlEENhbGwgZm9yIGRldGFpbHPjGzxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+SW50ZXJuYXRpb25hbCBDRVMgYXR0ZW5kZWVzIGZpbmQgdGhlJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPk9mZmljaWFsIFNob3cgR3VpZGUgJmFtcDsgQ29uZmVyZW5jZSBCcm9jaHVyZTwvZW0+PHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4mbmJzcDt0byBiZSB0aGUgbW9zdCBjcml0aWNhbCB0b29sIHRvIG5hdmlnYXRlIHRoZSBzaG93LCBjb25mZXJlbmNlcyBhbmQgc3BlY2lhbCBldmVudHMuIFRoZSZuYnNwOzwvc3Bhbj48ZW0gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5PZmZpY2lhbCBTaG93IEd1aWRlICZhbXA7IENvbmZlcmVuY2UgQnJvY2h1cmU8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7Y29udGFpbnMgbGlzdGluZ3Mgb2YgYWxsIGV2ZW50cyBhbmQgYXdhcmRzLCBUZWNoWm9uZXMsIHNob3cgc2VydmljZXMsIGludGVybmF0aW9uYWwgc2VydmljZXMsIGhvdGVsL3RyYXZlbC90cmFuc3BvcnRhdGlvbiBpbmZvcm1hdGlvbiwgdGhlIG1vc3QgdXAtdG8tZGF0ZSBleGhpYml0b3IgbGlzdGluZyBhbmQgYSBmdWxsIGNvbmZlcmVuY2UgYnJvY2h1cmUgZm9yIGF0dGVuZGVlcyBvbi10aGUtbW92ZS4gQXNrIGFib3V0IHBhY2thZ2UgYWQgZGVhbHMgd2l0aCB0aGUmbmJzcDs8L3NwYW4+PGVtIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+T2ZmaWNpYWwgU2hvdyBEaXI8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+ZWN0b3J5LCBvbi1zaXRlIHNob3cgbWFwcyBhbmQmbmJzcDs8L3NwYW4+PGVtIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+UHJlc2hvdyBQbGFubmVyPC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiwgYWxsIGN1c3RvbS1wdWJsaXNoZWQgYnkgdGhlIENvbnN1bWVyIFRlY2hub2xvZ3kgUHVibGlzaGluZyBHcm91cCwgcHVibGlzaGVyIG9mJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPkRlYWxlcnNjb3BlPC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiw8L3NwYW4+PGVtIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Q3VzdG9tUmV0YWlsZXI8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+LCZuYnNwOzwvc3Bhbj48ZW0gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5UZWxsOiBUZWNobm9sb2d5IEZvciBFdmVyeWRheSBMaWZlPC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiwmbmJzcDs8L3NwYW4+PGVtIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+UGhvdG8gSW5kdXN0cnkgUmVwb3J0ZXI8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7YW5kJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPkhvbWUgRnVybmlzaGluZ3MgQnVzaW5lc3M8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7bWFnYXppbmVzLiAmbmJzcDs8L3NwYW4+PGJyIC8+DQo8YnIgLz4NCjxzdHJvbmcgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj48aW1nIGFsdD0iIiBzcmM9In4vY2Vzd2ViL21lZGlhL0NFU1dlYi9Qcm9tbyUyME9wcHMvUHJpbnQlMjBBZHZlcnRpc2luZy9DRXNfUHJpbnRBZHZlcnRpc2luZ19TaG93R3VpZGUuanBnIiBzdHlsZT0id2lkdGg6IDExNHB4OyBoZWlnaHQ6IDE2MHB4OyBmbG9hdDogbGVmdDsgIiAvPiZuYnNwOyBEZWFkbGluZXM8L3N0cm9uZz48YnIgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIiAvPg0KPHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4mbmJzcDsgQWQgY2xvc2luZzogTm92ZW1iZXImbmJzcDsyNjwvc3Bhbj48YnIgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIiAvPg0KPHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4mbmJzcDsgVGFiIEFkIENsb3Npbmc6IE5vdmVtYmVyJm5ic3A7MjY8L3NwYW4+PGJyIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICIgLz4NCjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7IE1hdGVyaWFscyBkdWU6Jm5ic3A7Tm92ZW1iZXImbmJzcDsyOTwvc3Bhbj48YnIgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIiAvPg0KPHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4mbmJzcDsgRGlzdHJpYnV0ZWQ6IE9uLXNpdGU8L3NwYW4+PGJyIC8+DQo8YnIgLz4NCjxiciAvPg0KPGJyIC8+DQo8aW1nIGFsdD0iIiBzcmM9In4vY2Vzd2ViL21lZGlhL0NFU1dlYi9Qcm9tbyUyME9wcHMvUHJpbnQlMjBBZHZlcnRpc2luZy9DRVNfUHJpbnRBZHZlcnRpc2luZ19DVFBHX2xvZ28uZ2lmIiBzdHlsZT0id2lkdGg6IDE1MHB4OyBoZWlnaHQ6IDI0cHg7IGZsb2F0OiBsZWZ0OyAiIC8+PGJyIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICIgLz4NCgAAAIEBUmljayBBbGJ1Y2smbmJzcDs8YnIgLz5QaG9uZTombmJzcDsyMTUtMjM4LTUyMTU8YnIgLz5FbWFpbDombmJzcDs8YSBocmVmPSJtYWlsdG86cmlja2FsYnVja0BuYXBjby5jb20gIj5yaWNrYWxidWNrQG5hcGNvLmNvbSA8L2E+ZAICD2QWAmYPZBYCZg8VCAIxMC1DRVMgRGFpbHkg4oCUIFRoZSBPZmZpY2lhbCBEYWlseSBvZiB0aGUgU2hvdyAQQ2FsbCBmb3IgRGV0YWlsc9IXPHAgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4NCglXYW50IHRyYWZmaWMgYXQgeW91ciBDRVMgYm9vdGg/IFRoZW4gYWR2ZXJ0aXNpbmcgaW4gdGhlJm5ic3A7PGVtPk9mZmljaWFsIENFUyBEYWlseSAmbWRhc2g7IHByb2R1Y2VkIGJ5IFRXSUNFPC9lbT4mbmJzcDsmbWRhc2g7IGlzIHRoZSB3YXkgdG8gZ28gKDQgaXNzdWVzICZtZGFzaDsgb25lIGxvdyBwcmljZSkuIEZvciB5ZWFyIGJ1eWVycyBoYXZlIHJlbGllZCBvbiB0aGUmbmJzcDs8ZW0+T2ZmaWNpYWwgQ0VTIERhaWx5PC9lbT4mbmJzcDt0byBwb2ludCB0aGUgd2F5LCBhbmQgd2l0aCBvdmVyIDMsMDAwIGV4aGliaXRvcnMsIGl0IG1ha2VzIGdyZWF0IGJ1c2luZXNzIHNlbnNlIHRvIGxldCB0aGVtIGtub3cgd2hhdCB5b3UmcnNxdW87cmUgc2VsbGluZyAmbWRhc2g7IGFuZCB3aHkgdG8gdmlzaXQgeW91ciBib290aC4gV3JpdHRlbiBieSB0aGUgZWRpdG9ycyBvZiZuYnNwOzxlbT5UV0lDRTwvZW0+LCB0aGUgaW5kdXN0cnkgcHVibGljYXRpb24gb2YgcmVjb3JkLCB0aGUgT2ZmaWNpYWwgQ0VTIERhaWxpZXMgY292ZXIgbmV3cywgbmV3IHByb2R1Y3RzLCBnZW5lcmFsIHNob3cgaW5mb3JtYXRpb24gJm1kYXNoOyBhbmQgbW9yZS4gQW5kIHdpdGggYW4gZW5vcm1vdXMgZGlzdHJpYnV0aW9uIGNvbnNpc3Rpbmcgb2Ygcm9vbS10by1yb29tIGF0IG1hbnkgTGFzIFZlZ2FzIGhvdGVscywgb24gYnVzc2VzLCBpbiBiaW5zLCBtb2RlbCBoYW5kLW91dHMsIGFuZCBvbi1saW5lIHRvbywgdGhlc2UgZGFpbGllcyBhcmUgbm90IG9ubHkgc2VlbiwgYnV0IHV0aWxpemVkIGluIGEgdmVyeSBiaWcgd2F5IGhlbHBpbmcgYXR0ZW5kZWVzIG5hdmlnYXRlIHRoZSBzaG93LiZuYnNwOyBTbyBjYWxsIG9yIGVtYWlsIGZvciBkZXRhaWxzICZtZGFzaDsgYW5kIGRpc2NvdW50ZWQgT2ZmaWNpYWwgQ0VTIERhaWx5L1RXSUNFIFNob3cgUGFja2FnZXMuJm5ic3A7PHN0cm9uZz48ZW0+T2ZmaTwvZW0+PC9zdHJvbmc+PHN0cm9uZz48ZW0+Y2lhbCBDRVMgRGFpbHk8L2VtPiZuYnNwO0lzc3VlIERhdGVzOiBKYW51YXJ5IDgsIDksJm5ic3A7MTAgYW5kIDExLjwvc3Ryb25nPjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+DQoJPGJyIC8+DQoJPHN0cm9uZz48aW1nIGFsdD0iIiBzcmM9In4vY2Vzd2ViL21lZGlhL0NFU1dlYi9Qcm9tbyUyME9wcHMvUHJpbnQlMjBBZHZlcnRpc2luZy9DRVNfUHJpbnRBZHZlcnRpc2luZ19Ud2ljZV8xMjBwdy5qcGciIHN0eWxlPSJ3aWR0aDogMTIwcHg7IGhlaWdodDogMTMxcHg7IGZsb2F0OiBsZWZ0OyAiIC8+PC9zdHJvbmc+PC9wPg0KPGRpdj4NCgk8c3Ryb25nIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+RGU8L3N0cm9uZz48c3Ryb25nIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+YWRsaTwvc3Ryb25nPjxzdHJvbmcgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5uPC9zdHJvbmc+PHN0cm9uZyBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPmVzPC9zdHJvbmc+PC9kaXY+DQo8ZGl2Pg0KCTxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+QWQgQ2xvc2luZzombmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsgTm92ZW1iZXIgMjMsIDIwMTI8L3NwYW4+PGJyIC8+DQoJPGJyIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICIgLz4NCgk8c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPkFkIE1hdGVyaWFsIGR1ZTombmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsmbmJzcDsgJm5ic3A7ICZuYnNwO0RlY2VtYmVyIDMsIDIwMTI8L3NwYW4+PGJyIC8+DQoJPGJyIC8+DQoJPGJyIC8+DQoJPGJyIC8+DQoJPGJyIC8+DQoJPHRhYmxlIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7IHdpZHRoOiA1MjlweDsgaGVpZ2h0OiAxMTJweDsgIj4NCgkJPHRib2R5Pg0KCQkJPHRyPg0KCQkJCTx0ZD4NCgkJCQkJPHAgc3R5bGU9Im1hcmdpbjogMGluIDBpbiAwcHQ7ICI+DQoJCQkJCQk8c3Ryb25nPk1pZHdlc3QvV2VzdCBDb2FzdDo8L3N0cm9uZz48L3A+DQoJCQkJCTxwIHN0eWxlPSJtYXJnaW46IDBpbiAwaW4gMHB0OyAiPg0KCQkJCQkJVG9ueSBNb250ZWxlb25lPGJyIC8+DQoJCQkJCQlBc3NvY2lhdGUgUHVibGlzaGVyPGJyIC8+DQoJCQkJCQlQaG9uZTogOTE3LTI4MS00NzQyPGJyIC8+DQoJCQkJCQk8YSBocmVmPSJtYWlsdG86dG1vbnRlbGVvbmVAbmJtZWRpYS5jb20iPnRtb250ZWxlb25lQG5ibWVkaWEuY29tPC9hPjwvcD4NCgkJCQk8L3RkPg0KCQkJCTx0ZD4NCgkJCQkJPGJyIC8+DQoJCQkJCTxzdHJvbmc+RWFzdCBDb2FzdDo8L3N0cm9uZz48YnIgLz4NCgkJCQkJTWFyY2lhIEdyYW5kPGJyIC8+DQoJCQkJCVZQL1B1Ymxpc2hlcjxiciAvPg0KCQkJCQlQaG9uZTogOTE3LTI4MS00NzI0PGJyIC8+DQoJCQkJCTxhIGhyZWY9Im1haWx0bzptZ3JhbmRAbmJtZWRpYS5jb20iPm1ncmFuZEBuYm1lZGlhLmNvbTwvYT48YnIgLz4NCgkJCQkJJm5ic3A7PC90ZD4NCgkJCTwvdHI+DQoJCTwvdGJvZHk+DQoJPC90YWJsZT4NCjwvZGl2Pg0KPGJyIC8+DQoAAAC4AVRvbnkgTW9udGVsZW9uZSwgTWlkd2VzdC9XZXN0IENvYXN0IEFzc29jaWF0ZSBQdWJsaXNoZXImbmJzcDs8YnIgLz5QaG9uZTombmJzcDtQaG9uZTogOTE3LTI4MS00NzQyPGJyIC8+RW1haWw6Jm5ic3A7PGEgaHJlZj0ibWFpbHRvOnRtb250ZWxlb25lQG5ibWVkaWEuY29tIj50bW9udGVsZW9uZUBuYm1lZGlhLmNvbTwvYT5kAgMPZBYCZg9kFgJmDxUIAjQyKUludGVybmF0aW9uYWwgQ0VTIE9mZmljaWFsIFNob3cgRGlyZWN0b3J5EENhbGwgZm9yIGRldGFpbHPkHzxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+VGhlJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPk9mZmljaWFsIFNob3cgRGlyZWN0b3J5PC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiZuYnNwO2lzIHRoZSB1bHRpbWF0ZSByZWZlcmVuY2UgZ3VpZGUgZm9yIHRoZSBJbnRlcm5hdGlvbmFsIENFUy4gVGhlIG9ubHkgeWVhci1yb3VuZCByZWZlcmVuY2Ugc291cmNlLCB0aGUgZGlyZWN0b3J5IGxpc3RzIGNvbXBsZXRlIGV4aGliaXRvciBjb21wYW55IHByb2ZpbGVzLCBicmFuZCBsaXN0aW5ncyBhbmQgaW1wb3J0YW50IHByb2R1Y3QgaW5mb3JtYXRpb24uIEFkcyBhcmUgcHJvbWluZW50bHkgcGxhY2VkIGFuZCBicmluZyByZXN1bHRzLWV2ZW4gYWZ0ZXIgdGhlIHNob3cgaXMgb3Zlci4gQXNrIGFib3V0IHBhY2thZ2VzIHdpdGggdGhlJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPk9mZmljaWFsPC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiZuYnNwOzwvc3Bhbj48ZW0gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5TaG93IEd1aWRlICZhbXA7IENvbmZlcmVuY2UgQnJvY2h1cmUsPC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiZuYnNwO29uLXNpdGUgc2hvdyBtYXBzIGFuZCB0aGUmbmJzcDs8L3NwYW4+PGVtIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+UHJlc2hvdyBQbGFubmVyPC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiwgY3VzdG9tIHB1Ymxpc2hlZCBieSB0aGUgQ29uc3VtZXIgVGVjaG5vbG9neSBQdWJsaXNoaW5nIEdyb3VwLCBwdWJsaXNoZXIgb2YmbmJzcDs8L3NwYW4+PGVtIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+RGVhbGVyc2NvcGU8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+LDwvc3Bhbj48ZW0gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5DdXN0b21SZXRhaWxlcjwvZW0+PHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4sJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPlRlbGw6IFRlY2hub2xvZ3kgRm9yIEV2ZXJ5ZGF5IExpZmU8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+LCZuYnNwOzwvc3Bhbj48ZW0gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5QaG90byBJbmR1c3RyeSBSZXBvcnQ8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+ZXIgYW5kJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPkhvbWUgRnVybmlzaGluZ3MgQnVzaW5lc3M8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7bWFnYXppbmVzLiBJbmNsdWRlIHlvdXIgY29tcGFueSBsb2dvIGluIHRoZSBwcmludGVkIHZlcnNpb24gb2YgdGhlJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPk9mZmljaWFsIFNob3cgRGlyZWN0b3J5PC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiZuYnNwO2ZvciAkNjI1Ljwvc3Bhbj48c3Ryb25nIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7Jm5ic3A7PC9zdHJvbmc+PGJyIC8+DQo8YnIgLz4NCjxzdHJvbmcgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj48aW1nIGFsdD0iIiBzcmM9In4vY2Vzd2ViL21lZGlhL0NFU1dlYi9Qcm9tbyUyME9wcHMvUHJpbnQlMjBBZHZlcnRpc2luZy9DRVNfUHJpbnRBZHZlcnRpc2luZ19TaG93RGlyZWN0b3J5LmpwZyIgc3R5bGU9IndpZHRoOiAxMTRweDsgaGVpZ2h0OiAxNjBweDsgZmxvYXQ6IGxlZnQ7ICIgLz4mbmJzcDsgRGVhZGxpbmVzPC9zdHJvbmc+PGJyIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICIgLz4NCjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7IEFkIGNsb3Npbmc6IE5vdmVtYmVyJm5ic3A7MjE8L3NwYW4+PGJyIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICIgLz4NCjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7IE1hdGVyaWFscyBkdWU6IE5vdmVtYmVyJm5ic3A7Mjg8L3NwYW4+PGJyIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICIgLz4NCjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7IFRhYiBhZCBjbG9zaW5nOiBOb3ZlbWJlciZuYnNwOzE0PC9zcGFuPjxiciBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiIC8+DQo8c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiZuYnNwOyZuYnNwO1RhYiBtYXRlcmlhbHMgZHVlOiBOb3ZlbWJlciZuYnNwOzE1PC9zcGFuPjxiciBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiIC8+DQo8c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiZuYnNwOyBEaXN0cmlidXRlZDogT24tc2l0ZSZuYnNwOzwvc3Bhbj48YnIgLz4NCjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7IERlYWRsaW5lIHRvIGluY2x1ZGUgbG9nb3MgaW4gRGlyZWN0b3J5OiBOb3ZlbWJlciAyODwvc3Bhbj48YnIgLz4NCjxiciAvPg0KPGltZyBhbHQ9IiIgc3JjPSJ+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvUHJvbW8lMjBPcHBzL1ByaW50JTIwQWR2ZXJ0aXNpbmcvQ0VTX1ByaW50QWR2ZXJ0aXNpbmdfQ1RQR19sb2dvLmdpZiIgc3R5bGU9IndpZHRoOiAxNTBweDsgaGVpZ2h0OiAyNHB4OyBmbG9hdDogbGVmdDsgIiAvPjxiciAvPg0KPGJyIC8+DQo8YnIgLz4NCjxiciAvPg0KPGJyIC8+DQo8YnIgLz4NCgAAAIEBUmljayBBbGJ1Y2smbmJzcDs8YnIgLz5QaG9uZTombmJzcDsyMTUtMjM4LTUyMTU8YnIgLz5FbWFpbDombmJzcDs8YSBocmVmPSJtYWlsdG86cmlja2FsYnVja0BuYXBjby5jb20gIj5yaWNrYWxidWNrQG5hcGNvLmNvbSA8L2E+ZAIED2QWAmYPZBYCZg8VCAI0NSVDRVMgRGlnaXRhbCBJbWFnaW5nL1Bob3RvZ3JhcGh5IERhaWx5EENhbGwgZm9yIGRldGFpbHOPDDxwIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+DQoJV2l0aCBQTUEgbm93IHBhcnQgb2YgQ0VTLCBwcm9tb3RlIHlvdXIgb3JnYW5pemF0aW9uIGFuZCBkcml2ZSBib290aCB0cmFmZmljIHdpdGggYW4gYWQgaW4gdGhlIG5ldyZuYnNwOzxlbT5PZmZpY2lhbCBDRVMgRGlnaXRhbCBJbWFnaW5nL1Bob3RvZ3JhcGh5IERhaWx5PC9lbT4sIHByb2R1Y2VkIGJ5Jm5ic3A7PGVtPlBob3RvIEluZHVzdHJ5IFJlcG9ydGVyPC9lbT4uIFRoaXMgcHVibGljYXRpb24gd2lsbCBiZSBmb2N1c2VkIHNwZWNpZmljYWxseSBvbiBpbWFnaW5nLCBhbmQgZmVhdHVyZSBzaG93IGluZm9ybWF0aW9uLCB0aGUgbGF0ZXN0IGJyZWFraW5nIG5ld3MgYW5kIGluZHVzdHJ5IGluZm9ybWF0aW9uLCBhbmQgd2lsbCBiZSBkaXN0cmlidXRlZCB0aHJvdWdob3V0IENFUy4gTWFnYXppbmUgZGlzdHJpYnV0aW9uIHdpbGwgb2NjdXIgb24tc2l0ZSBpbiBudW1lcm91cyBoaWdoLXRyYWZmaWMgbG9jYXRpb25zIHRocm91Z2hvdXQgQ0VTLCBhcyB3ZWxsIGFzIGRpc3RyaWJ1dGVkIHRvIG9mZmljaWFsIFBNQS1kZXNpZ25hdGVkIGhvdGVscyBlYWNoIG1vcm5pbmcgb2YgSmFuLiAxMC0xMi48L3A+DQo8ZGl2Pg0KCTxiciAvPg0KCTxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7PGltZyBhbHQ9IiIgc3JjPSJ+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvUHJvbW8lMjBPcHBzL1ByaW50JTIwQWR2ZXJ0aXNpbmcvQ0VTX1ByaW50QWR2ZXJ0aXNpbmdfU2hvd0RhaWx5LmpwZyIgc3R5bGU9IndpZHRoOiAxMTRweDsgaGVpZ2h0OiAxNjBweDsgZmxvYXQ6IGxlZnQ7ICIgLz4mbmJzcDs8L3NwYW4+PHN0cm9uZyBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPkRlYWRsaW5lczwvc3Ryb25nPjxiciBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiIC8+DQoJPHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4mbmJzcDsgQWQgY2xvc2luZzogRGVjZW1iZXIgMzwvc3Bhbj48YnIgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIiAvPg0KCTxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7IE1hdGVyaWFscyBkdWU6IERlY2VtYmVyIDEyPC9zcGFuPjxiciBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiIC8+DQoJPHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4mbmJzcDsgRGlzdHJpYnV0ZWQ6IENFUzwvc3Bhbj48L2Rpdj4NCgAAAIkBQWxhbiBMZXZpbmUmbmJzcDs8YnIgLz5QaG9uZTombmJzcDs1MTYtMzY0LTA1MDM8YnIgLz5FbWFpbDombmJzcDs8YSBocmVmPSJtYWlsdG86YWxldmluZUBwaG90b3JlcG9ydGVyLmNvbSI+YWxldmluZUBwaG90b3JlcG9ydGVyLmNvbTwvYT5kAgUPZBYCZg9kFgJmDxUIAjQ2MEVudGVydGFpbm1lbnQgTWF0dGVycyBEYWlseSwgcHJvZHVjZWQgYnkgVmFyaWV0eRBDYWxsIGZvciBkZXRhaWxz+w48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPlZhcmlldHksIHRoZSBsZWFkaW5nIGVudGVydGFpbm1lbnQgdHJhZGUgbWFnYXppbmUsIHdpbGwgYmUgcHJvZHVjaW5nIHByaW50ZWQgZGFpbGllcyBmb3IgQ0VTIGRlZGljYXRlZCB0byBFbnRlcnRhaW5tZW50IE1hdHRlcnMgcHJvZ3JhbW1pbmcsIG5ld3MsIGV2ZW50cywgYW5ub3VuY2VtZW50cyBhbmQgc3BlY2lhbCBmZWF0dXJlcy4gVGhlIG1vc3QgaW5mbHVlbnRpYWwgbGVhZGVycyBpbiB0aGUgaW5kdXN0cnkgaGF2ZSB0dXJuZWQgdG8gVmFyaWV0eSBmb3IgdGltZWx5LCBjcmVkaWJsZSBhbmQgc3RyYWlnaHQtZm9yd2FyZCBuZXdzIGFuZCBhbmFseXNpcyB2aXRhbCB0byB0aGVpciBwcm9mZXNzaW9ucy4gTm93IHRoZXkgd2lsbCBoYXZlIGZpcnN0LWhhbmQgYWNjZXNzIGF0IHRoZSBtb3N0IGltcG9ydGFudCBuZXdzIGFuZCBhbm5vdW5jZW1lbnRzIGltcGFjdGluZyB0aGUgZW50ZXJ0YWlubWVudCBpbmR1c3RyeSBhdCBDRVMhPC9zcGFuPg0KPHVsIGNsYXNzPSJ0ZXh0IiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPg0KCTxsaSBjYXNzPSJ0ZXh0Ij4NCgkJRGlzdHJpYnV0aW9uIHdpbGwgYmUgZXh0ZW5zaXZlIHRocm91Z2hvdXQgdGhlIHNob3cgdmlhIHB1YiBiaW5zIGFuZCBtb2RlbHMgYXQga2V5IGRpc3RyaWJ1dGlvbiBwb2ludHM8L2xpPg0KCTxsaSBjbGFzcz0idGV4dCIgc3R5bGU9Imxpc3Qtc3R5bGUtaW1hZ2U6IHVybChodHRwOi8vd3d3LmNlc3dlYi5vcmcvaW1hZ2VzL2ZyYW1ld29yay9zbWFsbF9idWxsZXQtdGV4dC5naWYpOyAiPg0KCQlBZHZlcnRpc2luZyBpcyBhdmFpbGFibGUgLSBmcm9udCBjb3ZlciBhbmQgcHJlbWl1bSBzcG90cyBhcyB3ZWxsIGFzIHN0YW5kYXJkIGFkIHVuaXRzIGluIGJvb2s8L2xpPg0KCTxsaSBjbGFzcz0idGV4dCIgc3R5bGU9Imxpc3Qtc3R5bGUtaW1hZ2U6IHVybChodHRwOi8vd3d3LmNlc3dlYi5vcmcvaW1hZ2VzL2ZyYW1ld29yay9zbWFsbF9idWxsZXQtdGV4dC5naWYpOyAiPg0KCQkxMCwwMDAgY29waWVzIHdpbGwgYmUgZGlzdHJpYnV0ZWQgZWFjaCBkYXkgb2YgdGhlIHNob3c8L2xpPg0KCTxsaSBjbGFzcz0idGV4dCIgc3R5bGU9Imxpc3Qtc3R5bGUtaW1hZ2U6IHVybChodHRwOi8vd3d3LmNlc3dlYi5vcmcvaW1hZ2VzL2ZyYW1ld29yay9zbWFsbF9idWxsZXQtdGV4dC5naWYpOyAiPg0KCQlJbiBhZGRpdGlvbiB0aGUgcHJpbnRlZCBkYWlsaWVzIG9uLXNpdGUgYXQgQ0VTLCBvdmVyIDI3LDAwMCBWYXJpZXR5IHN1YnNjcmliZXJzIHdpbGwgaGF2ZSBhY2Nlc3MgdG8gdmlldyB0aGUgZGlnaXRhbCBlZGl0aW9ucyBvbi1saW5lPGJyIC8+DQoJCTxiciAvPg0KCQk8ZGl2Pg0KCQkJQWR2ZXJ0aXNpbmcgaXMgYXZhaWxhYmxlIC0gZnJvbnQgY292ZXIgYW5kIHByZW1pdW0gc3BvdHMgYXMgd2VsbCBhcyBzdGFuZGFyZCBhZCB1bml0cyBpbiBib29rPC9kaXY+DQoJCTxkaXY+DQoJCQkmbmJzcDs8L2Rpdj4NCgkJPGJyIC8+DQoJCTxzdHJvbmc+PGltZyBhbHQ9IiIgc3JjPSJ+L2Nlc3dlYi9tZWRpYS9DRVNXZWIvUHJvbW8lMjBPcHBzL1ByaW50JTIwQWR2ZXJ0aXNpbmcvQ0VzX1ByaW50QWR2ZXJ0aXNpbmdfVmFyaWV0eUZpbmFsQ292ZXIuanBnIiBzdHlsZT0id2lkdGg6IDEyN3B4OyBoZWlnaHQ6IDE2MHB4OyBmbG9hdDogbGVmdDsgIiAvPiZuYnNwO0RlYWRsaW5lczwvc3Ryb25nPjxiciAvPg0KCQkmbmJzcDtBZCBjbG9zaW5nOiBDYWxsIGZvciBkZXRhaWxzPGJyIC8+DQoJCSZuYnNwO01hdGVyaWFscyBkdWU6IENhbGwgZm9yIGRldGFpbHM8YnIgLz4NCgkJJm5ic3A7RGlzdHJpYnV0ZWQ6IENFUzwvbGk+DQo8L3VsPg0KAAAArwFMaW5kYSBCdWNrbGV5LUJydW5vLCBQdWJsaXNoaW5nIERpcmVjdG9yLCBWYXJpZXR5Jm5ic3A7PGJyIC8+UGhvbmU6Jm5ic3A7MzIzLTYxNy05NDI5PGJyIC8+RW1haWw6Jm5ic3A7PGEgaHJlZj0ibWFpbHRvOkxpbmRhLmJ1Y2tsZXlAdmFyaWV0eS5jb20iPkxpbmRhLmJ1Y2tsZXlAdmFyaWV0eS5jb208L2E+ZAIGD2QWAmYPZBYCZg8VCAE5IUludGVybmF0aW9uYWwgQ0VTIFByZXNob3cgUGxhbm5lchBDYWxsIGZvciBkZXRhaWxz+Aw8cCBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPg0KCVRoZSZuYnNwOzxlbT5PZmZpY2lhbCBQcmVzaG93IFBsYW5uZXI8L2VtPiZuYnNwO2lzIHRoZSBtb3N0IGNvbXBsZXRlIGd1aWRlIHRvIHBsYW5uaW5nIHBhY2tlZCBkYXlzIGF0IENFUy4gUHJvZHVjZWQgYnkgdGhlIENvbnN1bWVyIFRlY2hub2xvZ3kgUHVibGlzaGluZyBHcm91cCwgcHVibGlzaGVyIG9mJm5ic3A7PGVtPkRlYWxlcnNjb3BlPC9lbT4sJm5ic3A7PGVtPkN1c3RvbVJldGFpbGVyPC9lbT4sJm5ic3A7PGVtPlRlbGw6IFRlY2hub2xvZ3kgRm9yIEV2ZXJ5ZGF5IExpZmU8L2VtPiwmbmJzcDs8ZW0+UGhvdG8gSW5kdXN0cnkgUmVwb3J0ZXI8L2VtPiZuYnNwO2FuZDxlbT5Ib21lIEZ1cm5pc2hpbmdzIEJ1c2luZXNzPC9lbT4mbmJzcDttYWdhemluZXMsIHRoZSZuYnNwOzxlbT5QcmVzaG93IFBsYW5uZXI8L2VtPiZuYnNwO2lzIG1haWxlZCBpbiBlYXJseSBEZWNlbWJlciB0byBkb21lc3RpYywgcHJlLXJlZ2lzdGVyZWQgQ0VTIGF0dGVuZGVlcyBhbmQgaXMgYWxzbyBzZW50IGFzIGFuIGludGVyYWN0aXZlIGRpZ2l0YWwgbWFnYXppbmUgdG8gb3ZlciAzNSwwMDAgaW50ZXJuYXRpb25hbCBhdHRlbmRlZXMgaW4gMTUwIGNvdW50cmllcy4gVGhpcyBpcyBUSEUgcGxhY2UgdG8gZ2V0IGFuIGVhcmx5IHN0YXJ0IG9uIHJlYWNoaW5nIGF0dGVuZGVlcyBiZWZvcmUgdGhleSBhcnJpdmUuIENhbGwgbm93IHRvIHJlc2VydmUgYWQgc3BhY2UuIEFzayBhYm91dCBwYWNrYWdlIGFkIGRlYWxzIHdpdGggdGhlJm5ic3A7PGVtPk9mZmljaWFsIFNob3cgRGlyZWN0b3J5PC9lbT4mbmJzcDthbmQgdGhlJm5ic3A7PGVtPk9mZmljaWFsIFNob3cgR3VpZGUgJmFtcDsgQ29uZmVyZW5jZSBCcm9jaHVyZTwvZW0+LjwvcD4NCjxwIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+DQoJPHN0cm9uZz48aW1nIGFsdD0iIiBzcmM9In4vY2Vzd2ViL21lZGlhL0NFU1dlYi9Qcm9tbyUyME9wcHMvUHJpbnQlMjBBZHZlcnRpc2luZy9DRVNfUHJpbnRBZHZlcnRpc2luZ19QcmVzaG93cGxhbm5lci5qcGciIHN0eWxlPSJ3aWR0aDogMTE0cHg7IGhlaWdodDogMTYwcHg7IGZsb2F0OiBsZWZ0OyAiIC8+Jm5ic3A7ICZuYnNwO0RlYWRsaW5lczwvc3Ryb25nPjxiciAvPg0KCSZuYnNwOyZuYnNwOyBBZCBjbG9zaW5nOiBPY3RvYmVyJm5ic3A7MjUgKGNsb3NlZCk8YnIgLz4NCgkmbmJzcDsmbmJzcDsgTWF0ZXJpYWxzIGR1ZTogTm92ZW1iZXImbmJzcDsxPGJyIC8+DQoJJm5ic3A7Jm5ic3A7IERpc3RyaWJ1dGVkOiBFYXJseSBEZWNlbWJlcjxiciAvPg0KCSZuYnNwOzwvcD4NCjxkaXYgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7Ij4NCgk8YnIgLz4NCgk8YnIgLz4NCgk8aW1nIGFsdD0iIiBzcmM9Imh0dHA6Ly9zdGFnaW5nLmNlc3dlYi5vcmcvY2Vzd2ViL21lZGlhL0NFU1dlYi9Qcm9tbyUyME9wcHMvUHJpbnQlMjBBZHZlcnRpc2luZy9DRVNfUHJpbnRBZHZlcnRpc2luZ19DVFBHX2xvZ28uZ2lmIiBzdHlsZT0id2lkdGg6IDE1MHB4OyBoZWlnaHQ6IDI0cHg7IGZsb2F0OiBsZWZ0OyAiIC8+PGJyIC8+DQoJPGJyIC8+DQoJJm5ic3A7PC9kaXY+DQoAAACBAVJpY2sgQWxidWNrJm5ic3A7PGJyIC8+UGhvbmU6Jm5ic3A7MjE1LTIzOC01MjE1PGJyIC8+RW1haWw6Jm5ic3A7PGEgaHJlZj0ibWFpbHRvOnJpY2thbGJ1Y2tAbmFwY28uY29tICI+cmlja2FsYnVja0BuYXBjby5jb20gPC9hPmQCBw9kFgJmD2QWAmYPFQgCNDQvQ0VTIERpZ2l0YWwgSW1hZ2luZy9QaG90b2dyYXBoeSBQcmVzaG93IFBsYW5uZXIQQ2FsbCBmb3IgZGV0YWlsc4cQPHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj5QbGFjZSB5b3VyIGNvbXBhbnkmIzM5O3Mgc2FsZXMgbWVzc2FnZSBpbiBmcm9udCBvZiBkaWdpdGFsIGltYWdpbmcvcGhvdG9ncmFwaHkgYXR0ZW5kZWVzIGJlZm9yZSB0aGV5IHN0ZXAgZm9vdCBvbiB0aGUgc2hvdyBmbG9vciBieSB1dGlsaXppbmcgdGhlIGZpcnN0LWV2ZXImbmJzcDs8L3NwYW4+PGVtIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+T2ZmaWNpYWwgQ0VTIERpZ2l0YWwgSW1hZ2luZy9QaG90b2dyYXBoeSBQcmVzaG93IFBsYW5uZXI8L2VtPjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+LCBwcm9kdWNlZCBieSBEZWFsZXJzY29wZS4gVGhpcyBuZXcgcHVibGljYXRpb24gd2lsbCBoZWxwIGF0dGVuZGVlcyBwbGFuIHRoZWlyIHRyaXAgdG8gQ0VTIHdpdGggZGlnaXRhbCBpbWFnaW5nIHNwZWNpZmljIGNvbnRlbnQgYWJvdXQgdGhlIHNob3cuIERpc3RyaWJ1dGVkIGFsb25nIHdpdGggdGhlIERlY2VtYmVyIGlzc3VlIG9mJm5ic3A7PC9zcGFuPjxlbSBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPlBob3RvIEluZHVzdHJ5IFJlcG9ydGVyPC9lbT48c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiwgaXQgd2lsbCByZWFjaCBhdHRlbmRlZXMganVzdCBhcyB0aGV5IGFyZSBtYWtpbmcgdGhlaXIgc2hvdyBwbGFucy4gVGhpcyBwdWJsaWNhdGlvbiBpcyBlc3BlY2lhbGx5IHVzZWZ1bCwgYXMgUE1BQENFUyBpcyBhbiBpbnRlZ3JhbCBwYXJ0IG9mIHRoZSBzaG93LCBjcmVhdGluZyBhIG5ldyBleHBlcmllbmNlIGZvciB0aGUgZXhoaWJpdG9ycyBhbmQgYXR0ZW5kZWVzLiZuYnNwOzwvc3Bhbj48YnIgLz4NCjxiciAvPg0KPHN0cm9uZyBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPjxpbWcgYWx0PSIiIHNyYz0ifi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1Byb21vJTIwT3Bwcy9QcmludCUyMEFkdmVydGlzaW5nL0NFU19QcmludEFkdmVydGlzaW5nX3ByZS1zaG93LXBsYW5uZXIuanBnIiBzdHlsZT0id2lkdGg6IDExNHB4OyBoZWlnaHQ6IDE2MHB4OyBmbG9hdDogbGVmdDsgIiAvPiZuYnNwO0RlYWRsaW5lczwvc3Ryb25nPjxiciBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiIC8+DQo8c3BhbiBzdHlsZT0idGV4dC1hbGlnbjogbGVmdDsgYmFja2dyb3VuZC1jb2xvcjogcmdiKDI1NSwgMjU1LCAyNTUpOyAiPiZuYnNwO0FkIGNsb3Npbmc6IE9jdG9iZXIgMjY8L3NwYW4+IChjbG9zZWQpPGJyIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICIgLz4NCjxzcGFuIHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyBiYWNrZ3JvdW5kLWNvbG9yOiByZ2IoMjU1LCAyNTUsIDI1NSk7ICI+Jm5ic3A7TWF0ZXJpYWxzIGR1ZTogTm92ZW1iZXIgOTwvc3Bhbj48YnIgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIiAvPg0KPHNwYW4gc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7IGJhY2tncm91bmQtY29sb3I6IHJnYigyNTUsIDI1NSwgMjU1KTsgIj4mbmJzcDtEaXN0cmlidXRlZDogRWFybHkgRGVjZW1iZXI8L3NwYW4+PGJyIC8+DQo8YnIgLz4NCjxiciAvPg0KPGJyIC8+DQo8YnIgLz4NCjxpbWcgYWx0PSIiIHNyYz0ifi9jZXN3ZWIvbWVkaWEvQ0VTV2ViL1Byb21vJTIwT3Bwcy9QcmludCUyMEFkdmVydGlzaW5nL0NFU19QcmludEFkdmVydGlzaW5nX0NUUEdfbG9nby5naWYiIHN0eWxlPSJ3aWR0aDogMTUwcHg7IGhlaWdodDogMjRweDsiIC8+AAAAgQFSaWNrIEFsYnVjayZuYnNwOzxiciAvPlBob25lOiZuYnNwOzIxNS0yMzgtNTIxNTxiciAvPkVtYWlsOiZuYnNwOzxhIGhyZWY9Im1haWx0bzpyaWNrYWxidWNrQG5hcGNvLmNvbSAiPnJpY2thbGJ1Y2tAbmFwY28uY29tIDwvYT5kZCkhgaatG3Akdrbozu/ZoEiCTxUndLmyurKOKOw0YMng" />
</div>

<input type="hidden" name="lng" id="lng" value="en-US" />
<script src="/ScriptResource.axd?d=N6Jl9XMQzDo-M2VzrTGsHPZJGE_S0b4WAFqG2dSX7CkNtipRz9-bk6m1eCad7PfvRzztBSdjlldijvTkzJwz-B7gytD2o4JDVsEtYwIA_if0EqaKmLOMsnSmleNoFWfh0&amp;t=34d147fd" type="text/javascript"></script>
    <div id="CMSHeaderDiv">
	<!-- -->
</div>
    <script type="text/javascript" src="/cesweb/media/CESWeb/assets/js/custom/subpage.js"></script>
<!-- start black bar -->
            <div id="header-wrapper">
		<div id="header-top-wrapper">
			<div id="header-top">
				<div id="header-more-sites">
					<div id="header-more-expander">
						<ul>
                                                	<li><a href="http://www.ce.org">CEA - CE.org</a></li><li><a href="http://www.cesweb.org">International CES</a></li><li><a href="http://www.declareinnovation.com">Innovation Movement</a></li><li><a href="http://blog.ce.org">Digital Dialogue</a></li><li><a href="http://www.cevision.org">Vision Magazine</a></li><li><a href="http://www.greenergadgets.org">Greener Gadgets</a></li><li><a href="http://research.ce.org">Market Research</a></li>


						</ul>
						<a id="the-expander" href="#">More CEA sites</a>
					</div>
				</div>
				<div id="header-feed">
				</div>
			</div>
		</div>
            </div>
<!-- end black bar -->
<div id="newwrap">
    <div id="container">
        <div id="content-container">
            <div id="header">
                <div id="logo">
                    <a href="/Home.aspx"><img id="p_lt_zoneLogo_EditableImage_imgImage" src="/cesweb/media/CESWeb/assets/images/header/cesweb_headerlogo.png" alt="" /></a>
                </div>
                <div id="headTop">
                    <div id="topsearch">
                                    <input type="hidden" id="Hidden1" value="default_collection" name="site" />
            <input type="hidden" id="Hidden2" value="2011CESweb" name="client" />
            <input type="hidden" id="Hidden3" value="2011CESweb" name="proxystylesheet" />
            <input type="hidden" id="Hidden4" value="xml_no_dtd" name="output" />
<input class="searchbox" id="searchbox" name="q" onblur="if(this.value=='') this.value='Search';" onfocus="if(this.value=='Search') this.value='';" type="text" value="Search" />
                		<!-- Pyxl ADD search from below-->
						<!--        <form action="http://googlebox.ce.org/search?" method="GET" name="searchCES">
						            <input type="hidden" id="Hidden1" value="default_collection" name="site">
						            <input type="hidden" id="Hidden2" value="2011CESweb" name="client">
						            <input type="hidden" id="Hidden3" value="2011CESweb" name="proxystylesheet">
						            <input type="hidden" id="Hidden4" value="xml_no_dtd" name="output">
						            <input type="text" onfocus="if(this.value=='Search') this.value='';" onblur="if(this.value=='') this.value='Search';" value="Search" class="searchbox" name="q"><input type="submit" onclick="document.searchCES.submit();" class="searchbutton" value="">
						            </form> 
						<A href="http://www.cesweb.org/cesgreening.asp"><img src="http://www.cesweb.org/hp/images/ces-green.jpg" border="0" valign=top ></A>
					</div>
						    <div id="topimages">
						        <img src="http://www.cesweb.org/hp/images/divider.jpg" class="divider"/>
						         <a href=http://www.cesweb.org/socialcircle target="_blank"><img src="http://www.cesweb.org/hp/images/socialcircle.aspx" alt="Social Circle" /></a>
						&nbsp;&nbsp;&nbsp;&nbsp;-->
	             </div>
                </div>
                <div class="clr"></div>
                <div id="ctacontainer">
                    <div id="showdate"> <img id="p_lt_zoneShowDate_EditableImage1_imgImage" src="/cesweb/media/CESWeb/assets/images/header/CESweb_headerdate.png" alt="" /> </div>
                    <div id="register">
	<a href="/Register.aspx" target="_blank" title="Register for CES"><img alt="Register" border="0" name="cesweb_register" onmouseout="out(8)" onmouseover="over(8)" src="/cesweb/media/CESWeb/assets/images/nav/cesweb_register1.png" /></a></div>
<div id="exhibit">
	<a href="/For-Exhibitors/Exhibit-at-CES.aspx" title="Exhibit at CES"><img alt="Exhibit at CES" border="0" name="cesweb_exhibit" onmouseout="out(9)" onmouseover="over(9)" src="/cesweb/media/CESWeb/assets/images/nav/cesweb_exhibit1.png" /></a></div>

                </div>
            </div>
            <div style="display: none;">/followme.asp/exhibitor-directory.asp/cesgreening.asp/registration.asp/searchResults.asp/error404.asp/partners.asp/contactus.asp/sitemap.asp/privacyPolicy.asp/aboutces.asp/myCES.asp/aboutcea.asp</div>
			<div id="nav-bar">
                
	<ul class="level1CMSListMenuUL" id="topnav">
		<li class="level1CMSListMenuLI ExhibitorDirectory" style=""><a href="http://ces13.mapyourshow.com/5_0/search.cfm?" class="level1CMSListMenuLink" style="">Exhibitor Directory</a></li>
		<li class="level1CMSListMenuLI ConferenceProgram"><a href="/Conference-Program.aspx" class="level1CMSListMenuLink">Conference Program</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Conference-Tracks.aspx" class="level2CMSListMenuLink">Conference Tracks</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/SuperSessions.aspx" class="level2CMSListMenuLink">SuperSessions</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Session-Schedule.aspx" class="level2CMSListMenuLink">Session Schedule</a></li>
			<li class="level2CMSListMenuLI" style=""><a href="/Conference-Program/Conference-Pricing.aspx" class="level2CMSListMenuLink" style="">Conference Pricing</a></li>
			<li class="level2CMSListMenuLI"><a href="/Conference-Program/Speaker-Directory.aspx" class="level2CMSListMenuLink">Speaker Directory</a></li>
			<li class="hassub"><a href="/Conference-Program/Call-for-Speakers.aspx" class="level2CMSListMenuLink">Call for Speakers</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI last "><a href="/Conference-Program/Call-for-Speakers/Submission-FAQs.aspx" class="level3CMSListMenuLink">Submission FAQs</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI last "><a href="/Conference-Program/Speaker-Services.aspx" class="level2CMSListMenuLink">Speaker Services</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI Events"><a href="/Events.aspx" class="level1CMSListMenuLink">Events</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Events/Keynotes.aspx" class="level2CMSListMenuLink">Keynotes</a></li>
			<li class="level2CMSListMenuLI" style=""><a href="/Events/CES-Events.aspx" class="level2CMSListMenuLink" style="">CES Events</a></li>
			<li class="level2CMSListMenuLI last " style=""><a href="/Events/Cea-Events.aspx" class="level2CMSListMenuLink" style="">CEA Events</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI Awards"><a href="/Awards.aspx" class="level1CMSListMenuLink">Awards</a>
		<ul class="subnav">
			<li class="hassub"><a href="/Awards/CES-Innovations-Awards.aspx" class="level2CMSListMenuLink">CES Innovations Awards</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/About-Innovations.aspx" class="level3CMSListMenuLink">About Innovations</a></li>
				<li class="level3CMSListMenuLI"><a href="/Awards/CES-Innovations-Awards/2013-innovations-award-judges.aspx" class="level3CMSListMenuLink">2013 Innovations Award Judges</a></li>
				<li class="level3CMSListMenuLI last " style=""><a href="/Awards/CES-Innovations-Awards/2013.aspx" class="level3CMSListMenuLink" style="">2013 Innovations Honorees</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI"><a href="/Awards/IAWTV-Awards.aspx" class="level2CMSListMenuLink">IAWTV Awards</a></li>
			<li class="level2CMSListMenuLI"><a href="/Awards/CNET-Best-Of.aspx" class="level2CMSListMenuLink">CNET Best Of CES</a></li>
			<li class="level2CMSListMenuLI"><a href="/Awards/Hot-Stuff-Awards.aspx" class="level2CMSListMenuLink">2013 CES Hot Stuff Awards </a></li>
			<li class="level2CMSListMenuLI"><a href="/Awards/Stars-of-CES.aspx" class="level2CMSListMenuLink">The 2013 What HI-FI? Sound and Vision Stars of CES </a></li>
			<li class="level2CMSListMenuLI last "><a href="/Awards/Tech-Engineering-Emmy-Awards.aspx" class="level2CMSListMenuLink">Technology &amp; Engineering Emmy&#174; Awards</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI ShowFloor"><a href="/Show-Floor.aspx" class="level1CMSListMenuLink">Show Floor</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/By-Exhibit-Halls.aspx" class="level2CMSListMenuLink">By Exhibit Hall</a></li>
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/By-Product-Category.aspx" class="level2CMSListMenuLink">By Product Category</a></li>
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/CES-TechZones.aspx" class="level2CMSListMenuLink">CES TechZones</a></li>
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/CES-Mobile-App.aspx" class="level2CMSListMenuLink">CES Mobile App</a></li>
			<li class="level2CMSListMenuLI"><a href="/Show-Floor/Show-Floor-Tours.aspx" class="level2CMSListMenuLink">Show Floor Tours </a></li>
			<li class="level2CMSListMenuLI last " style=""><a href="http://www.mapyourshow.com/shows/index.cfm?SHOW_ID=CES13&alt_entry=true&curr_pri=facility&curr_sec=OO" class="level2CMSListMenuLink" style="">Floor Plans</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI HotelTravel"><a href="/Hotel-Travel.aspx" class="level1CMSListMenuLink">Hotel/Travel</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Hotel-Reservations.aspx" class="level2CMSListMenuLink">Hotel Reservations</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/CES-Block-Request-Form.aspx" class="level2CMSListMenuLink">CES Block Request Form</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Airline-Discounts.aspx" class="level2CMSListMenuLink">Airline Discounts</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/CES-Shuttle-Service.aspx" class="level2CMSListMenuLink">CES Shuttle Service</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Las-Vegas-Monorail.aspx" class="level2CMSListMenuLink">Las Vegas Monorail</a></li>
			<li class="level2CMSListMenuLI"><a href="/Hotel-Travel/Transportation,-Parking,-and-Car-Rental.aspx" class="level2CMSListMenuLink">Transportation, Parking, and Car Rental</a></li>
			<li class="level2CMSListMenuLI last "><a href="/Hotel-Travel/Las-Vegas-Travel-Tips.aspx" class="level2CMSListMenuLink">Las Vegas Travel Tips</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI News"><a href="/News.aspx" class="level1CMSListMenuLink">News</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/News/News-Feed.aspx" class="level2CMSListMenuLink">News Feed</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/Exhibitor-Releases.aspx" class="level2CMSListMenuLink">Exhibitor Releases</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/CES-Press-Releases.aspx" class="level2CMSListMenuLink">CES Press Releases</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/Media-Coverage.aspx" class="level2CMSListMenuLink">Media Coverage</a></li>
			<li class="level2CMSListMenuLI"><a href="/News/CES-TV.aspx" class="level2CMSListMenuLink">CES TV</a></li>
			<li class="hassub"><a href="/News/Newsletters.aspx" class="level2CMSListMenuLink">Newsletters</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/News/Newsletters/CES-Up-to-the-Minute.aspx" class="level3CMSListMenuLink">CES Up to the Minute</a></li>
				<li class="level3CMSListMenuLI" style=""><a href="/For-Exhibitors/Exhibitor-Source-Newsletter.aspx" class="level3CMSListMenuLink" style="">Exhibitor&#39;s Source Newsletter</a></li>
				<li class="level3CMSListMenuLI"><a href="/News/Newsletters/Exhibitor-PR-Newsletter.aspx" class="level3CMSListMenuLink">Exhibitor PR Newsletter</a></li>
				<li class="level3CMSListMenuLI last "><a href="/News/Newsletters/CES-Partner-Connection.aspx" class="level3CMSListMenuLink">CES Partner Connection</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI last " style=""><a href="/For-the-Press.aspx" class="level2CMSListMenuLink" style="">Press Services</a></li>
		</ul>
		</li>
		<li class="level1CMSListMenuLI last "><a href="/FAQ.aspx" class="level1CMSListMenuLink">FAQ</a>
		<ul class="subnav">
			<li class="level2CMSListMenuLI"><a href="/FAQ/General.aspx" class="level2CMSListMenuLink">General</a></li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Press.aspx" class="level2CMSListMenuLink">Press</a></li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Exhibitor.aspx" class="level2CMSListMenuLink">Exhibitor</a></li>
			<li class="hassub"><a href="/FAQ/FAQs-by-Venue.aspx" class="level2CMSListMenuLink">FAQs by Venue</a>
			<ul class="subsubnav">
				<li class="level3CMSListMenuLI"><a href="/FAQ/FAQs-by-Venue/Las-Vegas-Convention-Center.aspx" class="level3CMSListMenuLink">Las Vegas Convention Center</a></li>
				<li class="level3CMSListMenuLI"><a href="/FAQ/FAQs-by-Venue/The-Venetian.aspx" class="level3CMSListMenuLink">The Venetian</a></li>
				<li class="level3CMSListMenuLI"><a href="/FAQ/FAQs-by-Venue/Las-Vegas-Hilton.aspx" class="level3CMSListMenuLink">Las Vegas Hotel (LVH)</a></li>
				<li class="level3CMSListMenuLI last "><a href="/FAQ/FAQs-by-Venue/Renaissance-Hotel.aspx" class="level3CMSListMenuLink">Renaissance Hotel</a></li>
			</ul>
			</li>
			<li class="level2CMSListMenuLI"><a href="/FAQ/Speaker.aspx" class="level2CMSListMenuLink">Speaker</a></li>
			<li class="level2CMSListMenuLI last "><a href="/FAQ/First-Timer-ResourCES.aspx" class="level2CMSListMenuLink">First-Timer ResourCES</a></li>
		</ul>
		</li>
	</ul>
        
			    
			</div>
		</div>
	</div>
    <div class="container-home">
    	<div id="main-content"><div id="main-content-header">

  </div><div class="left">
<div class='greenbox-bg'><a href='/For-Exhibitors.aspx'><img src='/cesweb/media/CESWeb/assets/images/nav/cesweb_exhibitors2.png'></a><ul><li class=""><a href="/For-Exhibitors/Contact-Sales-Rep.aspx">Contact Sales Rep</a></li><li class=""><a href="/For-Exhibitors/Exhibit-at-CES.aspx">Exhibit at CES</a></li><li class=""><a href="/For-Exhibitors/Directory-Listing.aspx">Directory Listing</a></li><li class="active"><a href="/For-Exhibitors/Promotional-Opportunities.aspx">Promotional Opportunities</a><ul class='subnav'><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Sponsorships.aspx">Sponsorships</a></li><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/On-site-Advertising.aspx">On-site Advertising</a></li><li class="active hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Print-Advertising.aspx">Print Advertising</a></li><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Targeted-Media-Opportunities.aspx">Targeted Media Opportunities</a></li><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Award-Programs.aspx">Award Programs</a></li><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Direct-Mail-Online-Ads.aspx">Direct Mail/Online Ads</a></li><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Online-Directory-Sponsorships.aspx">Online Directory Sponsorships</a></li><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Speaking-Opportunities.aspx">Speaking Opportunities</a></li><li class=" hassub"><a href="/For-Exhibitors/Promotional-Opportunities/Free-Opportunities.aspx">Free Opportunities</a></li></ul></li><li class=""><a href="/For-Exhibitors/Show-Planning-Exhibitor-Manual.aspx">Show Planning/Exhibitor Manual</a></li><li class=""><a href="/For-Exhibitors/Deadline-Checklist.aspx">Deadline Checklist</a></li><li class=""><a href="/For-Exhibitors/Resources.aspx">Resources</a></li><li class=""><a href="/For-Exhibitors/PR-Help.aspx">PR Help</a></li><li class=" last"><a href="/For-Exhibitors/Exhibitor-Source-Newsletter.aspx">Exhibitor's Source Newsletter</a></li></ul></div><ul id='menu'><li><a class='press' href='/For-The-Press.aspx'></a><ul style='display: none; '><li class=""><a href="/For-The-Press/Exhibitor-Press-Events-Schedule.aspx">Exhibitor Press Events Schedule</a></li><li class=""><a href="/For-The-Press/Press-Events.aspx">Press Events</a></li><li class=""><a href="/For-The-Press/Press-Contacts.aspx">Press Contacts</a></li><li class=""><a href="/For-The-Press/Press-Services.aspx">Press Services</a></li><li class=""><a href="/For-The-Press/Image-Gallery.aspx">Image Gallery</a></li><li class=""><a href="/For-The-Press/International-Press-Visa-Information.aspx">International Press Visa Information</a></li><li class=""><a href="/News.aspx" >News</a></li><li class=" last"><a href="/For-The-Press/CES-B-roll.aspx">CES B-roll</a></li></ul></li><li><a class='international' href='/For-International-Visitors.aspx'></a><ul style='display: none; '><li class=""><a href="/For-International-Visitors/Travel-Visa.aspx">Travel & Visa</a></li><li class=""><a href="/For-International-Visitors/Hotel-Reservations.aspx">Hotel Reservations</a></li><li class=""><a href="/For-International-Visitors/Delegation-Group-Program.aspx">Delegation Group Program</a></li><li class=""><a href="/For-International-Visitors/International-Services.aspx">International Services</a></li><li class=""><a href="/For-International-Visitors/CES-Shuttle-Service.aspx">CES Shuttle Service</a></li><li class=""><a href="http://www.cesweb.org/FAQ/First-Timer-ResourCES.aspx" target="_blank">First Time Attendee Resources</a></li><li class=""><a href="/For-International-Visitors/Spanish.aspx">Español</a></li><li class=""><a href="/For-International-Visitors/French.aspx">Français</a></li><li class=""><a href="/For-International-Visitors/chinese.aspx">汉语</a></li><li class=""><a href="/For-International-Visitors/japanese.aspx">日本語</a></li><li class=" last"><a href="/For-International-Visitors/Korean.aspx">한국어</a></li></ul></li></ul>

<div id="connect-with-us">
	<img src="/cesweb/media/CESWeb/assets/images/tabs/cesweb_socialmediatab.png" />
	<div class="icon-wrap">
		<a href="/Twitter.aspx" target="_blank"><img alt="Twitter" src="/cesweb/media/CESWeb/assets/images/social/sub_twitter.png" /></a> <a href="/Facebook.aspx" target="_blank"><img alt="facebook" src="/cesweb/media/CESWeb/assets/images/social/sub_facebook.png" /></a> <a href="https://plus.google.com/b/114786898916421737866/114786898916421737866/" target="_blank"><img alt="Google+" src="/getmedia/aee9322f-1872-46c3-8e44-71b980028a49/CES-870-Google-logo_24x24.aspx?width=22&amp;height=22" style="width: 22px; height: 22px;" /></a> <a href="/Flickr.aspx" target="_blank"><img alt="flickr" src="/cesweb/media/CESWeb/assets/images/social/sub_flickr.png" /></a> <a href="/YouTube.aspx" target="_blank"><img alt="youtube" src="/cesweb/media/CESWeb/assets/images/social/sub_youtube.png" /></a> <a href="/LinkedIn.aspx" target="_blank"><img alt="linkedin" src="/cesweb/media/CESWeb/assets/images/social/sub_linkedin.png" /></a> <a href="/News/News-Feed.aspx" target="_blank"><img alt="rss" src="/cesweb/media/CESWeb/assets/images/social/sub_rss.png" /></a></div>
</div>
<br />
</div><div class="right">
        <div id="breadcrumb">
<ul id="breadcrumbs"><li class='home'><a href='/'>Home</a></li><li class='promotional-opportunities'><a href='/For-Exhibitors/Promotional-Opportunities.aspx'>Promotional ...</a></li><li class='print-advertising end'><a href='/For-Exhibitors/Promotional-Opportunities/Print-Advertising.aspx'>Print Advertising</a></li></ul>

</div>
<div id="inner-content-long">
 
<div class="headerbox">
      <h1>Print Advertising</h1>
</div>
Reach tech-savvy CE industry movers who read the leading trade publications and are anxious to plan for the International CES. Editorial calendars fill quickly, and space runs out. Reserve your space today.<br />

<a name="#Top">&nbsp;</a>
<div style="color: #233c82; font-size: 1.4em; padding-bottom: 10px;"><strong>&gt;&nbsp;On this page:</strong></div>
<div class="onThisPageItem">
    <a href="#71">It is Innovation (i3)- Official Publication of CEA, Producer of CES</a>
</div><div class="onThisPageItem">
    <a href="#43">International CES Official Show Guide & Conference Brochure</a>
</div><div class="onThisPageItem">
    <a href="#10">CES Daily — The Official Daily of the Show </a>
</div><div class="onThisPageItem">
    <a href="#42">International CES Official Show Directory</a>
</div><div class="onThisPageItem">
    <a href="#45">CES Digital Imaging/Photography Daily</a>
</div><div class="onThisPageItem">
    <a href="#46">Entertainment Matters Daily, produced by Variety</a>
</div><div class="onThisPageItem">
    <a href="#9">International CES Preshow Planner</a>
</div><div class="onThisPageItem">
    <a href="#44">CES Digital Imaging/Photography Preshow Planner</a>
</div>
<div style="clear: both; padding-bottom: 20px;"></div><div style="margin-top: 50px; clear: both;" ></div>

<hr />
<a name="71">&nbsp;</a>
<div class="sponsorshipTitle">It is Innovation (i3)- Official Publication of CEA, Producer of CES:&nbsp;<span class="lt_blue">Call for details</span></div>
<br />
What better way to attract publicity than to advertise in the inaugural edition of the Consumer Electronics Association&rsquo;s (CEA) &reg; new magazine, It is Innovation (i<strong><em><sup>3</sup></em></strong>).<br />
<br />
i<strong><em><sup>3</sup></em></strong> will showcase all aspects of innovation in technology, policy, business and engineering in the consumer technology industry. It is Innovation (i<strong><em><sup>3</sup></em></strong>) will lauch at the 2013 International CES in January. Gain exposure with those who care about innovation the most, attendees at the 2013 CES. As the official publication of CEA, i<strong><em><sup>3</sup></em></strong>has exclusive distribution to areas of the show that no other publication receives, including 3,000 exhibitor booths, pub bins, CEA lounges, executive suites, the press room, the VIP lunchroom, CES Unveiled and the Innovations Award Showcase.<br />
&nbsp;<br />
Ad Close: November 30<br />
Materials Due: December 7

<div style='float: right;'><img src='/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/i3_red.jpg' alt='It is Innovation (i3)- Official Publication of CEA, Producer of CES'/></div>

<p></p>
<p></p>
<strong>contact</strong><br />Dan Cole&nbsp;<br />Phone:&nbsp;703-907-7987<br />Email:&nbsp;<a href="mailto:dcole@CE.org">dcole@CE.org</a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    <hr />
<a name="43">&nbsp;</a>
<div class="sponsorshipTitle">International CES Official Show Guide & Conference Brochure:&nbsp;<span class="lt_blue">Call for details</span></div>
<br />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">International CES attendees find the&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Official Show Guide &amp; Conference Brochure</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;to be the most critical tool to navigate the show, conferences and special events. The&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Official Show Guide &amp; Conference Brochure</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;contains listings of all events and awards, TechZones, show services, international services, hotel/travel/transportation information, the most up-to-date exhibitor listing and a full conference brochure for attendees on-the-move. Ask about package ad deals with the&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Official Show Dir</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">ectory, on-site show maps and&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Preshow Planner</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">, all custom-published by the Consumer Technology Publishing Group, publisher of&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Dealerscope</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">,</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">CustomRetailer</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">,&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Tell: Technology For Everyday Life</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">,&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Photo Industry Reporter</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;and&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Home Furnishings Business</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;magazines. &nbsp;</span><br />
<br />
<strong style="text-align: left; background-color: rgb(255, 255, 255); "><img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CEs_PrintAdvertising_ShowGuide.jpg" style="width: 114px; height: 160px; float: left; " />&nbsp; Deadlines</strong><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Ad closing: November&nbsp;26</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Tab Ad Closing: November&nbsp;26</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Materials due:&nbsp;November&nbsp;29</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Distributed: On-site</span><br />
<br />
<br />
<br />
<img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_CTPG_logo.gif" style="width: 150px; height: 24px; float: left; " /><br style="text-align: left; background-color: rgb(255, 255, 255); " />




<p></p>
<p></p>
<strong>contact</strong><br />Rick Albuck&nbsp;<br />Phone:&nbsp;215-238-5215<br />Email:&nbsp;<a href="mailto:rickalbuck@napco.com ">rickalbuck@napco.com </a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    <hr />
<a name="10">&nbsp;</a>
<div class="sponsorshipTitle">CES Daily — The Official Daily of the Show :&nbsp;<span class="lt_blue">Call for Details</span></div>
<br />
<p style="text-align: left; background-color: rgb(255, 255, 255); ">
	Want traffic at your CES booth? Then advertising in the&nbsp;<em>Official CES Daily &mdash; produced by TWICE</em>&nbsp;&mdash; is the way to go (4 issues &mdash; one low price). For year buyers have relied on the&nbsp;<em>Official CES Daily</em>&nbsp;to point the way, and with over 3,000 exhibitors, it makes great business sense to let them know what you&rsquo;re selling &mdash; and why to visit your booth. Written by the editors of&nbsp;<em>TWICE</em>, the industry publication of record, the Official CES Dailies cover news, new products, general show information &mdash; and more. And with an enormous distribution consisting of room-to-room at many Las Vegas hotels, on busses, in bins, model hand-outs, and on-line too, these dailies are not only seen, but utilized in a very big way helping attendees navigate the show.&nbsp; So call or email for details &mdash; and discounted Official CES Daily/TWICE Show Packages.&nbsp;<strong><em>Offi</em></strong><strong><em>cial CES Daily</em>&nbsp;Issue Dates: January 8, 9,&nbsp;10 and 11.</strong></p>
<p style="text-align: left; background-color: rgb(255, 255, 255); ">
	<br />
	<strong><img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_Twice_120pw.jpg" style="width: 120px; height: 131px; float: left; " /></strong></p>
<div>
	<strong style="text-align: left; background-color: rgb(255, 255, 255); ">De</strong><strong style="text-align: left; background-color: rgb(255, 255, 255); ">adli</strong><strong style="text-align: left; background-color: rgb(255, 255, 255); ">n</strong><strong style="text-align: left; background-color: rgb(255, 255, 255); ">es</strong></div>
<div>
	<span style="text-align: left; background-color: rgb(255, 255, 255); ">Ad Closing:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; November 23, 2012</span><br />
	<br style="text-align: left; background-color: rgb(255, 255, 255); " />
	<span style="text-align: left; background-color: rgb(255, 255, 255); ">Ad Material due:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;December 3, 2012</span><br />
	<br />
	<br />
	<br />
	<br />
	<table style="text-align: left; background-color: rgb(255, 255, 255); width: 529px; height: 112px; ">
		<tbody>
			<tr>
				<td>
					<p style="margin: 0in 0in 0pt; ">
						<strong>Midwest/West Coast:</strong></p>
					<p style="margin: 0in 0in 0pt; ">
						Tony Monteleone<br />
						Associate Publisher<br />
						Phone: 917-281-4742<br />
						<a href="mailto:tmonteleone@nbmedia.com">tmonteleone@nbmedia.com</a></p>
				</td>
				<td>
					<br />
					<strong>East Coast:</strong><br />
					Marcia Grand<br />
					VP/Publisher<br />
					Phone: 917-281-4724<br />
					<a href="mailto:mgrand@nbmedia.com">mgrand@nbmedia.com</a><br />
					&nbsp;</td>
			</tr>
		</tbody>
	</table>
</div>
<br />




<p></p>
<p></p>
<strong>contact</strong><br />Tony Monteleone, Midwest/West Coast Associate Publisher&nbsp;<br />Phone:&nbsp;Phone: 917-281-4742<br />Email:&nbsp;<a href="mailto:tmonteleone@nbmedia.com">tmonteleone@nbmedia.com</a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    <hr />
<a name="42">&nbsp;</a>
<div class="sponsorshipTitle">International CES Official Show Directory:&nbsp;<span class="lt_blue">Call for details</span></div>
<br />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">The&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Official Show Directory</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;is the ultimate reference guide for the International CES. The only year-round reference source, the directory lists complete exhibitor company profiles, brand listings and important product information. Ads are prominently placed and bring results-even after the show is over. Ask about packages with the&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Official</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Show Guide &amp; Conference Brochure,</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;on-site show maps and the&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Preshow Planner</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">, custom published by the Consumer Technology Publishing Group, publisher of&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Dealerscope</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">,</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">CustomRetailer</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">,&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Tell: Technology For Everyday Life</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">,&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Photo Industry Report</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">er and&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Home Furnishings Business</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;magazines. Include your company logo in the printed version of the&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Official Show Directory</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;for $625.</span><strong style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;&nbsp;</strong><br />
<br />
<strong style="text-align: left; background-color: rgb(255, 255, 255); "><img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_ShowDirectory.jpg" style="width: 114px; height: 160px; float: left; " />&nbsp; Deadlines</strong><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Ad closing: November&nbsp;21</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Materials due: November&nbsp;28</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Tab ad closing: November&nbsp;14</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;&nbsp;Tab materials due: November&nbsp;15</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Distributed: On-site&nbsp;</span><br />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Deadline to include logos in Directory: November 28</span><br />
<br />
<img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_CTPG_logo.gif" style="width: 150px; height: 24px; float: left; " /><br />
<br />
<br />
<br />
<br />
<br />




<p></p>
<p></p>
<strong>contact</strong><br />Rick Albuck&nbsp;<br />Phone:&nbsp;215-238-5215<br />Email:&nbsp;<a href="mailto:rickalbuck@napco.com ">rickalbuck@napco.com </a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    <hr />
<a name="45">&nbsp;</a>
<div class="sponsorshipTitle">CES Digital Imaging/Photography Daily:&nbsp;<span class="lt_blue">Call for details</span></div>
<br />
<p style="text-align: left; background-color: rgb(255, 255, 255); ">
	With PMA now part of CES, promote your organization and drive booth traffic with an ad in the new&nbsp;<em>Official CES Digital Imaging/Photography Daily</em>, produced by&nbsp;<em>Photo Industry Reporter</em>. This publication will be focused specifically on imaging, and feature show information, the latest breaking news and industry information, and will be distributed throughout CES. Magazine distribution will occur on-site in numerous high-traffic locations throughout CES, as well as distributed to official PMA-designated hotels each morning of Jan. 10-12.</p>
<div>
	<br />
	<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;<img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_ShowDaily.jpg" style="width: 114px; height: 160px; float: left; " />&nbsp;</span><strong style="text-align: left; background-color: rgb(255, 255, 255); ">Deadlines</strong><br style="text-align: left; background-color: rgb(255, 255, 255); " />
	<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Ad closing: December 3</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
	<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Materials due: December 12</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
	<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp; Distributed: CES</span></div>




<p></p>
<p></p>
<strong>contact</strong><br />Alan Levine&nbsp;<br />Phone:&nbsp;516-364-0503<br />Email:&nbsp;<a href="mailto:alevine@photoreporter.com">alevine@photoreporter.com</a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    <hr />
<a name="46">&nbsp;</a>
<div class="sponsorshipTitle">Entertainment Matters Daily, produced by Variety:&nbsp;<span class="lt_blue">Call for details</span></div>
<br />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">Variety, the leading entertainment trade magazine, will be producing printed dailies for CES dedicated to Entertainment Matters programming, news, events, announcements and special features. The most influential leaders in the industry have turned to Variety for timely, credible and straight-forward news and analysis vital to their professions. Now they will have first-hand access at the most important news and announcements impacting the entertainment industry at CES!</span>
<ul class="text" style="text-align: left; background-color: rgb(255, 255, 255); ">
	<li cass="text">
		Distribution will be extensive throughout the show via pub bins and models at key distribution points</li>
	<li class="text" style="list-style-image: url(http://www.cesweb.org/images/framework/small_bullet-text.gif); ">
		Advertising is available - front cover and premium spots as well as standard ad units in book</li>
	<li class="text" style="list-style-image: url(http://www.cesweb.org/images/framework/small_bullet-text.gif); ">
		10,000 copies will be distributed each day of the show</li>
	<li class="text" style="list-style-image: url(http://www.cesweb.org/images/framework/small_bullet-text.gif); ">
		In addition the printed dailies on-site at CES, over 27,000 Variety subscribers will have access to view the digital editions on-line<br />
		<br />
		<div>
			Advertising is available - front cover and premium spots as well as standard ad units in book</div>
		<div>
			&nbsp;</div>
		<br />
		<strong><img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CEs_PrintAdvertising_VarietyFinalCover.jpg" style="width: 127px; height: 160px; float: left; " />&nbsp;Deadlines</strong><br />
		&nbsp;Ad closing: Call for details<br />
		&nbsp;Materials due: Call for details<br />
		&nbsp;Distributed: CES</li>
</ul>




<p></p>
<p></p>
<strong>contact</strong><br />Linda Buckley-Bruno, Publishing Director, Variety&nbsp;<br />Phone:&nbsp;323-617-9429<br />Email:&nbsp;<a href="mailto:Linda.buckley@variety.com">Linda.buckley@variety.com</a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    <hr />
<a name="9">&nbsp;</a>
<div class="sponsorshipTitle">International CES Preshow Planner:&nbsp;<span class="lt_blue">Call for details</span></div>
<br />
<p style="text-align: left; background-color: rgb(255, 255, 255); ">
	The&nbsp;<em>Official Preshow Planner</em>&nbsp;is the most complete guide to planning packed days at CES. Produced by the Consumer Technology Publishing Group, publisher of&nbsp;<em>Dealerscope</em>,&nbsp;<em>CustomRetailer</em>,&nbsp;<em>Tell: Technology For Everyday Life</em>,&nbsp;<em>Photo Industry Reporter</em>&nbsp;and<em>Home Furnishings Business</em>&nbsp;magazines, the&nbsp;<em>Preshow Planner</em>&nbsp;is mailed in early December to domestic, pre-registered CES attendees and is also sent as an interactive digital magazine to over 35,000 international attendees in 150 countries. This is THE place to get an early start on reaching attendees before they arrive. Call now to reserve ad space. Ask about package ad deals with the&nbsp;<em>Official Show Directory</em>&nbsp;and the&nbsp;<em>Official Show Guide &amp; Conference Brochure</em>.</p>
<p style="text-align: left; background-color: rgb(255, 255, 255); ">
	<strong><img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_Preshowplanner.jpg" style="width: 114px; height: 160px; float: left; " />&nbsp; &nbsp;Deadlines</strong><br />
	&nbsp;&nbsp; Ad closing: October&nbsp;25 (closed)<br />
	&nbsp;&nbsp; Materials due: November&nbsp;1<br />
	&nbsp;&nbsp; Distributed: Early December<br />
	&nbsp;</p>
<div style="text-align: left;">
	<br />
	<br />
	<img alt="" src="http://staging.cesweb.org/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_CTPG_logo.gif" style="width: 150px; height: 24px; float: left; " /><br />
	<br />
	&nbsp;</div>




<p></p>
<p></p>
<strong>contact</strong><br />Rick Albuck&nbsp;<br />Phone:&nbsp;215-238-5215<br />Email:&nbsp;<a href="mailto:rickalbuck@napco.com ">rickalbuck@napco.com </a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    <hr />
<a name="44">&nbsp;</a>
<div class="sponsorshipTitle">CES Digital Imaging/Photography Preshow Planner:&nbsp;<span class="lt_blue">Call for details</span></div>
<br />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">Place your company&#39;s sales message in front of digital imaging/photography attendees before they step foot on the show floor by utilizing the first-ever&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Official CES Digital Imaging/Photography Preshow Planner</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">, produced by Dealerscope. This new publication will help attendees plan their trip to CES with digital imaging specific content about the show. Distributed along with the December issue of&nbsp;</span><em style="text-align: left; background-color: rgb(255, 255, 255); ">Photo Industry Reporter</em><span style="text-align: left; background-color: rgb(255, 255, 255); ">, it will reach attendees just as they are making their show plans. This publication is especially useful, as PMA@CES is an integral part of the show, creating a new experience for the exhibitors and attendees.&nbsp;</span><br />
<br />
<strong style="text-align: left; background-color: rgb(255, 255, 255); "><img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_pre-show-planner.jpg" style="width: 114px; height: 160px; float: left; " />&nbsp;Deadlines</strong><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;Ad closing: October 26</span> (closed)<br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;Materials due: November 9</span><br style="text-align: left; background-color: rgb(255, 255, 255); " />
<span style="text-align: left; background-color: rgb(255, 255, 255); ">&nbsp;Distributed: Early December</span><br />
<br />
<br />
<br />
<br />
<img alt="" src="/cesweb/media/CESWeb/Promo%20Opps/Print%20Advertising/CES_PrintAdvertising_CTPG_logo.gif" style="width: 150px; height: 24px;" />



<p></p>
<p></p>
<strong>contact</strong><br />Rick Albuck&nbsp;<br />Phone:&nbsp;215-238-5215<br />Email:&nbsp;<a href="mailto:rickalbuck@napco.com ">rickalbuck@napco.com </a>
<div style="padding: 25px 0 25px 0;"><a class="back_to_top" href="#">[back to top]</a></div>
    

&nbsp;</div>
</div>
</div>

        
    </div>
    <div id="sitelinks">
        <div>
	<a href="/News/News-Feed.aspx"><img alt="CES NEWS" src="/cesweb/media/CESWeb/assets/images/footer/footer_cesnews.png" /></a>
	<ul>
		<li>
			<a href="/News/News-Feed.aspx">Sign up for RSS news feeds</a></li>
		<li>
			<a href="/Facebook.aspx">Follow CES on Facebook</a></li>
		<li>
			<a href="/News/News-Feed.aspx">See all the latest CES news</a></li>
	</ul>
</div>
<div>
	<a href="/Conference-Program.aspx"><img alt="SESSION HIGHLIGHTS" src="/cesweb/media/CESWeb/assets/images/footer/footer_confprog.png" /></a>
	<ul>
		<li>
			<a href="/Conference-Program.aspx">Conference program revealed Oct. 1</a></li>
		<li>
			<a href="/Conference-Program/Speaker-Services.aspx">See services CES provides its speakers</a></li>
		<li>
			<a href="/News/Multimedia-Gallery.aspx">Watch session videos from the most recent CES</a></li>
	</ul>
</div>
<div>
	<a href="/Events/Cea-Events.aspx"><img alt="EVENTS &amp; AWARDS" src="/cesweb/media/CESWeb/assets/images/footer/footer_eventsawards.png" /> </a>
	<ul>
		<li>
			<a href="/Events/Keynotes.aspx">See developing keynote lineup</a></li>
		<li>
			<a href="/Events/Cea-Events.aspx">See CEA&#39;s calendar of events</a></li>
		<li>
			<a href="/Awards/CES-Innovations-Awards.aspx">Innovations honorees on cutting-edge of engineering</a></li>
	</ul>
</div>
<div class="importantend">
	<a href="/Hotel-Travel.aspx"><img alt="HOTEL &amp; TRAVEL" src="/cesweb/media/CESWeb/assets/images/footer/footer_hoteltravel.png" /> </a>
	<ul>
		<li>
			<a href="/Hotel-Travel/Hotel-Reservations.aspx">Vegas hotels offer discounts for CES attendees</a></li>
		<li>
			<a href="/Hotel-Travel/CES-Shuttle-Service.aspx">CES offers free shuttle service all four days of show</a></li>
		<li>
			<a href="/Hotel-Travel/Las-Vegas-Travel-Tips.aspx">CES offers travel trips</a></li>
	</ul>
</div>
<br />

    </div>
</div> 
<div id="footer-home">
    <div id="footer_nav-home">
        <a href="/About-CES.aspx">About CES</a><span>|</span> <a href="/About-CEA.aspx">About CEA</a><span>|</span> <a href="/News/News-Feed.aspx">RSS News</a><span>|</span> <a href="/MyCES.aspx">MyCES</a><span>|</span> <a href="/Contact-Us.aspx">Contact Us</a><span>|</span> <a href="/Site-Map.aspx">Site Map</a><span>|</span> <a href="/Privacy-Policy.aspx">Privacy Policy</a><span>|</span> <a href="/Partners.aspx">Partners</a>&nbsp;
       
    </div>
    <div id="copyright-home">
    Copyright &copy; 2003 - 2012 CEA. All rights reserved.
    </div>
    
    <a target="_blank" href="http://www.CE.org"><img id="p_lt_footerLogoZone_EditableImage2_imgImage" src="/cesweb/media/CESWeb/assets/images/footer/cesweb_footerlogo.png" alt="" /></a>
</div>
<script type="text/javascript">
setTimeout(function(){var a=document.createElement("script");
var b=document.getElementsByTagName("script")[0];
a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0013/2569.js?"+Math.floor(new Date().getTime()/3600000);
a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

    
    

<script type="text/javascript">
//<![CDATA[
(function() {var fn = function() {$get("manScript_HiddenField").value = '';Sys.Application.remove_init(fn);};Sys.Application.add_init(fn);})();//]]>
</script>
</form>
</body>
</html>
