document.write('<div id="menu1" onmouseover="menuon(1)" onmouseout="menuoff(1)">');
document.write('<div class="submenu" id="submenu1">');
document.write('<ul class="sub">');
document.write('<li><a href="../attendee_info/index.html" >개최 개요</a></li>');
document.write('<li><a href="../attendee_info/floor.html" >Floor Plans</a></li>');
document.write('<li><a href="../attendee_info/exhibitors.html" >출품 회사 명단</a></li>');
document.write('<li><a href="../attendee_info/event.html" >행사</a></li>');
document.write('<li><a href="../attendee_info/forum.html" >TGS Forum</a></li>');
document.write('<li><a href="../attendee_info/matchup.html" >BizMatchups</a></li>');
document.write('<li><a href="../attendee_info/admission.html" >입장요금</a></li>');
document.write('<li><a href="../attendee_info/travel.html" >Travel</a></li>');
document.write('</ul>');
document.write('</div><!--div.submenu-->');
document.write('</div>');
document.write('<div id="menu2" onmouseover="menuon(2)" onmouseout="menuoff(2)">');
document.write('<div class="submenu_2" id="submenu2">');
document.write('<ul class="sub">');
document.write('<li><a href="../media/index.html">News Release</a></li>');
document.write('<li><a href="../media/registration.html" >Registration</a></li>');
document.write('<li><a href="../media/news.html" >Exhibitor\'s　release</a></li>');
document.write('<li><a href="https://www.filey.jp/tgs/"  target="_blank">Download Center</a></li>');
document.write('</ul>');
document.write('</div><!--div.submenu-->');
document.write('</div>');
document.write('<div id="menu3" onmouseover="menuon(3)" onmouseout="menuoff(3)">');
document.write('<div class="submenu_3" id="submenu3">');
document.write('<ul class="sub">');
document.write('<li><a href="../exhibitor/index.html">Overview</a></li>');
document.write('<li><a href="../exhibitor/report.html" >2006 Report</a></li>');
document.write('</ul>');
document.write('</div><!--div.submenu-->');
