document.write('<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"');
document.write('codebase="http://fpdownload.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0" width="543" height="336" align="middle">');
document.write('<param name="allowScriptAccess" value="sameDomain" />');
document.write('<param name="movie" value="main_en.swf" />');
document.write('<param name="quality" value="high" />');
document.write('<param name="bgcolor" value="#ffffff" />');
document.write('<param name="wmode" value="transparent" />');
document.write('<embed src="main_en.swf" quality="high" width="543" height="336" name="main" align="middle"');
document.write('allowscriptaccess="sameDomain" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" wmode="transparent" />');
document.write('</object>');