<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><!-- PageID 337 - generated by RedDot 5.6 - 5.6.0.25 - Y-9bp -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!-- INSERT PAGE TITLE HERE (immediately following gblPAGE_TITLE) -->
<title>2005 International CES:&nbsp;</title>

<!-- INSERT SEARCH ZONE HERE -->
 <META NAME="searchZone" CONTENT="generalCESweb">
<link rel="StyleSheet" href="/print/global_includes/js/mainMethod.css" type="text/css">
<LINK REL="SHORTCUT ICON" HREF="http://www.easymovement.com/ces/favicon.ico">
<!-- Browser detection script -->
    <script src="/print/global_includes/js/browser_detection.js" type="text/javascript"></script>
<SCRIPT language="javascript1.2">
    function newWin(urlString,pgNum) {
        var popupWindow;
        urlString += "?pageID=" + pgNum;
 
        popupWindow = window.open(urlString,"","toolbar=yes,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=550,width=618,left=50,top=50");
    }  
 
    function openNewWindow(strURL) {
        window.name = "main";
        var newWindow = window.open(strURL,"newWindow", "toolbar=no,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=400,width=450,left=50,top=50");
    }
    // Script for e-mail this page - gets the url of the page the user is on before the e-mail page tool button is clicked
    function loadReferrer() {
        referrerString = opener.document.location.href;
        document.emailForm.page.value = referrerString;
    }
</SCRIPT>
<!-- Rollover script (do we still need these?) --> 
<script language="javascript1.2"> 
    /* for graphical rollovers */
   function rollOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function rollOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function introllOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function introllOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function snrollOver(which,name) 
    {
    var on="/global_images/1.0/1.0" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function snrollOff(which) 
    {
    var on="/global_images/1.0/1.0" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
        
    //do we still need this?   
    function onLoadHandler() {
       if( typeof(bodyOnLoadFunction) != 'undefined' ) {
           return eval(bodyOnLoadFunction);
       }
    }
</script>
<script language="javascript">
    <!--
    var activeNavId=0;
    var thisPageUrl='/attendees/travel/rd_block_request.asp';
    
        var parentLinks=new Array('dummy','/print/attendees/default.htm','/print/attendees/travel/default.asp');
    
        function checkActiveNav(theUrl) {
            var linkUrl=theUrl;
            var returnValue=false;
            
            if (linkUrl==thisPageUrl) {
                returnValue=true;
            } else if (parentLinks.length>2 && linkUrl==parentLinks[parentLinks.length-1]) {
                returnValue=true;   
            } else if (parentLinks.length>3 && linkUrl==parentLinks[parentLinks.length-2]) {
                returnValue=true;
            } else if (parentLinks.length>4 && linkUrl==parentLinks[parentLinks.length-3]) {
                returnValue=true;
            }
        return returnValue;
    }
    //-->
    </script>
    <style>
        <!--
            .attendeesBGImg {
                background-image: url('/print/global_images2005/attendees_bg.gif');
            }
            .text_colored, .intro_copy, .section_title, .subhead, .body_title, .intro_dates, .box10 {
               color: #498429;
            }
            
        //-->
    </style>
</head>
<body leftmargin='0' topmargin='0' rightmargin='0' bottommargin='0' marginwidth='0' onLoad="onLoadHandler();self.focus();"> 
<div style="position:absolute; top: 15; left: 15" ><a href='javascript:;' onClick='window.print();return false'><img src="/print/global_images2005/print.jpg" width="115" height="20" border="0" alt=""></a></div>
<IMG SRC="/print/global_images2005/attPrintBanner.jpg" width="601" BORDER="0" vspace=0><br><table width="600" cellspacing="0" cellpadding="0" border="0">
    <tr>
<!-- /left column -->

<!-- main body content -->    
    <td width="10" class="attendees7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="100%" class="attendees7" valign="top">
    <img src="/print/global_images2005/spacer.gif" height="10" width="1"><br>
<!-- center content -->

<div class="body_title">Room Block Request<br><img src="/print/global_images2005/spacer.gif" height="16" width="1"></div>


<SCRIPT language="javascript1.2">
function newWin(urlString,pgNum)
  {
    var popupWindow;
	urlString += "?pageID=" + pgNum;
	
    popupWindow = window.open(urlString,"","toolbar=yes,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=550,width=610,left=50,top=50");
  }//  function for opening a new pop-up window for printing a page
  
 
function openNewWindow(strURL) {
	window.name = "main";
	
	var newWindow = window.open(strURL,"newWindow", "toolbar=no,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=400,width=450,left=50,top=50");
} //  function for opening a new pop-up window

// javascript for e-mail this page tool - gets the url of the page the user is on before the e-mail page tool button is clicked
	
	function loadReferrer() {
		referrerString = opener.document.location.href;
		document.emailForm.page.value = referrerString;
	}

</SCRIPT>

	<script language="JavaScript" src="/attendees/travel/include/js/calendar2.js"></script>
	<script>

function validForm(passedForm)
	{
		if (passedForm.first_name.value == "")
			{	
			alert("Please enter your first name.");
			passedForm.first_name.focus();
			return false
			}
		if (passedForm.last_name.value == "")
			{	
			alert("Please enter your last name.");
			passedForm.last_name.focus();
			return false
			}
		if (passedForm.company.value == "")
			{	
			alert("Please enter the name of your company.");
			passedForm.company.focus();
			return false
			}
		if (passedForm.email.value == "")
			{	
			alert("Please enter your e-mail address.");
			passedForm.email.focus();
			return false
			}
		if (checkemail(passedForm.email.value)==false)
			{				
				passedForm.email.focus();
				return false;
			}
			
		// set var radio_choice to false
		var radio_choice = false;
		
		// Loop from zero to the one minus the number of radio button selections
		for (counter = 0; counter < passedForm.hotel.length; counter++)
		{
		// If a radio button has been selected it will return true
		// (If not it will return false)
		if (passedForm.hotel[counter].checked)
		radio_choice = true; 
		}
		
		if (!radio_choice)
		{
		// If there were no selections made display an alert box 
		alert("Please select a hotel.")
		return (false);
		}
		
		if (passedForm.input6.value == "")
			{	
			alert("Please enter the check-in date for your room block.");
			passedForm.input6.focus();
			return false;
			}
			
		if (passedForm.input7.value == "")
			{	
			alert("Please enter the check-out date for your room block.");
			passedForm.input7.focus();
			return false;
			}
		///////////////////////////////
		if(passedForm.input7.value.length == 10){
		var month, day, year
		month=passedForm.input7.value.charAt(0)
		month=month+passedForm.input7.value.charAt(1)
		day=passedForm.input7.value.charAt(3)
		day=day+passedForm.input7.value.charAt(4)
		year=passedForm.input7.value.charAt(6)
		year=year+passedForm.input7.value.charAt(7)
		year=year+passedForm.input7.value.charAt(8)
		year=year+passedForm.input7.value.charAt(9)
		
		if((year != "2004") && (year != "2005")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input7.focus
		return false
		}
	
		if((year=="2004")&&(month != "12")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input7.focus
		return false
		}		
			
		if((year=="2004")&&(month == "12")&& (day < "26")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input7.focus
		return false
		}
		
		if((year=="2005")&&(month != "01")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input7.focus
		return false
		}		
			
		if((year=="2005")&&(month == "01")&& (day > "14")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input7.focus
		return false
		}
		}
		
		if(passedForm.input6.value.length == 10){
		var month, day, year
		month=passedForm.input6.value.charAt(0)
		month=month+passedForm.input6.value.charAt(1)
		day=passedForm.input6.value.charAt(3)
		day=day+passedForm.input6.value.charAt(4)
		year=passedForm.input6.value.charAt(6)
		year=year+passedForm.input6.value.charAt(7)
		year=year+passedForm.input6.value.charAt(8)
		year=year+passedForm.input6.value.charAt(9)
		
		if((year != "2004")&& (year != "2005")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input6.focus
		return false
		}
	
		if((year=="2004")&&(month != "12")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input6.focus
		return false
		}		
			
		if((year=="2004")&&(month == "12")&& (day < "26")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input6.focus
		return false
		}
		
		if((year=="2005")&&(month != "01")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input6.focus
		return false
		}		
			
		if((year=="2005")&&(month == "01")&& (day > "14")){
		alert("Your requested dates must be between 12/26/04 and 1/14/05.")
		passedForm.input6.focus
		return false
		}
		}
		//////////////////////////////
		
		if (passedForm.number_of_rooms.value == "")
			{	
			alert("Please enter the maximum number of rooms needed on your night of highest occupancy.");
			passedForm.number_of_rooms.focus();
			return false;
			}
		if (numbercheck(passedForm.number_of_rooms.value)==false)
			{
			passedForm.number_of_rooms.focus();
			return false;
			}
	
		var stringSpaceReqs = passedForm.space_reqs.value;
		var SpaceReqsCharCount = stringSpaceReqs.length;

		if (SpaceReqsCharCount > 250) {
			alert ("Please limit the explanation of additional space requirements to 250 characters (including spaces).");
			passedForm.space_reqs.focus();
			return false;
		}

		var stringRequests = passedForm.requests.value;
		var RequestsCharCount = stringRequests.length;

		if (RequestsCharCount > 250) {
			alert ("Please limit the explanation of other special requests to 250 characters (including spaces).");
			passedForm.number_of_rooms.focus();
			return false;
		}
		
	}
	
	function numbercheck (myvalue){
	var inputValue = parseInt(myvalue) 	
	if (isNaN(inputValue))	
		 {
			alert("Please enter a numeric value for max number of rooms requested.");
			return false;
		 }
	else
	     {
	        return true;
	     }
	}

	/*
	function checkemail(myEmail){
	var str= myEmail
	var filter=/^([\w-]+(?:\.[\w-]+)*)@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$/i
	if (filter.test(str))
		return true;
	else
		{
		alert("Please enter a valid email address.")
		return false;
		}	
	}*/
	</script>


<div>	
<!-- text for main page -->

<span class="subhead">Request a group block with a simple three-step process!</span>
<ol>
<li>If you require 10 rooms or more, use this form to submit your request to a participating International CES hotel.
<li>The hotel will respond to you within three business days regarding rates and availability.
<li>The hotel will give you a deadline date as to when you must commit to these rooms and sign a contract with them.	
</ol>
<br>
This request form delivers group block rates and availability. <b>You are under no obligation to confirm room blocks based on this request.</b>
<br><br>(<span class="required">*</span> Denotes a required field.)</span>
<form name="block_request"  method=post action="/print/attendees/travel/rd_block_request_confirmation.asp" onSubmit="return validForm(this);" >
<img src="/global_images2005/1.0/1.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="3" hspace="0" vspace="0" border="0"><br>

<table cellpadding="0" cellspacing="0" border="0" width="100%">
<tr>
	<td colspan="2"><span class="subhead">Contact Information</span></td>
</tr>

<tr><td colspan=2 height="16"><img src="/global_images2005/spacer.gif" height="16"></td></tr>

<tr>
	<td class="rowlabel"><span class="required">* </span>First name&nbsp;&nbsp;</td>
	<td><input type="text" size="25" name="first_name"></td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel"><span class="required">* </span>Last name&nbsp;&nbsp;</td>
	<td><input type="text" size="25" name="last_name"></td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>


<tr>
	<td class="rowlabel"><span class="required">* </span>Company&nbsp;&nbsp;</td>
	<td><input type="text" size="25" name="company"></td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel"><span class="required">* </span>E-mail&nbsp;&nbsp;</td>
	<td><input type="text" size="25" id=text4 name="email"></td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel">Phone&nbsp;&nbsp;</td>
	<td><input type="text" size="25" id=text2 name="phone"></td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel">Fax&nbsp;&nbsp;</td>
	<td><input type="text" size="25" id=text3 name="fax">
	<br><span class="text_colored">(please include country and city codes; e.g. +1 111 111 1111)<br>(+1 is the country code for the United States)</span></td>
</tr>

<tr><td colspan=2 height="30"><img src="/global_images2005/spacer.gif" height="30"></td></tr>

<tr>
	<td colspan="2">
	<img src="/global_images2005/1.0/1.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
	<img src="/global_images2005/spacer.gif" alt="" width="1" height="3" hspace="0" vspace="0" border="0"><br>
	</td>
</tr>

<tr>
	<td colspan="2"><span class="subhead">Hotel Information</span></td>
</tr>

<tr><td colspan=2 height="8"><img src="/global_images2005/spacer.gif" height="8"></td></tr>

<tr>
	<td colspan="2"><span class="required">*</span> Please select an offical 2005 International CES hotel.</td>
</tr>

<tr><td colspan=2 height="6"><img src="/global_images2005/spacer.gif" height="6"></td></tr>

<tr><td colspan="2"></tr>
<!-- ***************** START TABLE TO HOLD 3 COLUMN RADIO BUTTONS FOR HOTELS ***************** -->

<table cellpadding="0" cellspacing="0" border="0">
<tr><!--row1-->
	<!--<td width="20"><img src="/global_images2005/spacer.gif"></td>-->
	<td width="190" valign="top" class="text">
		<input type="radio" name="hotel" value="AlexisPark">Alexis Park Hotel<br>
		<!--<input type="radio" name="hotel" value="AmeriSuites">AmeriSuites Las Vegas<br>-->
		<!--<input type="radio" name="hotel" value="Ballys">Bally's<br>-->
		<input type="radio" name="hotel" value="Bellagio">Bellagio<br>
		<input type="radio" name="hotel" value="Caesars">Caesars Palace<br>
		<input type="radio" name="hotel" value="Circus">Circus Circus<br>
		<!--<input type="radio" name="hotel" value="Embassy Suites LV">Embassy Suites LV<br>-->
		<input type="radio" name="hotel" value="Excalibur">Excalibur Hotel and Casino<br>
		<input type="radio" name="hotel" value="Flamingo">Flamingo Las Vegas<br>
		<!--input type="radio" name="hotel" value="Golden Nugget">Golden Nugget<br>-->
		<input type="radio" name="hotel" value="Harrahs">Harrah's<br>
	</td>
	<td width="190" valign="top" class="text">
		<!--<input type="radio" name="hotel" value="HGVCHilton">HGVC at the LV Hilton<br>-->
		<input type="radio" name="hotel" value="HGVCStrip">HGVC on the LV Strip<br>
		<input type="radio" name="hotel" value="Hilton">Las Vegas Hilton<br>		
		<!--<input type="radio" name="hotel" value="Mandalay">Mandalay Bay<br>	-->
		<input type="radio" name="hotel" value="MGM">MGM Grand<br>	
		<!--<input type="radio" name="hotel" value="Mirage">Mirage<br>-->			
		<input type="radio" name="hotel" value="MonteCarlo">Monte Carlo Resort and Casino<br>		
		<input type="radio" name="hotel" value="Frontier">New Frontier Hotel<br>	
		<input type="radio" name="hotel" value="NewYork">New York New York<br>
	</td>
	<td width="190" valign="top" class="text">


		<!--<input type="radio" name="hotel" value="Paris">Paris<br>-->
		<input type="radio" name="hotel" value="Rio">Rio All-Suite Hotel & Casino<br>
		<input type="radio" name="hotel" value="Riviera">Riviera Hotel and Casino<br>
		<input type="radio" name="hotel" value="Sahara">Sahara Hotel<br>
		<!--<input type="radio" name="hotel" value="Stardust">Stardust<br>-->
		<input type="radio" name="hotel" value="TreasureIsland">Treasure Island<br>
		<input type="radio" name="hotel" value="Western">Westin Casuarina Las Vegas<br>
	</td>
</tr>

<tr><td>&nbsp;</td></tr>
<tr>
	<td colspan="3"><b>Unavailable Hotels</b></td>
</tr>
<tr>
	<td colspan="3">
		AmeriSuites Las Vegas <br>
		Bally's <br>
		HGVC at the LV Hilton <br>
		Mandalay Bay<br>
		Mirage<br>
		Paris <br>
	</td>
</tr>
	<!--<td>
		
		HGVC on the LV Strip <font style="color:CC0000"> **</font><br>
		Imperial Palace <font style="color:CC0000"> **</font><br>
		Las Vegas Hilton <font style="color:CC0000"> **</font><br>
		MGM Grand <font style="color:CC0000"> **</font><br>
		Mirage <font style="color:CC0000"> **</font><br>
		Monte Carlo Hotel <font style="color:CC0000"> **</font><br>
		New York New York <font style="color:CC0000"> **</font>
	</td>
	<td>
		Stardust <font style="color:CC0000"> **</font><br>
		Paris <font style="color:CC0000"> **</font><br>
		Rio All-Suite Hotel & Casino <font style="color:CC0000"> *</font><br>
		Riviera <font style="color:CC0000"> **</font><br>
		Sahara Hotel <font style="color:CC0000"> *</font><br>
		Treasure Island <font style="color:CC0000"> **</font><br>
		Westin Casuarina <font style="color:CC0000"> **</font>
	</td>
</tr>-->
</table>
<!--<img src="/global_images2005/spacer.gif" height="10"><br><font style="color:CC0000">*</font> only accepting individual room reservations-->
<!--<img src="/global_images2005/spacer.gif" height="10"><br><font style="color:CC0000">**</font> Sold Out-->

<!-- ***************** END TABLE TO HOLD 3 COLUMN RADIO BUTTONS FOR HOTELS ***************** -->

<table>
<tr><td colspan=2 height="30"><img src="/global_images2005/spacer.gif" height="30"></td></tr>

<tr>
	<td colspan="2">
	<img src="/global_images2005/1.0/1.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
	<img src="/global_images2005/spacer.gif" alt="" width="1" height="3" hspace="0" vspace="0" border="0"><br>
	</td>
</tr>

<tr>
	<td colspan="2"><span class="subhead">Room Block Information</span></td>
</tr>

<tr><td colspan=2 height="8"><img src="/global_images2005/spacer.gif" height="8"></td></tr>

<tr>
	<td colspan=2>Please indicate the first and last nights of your block and the maximum number of rooms needed on your night of highest occupancy. <span class="text_colored">Show days are January 6-9, 2005.</span><br>
	</td>
</tr>

<tr><td colspan=2 height="16"><img src="/global_images2005/spacer.gif" height="16"></td></tr>

<tr>
	<td class="rowlabel"><span class="required">*</span> First Night of Block&nbsp;&nbsp;</td><td><input type="Text" name="input6" value="" size="15">
			<a href="javascript:cal6.popup();"><img src="images/cal.gif" width="16" height="16" border="0" alt="Click Here to Pick up the date"></a><span class="text_colored">&nbsp;&nbsp;(Click on the calendar icon to select your start date.)</span><br>
	</td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel"><span class="required">*</span> Last Night of Block&nbsp;&nbsp;</td><td><input type="Text" name="input7" value="" size="15">
			<a href="javascript:cal7.popup();"><img src="images/cal.gif" width="16" height="16" border="0" alt="Click Here to Pick up the date"></a><span class="text_colored">&nbsp;&nbsp;(Click on the calendar icon to select your end date.)</span><br>
	</td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<!--

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel"><span class="required">*</span> Last Night of Block&nbsp;&nbsp;</td><td><input type=text name="enddate" size=10 disabled>&nbsp;<a href="javascript:show_calendar('block_request.enddate');" onmouseover="window.status='Date Picker';return true;" onmouseout="window.status='';return true;"><img src="images/show-calendar.gif" width=26 height=25 border=0></a>
		<br>(Click on the calendar icon to select your end date.)
	</td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

-->

<tr>
		<td class="rowlabel"><span class="required">*</span> Max Number of Rooms&nbsp;&nbsp;</td><td><input type="text" size="15" id=text5 name="number_of_rooms">
		</td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel">Additional Space&nbsp;&nbsp;<br>Requirements&nbsp;&nbsp;</td><td><textarea name="space_reqs" cols="35" rows="3"></textarea>
	</td>
</tr>

<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="4"></td></tr>

<tr>
	<td class="rowlabel">Other Special Requests&nbsp;&nbsp;</td><td><textarea name="requests" cols="35" rows="3"></textarea>
	</td>
</tr>

<tr><td colspan=2 height="12"><img src="/global_images2005/spacer.gif" height="12"></td></tr>

<tr>
	<td colspan="2">
	When you confirm your block with the hotel, you will be able to confirm exact dates, shoulder nights, overall room pattern, and other details.
	</td>
</tr>


<tr><td colspan=2 height="4"><img src="/global_images2005/spacer.gif" height="18"></td></tr>

<tr>
	<td>&nbsp;</td>
	<td><input type="submit" name="submit" value="Send Request" class="formData">&nbsp;<input type="reset" name="reset" value="Clear" class="formData"></td>
</tr>
</table>

</form>
<b>Questions?</b>   Problems submitting the form? Please e-mail <a href="mailto:CESHotels@CE.org?subject=online block request submission">CESHotels@CE.org</a>.
<script language="JavaScript">
		<!-- // create calendar object(s) just after form tag closed
			 // specify form element as the only parameter (document.forms['formname'].elements['inputname']);
			 // note: you can have as many calendar objects as you need for your application
			
			var cal6 = new calendar2(document.forms['block_request'].elements['input6']);
			cal6.year_scroll = false;
			cal6.time_comp = false;
			var cal7 = new calendar2(document.forms['block_request'].elements['input7']);
			cal7.year_scroll = false;
			cal7.time_comp = false;
			
		//-->
</script>

<!-- /text for main page -->
</div>		




<!-- /center content -->
    <br><br><br>
    </td>
    <td width="10" class="attendees7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
<!-- optional added value -->

<!-- /optional added value -->
</tr>
<!-- /main body row -->
<!--/print/attendees/conferences/default.asp/print/attendees/directory/default.asp/print/attendees/show_floor/default.asp/print/attendees/special_events/default.asp/print/attendees/awards/default.asp/print/attendees/travel/default.asp-->
<!--/print/attendees/travel/hotel.asp

/print/attendees/travel/rd_block_request.asp
/print/attendees/travel/airlines.asp

/print/attendees/travel/shuttle.asp

/print/attendees/travel/taxi.asp

/print/attendees/travel/vegas.asp

-->
</table>
</body>
</html>