<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><!-- PageID 1785 - generated by RedDot 5.6 - 5.6.1.8 - Y-9bp -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!-- INSERT PAGE TITLE HERE (immediately following gblPAGE_TITLE) -->
<title>2005 International CES:&nbsp;</title>

<!-- INSERT SEARCH ZONE HERE -->
 <META NAME="searchZone" CONTENT="generalCESweb">
<link rel="StyleSheet" href="/print/global_includes/js/mainMethod.css" type="text/css">
<LINK REL="SHORTCUT ICON" HREF="http://www.easymovement.com/ces/favicon.ico">
<!-- Browser detection script -->
    <script src="/print/global_includes/js/browser_detection.js" type="text/javascript"></script>
<SCRIPT language="javascript1.2">
    function newWin(urlString,pgNum) {
        var popupWindow;
        urlString += "?pageID=" + pgNum;
 
        popupWindow = window.open(urlString,"","toolbar=yes,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=550,width=618,left=50,top=50");
    }  
 
    function openNewWindow(strURL) {
        window.name = "main";
        var newWindow = window.open(strURL,"newWindow", "toolbar=no,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=400,width=450,left=50,top=50");
    }
    // Script for e-mail this page - gets the url of the page the user is on before the e-mail page tool button is clicked
    function loadReferrer() {
        referrerString = opener.document.location.href;
        document.emailForm.page.value = referrerString;
    }
</SCRIPT>
<!-- Rollover script (do we still need these?) --> 
<script language="javascript1.2"> 
    /* for graphical rollovers */
   function rollOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function rollOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function introllOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function introllOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function snrollOver(which,name) 
    {
    var on="/global_images/1.0/1.0" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function snrollOff(which) 
    {
    var on="/global_images/1.0/1.0" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
        
    //do we still need this?   
    function onLoadHandler() {
       if( typeof(bodyOnLoadFunction) != 'undefined' ) {
           return eval(bodyOnLoadFunction);
       }
    }
</script>
<script language="javascript">
    <!--
    var activeNavId=0;
    var thisPageUrl='/attendees/awards/innovations/CFE.asp';
    
        var parentLinks=new Array('dummy','/print/attendees/default.htm','/print/attendees/awards/default.asp');
    
        function checkActiveNav(theUrl) {
            var linkUrl=theUrl;
            var returnValue=false;
            
            if (linkUrl==thisPageUrl) {
                returnValue=true;
            } else if (parentLinks.length>2 && linkUrl==parentLinks[parentLinks.length-1]) {
                returnValue=true;   
            } else if (parentLinks.length>3 && linkUrl==parentLinks[parentLinks.length-2]) {
                returnValue=true;
            } else if (parentLinks.length>4 && linkUrl==parentLinks[parentLinks.length-3]) {
                returnValue=true;
            }
        return returnValue;
    }
    //-->
    </script>
    <style>
        <!--
            .attendeesBGImg {
                background-image: url('/print/global_images2005/attendees_bg.gif');
            }
            .text_colored, .intro_copy, .section_title, .subhead, .body_title, .intro_dates, .box10 {
               color: #498429;
            }
            
        //-->
    </style>
</head>
<body leftmargin='0' topmargin='0' rightmargin='0' bottommargin='0' marginwidth='0' onLoad="onLoadHandler();self.focus();"> 
<div style="position:absolute; top: 15; left: 15" ><a href='javascript:;' onClick='window.print();return false'><img src="/print/global_images2005/print.jpg" width="115" height="20" border="0" alt=""></a></div>
<IMG SRC="/print/global_images2005/attPrintBanner.jpg" width="601" BORDER="0" vspace=0><br><table width="600" cellspacing="0" cellpadding="0" border="0">
    <tr>
<!-- /left column -->

<!-- main body content -->    
    <td width="10" class="attendees7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="100%" class="attendees7" valign="top">
    <img src="/print/global_images2005/spacer.gif" height="10" width="1"><br>
<!-- center content -->


<div class="body_title">CES Innovations 2005 Awards Call for Entries - Closed<br><img src="/print/global_images2005/spacer.gif" height="16" width="1"></div>
<div class="text"> 
<!-- text for main page -->

<span class="text">
<SPAN class=section_title><IMG height=163 hspace=8 src="/print/images/general/Innovations_Napping_PC.gif" width=80 align=left>Earn the right to hang this on your door!</SPAN>&nbsp;&nbsp; <BR><BR>The Innovations Design and Engineering Awards program recognizes the most innovative consumer electronics products in 29 categories. <BR><BR>Winning this award is your ticket to meeting industry journalists, retailers, and high-tech heavyweights—in one of the most popular exhibits at the International CES. Honorees are displayed in CES Central Plaza. <BR><BR><STRONG><BR><BR><IMG height=131 hspace=6 src="/print/images/general/2k5_InnovSample.gif" width=80 align=right>Here are a few tips in preparing your entry for the online submission process:</STRONG> 
<UL>
<LI>You'll be required to create a user account&nbsp;to submit your entry. Even if you had one last year, a new account is required. </LI>
<LI>Remember to jot down your username/password, as you may wish to edit an entry or submit additional entries. </LI>
<LI>For your product to be considered, it must be available to US consumers through retail or your company's&nbsp;website NO EARLIER THAN January 1, 2004, or NO LATER THAN June 30, 2005. </LI>
<LI>Download the <A href="/print/docs/Innovations_Entry_Form.pdf" target=_blank>Innovations Entry Form (pdf)</A> and <A href="/print/docs/Innovations_2005_Product_Category_Guide.pdf" target=_blank>Product Category Guide (pdf)</A>. </LI>
<LI>Using a word processing document, type in the required information. </LI>
<LI>Or handwrite the information onto the downloaded form. </LI>
<LI>When ready,&nbsp; just cut/paste or retype the information into the online entry tool. </LI>
<LI>When preparing your entry, focus on providing substantive information, not on creative formatting or typefaces.&nbsp;Entries will be given a standardized look before the judges see them.</LI></UL><BR><SPAN class=subhead>Questions?<BR></SPAN>Contact Roz Graham at <A href="mailto:Innovations@CE.org">Innovations@CE.org</A>.
</span>

<!-- text for main page -->
</div>

<!-- /center content -->
    <br><br><br>
    </td>
    <td width="10" class="attendees7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
<!-- optional added value -->

<!-- /optional added value -->
</tr>
<!-- /main body row -->
<!--/print/attendees/conferences/default.asp/print/attendees/directory/default.asp/print/attendees/show_floor/default.asp/print/attendees/special_events/default.asp/print/attendees/awards/default.asp/print/attendees/travel/default.asp-->
<!--/print/attendees/awards/innovations/default.asp

/print/attendees/awards/innovations/rd_entry_details.asp
/print/attendees/awards/innovations/CFE.asp
/print/attendees/awards/innovations/details.asp
/print/attendees/awards/innovations/rd_2004honorees.asp
/print/attendees/awards/dtv_pioneers.asp

/print/attendees/awards/hall_of_fame/default.asp

/print/attendees/awards/next_big_thing.asp

/print/attendees/awards/best_of_ces/default.asp

/print/attendees/awards/best_of_ces/about.asp
/print/attendees/awards/best_of_ces/2004.asp
/print/attendees/awards/techgirl/default.asp

/print/attendees/awards/techgirl/submission.asp
/print/attendees/awards/techgirl/rd_honorees.asp
/print/attendees/awards/ziff_davis.asp

-->
</table>
</body>
</html>