(function($){var defferedSPageLoadObject=$.Deferred();var defferedScheduleCardTemplateLoaded=$.Deferred();$.when(defferedSPageLoadObject,defferedScheduleCardTemplateLoaded).done(ConfigureMyAgendaButton);$(document).ready(function(){defferedSPageLoadObject.resolve();});function ConfigureMyAgendaButton(){if(isAddToAgendaEnabled){var agendaBtns=$(".addToMyAgenda");if(agendaBtns.length){agendaBtns.configureMyAgendaButton();}}}
function loadScheduleItems(filters){setLoading(true);$.get("/api/Schedule/",filters).done(function(data,textStatus,jqXhr){scheduleData=data;scheduleData.totalRecordsCount=jqXhr.getResponseHeader("X-Pagination-Total");scheduleData.totalPagesCount=jqXhr.getResponseHeader("X-Pagination-TotalPagesCount");scheduleData.currentPage=jqXhr.getResponseHeader("X-Pagination-CurrentPage");scheduleData.pageSize=jqXhr.getResponseHeader("X-Pagination-PageSize");scheduleData.nextPageUrl=jqXhr.getResponseHeader("X-Pagination-NextPageUrl");if(typeof scheduleData.nextPageUrl=="string")
scheduleData.nextPageUrl=scheduleData.nextPageUrl.replace("Events&Awards","Events%26Awards");scheduleData.previousPageUrl=jqXhr.getResponseHeader("X-Pagination-PreviousPageUrl");defferedScheduleObject.resolve();}).fail(function(){alert("There was an error retreiving the schedule.");}).always(function(){});}
function lazyLoadScheduleItems(url){$.get(url).done(function(data,textStatus,jqXhr){scheduleData.filters=data.filters;$.merge(scheduleData.scheduleItems,data.scheduleItems);scheduleData.totalRecordsCount=jqXhr.getResponseHeader("X-Pagination-Total");scheduleData.totalPagesCount=jqXhr.getResponseHeader("X-Pagination-TotalPagesCount");scheduleData.currentPage=jqXhr.getResponseHeader("X-Pagination-CurrentPage");scheduleData.pageSize=jqXhr.getResponseHeader("X-Pagination-PageSize");scheduleData.nextPageUrl=jqXhr.getResponseHeader("X-Pagination-NextPageUrl");if(typeof scheduleData.nextPageUrl=="string")
scheduleData.nextPageUrl=scheduleData.nextPageUrl.replace("Events&Awards","Events%26Awards");scheduleData.previousPageUrl=jqXhr.getResponseHeader("X-Pagination-PreviousPageUrl");renderPage(true);}).fail(function(){alert("There was an error retreiving the schedule.");}).always(function(){});}
function loadMyAgenda(){$.ajax({type:"GET",url:"/api/MyAgenda?includeDeleted=false ",headers:{apikey:apiKey,accesstoken:accessToken,'ctaapi-version':myAgendaApiVer},contentType:"application/json"}).done(function(data){if(data!==undefined&&data!==null){myAgendaIds=data.myAgendaItems.map(function(item){return item.sessionId;});}
defferedMyAgendaObject.resolve();}).fail(function(data){if(data.status===401){myAgendaIds=null;defferedMyAgendaObject.resolve();}
else
alert("There was an error retreiving your agenda. "+data.status);}).always(function(){});}
var defferedMyAgendaObject;var defferedScheduleObject;function load(filters,refreshMyAgenda,configureMyAgendaBtn){if(refreshMyAgenda)defferedMyAgendaObject=$.Deferred();defferedScheduleObject=$.Deferred();$.when(defferedMyAgendaObject,defferedScheduleObject).done(function(){renderPage(configureMyAgendaBtn);});loadScheduleItems(filters);if(refreshMyAgenda)loadMyAgenda();}
function setLoading(){$scheduleEventsContainer.html(CES.templates.scheduleLoading());}
function setDateBar(){var barContainerRect=barContainer.get(0).getBoundingClientRect();var barRect=bar.get(0).getBoundingClientRect();var barBottomEdge=Math.max(barRect.top+bar.outerHeight(),0);var className="schedule-date-bar--locked";var locked=barContainerRect.top<=0;$(document.body).toggleClass(className,locked);dateWrappers.each(function(i,wrapper){var wrapperRect=wrapper.getBoundingClientRect();var intersects=barBottomEdge>wrapperRect.top&&barBottomEdge<wrapperRect.bottom;var wrapperId=wrapper.id;if(intersects&&previousIntersectionId!==wrapperId){previousIntersectionId=wrapperId;dateButton.stop().fadeOut(200,function(){dateLabel.text($('.event-date-title',wrapper).first().text());dateButton.stop().fadeIn(200);});}});}
function setBlueBarDate(dates){var $eventFirstDate=$(".schedule-events .event-date-wrapper:first-child .event-date-title").text();$("#schedule-date-label").text($eventFirstDate);$("#schedule-date-select").html('');$.each(dates,function(index,value){var $eventDates=value.displayName;var $eventDay=$eventDates.split("January ");var $eventDayNumber=$eventDay[1];var $eventDayNumInt=parseInt($eventDayNumber);if($eventDayNumInt<=9){$("#schedule-date-select").append('<option value="2018-01-0'+$eventDayNumber+'">'+$eventDates+'</option>');}else{$("#schedule-date-select").append('<option value="2018-01-'+$eventDayNumber+'">'+$eventDates+'</option>');}});}
function dateBarInitialize(){dateWrappers=$('.event-date-wrapper');barContainer=$('#schedule-date-bar-container');bar=$('#schedule-date-bar');dateButton=$('#schedule-date-button');dateLabel=$('#schedule-date-label');previousIntersectionId=null;}
function groupByArray(xs,key,valueModifier){return xs.reduce(function(rv,x){var v=key instanceof Function?key(x):x[key];if(valueModifier)
v=valueModifier(v);var el=rv.find(function(r){return r.key===v;});if(el){el.values.push(x);}else{rv.push({key:v,values:[x]});}
return rv;},[]);}
function addPageSize(filters){return filters+"&pageSize="+pageSize;}
function addTimes(filters){var times=$scheduleFilterRange.slider("values");return filters+"&beginTime="+times[0]/60+":00:00"+"&EndTime="+times[1]/60+":00:00";}
function getUrlParameter(sParam){var sPageUrl=window.location.search.substring(1);var sUrlVariables=sPageUrl.split('&');for(var i=0;i<sUrlVariables.length;i++)
{var sParameterName=sUrlVariables[i].split('=');if(sParameterName[0]==sParam)
{return sParameterName[1];}}}
function renderPage(configureMyAgendaBtn){if(isFiltered){if(scheduleData.totalRecordsCount){$resultsCount.text(scheduleData.totalRecordsCount+" results");}else{$resultsCount.text("0 results");}}
var lazyInstance=$(".load-more-spinner-container").data("plugin_lazy");if(lazyInstance){lazyInstance.destroy();}
$scheduleEventsContainer.removeClass("loading-container--load-more");$(".schedule-events__load-more").hide();$.each(scheduleData.scheduleItems,function(index,value){if(!myAgendaIds){value.notLoggedIn=true;}else if($.inArray(value.SessionId,myAgendaIds)!==-1){value.added=true;}
value.pressOnly=value.access=="pressOnly";value.addToAgendaEnabled=isAddToAgendaEnabled;});var groupedItems=groupByArray(scheduleData.scheduleItems,"startsOn",function(date){return moment(date).format("YYYY-MM-DD");});var templateData={groupedItems:groupedItems};if(searchTermOldValue)templateData.searchTerm=searchTermOldValue;if(scheduleData.nextPageUrl)templateData.more=true;$scheduleEventsContainer.html(CES.templates.scheduleCards(templateData));if(groupedItems.length<=0){$scheduleEventsContainer.addClass("loading-container--no-results");}else{$scheduleEventsContainer.removeClass("loading-container--no-results");}
$scheduleEventsContainer.find(".agenda-btn-add").click(addToAgendaClick);$scheduleEventsContainer.find(".agenda-btn-lock").click(loginClick);$scheduleEventsContainer.find(".ces-btn--remove-from-agenda").click(removeFromAgendaClick);$scheduleFilterCollapseDate.html(CES.templates.scheduleFilters({filters:scheduleData.filters.dates,apiName:"dates",subApiName:"dates"}));$scheduleFilterCollapseTopic.html(CES.templates.scheduleFilters({filters:scheduleData.filters.topics,apiName:"topics",subApiName:"topics"}));$scheduleFilterCollapseSessionType.html(CES.templates.scheduleFilters({filters:scheduleData.filters.types,apiName:"type",subApiName:"type"}));$scheduleFilterCollapseConferenceTrack.html(CES.templates.scheduleFilters({filters:scheduleData.filters.tracks,apiName:"track",subApiName:"track"}));$scheduleFilterCollapseLocation.html(CES.templates.scheduleFilters({filters:scheduleData.filters.venues,apiName:"locations",subApiName:"buildings"}));$scheduleFilterCollapseTopic.find("input:checkbox").change(filterRelativesChange);$scheduleFilterCollapseLocation.find("input:checkbox").change(filterRelativesChange);$scheduleFilterCollapseConferenceTrack.find("input:checkbox").change(filterSiblingChange);$scheduleFilterCollapseSessionType.find("input:checkbox").change(filterRelativesChange);$scheduleFiltersContainer.find("input:checkbox").change(filterChange);dateBarInitialize();setDateBar();setBlueBarDate(scheduleData.filters.dates);if(isAddToAgendaEnabled&&configureMyAgendaBtn){$(".addToMyAgenda").configureMyAgendaButton();}
const btnLoadMore=document.querySelector(btnLoadMoreSelector);if(btnLoadMore){if(pageNo===1){btnLoadMore.addEventListener('click',elClickBtnLoadMore);}else{btnLoadMoreOuterHtml=btnLoadMore.outerHTML;btnLoadMore.remove();}}}
var filterChangedDelayTimer;function filterChange(){clearTimeout(filterChangedDelayTimer);filterChangedDelayTimer=setTimeout(function(){var filters=$("#filter-collapse-parent-xl input").serialize();filters=addPageSize(filters);filters=addTimes(filters);load(filters,false,true);},1000);isFiltered=true;pageNo=1;const btnLoadMore=document.querySelector(btnLoadMoreSelector);if(!btnLoadMore){const spinnerContainer=document.querySelector(spinnerContainerSelector);if(!spinnerContainer){console.error('"'+spinnerContainerSelector+'" DOES NOT EXIST!');return;}
spinnerContainer.outerHTML=btnLoadMoreOuterHtml+spinnerContainer.outerHTML;}
$("html,body").animate({scrollTop:$("#schedule-date-bar-container").offset().top},1000);}
function filterRelativesChange(){if($(this).parents("ul").slice(0,1).find("input:checkbox:not(:checked)").length===0){$(this).parents("li").slice(1,2).children("input:checkbox").prop('checked',true);}else{$(this).parents("li").slice(1,2).children("input:checkbox").prop('checked',false);}
if(this.checked){$(this).nextAll("ul").find("li").children("input:checkbox").prop('checked',true);}else{$(this).nextAll("ul").find("li").children("input:checkbox").prop('checked',false);}}
function filterSiblingChange(){if(this.checked)
$(this).parent("li").siblings().find("input:checkbox").prop('disabled',true);else
$(this).parent("li").siblings().find("input:checkbox").prop('disabled',false);}
function addToAgendaClick(event){var $this=$(this);event.preventDefault();$.ajax({type:"POST",url:"/api/MyAgenda",data:JSON.stringify({SessionId:$this.data("id")}),headers:{apikey:apiKey,accesstoken:accessToken,'ctaapi-version':myAgendaApiVer},contentType:"application/json"}).done(function(){var $removeButton=$(CES.templates.scheduleCardAgendaButton({added:true,id:$this.data("id")}));$this.replaceWith($removeButton);$removeButton.click(removeFromAgendaClick);loadMyAgenda();}).fail(function(){alert("There was an error adding to your agenda.");});}
function removeFromAgendaClick(event){var $this=$(this);event.preventDefault();$.ajax({type:"DELETE",url:"/api/MyAgenda/"+$this.data("id"),headers:{apikey:apiKey,accesstoken:accessToken,'ctaapi-version':myAgendaApiVer}}).done(function(){var $addButton=$(CES.templates.scheduleCardAgendaButton({added:false,id:$this.data("id")}));$this.replaceWith($addButton);$addButton.click(addToAgendaClick);loadMyAgenda();}).fail(function(){alert("There was an error removing from your agenda.");});}
function loginClick(event){var $this=$(this);event.preventDefault();window.location="/Login.aspx?returnurl=/my-agenda.aspx?addToAgenda="+$this.data("id");}
function clearFiltersClick(event){event.preventDefault();$scheduleFiltersContainer.find("input:checkbox").prop('checked',false);filterChange();}
var searchTermChangedDelayTimer;var searchTermOldValue;function searchTermChange(){if(searchTermOldValue===$filtersSearch.val())return;searchTermOldValue=$filtersSearch.val();clearTimeout(searchTermChangedDelayTimer);searchTermChangedDelayTimer=setTimeout(function(){var filters=$("#filter-collapse-parent-xl input").serialize();filters=addPageSize(filters);filters=addTimes(filters);load(filters,false,true);},1000);}
function elClickBtnLoadMore(e){const btnLoadMore=e.target;if(!btnLoadMore){return;}
e.preventDefault();pageHeight=getPageHeight();getNextPage();}
function elScroll(e){if(pageNo===1){e.preventDefault();return;}
if(window.pageYOffset>pageHeight*pageNo*5/6){getNextPage();}}
function getPageHeight(){if(!pageSize){return 0;}
const elementSelector='article.row.event-card';var elementList=document.querySelectorAll(elementSelector);const firstElement=elementList[0];const lastElement=elementList[elementList.length-1];const pageHeight=(lastElement.getBoundingClientRect().top-firstElement.getBoundingClientRect().top);return pageHeight;}
function getNextPage(){pageNo++;lazyLoadScheduleItems(scheduleData.nextPageUrl);}
const pageSize=15;let pageNo=1;let pageHeight=0;let btnLoadMoreOuterHtml=null;Handlebars.registerHelper("scheduleItemTimes",function(startsOn,endsOn){var result=moment(startsOn).format("h:mm A")+" – "+moment(endsOn).format("h:mm A");return new Handlebars.SafeString(result);});Handlebars.registerHelper("datePretty",function(date){var result=moment(date).format("dddd, MMMM D");return new Handlebars.SafeString(result);});Handlebars.registerPartial("scheduleCardAgendaButton",CES.templates.scheduleCardAgendaButton);Handlebars.registerPartial("scheduleFilters",CES.templates.scheduleFilters);const btnLoadMoreSelector='button.btn.schedule-events__load-more';const spinnerContainerSelector='div.load-more-spinner-container';var $form=$("#form");var $resultsCount=$(".results-count");var $scheduleEventsContainer=$(".schedule-events");var $scheduleFiltersContainer=$(".schedule-filters");var $filtersSearch=$("#filters-search");var $scheduleFilterCollapseDate=$("#schedule-filter-collapse-date-xl");var $scheduleFilterCollapseTopic=$("#schedule-filter-collapse-topic-xl");var $scheduleFilterCollapseSessionType=$("#schedule-filter-collapse-sessionType-xl");var $scheduleFilterCollapseLocation=$("#schedule-filter-collapse-location-xl");var $scheduleFilterCollapseConferenceTrack=$("#schedule-filter-collapse-conferenceTrack-xl");var $scheduleFilterRange=$(".schedule-filter__slider-range");var $scheduleFilterTime1=$(".schedule-filter__time").not(".schedule-filter__time--2");var $scheduleFilterTime2=$(".schedule-filter__time--2");var dateWrappers=$('.event-date-wrapper');var barContainer=$('#schedule-date-bar-container');var bar=$('#schedule-date-bar');var dateButton=$('#schedule-date-button');var dateLabel=$('#schedule-date-label');var previousIntersectionId=null;var myAgendaIds;var scheduleData;var isAddToAgendaEnabled=addToAgendaEnabled==="True";var isFiltered=false;$form.submit(function(e){e.preventDefault();});$(".clear-filters").click(clearFiltersClick);$filtersSearch.on("propertychange change click keyup input paste",searchTermChange);$(".filters-search-icon").on("click",function(){$filtersSearch.val("");searchTermChange();});$scheduleFilterRange.on("slidechange",filterChange);document.addEventListener('scroll',elScroll);$('#schedule-date-select').on('change',function(e){$("html,body").animate({scrollTop:$("#schedule-date-bar-container").offset().top},1000);$scheduleFilterCollapseDate.find("input:checkbox").prop("checked",false);var targetEl=$('#filter-checkbox-'+e.target.value+'-xl');targetEl.prop("checked",true);targetEl.change();});$(window).on('scroll',setDateBar);$(window).on('resize',setDateBar);var topics=getUrlParameter("topics");var filters={pageSize:pageSize};if(topics){var topicsArray=topics.split(",");filters.topics=topicsArray;}
load(filters,isAddToAgendaEnabled,false);defferedScheduleCardTemplateLoaded.resolve;}($));if(!Array.prototype.find){Object.defineProperty(Array.prototype,'find',{value:function(predicate){if(this==null){throw new TypeError('"this" is null or not defined');}
var o=Object(this);var len=o.length>>>0;if(typeof predicate!=='function'){throw new TypeError('predicate must be a function');}
var thisArg=arguments[1];var k=0;while(k<len){var kValue=o[k];if(predicate.call(thisArg,kValue,k,o)){return kValue;}
k++;}
return undefined;}});}