<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><!-- PageID 530 - generated by RedDot 5.6 - 5.6.0.25 - Y-9bp -->

<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />

<!-- INSERT PAGE TITLE HERE (immediately following gblPAGE_TITLE) -->
<title>2005 International CES:&nbsp;TechZones</title>



<META NAME="searchZone" CONTENT="exhibitor">

<link rel="StyleSheet" href="/global_includes/css/mainMethod.css" type="text/css">
<LINK REL="SHORTCUT ICON" HREF="http://www.easymovement.com/ces/favicon.ico">

<!-- Browser detection script -->
    <script src="/global_includes/js/browser_detection.js" type="text/javascript"></script>

<SCRIPT language="javascript1.2">
    function newWin(urlString,pgNum) {
        var popupWindow;
        urlString += "?pageID=" + pgNum;
 
        popupWindow = window.open(urlString,"","toolbar=yes,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=550,width=618,left=50,top=50");
    }  
 
    function openNewWindow(strURL) {
        window.name = "main";
        var newWindow = window.open(strURL,"newWindow", "toolbar=no,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=400,width=450,left=50,top=50");
    }

    // Script for e-mail this page - gets the url of the page the user is on before the e-mail page tool button is clicked
    function loadReferrer() {
        referrerString = opener.document.location.href;
        document.emailForm.page.value = referrerString;
    }
</SCRIPT>

<!-- Rollover script (do we still need these?) --> 
<script language="javascript1.2"> 
    /* for graphical rollovers */
   function rollOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function rollOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function introllOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function introllOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function snrollOver(which,name) 
    {
    var on="/global_images/1.0/1.0" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function snrollOff(which) 
    {
    var on="/global_images/1.0/1.0" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
        
    //do we still need this?   
    function onLoadHandler() {
       if( typeof(bodyOnLoadFunction) != 'undefined' ) {
           return eval(bodyOnLoadFunction);
       }
    }
</script>

<script language="javascript">
    <!--
    var activeNavId=0;
    var thisPageUrl='/exhibitors/space/techzones.asp';
    
        var parentLinks=new Array('dummy','/exhibitors/default.htm','/exhibitors/space/default.asp');
    
    
function checkActiveNav(theUrl) {
    var linkUrl=theUrl;
    var returnValue=false;
    
    if (linkUrl==thisPageUrl) {
        returnValue=true;
    } else if (parentLinks.length>2 && linkUrl==parentLinks[parentLinks.length-1]) {
        returnValue=true;   
    } else if (parentLinks.length>3 && linkUrl==parentLinks[parentLinks.length-2]) {
        returnValue=true;
    } else if (parentLinks.length>4 && linkUrl==parentLinks[parentLinks.length-3]) {
        returnValue=true;
    }
    return returnValue;
}
//-->
</script>

    <style>
        <!--
            .exhibitorBGImg {
                background-image: url('/global_images2005/exhibitor_bg.gif');
            }
            .text_colored, .intro_copy, .section_title, .subhead, .body_title, .intro_dates, box10 {
               color: #2B5492;
            }
            
        //-->
    </style>

</head>

<body leftmargin='0' topmargin='0' rightmargin='0' bottommargin='0' marginwidth='0' onLoad="onLoadHandler();self.focus();"> 

<table width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
        <td width="50%" valign="top" class="exhibitorBGImg">&nbsp;</td>
        <td valign="top" class="exhibitorBGImg">
            <table width="770" cellspacing="0" cellpadding="0" border="0">
                <!-- blank 1 pixel row at top of page -->
<tr>
     <td width="10"><img src="/global_images2005/spacer.gif" alt="" width="10" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="140"><img src="/global_images2005/spacer.gif" alt="" width="140" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="10"><img src="/global_images2005/spacer.gif" alt="" width="10" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="10"><img src="/global_images2005/spacer.gif" alt="" width="10" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="380"><img src="/global_images2005/spacer.gif" alt="" width="380" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="10"><img src="/global_images2005/spacer.gif" alt="" width="10" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="10"><img src="/global_images2005/spacer.gif" alt="" width="10" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="190"><img src="/global_images2005/spacer.gif" alt="" width="190" height="1" hspace="0" vspace="0" border="0"></td>
     <td width="10"><img src="/global_images2005/spacer.gif" alt="" width="10" height="1" hspace="0" vspace="0" border="0"></td>
</tr>
<!-- /blank 1 pixel row at top of page -->

<!-- global navigation row - register, about, faqs, contact, and site map -->
<tr>
     <td width="10"></td>
     <td width="140"></td>
     <td width="10"></td>
     <td width="10"></td>
     <td width="600" colspan="5" class="nav_global"><span class="intro_dates">January 6-9, 2005</span><img src="/global_images2005/spacer.gif" width="4" height="20" hspace="0" vspace="0" border="0" align="absmiddle">| Las Vegas<img src="/global_images2005/spacer.gif" alt="" width="225" height="1" border="0"> <!-- | <!-- --><a href="/about_ces/default.asp">About CES</a> | <!-- --><a href="/faqs/default.asp">FAQs</a> | <!-- --><a href="/contact_us/default.asp">Contact Us</a><!-- --></td>
</tr>
<!-- /global navigation row - register, about, faqs, contact, and site map -->


<!-- logo and banner image row -->

<tr>
     <td width="10"></td>
     <td width="140"><a href="/default.htm"><img src="/global_images2005/logo.gif" alt="International CES" width="140" height="74" hspace="0" vspace="0" border="0"></a></td>
     <td width="10"></td>
     <td width="610" colspan="6"><img src="/global_images2005/exhTop1.gif" alt="" width="610" height="74" border="0"></td>
</tr>
<!-- /logo and banner image row -->  

<!-- primary navigation row -->
<tr>
     <td width="10"></td>
     <td width="140"></td>
     <td width="10"></td>
     <td width="610" colspan="6" background="/global_images2005/spacer.gif"><a href="/attendees/default.htm" onmouseover="headerRollOver('tab_attendees', '/global_images2005/2.0_tab_attendees_r.gif');" onmouseout="headerRollOff('tab_attendees', '/global_images2005/2.0_tab_attendees.gif');"><img name="tab_attendees" id="tab_attendees" src="/global_images2005/2.0_tab_attendees.gif" alt="Attendees" width="70" height="27" hspace="0" vspace="0" border="0" ></a><a href="/exhibitors/default.htm" onmouseover="headerRollOver('tab_exhibitor', '/global_images2005/2.0_tab_exhibitor_r.gif');" onmouseout="headerRollOff('tab_exhibitor', '/global_images2005/2.0_tab_exhibitor.gif');"><img name="tab_exhibitor" id="tab_exhibitor" src="/global_images2005/2.0_tab_exhibitor.gif" alt="Exhibitor Services" width="118" height="27" hspace="0" vspace="0" border="0"></a><a href="/press/default.htm" onmouseover="headerRollOver('tab_press', '/global_images2005/2.0_tab_press_r.gif');" onmouseout="headerRollOff('tab_press', '/global_images2005/2.0_tab_press.gif');"><img name="tab_press" id="tab_press" src="/global_images2005/2.0_tab_press.gif" width="78" height="27" alt="Press" border="0"></a><a href="/international/default.htm" onmouseover="headerRollOver('tab_international', '/global_images2005/exhIntR1.gif');" onmouseout="headerRollOff('tab_international', '/global_images2005/exhInt1.gif');"><img src="/global_images2005/exhInt1.gif" width="134" height="27" alt="" border="0" name="tab_international" id="tab_international"></a><img src="/global_images2005/exhMiddle1.gif" alt="" width="210" height="27" hspace="0" vspace="0" border="0"></td>
</tr>
<!-- /primary navigation row -->

<!-- secondary navigation row -->  

<tr>
    <td width="10"></td>
    <form name="searchCESWeb" method="POST" action="/search/rd_searchResult.asp">
    <td width="760" colspan="10"  background="/global_images2005/spacer.gif"  class="exhibitor3">

<!-- table for secondary navigation and search box -->
        <table cellspacing="0" cellpadding="0" border="0" width="760"  background="/global_images2005/spacer.gif" >
        <tr>
            <td class="exhibitor_second_nav" width="560"><!--&nbsp;|&nbsp;&nbsp;<!-- --><span id="secondaryNav22"><a href="/exhibitors/space/default.asp">Exhibit Space</a></span>
<script>
<!--
if (checkActiveNav("/exhibitors/space/default.asp")) {
    document.getElementById("secondaryNav22").className="exhibitor_sec_nav_active"
}
// -->
</script>&nbsp;|&nbsp;&nbsp;<!-- --><span id="secondaryNav23"><a href="/exhibitors/promotions/default.asp">Promotions</a></span>
<script>
<!--
if (checkActiveNav("/exhibitors/promotions/default.asp")) {
    document.getElementById("secondaryNav23").className="exhibitor_sec_nav_active"
}
// -->
</script>&nbsp;|&nbsp;&nbsp;<!-- --><span id="secondaryNav24"><a href="/exhibitors/resource_center/default.asp">Resource Center</a></span>
<script>
<!--
if (checkActiveNav("/exhibitors/resource_center/default.asp")) {
    document.getElementById("secondaryNav24").className="exhibitor_sec_nav_active"
}
// -->
</script>&nbsp;|&nbsp;&nbsp;<!-- --><span id="secondaryNav295"><a href="/exhibitors/pr/default.asp">PR Help</a></span>
<script>
<!--
if (checkActiveNav("/exhibitors/pr/default.asp")) {
    document.getElementById("secondaryNav295").className="exhibitor_sec_nav_active"
}
// -->
</script>&nbsp;|&nbsp;&nbsp;<!-- --><span id="secondaryNav98"><a href="/exhibitors/manual/default.asp">Manual</a></span>
<script>
<!--
if (checkActiveNav("/exhibitors/manual/default.asp")) {
    document.getElementById("secondaryNav98").className="exhibitor_sec_nav_active"
}
// -->
</script>&nbsp;|&nbsp;&nbsp;<!-- --><span id="secondaryNav"><a href="/exhibitors/newsletter/default.asp">Newsletter</a></span>
<script>
<!--
if (checkActiveNav("/exhibitors/newsletter/default.asp")) {
    document.getElementById("secondaryNav").className="exhibitor_sec_nav_active"
}
// -->
</script>&nbsp;|&nbsp;&nbsp;<!-- --><span id="secondaryNav26"><a href="/exhibitors/downloads/default.asp">Downloads</a></span>
<script>
<!--
if (checkActiveNav("/exhibitors/downloads/default.asp")) {
    document.getElementById("secondaryNav26").className="exhibitor_sec_nav_active"
}
// -->
</script><!-- --></td>
            <td width="173" align="right">

<!-- Script for setting correct search box size -->
    <script LANGUAGE="JavaScript">
    <!--
    if (is_nav4) {
        document.write("<input  size=20 ");
    } 
    else if (is_mac) {
        document.write("<input  size=30 ");
    }
    else if (is_safari) {
        document.write("<input  size=25 ");
    }
    else {
        document.write("<input  size=34 ");
    }
    function checkSearch() {
        var searchForm = document.searchCESWeb;
                            
        if(searchForm.SEARCH_STRING.value.search(/\S/) == -1) {
            alert("Please enter text to search for.");
            return;
        }
            searchForm.submit();
        }
    //-->
    </script>
    type="text" name="SEARCH_STRING" value=" Search CESweb.org" class="exhibitorform"  ONFOCUS="if(this.value==' Search CESweb.org')this.value=''; headerRollOver('button_search', '/global_images2005/2.0.button_search_r.gif');" ONBLUR="if(this.value=='')this.value=' Search CESweb.org'; headerRollOff('button_search', '/global_images2005/2.0.button_search.gif');" >&nbsp;&nbsp;</td>
            <td width="27"><img name="button_search"  src="/global_images2005/2.0.button_search.gif" alt="go" width="27" height="33" hspace="0" vspace="0" border="0" onmouseover="headerRollOver('button_search', '/global_images2005/2.0.button_search_r.gif');" onmouseout="headerRollOff('button_search', '/global_images2005/2.0.button_search.gif');" onClick="checkSearch();"></td>
        </tr>
        </table>
<!-- /table for secondary navigation and search box -->   

    </td>
       <input type="hidden" name="" value="on">
       <input type="hidden" name="" value="on">
       <input type="hidden" name="" value="on">
       <input type="hidden" name="" value="on">
       <input type="hidden" name="" value="on">
    </form>
</tr>
<!-- /secondary navigation row -->

<script language="JavaScript">
        <!--
        function headerRollOver(imgName, imgSrc) {
            if(document.images) {document.images[imgName].src=imgSrc;}
            else if (document.getElementById){document.getElementById(imgName).src=imgSrc;}
        }
        function headerRollOff(imgName, imgSrc) {
            if(document.images){document.images[imgName].src=imgSrc;}
            else if (document.getElementById){document.getElementById(imgName).src=imgSrc;}
        }
        //-->
</script>

<!-- colored row with section color 4 - 5 pixels high --> 
<tr>
     <td width="10"></td>
     <td width="140"></td>
     <td width="10"></td>
     <td width="610" colspan="6"  background="/global_images2005/spacer.gif" class="exhibitor4"><img src="/global_images2005/spacer.gif" alt="" width="610" height="5" hspace="0" vspace="0" border="0"></td>
 </tr>
<!-- /colored row with section color 4 - 5 pixels high --> 
  
<!-- breadcrumb row -->
<tr>
    <td width="10"></td>
    <td width="140"><a href="/exhibitors/resource_center/badges/" onmouseover="headerRollOver('register', '/global_images2005/2.0.register_r.gif');" onmouseout="headerRollOff('register', '/global_images2005/2.0.register.gif');"><img src="/global_images2005/2.0.register.gif" alt="Register" name="register" id="register" width="140" height="40" hspace="0" vspace="0" border="0"></a></td>
    <td width="10"></td>  
    <td width="10" background="/global_images2005/spacer.gif" class="exhibitor6"><img src="/global_images2005/spacer.gif" alt="" width="10" height="40" hspace="0" vspace="0" border="0"></td>
    <td width="390" colspan="2" background="/global_images2005/spacer.gif" class="exhibitor6" valign="bottom"><span class="exhibitor_nav_breadcrumb">

   <a href="/default.htm">Home</a>&nbsp;&gt;&nbsp;<a href="/exhibitors/default.htm">Exhibitor Services</a>&nbsp;&gt;&nbsp;<a href="/exhibitors/space/default.asp">Exhibit Space</a>&nbsp;&gt;&nbsp;TechZones

    </span><br><img src="/global_images2005/spacer.gif" height="8" width="1"></td>
    <td width="200" background="/global_images2005/spacer.gif" colspan="2" class="exhibitor6"><img src="/global_images2005/2.0_print_mail.gif" width="115" height="40" alt="print - email" border="0"><a href="#" id="print_link" onmouseover="headerRollOver('button_print', '/global_images2005/2.0_button_print_r.gif');" onmouseout="headerRollOff('button_print', '/global_images2005/2.0_button_print.gif');" onclick="window.open('/print/exhibitors/space/techzones.asp?', '_blank', 'status=yes,toolbar=yes,menubar=yes,scrollbars=yes,location=no,width=620');return false;"><img src="/global_images2005/2.0_button_print.gif" alt="Print" name="button_print" id="button_print" width="42" height="40" hspace="0" vspace="0" border="0"></a><a href="javascript:newWin('/global_include/asp/page_tools/email.asp');" id="mail_link" onmouseover="headerRollOver('button_mail', '/global_images2005/2.0_button_mail_r.gif');" onmouseout="headerRollOff('button_mail', '/global_images2005/2.0_button_mail.gif');"><img src="/global_images2005/2.0_button_mail.gif" alt="Email" name="button_mail" id="button_mail" width="42" height="40" hspace="0" vspace="0" border="0"></a></td>
    <td width="10" background="/global_images2005/spacer.gif" class="exhibitor6">&nbsp;</td>
</tr>
<!-- /breadcrumb row --> 

</table>
<table width="770" cellspacing="0" cellpadding="0" border="0">

<!-- main body row -->
<tr>

<!-- left column -->
    <td width="10" rowspan="2"><img src="/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="140" valign="top" rowspan="2"><img src="/global_images2005/spacer.gif" width="140" height="20" alt="" border="0"><br>

<!-- left nav -->    
    <!-- left nav -->
        <span class="nav_third">

        <img src="/global_images2005/3nav_bar_gray.gif" alt="--------" width="140" height="1" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" width="140" height="4" alt="" border="0"><br>
<a href="/exhibitors/space/areas.asp">Exhibit Booth Space</a><br>





    <img src="/global_images2005/spacer.gif" width="140" height="6" alt="" border="0"><br>
               <script language="JavaScript">
              <!--
                  if (checkActiveNav("/exhibitors/space/areas.asp")) { document.getElementById("fourth_row_container297").style.display = "";}
              //-->
              </script> <img src="/global_images2005/3nav_bar_gray.gif" alt="--------" width="140" height="1" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" width="140" height="4" alt="" border="0"><br>
TechZones<br>




    <script language="JavaScript">
        <!--
            if (document.getElementById("fourth_row_container529")) { document.getElementById("fourth_row_container529").style.display = "";}
        //-->
    </script>


    <img src="/global_images2005/spacer.gif" width="140" height="6" alt="" border="0"><br>
               <script language="JavaScript">
              <!--
                  if (checkActiveNav("/exhibitors/space/techzones.asp")) { document.getElementById("fourth_row_container529").style.display = "";}
              //-->
              </script> <img src="/global_images2005/3nav_bar_gray.gif" alt="--------" width="140" height="1" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" width="140" height="4" alt="" border="0"><br>
<a href="/exhibitors/space/suites.asp">CES Meeting Place</a><br>





    <img src="/global_images2005/spacer.gif" width="140" height="6" alt="" border="0"><br>
               <script language="JavaScript">
              <!--
                  if (checkActiveNav("/exhibitors/space/suites.asp")) { document.getElementById("fourth_row_container605").style.display = "";}
              //-->
              </script> <img src="/global_images2005/3nav_bar_gray.gif" alt="--------" width="140" height="1" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" width="140" height="4" alt="" border="0"><br>
<a href="/exhibitors/space/contacts.asp">Business Development Contacts</a><br>





    <img src="/global_images2005/spacer.gif" width="140" height="6" alt="" border="0"><br>
               <script language="JavaScript">
              <!--
                  if (checkActiveNav("/exhibitors/space/contacts.asp")) { document.getElementById("fourth_row_container341").style.display = "";}
              //-->
              </script> 
        <img src="/global_images2005/3nav_bar_gray.gif" alt="--------" width="140" height="1" hspace="0" vspace="0" border="0"><br>

        <img src="/global_images2005/spacer.gif" width="140" height="28" alt="" border="0"><br>
        </span>
<!-- /left nav -->
<!-- /left nav --> 

<!-- CEA badge -->
    <a href="http://www.ce.org" target="new" onmouseover="headerRollOver('leftAddedValue530', '/global_images2005/2.0_logo_cea_r.gif');" onmouseout="headerRollOff('leftAddedValue530', '/global_images2005/2.0_logo_cea.gif');"><img src="/global_images2005/2.0_logo_cea.gif" name="leftAddedValue530" id="leftAddedValue530" border="0"></a><br><img src="/global_images2005/spacer.gif" height="10" width="1">
<!-- /CEA badge -->

<!-- left added value -->
    
    
<!-- left added value -->

    </td>
    <td width="10" rowspan="2"><img src="/global_images2005/spacer.gif" height="1" width="10"></td>
<!-- /left column -->



<!-- main body content -->    
    <td width="10" class="exhibitor7"><img src="/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="100%" class="exhibitor7" valign="top">
    <img src="/global_images2005/spacer.gif" height="10" width="1"><br>

<!-- center content -->






<img src="/global_images2005/spacer.gif" height="10" width="1"><br>
<div class="body_title">2005 International CES TechZones<br><img src="/global_images2005/spacer.gif" height="16" width="1"></div>

<div class="text">
<!-- text for main page -->
<a name="top"></a>

<IMG height=46 src="/images/general/techzone_logo.gif" width=200 align=right>See what brands are building and dominating in your market. Meet the tech players who set the standard for your niche. Get your hands on new and emerging technologies, products and companies. <BR><BR>All in one spot. All at market-specific International CES TechZones. Look for the CES TechZone logo and get in the zone.

<br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<div class="section_title">Get in the zone</div>
As you plan your 2005 business strategy, get what you need to know at the International CES TechZones. These zones—all located within the International CES—are concentrated versions of the markets they represent.&nbsp;<BR><BR><STRONG><IMG height=60 hspace=6 src="/images/general/InnovationsPlus.gif" width=200 align=right>NEW!</STRONG> Consider participation in the <STRONG>Innovations Plus</STRONG> exhibit area, home to a variety of CES TechZones. Located just outside the Las Vegas Convention Center in the Central Plaza, Innovations Plus also features the 2005 International CES Innovations Honorees displays.<br><br>


<table width="590" cellspacing=0 cellpadding=2 border=0>
<tr>
    <td width="190"><span class="subhead">TechZone Name</span></td>
    <td width="140"><span class="subhead">Location</span></td>
    <td width="180"><span class="subhead">Sponsor</span></td>
</tr>



    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone534">Assistive Technologies</a></td>
        <td>Innovations Plus</td>
        <td><i>ABILITY</i> Magazine</td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone537">Automotive Aftermarket Showcase</a></td>
        <td>LVCC North</td>
        <td></td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone1490">Bluetooth</a></td>
        <td>Innovations Plus</td>
        <td>Bluetooth SIG</td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone1491">Cardio PlayZone</a></td>
        <td>Innovations Plus</td>
        <td></td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone539">Connected Home Entertainment</a></td>
        <td>LVCC South 1-2</td>
        <td></td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone540">Digital Car/Telematics</a></td>
        <td>LVCC North</td>
        <td>ITS America</td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone1492">Digital Content Storage</a></td>
        <td>Innovations Plus</td>
        <td></td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone542">DSL Forum</a></td>
        <td>Innovations Plus</td>
        <td></td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone543">DVD-RAM</a></td>
        <td>LVCC Central</td>
        <td>RAM Promotion Group (RAMPRG)</td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone544">Energy Efficiency and Electronics Recycling</a></td>
        <td>Innovations Plus</td>
        <td>Energy Star, EPA</td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone546">Flash Forward 2.0: Bringing Digital Imaging Into Focus</a></td>
        <td>Central Plaza</td>
        <td>International CES and InfoTrends</td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone1493">Launch</a></td>
        <td>Innovations Plus</td>
        <td></td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone553">MP3 and Internet Audio</a></td>
        <td>Innovations Plus</td>
        <td></td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone1494">MultiMediaCard Association</a></td>
        <td>Innovations Plus</td>
        <td>MultiMediaCard Association</td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone555">Portable Power</a></td>
        <td>Innovations Plus</td>
        <td></td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone1573">RFID</a></td>
        <td>Innovations Plus</td>
        <td>AIM</td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone557">RWPPI</a></td>
        <td>LVCC Central</td>
        <td>RWPPI</td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone558">SD Card</a></td>
        <td>LVCC Central</td>
        <td>SD Card Association</td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone559">Studio at Home</a></td>
        <td>Central Plaza</td>
        <td></td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone560">TechHome</a></td>
        <td>LVCC South 1-2</td>
        <td>CEA's TechHome Division</td>
    </tr>
    

    <!---->
    <tr class="exhibitor11">
        <td><a href="#techzone561">Ultrawideband</a></td>
        <td>Innovations Plus</td>
        <td>MultiBand OFDM Alliance</td>
    </tr>
    

    <!---->
    <tr>
        <td><a href="#techzone1496">USB</a></td>
        <td>Innovations Plus</td>
        <td>USB Implementers Forum, Inc.</td>
    </tr>
    

</table>


<a name="techzone534"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Assistive Technologies</span><br>
<span class="text_colored">Innovations Plus</span>
<br>Sponsor(s): <span class="text_colored"><i>ABILITY</i> Magazine</span>

<br><br>

<IMG height=53 src="/images/partners/abilityMag.gif" width=190 align=right> 
<P>Today’s electronics and information technology products and services address universal design for the aging “baby boom” generation, along with product accessibility for people with disabilities. If your company is involved in any way with Accessibility, Assistive Technology or Universal Design, then you need to participate in the <B>Assistive Technologies TechZone, sponsored by <I>ABILITY Magazine</I></B><I>,</I> at the 2005 International CES.</P>
<P><B>Who should exhibit here?</B><BR>Manufacturers and suppliers of accessible hardware or software, accessories and services including: 
<UL>
<LI>Digital captioning </LI>
<LI>Telecommunications </LI>
<LI>Wireless devices </LI>
<LI>Audio and visual indicators </LI>
<LI>Speech recognition technology </LI>
<LI>Easy-to-use controls </LI>
<LI>TTY or hearing aid access </LI>
<LI>Wheelchair mounts </LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone537"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Automotive Aftermarket Showcase</span><br>
<span class="text_colored">LVCC North</span>


<br><br>

More than ever, Mobile Electronics and aftermarket automotive accessories are being marketed, distributed and sold through similar channels. Now, the International CES, the world's largest Mobile Electronics event, brings you the <B>CES Automotive Aftermarket Showcase</B>. Stay ahead of your competition in the burgeoning aftermarket industry by showcasing your products in front of the largest gathering of specialty automotive retailers, distributors and manufacturers from the U.S. and abroad. 
<P><B>Who should exhibit here?</B><BR>This event is ideal for exhibitors from every area of the aftermarket industry, including: 
<UL>
<LI>Wheel, tire and suspension </LI>
<LI>Car care/detailing </LI>
<LI>Body kits and modification products I</LI>
<LI>In car electronics </LI>
<LI>Engine performance and diagnostic products </LI>
<LI>Safety products/accessories</LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone1490"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Bluetooth</span><br>
<span class="text_colored">Innovations Plus</span>
<br>Sponsor(s): <span class="text_colored">Bluetooth SIG</span>

<br><br>

We all want low-cost, low-power wireless personal connectivity — at our fingertips. International CES attendees want to see the newest developments in personal connectivity. If you provide solutions for short-range wireless technologies and interoperability, you need to be part of the&nbsp;<STRONG>Bluetooth TechZone</STRONG>&nbsp;at the 2005 International CES. 
<P><B>Who should exhibit here?<IMG height=49 src="/images/partners/Bluetooth_Color.gif" width=200 align=right></B> 
<UL>
<LI>Software developers </LI>
<LI>Silicon vendors </LI>
<LI>Peripheral and camera manufacturers </LI>
<LI>Mobile PC manufacturers </LI>
<LI>Handheld device developers </LI>
<LI>Consumer electronics manufacturers </LI>
<LI>Car manufacturers </LI>
<LI>Test and measurement equipment manufacturers </LI></UL><I><BR>Participants must be members of the Bluetooth SIG.</I> 
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone1491"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Cardio PlayZone</span><br>
<span class="text_colored">Innovations Plus</span>


<br><br>

Fitness today means high-intensity products and technologies that entertain us while we’re getting a maximum cardio workout. They’re the products that count calories burned or speed. They help increase/decrease intensity levels, feature videos or play music that make a killer workout fun. If you manufacture products that entertain end users—while they increase their heart rate and burn calories—then consider featuring it in the&nbsp;<STRONG>Cardio PlayZone</STRONG>&nbsp;at the 2005 International CES.<BR><BR><STRONG>Who should exhibit here?</STRONG><BR>Manufacturers or suppliers of cardio-related “EXCER-TAINMENT” or gaming products or software that help consumers increase their physical activity and heart rate.<BR>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone539"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Connected Home Entertainment</span><br>
<span class="text_colored">LVCC South 1-2</span>


<br><br>

Here's your chance to raise homebuilder, installer and consumer awareness on the value and benefits of whole-house audio and video. Show off your innovative, hard-wired, professionally installed systems in the <STRONG>Connected Home Entertainment TechZone</STRONG>. Demo new multi-room networked entertainment, including audio, structured wiring, whole-house video, no-new-wires and wireless products to a captive audience.<BR><BR><B>Who should exhibit here?</B><BR>Manufacturers or suppliers of products such as: 
<UL>
<LI>Audio, structured wiring or home networking solutions </LI>
<LI>Whole-house video entertainment systems, including video source, delivery and display </LI>
<LI>Video adapters and set-top boxes, including networked PVRs and thin clients </LI>
<LI>Multi-room audio equipment and source controllers </LI>
<LI>Amplifiers and in-ceiling, in-wall and outdoor speakers </LI>
<LI>Networked monitors and displays </LI>
<LI>Infrared and other wireless distribution systems </LI>
<LI>Music storage and management systems </LI>
<LI>User interfaces </LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone540"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Digital Car/Telematics</span><br>
<span class="text_colored">LVCC North</span>
<br>Sponsor(s): <span class="text_colored">ITS America</span>

<br><br>

What a sweet ride! You have the products that make travel easier and more enjoyable. The energized&nbsp;<STRONG>Digital Car/Telematics&nbsp;TechZone</STRONG> features the most innovative digital car products, at the world's largest mobile electronics tradeshow: The International CES. Make strategic connections at the only show focused on the most complete range of relevant consumer, convergence and communications technologies.&nbsp;<BR><BR><IMG height=88 src="/images/partners/ITS.gif" width=210 align=right><B>Who should exhibit here?</B><BR>Manufacturers or suppliers of products such as: 
<UL>
<LI>Mobile electronics components </LI>
<LI>Software and/or hardware-integrated into vehicle systems </LI>
<LI>Navigation devices and intelligent transportation systems </LI>
<LI>Wireless communications and hands-free devices </LI>
<LI>Audio/visual entertainment </LI>
<LI>Mobile electronics safety and security </LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone1492"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Digital Content Storage</span><br>
<span class="text_colored">Innovations Plus</span>


<br><br>

The International CES defines consumer technology’s future. The future is certain to contain a great deal of rich multimedia content. To enjoy that content, we need available, inexpensive, well-managed digital storage. Participate in the <STRONG>Digital Content Storage TechZone</STRONG> to demonstrate how your products use, manage and store your customers’ digital experiences! Sign up now to show your customers where their content lives!
<P><STRONG>Who should exhibit here?<BR></STRONG>If you develop or produce:</P>
<UL>
<LI>Digital content creation, editing, archiving, distribution</LI>
<LI>Consumer electronics products that deliver rich multimedia content to customers</LI>
<LI>Digital storage devices used to store multimedia content</LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone542"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">DSL Forum</span><br>
<span class="text_colored">Innovations Plus</span>


<br><br>


<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone543"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">DVD-RAM</span><br>
<span class="text_colored">LVCC Central</span>
<br>Sponsor(s): <span class="text_colored">RAM Promotion Group (RAMPRG)</span>

<br><br>

<IMG height=87 src="/images/partners/dvdram.gif" width=144 align=right>Join leading technology companies, including Hitachi, HLDS, Maxell, LG, Panasonic, Samsung, TEAC, Toshiba, JVC and the Recordable DVD Council to promote DVD-RAM capabilities and new technologies at this exclusive CES TechZone. <BR><BR><B>Who should exhibit here?</B><BR>Manufacturers or suppliers of DVD-RAM compatible products. <BR>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone544"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Energy Efficiency and Electronics Recycling</span><br>
<span class="text_colored">Innovations Plus</span>
<br>Sponsor(s): <span class="text_colored">Energy Star, EPA</span>

<br><br>

<IMG height=64 src="/images/partners/EnergyStar.gif" width=200 align=right>Look to the future. If your products demonstrate how to save energy and protect the environment or address the productive handling of used electronics equipment, you need to be part of the <STRONG>Energy Efficiency and Electronics Recycling TechZone</STRONG>.&nbsp;This CES TechZone promotes energy-efficient products and electronics recycling. Exhibit here, and make your most productive contacts all year. <BR><BR>&nbsp;<BR><IMG height=98 hspace=10 src="/images/partners/GreenDay.gif" width=140 align=left>The International CES dedicates Saturday, January 8, 2005, to <STRONG>Green Saturday, Environmental Awareness Day</STRONG>.&nbsp;Look for special conference announcements that address the future of recycling electronics products. Help us advance electronics recycling and the future of the CE industry.&nbsp;<BR><BR><IMG height=121 src="/images/partners/EPA.gif" width=120 align=right>&nbsp;<BR><B><BR>Who should exhibit here?</B><BR>
<UL>
<LI>Manufacturers that produce or sell energy efficient audio/video products, computers, chips, power management devices, home monitoring devices and more </LI>
<LI>Companies that recycle products such as computers, televisions and mobile phones </LI>
<LI>Electronics collections agencies </LI>
<LI>Energy and recycling industry groups </LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone546"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Flash Forward 2.0: Bringing Digital Imaging Into Focus</span><br>
<span class="text_colored">Central Plaza</span>
<br>Sponsor(s): <span class="text_colored">International CES and InfoTrends</span>

<br><br>

Get the exposure you deserve at the <STRONG>Flash Forward 2.0: Bringing Digital Imaging Into Focus</STRONG> TechZone. Participate in an exclusive digital imaging retail model brought to you by CEA and InfoTrends Research Group. <BR><BR>Offer critical, <EM>real</EM> solutions to the developing digital imaging experience. Gain front-line exposure to retailers, as you demo tomorrow's new products and most versatile applications. <BR><BR><STRONG><A href="/docs/flashFWD2005.pdf" target=_blank>Read more details (pdf)</A></STRONG> about the digital imaging industry's essential venue to showcase, train and sell digital.&nbsp;<BR><BR><A href="http://www.cesweb.org/exhibitors/space/flash_forward.asp"></A><B><IMG height=86 src="/images/partners/FlashForward2_280.gif" width=280 align=right>Who should exhibit here?</B><BR>Manufacturers of: 
<TABLE>
<TBODY>
<TR>
<TD>
<UL>
<LI>Accessories </LI>
<LI>Broadband services </LI>
<LI>Digital cameras </LI>
<LI>Digital video </LI>
<LI>Duplication </LI>
<LI>Flash memory </LI>
<LI>In-store photo kiosks </LI></UL></TD>
<TD width=10>&nbsp;</TD>
<TD vAlign=top>
<UL>
<LI>Inks and papers </LI>
<LI>Monitors </LI>
<LI>Personal computers </LI>
<LI>Printers </LI>
<LI>Software </LI>
<LI>Storage and memory </LI>
<LI>and more </LI></UL></TD></TR></TBODY></TABLE>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone1493"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Launch</span><br>
<span class="text_colored">Innovations Plus</span>


<br><br>

Put a spotlight on your new consumer market products and technologies. Meet the players and key alliances that can complement your business plan—or represent an important OEM relationship. There’s a new home for emerging technologies, companies and products: the exciting, energized <STRONG>Launch TechZone </STRONG>at the 2005 International CES. Make strategic connections at the largest technology event in North America.<BR><BR><STRONG>Who should exhibit here?</STRONG><BR>The Launch TechZone is specifically for smaller companies with a product or technology whose science and theory are understood, and some useful applications exist, but its potential in the consumer market is not yet realized.&nbsp; Categories include: 
<UL>
<LI>Nanotechnologies </LI>
<LI>Robotics </LI>
<LI>Biometrics </LI>
<LI>Voice recognition devices </LI>
<LI>Disposable technology </LI>
<LI>New audio media </LI>
<LI>Flexible computing devices </LI></UL>
<P>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone553"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">MP3 and Internet Audio</span><br>
<span class="text_colored">Innovations Plus</span>


<br><br>

If you offer solutions for hours of portable digital listening, participate in the <STRONG>MP3 and Internet Audio TechZone</STRONG>, a cost-effective complement to your marketing plan. The International CES connects digital content, the Internet and broadband with wireless media and devices. Introduce your innovative products to the mass market through the most comprehensive array of distribution channels. <BR><BR><B>Who should exhibit here?</B><BR>Manufacturers or suppliers of: 
<UL>
<LI>Digital music </LI>
<LI>Hardware </LI>
<LI>Devices </LI>
<LI>Accessories </LI>
<LI>Software </LI>
<LI>Content services </LI>
<LI>Pipelines </LI></UL><!--
<table>
<tr>
	<td>
	<ul>
		<li>58 Wireless
		<li>AMAC Tek Co. Ltd./ACE Korea
		<li>COWON Co., Ltd./ACE Korea
		<li>Diasonic Technology Co., Ltd./ACE Korea
		<li>Digitalway Co., Ltd./ACE Korea
		<li>DYNE TELECOM CO., LTD.
		<li>Eratech Co. Ltd./ACE Korea
		<li>Hyun Won, Inc./ACE Korea
	</ul>	
	</td>
	<td valign="top">
	<ul>
		<li>Imaginative Design Operation Co., Ltd.
		<li>JM Tek LLC/USBDrive
		<li>MultiChannel Labs Co., Ltd.
		<li>Nextway Co. Ltd./ACE Korea
		<li>S. Cam Co. Ltd./ACE Korea
		<li>Safa Media Co., Ltd./ACE Korea
		<li>The TW/Keen High Technologies Ltd.
	</ul>	
	</td>
</tr>
</table>
-->
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone1494"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">MultiMediaCard Association</span><br>
<span class="text_colored">Innovations Plus</span>
<br>Sponsor(s): <span class="text_colored">MultiMediaCard Association</span>

<br><br>

The MultiMediaCard Association (MMCA) (<A href="http://www.mmca.org/">http://www.mmca.org/</A>) is the open standard memory card organization, promoting worldwide adoption of postage-stamp size, removable storage cards designed for mobile phones and digital imaging. These convenient, reliable, rugged and lightweight standardized data carriers store up to 1 Gbyte, or approximately 640,000 book pages.&nbsp; The cards are fast for excellent system performance; energy efficient for prolonged battery life in portable products; and cost-efficient for use in systems sold at consumer price points. &nbsp; <STRONG>Who should exhibit here? </STRONG><BR>Manufacturers and suppliers of:<BR>
<UL>
<LI>Removable solid-state memory solutions for mobile applications, such as MP3 music players, portable video games, laptop computers, personal digital assistants (PDAs), mobile telephones and digital cameras </LI>
<LI>ROM technology for read-only applications </LI>
<LI>Flash technology for read/write applications </LI>
<LI>Energy efficient products for prolonged battery life in portable products </LI>
<LI>Digital communications devices </LI>
<LI>Internet music players </LI>
<LI>Digital video cameras </LI>
<LI>Global positioning systems </LI>
<LI>Security devices<BR></LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone555"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Portable Power</span><br>
<span class="text_colored">Innovations Plus</span>


<br><br>

Rapid industry growth requires new power sources for portable computers, communications and entertainment devices. The battery-powered product market calls for innovative, efficient solutions to keep us going. Build strong OEM relationships with manufacturers of products your batteries power. Demonstrate the synergy between the products, the batteries, the chargers, and power management systems that keep the batteries charged. All at the&nbsp;<STRONG>Portable Power&nbsp;TechZone</STRONG>. <BR><BR><B>Who should exhibit here?</B><BR>Manufacturers or suppliers of new power sources for portable computers, communications and entertainment devices and product providers of solutions that are: 
<UL>
<LI>Rechargeable </LI>
<LI>Disposable </LI>
<LI>Fuel cell </LI>
<LI>Alkaline </LI>
<LI>Nickel metal hydride </LI>
<LI>Lithium </LI>
<LI>Zinc </LI></UL><IMG height=5 hspace=0 src="http://www.cesweb.org/global_images2005/spacer.gif" width=1 border=0><BR>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone1573"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">RFID</span><br>
<span class="text_colored">Innovations Plus</span>
<br>Sponsor(s): <span class="text_colored">AIM</span>

<br><br>

<IMG height=123 hspace=6 src="/images/partners/Aim-Global-Logo.gif" width=155 align=right>Radio frequency (RF) tags are used to be placed on almost anything to become the are sure to become the barcode of the future and can be placed on almost anything.&nbsp; Anything with an RF chip could be tracked at any time&nbsp;to determine its location,&nbsp;and the chip&nbsp;provides valuable remote information about the product.&nbsp;Help show the advantages of this&nbsp;technology.<BR><BR><STRONG>Who should exhibit here?</STRONG><BR>Manufacturers and developers of RF technologies. <BR>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone557"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">RWPPI</span><br>
<span class="text_colored">LVCC Central</span>
<br>Sponsor(s): <span class="text_colored">RWPPI</span>

<br><br>

The RWPPI (RW Products Promotion Initiative) has actively promoted DVD-R and DVD-RW format-related products in the converging audio-visual and PC worlds. DVD-R and DVD-RW are versatile DVD recording formats and accepted international standards.&nbsp;Help demonstrate&nbsp;DVD recorders, players, PC application software and optical disc media products. <A href="http://www.rwppi.com/" target=_blank>http://www.rwppi.com/</A>&nbsp;<BR><BR><IMG height=43 src="/images/partners/RWPPI.gif" width=135 align=right><B>Who should exhibit here?</B><BR>If you manufacture or sell next-generation home entertainment through DVD-R/RW materials, then consider a presence in the RWPPI TechZone.
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone558"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">SD Card</span><br>
<span class="text_colored">LVCC Central</span>
<br>Sponsor(s): <span class="text_colored">SD Card Association</span>

<br><br>

More memory in a smaller chip! The Secure Digital (SD) Memory Card has a powerful influence on advanced digital storage technology of information, entertainment and communications. SD Memory Cards do not require power to retain the information stored on them, yet offer high storage capacity, fast data transfer, great flexibility and excellent security.&nbsp;<BR><BR><IMG height=87 src="/images/partners/sdcard.gif" width=200 align=right><B>Who should exhibit here?</B><BR>Companies that design, develop, manufacture or sell products that utilize the SD specifications, including: 
<UL>
<LI>Digital files </LI>
<LI>SD-enabled products </LI>
<LI>Products compatible with SD memory cards </LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone559"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Studio at Home</span><br>
<span class="text_colored">Central Plaza</span>


<br><br>


<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone560"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">TechHome</span><br>
<span class="text_colored">LVCC South 1-2</span>
<br>Sponsor(s): <span class="text_colored">CEA's TechHome Division</span>

<br><br>

<IMG height=150 src="/images/partners/TechHome.gif" width=160 align=right>If your products are at the core of the networked home, increase efficiency, conserve energy or make consumers' home lives easier, then join the International CES at the&nbsp;<STRONG>TechHome TechZone</STRONG>, featuring the most cutting-edge innovations of tomorrow's smart home. <BR><BR><B>Who should exhibit here?</B><BR>Manufacturers or suppliers of products such as: 
<TABLE border=0>
<TBODY>
<TR>
<TD vAlign=top>
<UL>
<LI>Networking or automation products </LI>
<LI>Data or entertainment distribution<BR>systems and solutions </LI>
<LI>Set-top boxes </LI>
<LI>System interfaces </LI>
<LI>Embedded technology products </LI>
<LI>PC networking </LI></UL></TD>
<TD width=6>&nbsp;</TD>
<TD vAlign=top>
<UL>
<LI>High-speed Internet access </LI>
<LI>Data distribution </LI>
<LI>Music and video throughout the home </LI>
<LI>Automated comfort and convenience </LI>
<LI>Energy management </LI>
<LI>Security </LI></UL></TD></TR></TBODY></TABLE>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone561"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">Ultrawideband</span><br>
<span class="text_colored">Innovations Plus</span>
<br>Sponsor(s): <span class="text_colored">MultiBand OFDM Alliance</span>

<br><br>

Wireless connectivity has enabled a new mobile lifestyle filled with conveniences for mobile computing users—at work and in our digital homes. Ultrawideband (UWB) technology offers a solution for the bandwidth, cost, power consumption and physical size requirements of next-generation consumer electronic devices. UWB enables wireless connectivity with consistent high data rates across multiple devices and PCs and promises to make it easy to create highspeed WPANs that connect devices.&nbsp;<BR><BR><B><IMG height=107 src="/images/partners/MBOA.gif" width=170 align=right>Who should exhibit here?</B><BR>Manufacturers or suppliers of products such as: 
<UL>
<LI>Consumer electronic manufacturers </LI>
<LI>Silicon/software developers </LI>
<LI>Personal computing companies </LI>
<LI>Industry organizations/ecosystem participants </LI></UL>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>

<a name="techzone1496"></a>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="590" height="2" hspace="0" vspace="0" border="0"><br>
<img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>

<span class="subhead">USB</span><br>
<span class="text_colored">Innovations Plus</span>
<br>Sponsor(s): <span class="text_colored">USB Implementers Forum, Inc.</span>

<br><br>

<IMG height=91 hspace=6 src="/images/partners/USB_HS_color_press.gif" width=160 align=right>USB technology makes “plug and play” a reality and accommodates our busy work styles and lifestyles. The impact of USB connectivity on small office/home office, our PCs, printers,&nbsp; scanners, PDAs and digital cameras is huge. Join us in the <STRONG>USB TechZone</STRONG>—dedicated exclusively to the use of this standard—at the 2005 International CES.
<P><STRONG>Who should exhibit here?<BR></STRONG>Any manufacturer or supplier whose business involves USB products should exhibit in the USB TechZone.&nbsp; <BR></P>
<br><img src="/global_images2005/spacer.gif" alt="" width="1" height="5" hspace="0" vspace="0" border="0"><br>[<a href="#top">back to top</a>]<br>
<!-- /text for main page -->
</div>

<!-- /center content -->
    <br><br><br>
    </td>
    <td width="10" class="exhibitor7"><img src="/global_images2005/spacer.gif" height="1" width="10"></td>
<!-- /main body content -->

<!-- optional added value -->

<!-- /optional added value -->

</tr>
<!-- /main body row -->

<!-- shaded row above footer -->
<tr>
<td colspan=3 bgcolor="#BCD6DB"><img src="/global_images2005/spacer.gif" width="1" height="10"></td>

</tr>
<!-- /shaded row above footer -->

</table>
<table width="770" cellspacing="0" cellpadding="0" border="0">

            <tr>
     <td width="10"></td>
     <td width="140"></td>
     <td width="10"></td>
     <td width="10" class="footer"><img src="/global_images2005/footer_left.gif" alt="(" width="10" height="30" hspace="0" vspace="0" border="0"></td>
     <td width="380" background="/global_images2005/footer_bg.gif" class="footer"><span class="nav_footer"><a href="/about_ces/default.asp">About CES</a> | <a href="/faqs/default.asp">FAQs</a> | <a href="/contact_us/default.asp">Contact Us</a> | <a href="/privacy_policy.asp">Privacy Policy</a> | <a href="/rd_vendors.asp">Vendors</a></span></td>
     <td width="210" colspan="3" align="right" background="/global_images2005/footer_bg.gif" class="footer"><span class="nav_footer"> &#169; 2004 CEA, All rights reserved</span></td>
     <td width="10" class="footer"><img src="/global_images2005/footer_right.gif" alt=")" width="10" height="30" hspace="0" vspace="0" border="0"></td>
</tr>   
            </table>
            <img src="/global_images2005/spacer.gif" alt="" width="1" height="20" hspace="0" vspace="0" border="0"">
        </td>
        <td width="50%" valign="top" class="exhibitorBGImg">&nbsp;</td>
    </tr>
</table>

</body>
</html>