<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><!-- PageID 26 - generated by RedDot 5.6 - 5.6.0.25 - Y-9bp -->
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!-- INSERT PAGE TITLE HERE (immediately following gblPAGE_TITLE) -->
<title>2005 International CES:&nbsp;Downloads</title>



<!-- INSERT SEARCH ZONE HERE -->


<link rel="StyleSheet" href="/print/global_includes/css/mainMethod.css" type="text/css">
<LINK REL="SHORTCUT ICON" HREF="http://www.easymovement.com/ces/favicon.ico">

<!-- Browser detection script -->
    <script src="/print/global_includes/js/browser_detection.js" type="text/javascript"></script>

<SCRIPT language="javascript1.2">
    function newWin(urlString,pgNum) {
        var popupWindow;
        urlString += "?pageID=" + pgNum;
 
        popupWindow = window.open(urlString,"","toolbar=yes,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=550,width=618,left=50,top=50");
    }  
 
    function openNewWindow(strURL) {
        window.name = "main";
        var newWindow = window.open(strURL,"newWindow", "toolbar=no,menubar=no,resizable=no,status=no,scrollbars=yes,location=no,directories=no,copyhistory=no,height=400,width=450,left=50,top=50");
    }

    // Script for e-mail this page - gets the url of the page the user is on before the e-mail page tool button is clicked
    function loadReferrer() {
        referrerString = opener.document.location.href;
        document.emailForm.page.value = referrerString;
    }
</SCRIPT>

<!-- Rollover script (do we still need these?) --> 
<script language="javascript1.2"> 
    /* for graphical rollovers */
   function rollOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function rollOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function introllOver(which,name) 
    {
    var on="/global_images/1.0/1.0_" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function introllOff(which) 
    {
    var on="/global_images/1.0/1.0_" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
   function snrollOver(which,name) 
    {
    var on="/global_images/1.0/1.0" + which + "_r.gif";
    if(document.images) {document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(name).src=on;}
    }
   function snrollOff(which) 
    {
    var on="/global_images/1.0/1.0" + which + ".gif";
    if(document.images){document.images[which].src=on;}
    else if (document.GetElementById){document.GetElementById(which).src=on;}
    }
        
    //do we still need this?   
    function onLoadHandler() {
       if( typeof(bodyOnLoadFunction) != 'undefined' ) {
           return eval(bodyOnLoadFunction);
       }
    }
</script>
<script language="javascript">
<!--
var activeNavId=0;
var thisPageUrl='/exhibitors/downloads/default.asp';

var parentLinks=new Array('dummy','/print/exhibitors/default.htm');

function checkActiveNav(theUrl) {
    var linkUrl=theUrl;
    var returnValue=false;
    
    if (linkUrl==thisPageUrl) {
        returnValue=true;
    } else if (parentLinks.length>2 && linkUrl==parentLinks[parentLinks.length-1]) {
        returnValue=true;   
    } else if (parentLinks.length>3 && linkUrl==parentLinks[parentLinks.length-2]) {
        returnValue=true;
    } else if (parentLinks.length>4 && linkUrl==parentLinks[parentLinks.length-3]) {
        returnValue=true;
    }
    return returnValue;
}

//-->
</script>
    <style>
        <!--
            UL {
                MARGIN-TOP: .5em;
                /*LIST-STYLE-IMAGE: url(/print/global_images2005/bullet.gif);*/
                MARGIN-BOTTOM: 0em;
                MARGIN-LEFT: 2em;
                VERTICAL-ALIGN: top;
            }

            .exhibitorBGImg {
                background-image: url('/print/global_images2005/exhibitor_bg.gif');
            }

            .text_colored, .intro_copy, .section_title, .subhead, .body_title, .intro_dates {
               color: #2B5492;
            }

        //-->
    </style>

</head>

<body leftmargin='0' topmargin='0' rightmargin='0' bottommargin='0' marginwidth='0' onLoad="onLoadHandler();self.focus();"> 
<div style="position:absolute; top: 15; left: 15" ><a href='javascript:;' onClick='window.print();return false'><img src="/print/global_images2005/print.jpg" width="115" height="20" border="0" alt=""></a></div>
<IMG SRC="/print/global_images2005/attPrintBanner.jpg" width="601" BORDER="0" vspace=0><br><table width="600" cellspacing="0" cellpadding="0" border="0">
    <tr>
<!-- /left column -->

<!-- main body content -->    
    <td width="10" class="exhibitor7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
    <td width="100%" class="exhibitor7" valign="top">
    <img src="/print/global_images2005/spacer.gif" height="10" width="1"><br>
<!-- center content -->


<div class="body_title">Exhibitor Downloads<br><img src="/print/global_images2005/spacer.gif" height="16" width="1"></div>
<div class="text"> 
<!-- text for main page -->

<span class="text">
<STRONG>To see how the International CES can benefit you</STRONG>, download our <A href="/print/exhibitors/downloads/Exhibit_Overview.pdf" target=new>Exhibitor Overview (pdf)</A> or these market-specific documents: 
<TABLE>
<TBODY>
<TR>
<TD>
<UL>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-Audio.pdf" target=new>Audio (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-DigEnt.pdf" target=new>Digital Entertainment (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-DigImag.pdf" target=new>Digital Imaging (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-EmbeddedTech.pdf" target=new>Embedded Technologies (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-IT.pdf" target=new>Information Technologies (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-IntBusiness.pdf" target=new>International Business (pdf)</A> </LI></UL></TD>
<TD>&nbsp;&nbsp;&nbsp;</TD>
<TD vAlign=top>
<UL>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-HomeTheater.pdf" target=new>Home Theater (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-MobileElec.pdf" target=new>Mobile Electronics (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-NetworkedHome.pdf" target=new>Networked Home (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-Video.pdf" target=new>Video Technologies (pdf)</A> </LI>
<LI><A href="/print/exhibitors/downloads/VerticalMarkets-Wireless.pdf" target=new>Wireless (pdf)</A> </LI></UL></TD></TR></TBODY></TABLE><BR><A href="/print/exhibitors/downloads/2k5_space_contract.pdf" target=blank>2005 International CES Exhibit Space Contract (pdf)</A> <BR><BR><A href="/print/exhibitors/resource_center/logos/default.asp">International CES Logos</A>&nbsp;(login required) <BR><BR><STRONG>NEW! </STRONG><A href="/print/exhibitors/downloads/2k4_ces_audit.pdf" target=_blank>2004 International CES Attendee Audit Highlights (pdf)</A><BR>The International CES stands behind our attendance with Veris Consulting's independent audit of the show. Here's a glimpse of the type of attendees International CES exhibitors can expect to meet.
</span>

<a name="920"></a>
<img src="/print/global_images2005/spacer.gif" alt="" width="100%" height="30" hspace="0" vspace="0" border="0"><br>

<img src="/print/global_images2005/2.0.line.gif" alt="-----------------------------------------------" width="100%" height="2" hspace="0" vspace="0" border="0"><br>

<div class="subhead" style="padding-top:3px; padding-bottom:7px">Download Adobe Acrobat Reader</div>
<span class="text">
<A href="http://www.adobe.com/products/acrobat/readstep.html" target=new></A><IMG height=49 hspace=6 src="/print/images/general/adobe_exh.gif" width=46 align=left>You will need the Adobe Acrobat Reader in order to view the above PDF document(s). Need the Acrobat Reader? <A href="http://www.adobe.com/products/acrobat/readstep.html" target=new>Download it now</A> for free! <BR><BR><BR><STRONG>Still need help?</STRONG> Let someone from the International CES <A href="/print/exhibitors/space/contacts.asp">business development team assist you</A>. 
</span>
<!-- text for main page -->
</div>

<!-- /center content -->
    <br><br><br>
    </td>
    <td width="10" class="exhibitor7"><img src="/print/global_images2005/spacer.gif" height="1" width="10"></td>
<!-- optional added value -->

<!-- /optional added value -->
</tr>
<!-- /main body row -->
<!--/print/exhibitors/space/default.asp/print/exhibitors/promotions/default.asp/print/exhibitors/resource_center/default.asp/print/exhibitors/pr/default.asp/print/exhibitors/manual/default.asp/print/exhibitors/newsletter/default.asp/print/exhibitors/downloads/default.asp-->
<!---->
</table>
</body>
</html>